### ISSUE TITLE
Tiled Popover

### ISSUE THREAD

**Issue by xiecsuk** [olton/Metro-UI-CSS#1000]
I created the following https://codepen.io/xiecsuk/pen/rJbpae which shows a tiled menu selection popover using Metro-UI 3. Can you please confirm that it is possible to create a similar effect in Metro UI 4. I have managed to create the tiled menu and it drops down, but I can't get it to display over the current page. Everything underneath it is displaced.
A couple of suggestions to set me in the right direction would be much appreciated.

**Comment by olton** [comment]
Hi @xiecsuk 

https://codepen.io/olton/pen/rJbJmv

**Comment by xiecsuk** [comment]
Perfect!!! Thank you very much indeed. I look forward to continuing my journey through Metro-UI 4.
