### ISSUE TITLE
Select - Ajax

### ISSUE THREAD

**Issue by Cadorin** [olton/Metro-UI-CSS#1001]
Hey, I'm having a problem with selects when they are loaded dynamically (Ajax). Other elements, like date pickers and inputs, are ok, but the selects don't open showing the options. What does it can be?

**Comment by penyin** [comment]
i had the same problem.
mean is "how to re initial the select"
Thx.

**Comment by olton** [comment]
```
var select = $(el);
Metro.destroyPlugin(select, 'select');
Metro.initPlugin(select, 'select');
```

**Comment by olton** [comment]
Currently Metr 4 select component not support change options at runtime. This feature will be added later.

**Comment by penyin** [comment]
hmm, thank you, and look forward to this new addition.
