### ISSUE TITLE
How to create a AppBar(with place-right items) like Metro3?

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1002]
Hi, I wanna make something place-right, e.g. the attach image, AppBar in Metro 3.  
In Metro 4, app-bar-menu will be converted to Hamburger icon. I browsed the code of metroui.org.ua, you are using [topbar](https://metroui.org.ua/header.html)？
![qq 20180304103529](https://user-images.githubusercontent.com/1308706/36941526-4f373656-1f98-11e8-9bc1-e592f57d73e4.jpg)

**Comment by olton** [comment]
https://codepen.io/olton/pen/PQgvMW

**Comment by taurenshaman** [comment]
Done. Thank you!
