### ISSUE TITLE
Submit again the question of form validation

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1003]
In the form validation component.
Entitled:  Events the location of the

When Validator is works, fired any events: onBeforeSubmit(form), onError(element, value), onValid(element, value), onSubmit(form), onValidatorCreate(form).
To use event add attribute data-on-* to form.

-----------------------------------------------------------------------------------------
among onError(element, value)  onValid(element, value) these two functions
The value of the second parameter.
Find that even if get the data, I can't use it.
It is be a string.
When multiple input tag are used at the same time
I can't take this string,
Perform effective segmentation and extraction.
This value parameter should be a json data. while is  not a string

When multiple input tags need to be submitted.
The validation form should have been validated and sent validated data uniformly.
When one of the input tags must be validated.

If a validation error occurs.
The function of the onValid function should be to send a suggestion error
This suggestion error makes it easy for us to manipulate data and user processes.
Rather than not simply give the user the right data, wrong data Don't have to give user。
I don't think this model is correct.
Don't think more this model is a good idea.

**Comment by olton** [comment]
onError and onValid triggered for each input element. Other behavior will not be implemented in the near future

**Comment by chongzia** [comment]
I want to know how to use it.
How do you use onError and onValid for each element?
And can affect the button behavior, how do I determine a set of input tags，whether all has passed the verification？

**Comment by olton** [comment]
@chongzia 
1) The form will not be sent until all checks are completed
2) use `console.log()` to view events params `data-on-error="conaole.log(arguments)"`

**Comment by chongzia** [comment]
https://codepen.io/dreamcc/pen/aqrOzY

Help me to look at should it be done this way.
Error and correct validation.

**Comment by olton** [comment]
@chongzia What result do you want?

**Comment by olton** [comment]
Why here to process events onError and onValid?

**Comment by chongzia** [comment]
In the form validation,In multiple input tags I want to get the final result of all the validation.
This result would it be possible for me to Know if i need to perform the next step.
But in the process of using your framework validation mechanism.
This step is difficult to implement.

To do thi I can only write my own verification and operation.
The validation of the framework itself.
It becomes a decoration

**Comment by chongzia** [comment]
In this case, it's useless.
I have to rewrite the js code,To verify that the contents of the input tag proceed to the next step.

**Comment by chongzia** [comment]
Maximum possible
Or I don't have it at all，Master the rules and get the gist of the correct results.

**Comment by olton** [comment]
Also you can use validator funcs without a form

**Comment by Kohins** [comment]
It's very complicated to use the form, and I want the author to change it

**Comment by olton** [comment]
@Kohins read the docs, in fact, everything is very simple, you need to carefully read the documentation and turn on the brain.

**Comment by olton** [comment]
@chongzia @Kohins Metro 4 updated to 4.0.3
4.0.3
 Validator: rename event onValid to onValidate
 Validator: add events onErrorForm, onValidateForm
 Validator: added checkbox validation (required function)
Read docs (also updated) for more information

**Comment by chongzia** [comment]
Wow!
Rubbing their hands，Give it a try

**Comment by chongzia** [comment]
好用了~~~

**Comment by chongzia** [comment]
Now finally 
only need to use custom properties the HTML tag validation protocol.
Recent happiness has finally been satiated by the author.
