### ISSUE TITLE
Validator in charms

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1004]
The blocking event occurrence scenario has been committed.

https://codepen.io/dreamcc/pen/xYBGjK

When using the charms component.
Form validation cannot be executed again.
When my cancel the component charms, the form validation can be performed.
That is, no matter who is in the component charms,  can't use the form validation component.
After deleting data-role="charms" The test is available

**Comment by olton** [comment]
@chongzia  I found this problem point. I fix it today. Thanks

**Comment by olton** [comment]
@chongzia do not need to build unnecessary guesses

**Comment by chongzia** [comment]
Radio and select the form.
Can you add to the form validation, just a simple request.
Wonder if like to help.
Improve this missing basic validation function.

**Comment by olton** [comment]
Fixed in 4.0.4

+ [x] Charms: remove `preventDefault` from click event (form now submitted)
+ [x] Nuget: change target location for Metro 4
+ [x] Validator: add `radio` and `select` to validation (read docs)
+ [x] Validator: add function `not` (read docs)

**Comment by chongzia** [comment]
I estimate the basic public requirements of the validation component 
Basically Is close to perfect improve
At present Maybe bugs can't test too much stuff and public demand. 
In addition to manual the page of the document .
hah~ 

Thank you for all the questions I've had since I used your framework at work.
