### ISSUE TITLE
Metro Fonts showing like square

### ISSUE THREAD

**Issue by CharlyCUU** [olton/Metro-UI-CSS#1007]
I have added Metro 4 to our application, but I have this issue, like you see in the image, the metro fonts are showed like you see, the font just shows the borders like a square shape. 

Can you help me to fis this issue? 

Thank you very much for your help. 

Have a good day..! 

This is my console browser, I'm using chrome browser, using Explorer the metro fonts not who nothing:

![consolemetro4](https://user-images.githubusercontent.com/37152000/37104492-17f04c60-21ea-11e8-8d92-8cffba35558b.JPG)

This is what and how I have the libraries includes in my html:

![metro4fontscss](https://user-images.githubusercontent.com/37152000/37104324-a8e1ff9e-21e9-11e8-8bfc-fdef1ed1d559.JPG)

This is how is showen the fonts in my browser:

![metro4fonts](https://user-images.githubusercontent.com/37152000/37104701-9a660c5c-21ea-11e8-9fbc-d91bad257614.JPG)

**Comment by olton** [comment]
You do not have an icon font loaded, check the paths

**Comment by chongzia** [comment]
The browser should add a font that supports a general-purpose PC.
Such as    Microsoft jas black  
The font set by the author is not recognized in my country.
He can't support more languages.

**Comment by olton** [comment]
@CharlyCUU And this is Metro 3, not Metro 4

**Comment by CharlyCUU** [comment]
The libraries that I have in my project are just Metro 4, I have nothing of Metro 3

**Comment by olton** [comment]
@CharlyCUU on your image I see Metro 3 files

**Comment by olton** [comment]
@CharlyCUU Please read Metro 4 docs https://metroui.org.ua/intro.html

**Comment by CharlyCUU** [comment]
Ok, then here is my code modified as metro 4 docs:

This is my CSS libraries in code:

![metro4fontscss_v2](https://user-images.githubusercontent.com/37152000/37106456-20828622-21ef-11e8-9e9c-bbe8eb482254.JPG)

This is my JS libraries in code, this libraries are of Meta 4:

![metro4jsbeforebody](https://user-images.githubusercontent.com/37152000/37106487-34bccfe4-21ef-11e8-91a5-944eadec22d5.JPG)

I ran again my project and still shown like this the metro fonts:

![metro4fonts](https://user-images.githubusercontent.com/37152000/37106536-4bb59168-21ef-11e8-9b0c-63ddd6e2bb54.JPG)

**Comment by CharlyCUU** [comment]
The console shows it:

![consolemetro4_v2](https://user-images.githubusercontent.com/37152000/37106642-9321b78e-21ef-11e8-9598-4f0edc0b81c0.JPG)

**Comment by olton** [comment]
Font with icons not loaded. Check file metro.woff in path `~/MetroUI/mif/metro.woff`

**Comment by CharlyCUU** [comment]
Ok, this what I Have in mif folder:

![miffolder](https://user-images.githubusercontent.com/37152000/37106740-d172170e-21ef-11e8-8105-bcb334a7ba4c.JPG)

**Comment by olton** [comment]
Check your server configuration. I can not know why your server does not return a font file.

**Comment by CharlyCUU** [comment]
Ok Olton, thank you, let me see the server configuration

**Comment by olton** [comment]
@CharlyCUU try using the library from CDN

**Comment by CharlyCUU** [comment]
Issue resolved:

Thank you all, I had to add this code in web.config:

<system.webServer>
    <staticContent>
        <remove fileExtension=".woff" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
    </staticContent>
</system.webServer>


Please, go to this link for more information about it.

http://codingstill.com/2013/01/set-mime-types-for-web-fonts-in-iis/

**Comment by CharlyCUU** [comment]
I think the lines of code added were not showen correctly, here is an image:

![staticwebconfig](https://user-images.githubusercontent.com/37152000/37121964-0d34f8fc-221c-11e8-9d5e-548825208946.JPG)

**Comment by codefactorymx** [comment]
Charly, if you're using MVC you can also ignore that extension in routeConfig
