### ISSUE TITLE
Selsec tag displays the problem.

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1008]
Js dynamically loads option data in select.
The li tag on the select component in the framework.
The data is not written, not shown.
Try creating notes on codepen.found Unable to create this process, Restore the scene difficult
Had to I'm going to describe it here.
If you can try to add or remove this `Data - role = "select"` property here , use ajax dynamic loading.

**Comment by olton** [comment]
Metro 4 select not supported loading options at runtime

**Comment by olton** [comment]
issues exists https://github.com/olton/Metro-UI-CSS/issues/1001

**Comment by chongzia** [comment]
That means I have to cancel this property when I want to load the select data dynamically.
i saw， must be closed
data-role="select"
thank you
