### ISSUE TITLE
Commit some components conflict of the problem

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1009]
The notes have been created
The scene has been restored
https://codepen.io/dreamcc/pen/mxbPGa

1. It's all form components.
Using dropdown and collapse components, this conflict is a problem in which input function labels are added.all will there are such the problem

2.It is recommended to add some color element styles to redio  and switch  and checkbox.
It should be too close to grey, so it's hard to see them.

3.The collapse component and the falling component feel like a function.

**Comment by chongzia** [comment]
Should be some components in the form.
Lack of color matching function and solution.
so is why we found these problems.

**Comment by olton** [comment]
@chongzia  Dear friend! Write the code in accordance with the documentation.
```
<button class="button dark p-0 small" style="width:120px;">
          <input type="radio" data-role="radio"
                 data-caption="<span class='fg-white'>test</span>" name="storeid" value="">
</button>
```
In Metro 4 no such constructions. Use the components of Metro 4 as they are described in the documentation and do not come up with absurd designs.

**Comment by chongzia** [comment]
I said my face was red. 
awkward
Can I change it?
```
<div class="button dark p-0 small" style="width:120px;">
          <input type="radio" data-role="radio"
                 data-caption="<span class='fg-white'>test</span>" name="storeid" value="">
</div>
```

Weak weak ask, such line not line 
Use div to change the shell style of the component.

The point is not here,
The emphasis should be on single box, multiple marquee, switch,
they have no color scheme, 
if I simply use color, can not change his color style.

**Comment by olton** [comment]
Scheme builder in develop. In this time you must manually redefine styles for the required component.
How to change, you can see in 
https://github.com/olton/Metro-UI-CSS/blob/master/less/schemes/builder/builder.less#L149

**Comment by chongzia** [comment]
I'll keep an eye on it
