### ISSUE TITLE
Notify container definition

### ISSUE THREAD

**Issue by RandyOrton91** [olton/Metro-UI-CSS#1011]
Hello, how can i define notify container in the notify options? Syntax isn't explained. Thanks

**Comment by olton** [comment]
the option is valid CSS selector: class or id

**Comment by RandyOrton91** [comment]
Metro.notify.create("This is a notify", "Title", { container: ".container-fluid" });

As this?

**Comment by RandyOrton91** [comment]
My problem is that the notify go behind the Appbar

**Comment by olton** [comment]
Create a container for notifies with `.z-charms` class. This class add `z-index` more than `app-bar`.

**Comment by olton** [comment]
In next patch, I will increase `z-index` for default container

**Comment by RandyOrton91** [comment]
Ok, thank you!
