### ISSUE TITLE
How to dynamically fill Popover Content

### ISSUE THREAD

**Issue by rcheung9** [olton/Metro-UI-CSS#1012]
When I try to populate popover content dynamically, it keeps flickering.

https://codepen.io/anon/pen/yKLpNp?editors=1010

**Comment by olton** [comment]
Popover is a static component

**Comment by rcheung9** [comment]
What does it mean here **Value fo this attribute can be simple text or valid html text. You can change this attribute at runtime.**

https://metroui.org.ua/popovers.html

**Comment by olton** [comment]
Its true for closed popover

**Comment by olton** [comment]
You can not change content for open popover.
