### ISSUE TITLE
Support for SPA frameworks? 

### ISSUE THREAD

**Issue by montella1507** [olton/Metro-UI-CSS#1014]
Hello are you going to make SPA (Angular/React) version of components?  

Especially only Wrappers arround JQuery calls should not be so hard to make?

Is it JQuery really so neccesarry?

**Comment by olton** [comment]
I don't have plans to create it

**Comment by codefactorymx** [comment]
Works fine with Knockout and Crossroads over Typescript

**Comment by ShiruJan** [comment]
> Works fine with Knockout and Crossroads over Typescript

Hey codefactorymx, did you manage to run the "change" event of the "select" control in typescript? i try with (change), onchange and data-on-change, but not work.

regards!
