### ISSUE TITLE
For the TreeView style custom expectations.

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1015]
Hopefully, like some of your other components.
we can control the style of the tree
and or we can decide whether or not to display it in a progressive hierarchical relationship.
for example

**data-role-hierarchy=“true”**
```
<ul data-role="treeview" data-role-hierarchy=“true”>
    ........................................
</ul>
1. -------------------
            2.------------
                         3.--
            4.------------
5.--------------------
```
**data-role-hierarchy=“false”**
```
<ul data-role="treeview" data-role-hierarchy=“false”>
    ........................................
</ul>
1. -------------------
2.-------------------
3.-------------------
4.-------------------
5.-------------------
```

**Comment by olton** [comment]
I do not need such functionality

**Comment by olton** [comment]
You can use for this simple CSS class:
```
.treeview.no-hierarchy ul {
    margin-left: 0;
}
```

**Comment by chongzia** [comment]
···········
Before I submit this question,
is the such write 
So want to make adjustments and do some skin customization.
hah~ 
When I'm not busy with my work, I'll write something like this for you.
I hope you don't mind my writing.
