### ISSUE TITLE
The < hr > tag   Style failure 

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1016]
Request restore,
A large amount of document content is used to split the header using < hr> tag.
If you don't have this, have to write I own style.
But there are too many pages.
Many places are different color schemes.

At the same time, I hope to update some of the < hr> style scheme to provide user principles easily.

**Comment by olton** [comment]
Sorry, but I don't understand what you want

**Comment by olton** [comment]
you can use three predefined styles for `<hr>`: 
 - `<hr>` (2px)
 - `<hr class="thin">` (1px)
 - `<hr class="fat">` (3px)
To change `<hr>` color you can use color classes for background `.bg-*`

**Comment by chongzia** [comment]
`<hr class="border w-100 bg-red">`
That's what I'm using right now.
Nearly a hundred places have been changed.

**Comment by chongzia** [comment]
It seems unlikely,I still need to write it myself
(*゜ー゜*)
Maybe the is requirements a little bit abrupt
