### ISSUE TITLE
Plans for fluent design?

### ISSUE THREAD

**Issue by codefactorymx** [olton/Metro-UI-CSS#1017]
Hi, MetroUI, is a good option for us who want a design similar to MS apps. Do you have any plans to do something like Fluent Design from MS but for web?

**Comment by olton** [comment]
Yes, I have plans to extend FD to web.

**Comment by codefactorymx** [comment]
If I can help please let me know.
Not asking for a job, just want to collaborate, because I like your framework.

Thanks,
Victor

Enviado desde mi teléfono con Windows 10

________________________________
De: Sergey Pimenov <notifications@github.com>
Enviado: Saturday, March 10, 2018 1:26:10 PM
Para: olton/Metro-UI-CSS
CC: Victor Hugo Lara Santillan; Author
Asunto: Re: [olton/Metro-UI-CSS] Plans for fluent design? (#1017)


Yes, I have plans to extend FD to web.
