### ISSUE TITLE
Focus on suggest box when it is clicked when in compact mode

### ISSUE THREAD

**Issue by sangeeth96** [olton/Metro-UI-CSS#1018]
Currently, when the suggest box is clicked when in compact mode, the nav view expands and displays the entire input box but doesn't focus into it and it needs an additional click into input box to trigger focus. It'd be better to focus on the input box when the nav view is expanded.

Suggest box doc with preview: https://metroui.org.ua/navview.html#_navview_pane_suggest-box

**Comment by olton** [comment]
I will add this to 4.2.3. Wait for release.
