### ISSUE TITLE
Testing MetroUI

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1023]
(I'm testing MetroUI to see if it's right for me)

I have a FORM with three fields:

&lt;FORM id="SEARCH" name="search"
      data-role="validator"
      data-on-before-submit="if($('#ROM').val()=='' && $('#CRC').val()=='' && $('#SHA1').val()=='') return(false); else return(true);"
      data-on-error-form="alert('Immettere almeno un Valore');"
      method="post" action="/test.htm"&gt;
&lt;DIV class="row mb-2"&gt;
   &lt;LABEL class="cell-sm-2 text-bold" for="ROM"&gt;ROM&lt;/LABEL&gt;
   &lt;DIV class="cell-sm-8"&gt;
      &lt;INPUT id="ROM" name="rom" type="text" data-role="input" class="info" size="20" maxlength="60" value="" /&gt;
   &lt;/DIV&gt;
&lt;/DIV&gt;
&lt;DIV class="row mb-2"&gt;
   &lt;LABEL class="cell-sm-2 text-bold" for="CRC"&gt;CRC&lt;/LABEL&gt;
   &lt;DIV class="cell-sm-8"&gt;
      &lt;INPUT id="CRC" name="crc" type="text" data-role="input" class="info" size="10" maxlength="8" value="" /&gt;
   &lt;/DIV&gt;
&lt;/DIV&gt;
&lt;DIV class="row mb-2"&gt;
   &lt;LABEL class="cell-sm-2 text-bold" for="SHA1"&gt;SHA1&lt;/LABEL&gt;
   &lt;DIV class="cell-sm-8"&gt;
      &lt;INPUT id="SHA1" name="sha1" type="text" data-role="input" class="info" size="45" maxlength="40" value="" /&gt;
   &lt;/DIV&gt;
&lt;/DIV&gt;
&lt;DIV class="row mb-2"&gt;
   &lt;LABEL class="cell-sm-2" for="SUBMIT"&gt;&nbsp;&lt;/LABEL&gt;
   &lt;DIV class="cell-sm-8"&gt;
      &lt;BUTTON id="SUBMIT" class="button info"&gt;&lt;SPAN class="mif-search mif-1x"&gt;&lt;/SPAN&gt;&lt;SPAN class="text-bold"&gt; Cerca&lt;/SPAN&gt;&lt;/BUTTON&gt;
   &lt;/DIV&gt;
&lt;/DIV&gt;
&lt;/FORM&gt;

I can enter one or more search fields, but at least one is mandatory. If I do not enter any values, I would like to report all three fields as incorrect and use the MetroUI method (the ! character before the field and border that turns red). Furthermore, for the CRC and SHA1 fields, if a value is present, this must be 8 and 40 characters long respectively. Is it possible to do this with the MetroUI FORM validator?

**Comment by xJoeyv** [comment]
Please use code formatting on Github and Format your document. Its hard to read.

**Comment by TorakikiSan** [comment]
(I'm testing MetroUI to see if it's right for me)

I have a FORM with three fields:

<PRE>
&lt;FORM id="SEARCH" name="search"
         data-role="validator"
         data-on-before-submit="if($('#ROM').val()=='' && $('#CRC').val()=='' && $('#SHA1').val()=='') return(false); else return(true);"
         data-on-error-form="alert('Immettere almeno un Valore');"
         method="post" action="/test.htm"&gt;
&lt;DIV class="row mb-2"&gt;
&lt;LABEL class="cell-sm-2 text-bold" for="ROM"&gt;ROM&lt;/LABEL&gt;
&lt;DIV class="cell-sm-8"&gt;
&lt;INPUT id="ROM" name="rom" type="text" data-role="input" class="info" size="20" maxlength="60" value="" /&gt;
&lt;/DIV&gt;
&lt;/DIV&gt;
&lt;DIV class="row mb-2"&gt;
&lt;LABEL class="cell-sm-2 text-bold" for="CRC"&gt;CRC&lt;/LABEL&gt;
&lt;DIV class="cell-sm-8"&gt;
&lt;INPUT id="CRC" name="crc" type="text" data-role="input" class="info" size="10" maxlength="8" value="" /&gt;
&lt;/DIV&gt;
&lt;/DIV&gt;
&lt;DIV class="row mb-2"&gt;
&lt;LABEL class="cell-sm-2 text-bold" for="SHA1"&gt;SHA1&lt;/LABEL&gt;
&lt;DIV class="cell-sm-8"&gt;
&lt;INPUT id="SHA1" name="sha1" type="text" data-role="input" class="info" size="45" maxlength="40" value="" /&gt;
&lt;/DIV&gt;
&lt;/DIV&gt;
&lt;DIV class="row mb-2"&gt;
&lt;LABEL class="cell-sm-2" for="SUBMIT"&gt; &lt;/LABEL&gt;
&lt;DIV class="cell-sm-8"&gt;
&lt;BUTTON id="SUBMIT" class="button info"&gt;&lt;SPAN class="mif-search mif-1x"&gt;&lt;/SPAN&gt;&lt;SPAN class="text-bold"&gt; Cerca&lt;/SPAN&gt;&lt;/BUTTON&gt;
&lt;/DIV&gt;
&lt;/DIV&gt;
&lt;/FORM&gt;
</PRE>

I can enter one or more search fields, but at least one is mandatory. If I do not enter any values, I would like to report all three fields as incorrect and use the MetroUI method (the ! character before the field and border that turns red). Furthermore, for the CRC and SHA1 fields, if a value is present, this must be 8 and 40 characters long respectively. Is it possible to do this with the MetroUI FORM validator?

**Comment by TorakikiSan** [comment]
Better?

**Comment by olton** [comment]
@TorakikiSan  You must use attribute `data-validate` for input
https://codepen.io/olton/pen/YayXJp

**Comment by TorakikiSan** [comment]
Thank's for the answer. 

But I can not use "required" for all three fields, because I use them as "search parameters" and I can enter one, two or all three. I should check that at least one is entered.
Thank's

**Comment by olton** [comment]
@TorakikiSan pen updated https://codepen.io/olton/pen/YayXJp
2) use function for event `onBeforeSubmit`

**Comment by TorakikiSan** [comment]
Thank you very much.

Very kind and very useful.
