### ISSUE TITLE
Panel Usage / Duplication

### ISSUE THREAD

**Issue by xJoeyv** [olton/Metro-UI-CSS#1024]
Hi,

Based of the documentation I created a panel 
```html
<div class="cell-4">
  <div data-role="panel" data-title-caption="Panel title" data-title-icon="<span class='mif-apps'></span>" data-width="240"
              data-collapsible="true" data-draggable="true">
              Raptus capios ducunt ad genetrix. Joy doesn’t beautifully respect any believer — but the power is what flies.
  </div>
</div>
```

After using this exact code this is the HTML Result:
![Result Image](https://i.imgur.com/UYkcQ0H.png)

**Comment by olton** [comment]
@xJoeyv https://codepen.io/olton/pen/WzQQme

**Comment by xJoeyv** [comment]
@olton I tested around a bit and if I load in Vue.JS Metro will have this bug.

**Comment by olton** [comment]
create pen on codepen.io

**Comment by xJoeyv** [comment]
@olton Done: https://codepen.io/xjoeyv/pen/dmYXrm you can see when you remove the part of Vue in the JS it is fixed

**Comment by olton** [comment]
@xJoeyv This is not a problem of Metro 4, write to the author of Vue.js. The problem is with him.

**Comment by olton** [comment]
@xJoeyv The problem is related to how the Vue works with the DOM. Metro 4 use mutationObserver for monitoring DOM.

**Comment by olton** [comment]
@xJoeyv strange, but it works for me
https://codepen.io/olton/pen/LdpxBj

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1038
