### ISSUE TITLE
Collapsible Vertical menu?

### ISSUE THREAD

**Issue by simonwjackson** [olton/Metro-UI-CSS#1025]
I'd like to use vertical menu (.v-menu) collapsed, but it looks like it only supports the expanded state.

**Comment by olton** [comment]
why not? 
https://codepen.io/olton/pen/mxewyM

**Comment by simonwjackson** [comment]
Sorry, I wasn't very clear in my explanation.

I am looking for a Side Navigation with:
 * no counter
 * collapsible (compact)
 * menu titles (the same style as the one presented under the "Vertical Menu" section in the documentation)

I tried to create this without adding custom styles, but i'm not sure it's possible

**Comment by olton** [comment]
navigation view component?

**Comment by simonwjackson** [comment]
Wow, I don't know how I missed this. 😫 

Thanks.
