### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by simonwjackson** [olton/Metro-UI-CSS#1026]
https://metroui.org.ua/sidenavigation.html

>Vertical menu
>The vertical menu is intended, first of all, to create sidebar menus of your site. To create vertical menu add class .v-menu to list. How to create it you can read in **_this article_**.

**_this article_** pints to http://localhost:63342/Metro-UI-CSS-4/docs/menu.html#_v_menu

**Comment by olton** [comment]
Thanks
