### ISSUE TITLE
Form validator :  data-validate="date" issue

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1027]
Hello,

I've got a problem with form validator when I'm using data-validate="date"

-> validator failed to check the data-format I set. It check using the "us" one.

My input field : 

`<input type="text" value="" data-role="calendarpicker" data-locale="fr-FR" data-format="%d/%m/%Y" data-validate="date" data-header-format="%A %e %B"/>`

I'm using this local : 

`Metro.utils.addLocale({
        'fr-FR': {
        "calendar": {
            "months": [
                "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre",
                "Jan", "Fev", "Mar", "Avr", "Mai", "Juin", "Jui", "Aou", "Sep", "Oct", "Nov", "Dec"
            ],
            "days": [
                "Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi",
                "Di", "Lu", "Ma", "Me", "Je", "Ve", "Sa",
                "Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"
            ],
            "time": {
                "days": "JOURS",
                "hours": "HEURES",
                "minutes": "MINS",
                "seconds": "SECS"
            }
        },
        "buttons": {
            "ok": "OK",
            "cancel": "Cancel",
            "done": "Done",
            "today": "Today",
            "now": "Now",
            "clear": "Clear",
            "help": "Help",
            "yes": "Yes",
            "no": "No",
            "random": "Random"
        }
    }
    });	`

**Comment by olton** [comment]
The validator return false if value can not be converted to date with js date parser. You use formating for date value. To check it, use rule `requared`

**Comment by Falconpage** [comment]
Thanks, I have modified this input to allow me specify a value manually using your picker.
This is why I would like to validate this input.
Sorry I don't understand "requared", do you mean regular expression ?

**Comment by olton** [comment]
Use `data-validate="required"`

**Comment by Falconpage** [comment]
Ok, done.
For the input where I allow modification I'm using this expression that allow check the french format.
If it help someone : dd/mm/yyyy

data-validate='pattern=^(((((0[1-9])|(1\d)|(2[0-8]))\/((0[1-9])|(1[0-2])))|((31\/((0[13578])|(1[02])))|((29|30)\/((0[1,3-9])|(1[0-2])))))\/((20[0-9][0-9])|(19[0-9][0-9])))|((29\/02\/(19|20)(([02468][048])|([13579][26]))))$'
