### ISSUE TITLE
Buttongroups set first button checked

### ISSUE THREAD

**Issue by TicTacTeo** [olton/Metro-UI-CSS#1028]

**Comment by olton** [comment]
Add class `active`

**Comment by RandyOrton91** [comment]
And how can i remove the default value?
Whe i create a button groups the first button is always checked

**Comment by olton** [comment]
@RandyOrton91 Thank you, this is a bug. I fix it today or tomorrow.

**Comment by olton** [comment]
@RandyOrton91 Fixed in 4.0.7. Check it, please.

**Comment by RandyOrton91** [comment]
It seem's not to be fixed, I downloaded the ultimate version from github but nothing changed

**Comment by olton** [comment]
Clear your browser cache

**Comment by RandyOrton91** [comment]
I already did it... I really don't know why they're still remaining checked

**Comment by olton** [comment]
Re-read docs, also changed.

**Comment by RandyOrton91** [comment]
I noticed that also in the buttons documentation the last example (that with data-targets="..." attribute) still have the first button checked

**Comment by olton** [comment]
the data-target attribute is needed to enumerate all the tags that are used to create the buttons

**Comment by RandyOrton91** [comment]
Sorry but probably I'm not being clear, I need to create a buttongroups with all the buttons unchecked

**Comment by RandyOrton91** [comment]
In your codepen if i delete Active attribute from the first button it will remain checked

**Comment by olton** [comment]
It possible with mode multi

**Comment by RandyOrton91** [comment]
Yeah I know, but It'isnt possible to do it with single selection? It was possible in metro 3, I did it

**Comment by olton** [comment]
Ok, I add this feature tomorrow

**Comment by RandyOrton91** [comment]
Awesome, thank you!

**Comment by olton** [comment]
Added
