### ISSUE TITLE
Can't assign value to Select

### ISSUE THREAD

**Issue by IvanVasquez** [olton/Metro-UI-CSS#1030]
Hi, I've a select with the **data-role="select"** and I'm trying to set the value at runtime with jQuery but it doesn't work, my select look like this:
`<select name="option" data-role="select" data-validate="required not=-1">`
 `<option value="-1" class="d-none"></option>`
`<option value="1">Option 1</option>`
`<option value="2">Option 2</option>`
`<option value="3">Option 2</option>`
`</select>`
I already tried to use the method **Metro.reinitPligin($("select[name=option]"), 'select')** but only creates a new one inside the original

**Comment by olton** [comment]
Changing option at runtime will be added in 4.1.0

**Comment by olton** [comment]
Methods `destroyPlugin`, `initPlugin`, `reinitPlugin` now in development, not for all components have a method `destroy`.

**Comment by olton** [comment]
Added, read docs for select

**Comment by IvanVasquez** [comment]
Hi again, I tried to create a single method inside the data('select') object to assign the value using the data method

`value: function (val) {`
`            var element = this.element;`
`            element.find("option:selected").removeAttr("selected");`
`            element.find("option[value='" + val + "']").attr("selected", "true");`
`            this.data(element.prop('innerHTML'));`
`        },`

**Comment by olton** [comment]
Thanks, but everything is somewhat more complicated :) wait for 4.1.2 (today)

**Comment by olton** [comment]
Added. Use method `val()`. More info in documentation

**Comment by jeffreyhyw** [comment]
Hi, I've tried to use append function to  assign value to the select component but it doesn't work. Could you point me out what did I miss in the code?

```
<html>

<head>
    <link rel="stylesheet" href="css/metro-all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="js/metro.min.js"></script>

</head>

<body>
    <select data-role="select" id="custom_select_list">
    </select>


    <!--JavaScript at end of body for optimized loading-->
    <script>
        $(document).ready(function() {
            $('#custom_select_list').append($('<option>', {
                value: "myvalue",
                text: "mytext"
            }));
        });
    </script>
</body>

</html>
```

**Comment by olton** [comment]
Use select api method `data()`. Example https://github.com/olton/Metro4-Docs/blob/master/public_html/examples/ajax/select.html

**Comment by jeffreyhyw** [comment]
Thanks a lot! Saved my day :)

Changed the code to this and it worked!
```
$(document).ready(function() {
    var select = Metro.getPlugin("#custom_select_list", 'select');
    select.data({
        "myvalue": "mytext",
        "myvalue2": "mytext2"
    });
});
```
