### ISSUE TITLE
App Bar and... Edge

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1034]
Again me and Microsoft browsers ^^
When collapsed mode wih EDGE (not tested with IE), each line of menu is bigger as waiting : 

![image](https://user-images.githubusercontent.com/35603194/37519636-2024e4ea-291a-11e8-8c46-662f1b5d6031.png)

**Comment by olton** [comment]
Same bug in IE11. At the moment I do not have a solution :(

**Comment by olton** [comment]
Fixed

**Comment by arjarn** [comment]
You're the best ;-)

Many thanx for your reactivity.
Surely made others issues : I'm testing different menu for a site...
