### ISSUE TITLE
menu-title in d-menu cannot be like in v-menu?

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1039]
so, use "divider" only?  
menu-title in d-menu can trigger hover and click event. Should it be like in v-menu?

**Comment by olton** [comment]
menu title not present in d-menu

**Comment by olton** [comment]
You can use `v-menu` to create dropdown menu https://codepen.io/olton/pen/mxewyM

**Comment by taurenshaman** [comment]
thank you. I copied the code, but not worked very well in app-bar-container. So I split one d-menu to mutiple menus -_-
https://github.com/olton/Metro-UI-CSS/issues/1002

**Comment by olton** [comment]
I added support `v-menu` for `app-bar` in 4.1.1

https://codepen.io/olton/pen/BrpGbj
