### ISSUE TITLE
Minor Glitch!

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1043]
Metro-UI version 4.1.2

<PRE>
&lt;INPUT id="DUMMY" name="dummy" type="text"
       class="text-center"
       data-role="input"
       data-clear-button="false" /&gt;
</PRE>

The right border of the field is not drawn.

Thank's

**Comment by olton** [comment]
All ok for me

https://codepen.io/olton/pen/xWdaKY

**Comment by TorakikiSan** [comment]
Sorry, missing DIVs:

<pre>
&lt;DIV class="row mb-2"&gt;
   &lt;LABEL class="cell-sm-1 offset-1 text-bold text-right" for="CRC"&gt;Search&lt;/LABEL&gt;
   &lt;DIV class="cell-sm-1"&gt;
      &lt;INPUT id="CRC" name="crc" type="text" class="success"
                data-role="input"
                data-clear-button="false"
                data-validate="maxlength=8" value="" /&gt;
   &lt;/DIV&gt;
   &lt;DIV class="cell-sm-4"&gt;
      &lt;INPUT id="SHA1" name="sha1" type="text" class="success"
                data-role="input"
                data-validate="maxlength=40" value="" /&gt;
   &lt;/DIV&gt;
   &lt;DIV class="cell-sm-1"&gt;
      &lt;INPUT id="ROM" name="rom" type="text" class="success"
                data-role="input"
                data-clear-button="false"
                data-validate="maxlength=30" value="" /&gt;
   &lt;/DIV&gt;
&lt;/DIV&gt;
</pre>

**Comment by olton** [comment]
Please read contributing for issues

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/CONTRIBUTING.md#issues-guidelines
