### ISSUE TITLE
bug of the new v-menu in 4.1.2

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1045]
Case:
https://codepen.io/taurenshaman/pen/JLJBzJ

Ref:
https://github.com/olton/Metro-UI-CSS/issues/1039

**Comment by olton** [comment]
At the moment, I'm restructuring the `app-bar` component, while I can recommend use `v-menu` inside the `app-bar-menu` element. 
More about `appbar` https://metroui.org.ua/app-bar.html 
V-menu iside an app-bar https://codepen.io/olton/pen/BrpGbj

**Comment by olton** [comment]
+ [x] App bar: fix using `.v-menu` in `.app-bar-container`

**Comment by olton** [comment]
Example https://metroui.org.ua/examples/github/github.html

**Comment by olton** [comment]
Wait for CDN update

**Comment by olton** [comment]
https://codepen.io/olton/pen/XEaKxX
