### ISSUE TITLE
Will Fluent's design be supported?

### ISSUE THREAD

**Issue by AGDholo** [olton/Metro-UI-CSS#1047]
Fluent already has detailed documentation and design criteria.
Reference: https://fluentweb.com/ Existing React & Angular Versions.
And: https://fluent.microsoft.com/
This is Microsoft's new design language, just like Metro.
I have this problem with the premise, but it has been closed because fluent has no specific design document.

**Comment by olton** [comment]
Active development in the direction of fluent design will begin after I collect the amount on Patreon (https://www.patreon.com/metroui) sufficient for the half-time work on the project
