### ISSUE TITLE
Questions about navview/container-fluid

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1050]
Scene:
UWP style.

1. cannot adjust to height 100%
I must set height of the navview if menu items is very few; And if its height will be 0 if there is no items and not set height.
https://codepen.io/taurenshaman/pen/JLJBzJ
Tried but not work:
a. Desktop css (https://metroui.org.ua/examples/desktop/desktop.html);
b. set h-100

2. Can some items (e.g. settings) placed on bottom?

Thank you very much!

**Comment by olton** [comment]
1) change your container to: `<div class="container-fluid bg-gray h-vh-100">`
2) To place item to bottom:
```
<li class="pos-absolute pos-bottom-left">
                    <a href="#">
                        <span class="icon"><span class="mif-cog"></span></span>
                        <span class="caption">Settings</span>
                    </a>
                </li>
```

**Comment by taurenshaman** [comment]
1. done
2. This solution only support one item on bottom. Second one will be overlapped.
see Settings and Profile: https://codepen.io/taurenshaman/pen/JLJBzJ

Thank you~

**Comment by olton** [comment]
https://codepen.io/olton/pen/NYyyxo
