### ISSUE TITLE
File browser name formatting

### ISSUE THREAD

**Issue by cptx032** [olton/Metro-UI-CSS#1051]
If I upload a image with a large text i get something like that:

![image](https://user-images.githubusercontent.com/12432805/38091716-ba0b7c50-333c-11e8-8f5c-42772e96aaca.png)

I try it in last version of Google Chrome. This screeshot is in example here: https://metroui.org.ua/forms.html?

Is possible make Metro show file name with "..." or something like that?

**Comment by olton** [comment]
Thanks, overflow fixed in 4.1.8
