### ISSUE TITLE
navview-menu li icon not aligned correctly

### ISSUE THREAD

**Issue by ChiyodaRuri** [olton/Metro-UI-CSS#1052]
The icon for a menu li only aligns to the top, never the middle.

+----------+ 
|____icon___|
|____________|    Menu Item Caption
|____________|
+----------+

This means you cannot create visually appealing menus because the icon is aligned top and the text is aligned middle.

**Comment by olton** [comment]
Menu type?

**Comment by olton** [comment]
Create pen on codepen.io

**Comment by olton** [comment]
All ok for me. Check your metro version
