### ISSUE TITLE
Metro Icon Font sometimes doesnt show up

### ISSUE THREAD

**Issue by omowaku** [olton/Metro-UI-CSS#1054]
We use Metro-UI-CSS and its  Metro Icon Font feature in our project. 

But sometimes, the fonts do not show up in some embedded browsers.

What might be the causes ? Is there any work around ?

Thanks very much for the  Metro-UI-CSS team!

**Comment by omowaku** [comment]
This is the URL for the page.

http://www.buit2b.com/buit2b/guest/tablecodeseq/8a101c315b426316015b461438050496?tableid=seq

**Comment by olton** [comment]
All ok for me
![2018-04-01_12h55_23](https://user-images.githubusercontent.com/365108/38171955-ff02ee8a-35ab-11e8-94c2-c81c5a28847a.png)

**Comment by omowaku** [comment]
Thanks for confirmation!

**Comment by olton** [comment]
which browser are you using?

**Comment by omowaku** [comment]
There are two cases, in which we encountere this problem. 

1, In the WeChat embedded browser (The screenshots provided)
2, In our own android app using the embedded browser(webkit). If we reinstall the app, the problem disappears.

**Comment by olton** [comment]
At the moment I do not support Metro 3. At least until I gain enough financial support for Patreon. Sorry. No time to support all versions.
