### ISSUE TITLE
Right-floated in navbar?

### ISSUE THREAD

**Issue by thomasuebi** [olton/Metro-UI-CSS#1055]
Hey guys, first of all: good work! Metro-UI-CSS 4 is awesome!

It was no problem to right-align an element in the navbar component in the earlier version, but now it is. And i can't figure out why it is handling that strange... I also tried to work with the solution provided by you called "clear float" - but it doesnt work for any reason...

Hope someone is able to reproduce this issue and may help.

Best regards, Thomas

**Comment by olton** [comment]
If you mean the `appbar`, the support for `rtl` for it is still in development

**Comment by thomasuebi** [comment]
Super example, thank you very very much! :)
