### ISSUE TITLE
bug: icon of panel align to top, not center

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1058]
https://codepen.io/taurenshaman/pen/JLJBzJ

**Comment by olton** [comment]
All ok

![2018-04-01_12h53_13](https://user-images.githubusercontent.com/365108/38171921-a6694ecc-35ab-11e8-8f2b-372c77d827d8.png)

**Comment by olton** [comment]
which browser are you using?

**Comment by taurenshaman** [comment]
Opera 52.0.2871.40
Maybe it's Opera's problem.
IE 11 and Edge are both ok.

**Comment by olton** [comment]
In my opera all ok Ver:  51.0.2830.55 Stable Windows 10 64-bit

![2018-04-02_14h35_26](https://user-images.githubusercontent.com/365108/38194893-1c538940-3683-11e8-9b41-6eea789eba39.png)
