### ISSUE TITLE
data-cls-active has no effect on default active button in buttongroup

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1059]
If a button is active  by default, data-cls-active has no effect on it, and it has a default background (gray). Except you click it, it will work. But if another button is active, that default button will be in gray background again.
https://codepen.io/taurenshaman/pen/oqdeoK

**Comment by olton** [comment]
Create class for active state
```
.btn-active {
    background: orange!important;
    color: white!important;
}
```
Create group
```
<div class="ml-5 mt-5" data-role="buttongroup"
     data-cls-active="btn-active">
    <button class="button">1234</button>
    <button class="button">ABCD</button>
    <button class="button btn-active">Default</button>
</div>
```
