### ISSUE TITLE
Forum or Chatroom project ?

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1063]
Not real issue with this message but I'm wondering if you project to have forum or chatrrom (like https://gitter.im ) for MetroUI where users can sharing tips.

**Comment by olton** [comment]
[![Join the chat at https://gitter.im/metro4/Lobby](https://badges.gitter.im/metro4/Lobby.svg)](https://gitter.im/metro4/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
