### ISSUE TITLE
Under in the prompt box Perform validation the operation  be prevented from

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1068]
https://codepen.io/dreamcc/pen/PQRwrZ
The location of The problem in js has been marked.
expect can get the solution
Thank you

**Comment by olton** [comment]
the question is not clear

**Comment by olton** [comment]
In your code form and input have same `id` property

**Comment by olton** [comment]
Check your code before submitting issue! Respect my time, please!
