### ISSUE TITLE
How to remove clear (X) button from textarea (no undo possibility on accidental cleanning)

### ISSUE THREAD

**Issue by leandroisrael** [olton/Metro-UI-CSS#1070]
Hi, 

I'm using Metro UI in a ticket system. My issue is that sometimes the user will write a long text in a textarea, then accidentaly, he can click in that cross icon. The CTRL+Z feature can note recover the text.

Check the code:

[CODEPEN Example](https://codepen.io/anon/pen/bvZbpQ)

I have not found a way to remove that cross, And I want the auto-size feature.

Regards

**Comment by olton** [comment]
https://codepen.io/olton/pen/ZxPEWK

**Comment by leandroisrael** [comment]
Many thanks by the `data-clear-button="false"`
=]
