### ISSUE TITLE
Calendar picker input button not rendering correctly on Firefox with grid < 1200px and Segoe UI

### ISSUE THREAD

**Issue by rcheung9** [olton/Metro-UI-CSS#1072]
This renders correctly on IE and Chrome but on Firefox, the calendar button is outside the box.

Using "Segoe UI" and Max-Width of 1000px (Problem)
https://codepen.io/anon/pen/EEJXGE

Using "Segoe UI" and Max-Width of 1200px (No Problem)
https://codepen.io/anon/pen/NYmvdp

Although at below 1000px, no font renders correctly on firefox.
https://codepen.io/anon/pen/LdvjjK

**Comment by olton** [comment]
This is a firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1043520
I fix this behavior in 4.1.14 (maybe today)

**Comment by olton** [comment]
fixed
