### ISSUE TITLE
Vue.JS and List Rendering

### ISSUE THREAD

**Issue by xJoeyv** [olton/Metro-UI-CSS#1073]
Hi,

After the fix for loading Vue with metro I still wonder how to list render and do other stuff with Metro and Vue. The list rendering will be done via vue since Vue makes the Ajax Call and then should update the List. I'm using a listview from metro

**Comment by olton** [comment]
Create code example on codepen.io

**Comment by xJoeyv** [comment]
@olton I hope you can find a solution to this that would be awesome. Since the components you made are amazing. https://codepen.io/xjoeyv/pen/MVRGJr

**Comment by olton** [comment]
Use
```
<li v-for="todo in todos" 
                :data-icon="todo.icon"
                :data-caption="todo.caption"
                :data-date="todo.date"
                :data-name="todo.name">
```
and
```
      this.todos = [
      { icon: "<span class='mif-folder'></span>", caption: "Images", date: "12/21/2017", name: "Test Name"},
      { icon: "<span class='mif-home'></span>", caption: "Something", date: "12/21/2018", name: "Home Sweet Home"}
      ];

```

**Comment by olton** [comment]
Also, in the 4.1.14, I will correct table mode view for listview

**Comment by olton** [comment]
https://codepen.io/olton/pen/ZxZoZm
