### ISSUE TITLE
Allow right and wheel clic on tile

### ISSUE THREAD

**Issue by FloOows** [olton/Metro-UI-CSS#1074]
I used to _wheel click_ inside my browser to open the link in a new tab. But using tile of MetroUI v3, it opens link in both new tab and current tab.
Is that a bug or a wanted behavior? Is there a workaround to that. I tried to debug the code, but I wasn't able to find a solution.

Here is an extract of my code creating tiles
```
      <div class="tile-group one">
            <div class="tile-container">
		<a href="www.google.fr" class="tile bg-cobalt fg-white" data-role="tile">
                    <div class="tile-content iconic">
                             <span class="icon mif-microscope"></span>
                    </div>
                    <span class="tile-label">LABEL</span>
                </a>
            </div>
       </div>
```
				

Thanks & Regards

**Comment by olton** [comment]
This is probably a browser problem, not a library

**Comment by FloOows** [comment]
Tested KO with 

- Google Chrome v65
- IE 11
- Firefox 56

If it does work on your browser I guess there is a option I set differently.

**Comment by olton** [comment]
In m3 has not implemented any methods for click event for the anchor in a role a tile
https://github.com/olton/Metro-UI-CSS/blob/metrouicss-3x/js/widgets/tile.js#L46
