### ISSUE TITLE
Why don't the sizing classes have all responsive modifiers?

### ISSUE THREAD

**Issue by kdam** [olton/Metro-UI-CSS#1077]
The documentation for [Sizing](https://metroui.org.ua/sizing.html?) says

> All sizing utilities classes has media variants with breakpoints suffixes: `-sm`, `-md`, `-lg`, `-xl`, `-xxl`.

However, it looks like there are only the following (using `w` as example): `w-25-fs`, `w-50-sm`, `w-75-md`, `w-100-lg`.

Why are there no classes like `w-25-md`, `w-25-lg`, `w-100-sm`, etc...?

I ask because I would like the [tabs](https://metroui.org.ua/tabs.html) to have 100% width on small screens, and then only 25% width on medium screens, but there does not seem to be a way to do this using the sizing classes.

**Comment by olton** [comment]
Thank you, This is a bug. I will correct it in 4.1.16

**Comment by olton** [comment]
fixed

**Comment by asdsteven** [comment]
However, it now generates
``w-0-sm w-25-sm w-50-sm w-75-sm``  etc
instead of the expected
``w-25-sm w-50-sm w-75-sm w-100-sm`` etc

**Comment by olton** [comment]
Thank you, fixed in 4.2.19
