### ISSUE TITLE
Overflow Boxes for Dialogs and Windows

### ISSUE THREAD

**Issue by hydexon** [olton/Metro-UI-CSS#1079]
**Feature Request:** 
I use Modal dialogs in Metro CSS (Moving an former UIKit 3 project to Metro CSS) for adding and editing data from forms, and kinda messes up when is used in mobiles, specially when the form has many fields, and once they overflow, there's no way to scroll back to the rest of the controls in the dialog, only the page itself, the dialogs will remain static.

UIKit3 has an component called `uk-overflow` as seen [here](https://getuikit.com/docs/modal#overflow) which allows multiple content and controls to be inside of an dialog.

Thanks.

**Comment by olton** [comment]
https://codepen.io/olton/pen/RyVjxw
