### ISSUE TITLE
TreeView not to collapsed

### ISSUE THREAD

**Issue by deepikasharma810** [olton/Metro-UI-CSS#1080]
Hi,
I am using  Treeview in my program and I want the Treenodes not expanded at begining.
In version 3 there was a possibility to collapse or expand the Nodes at the begining but in version 4 I cant find any possiblity.

Please Help!

**Comment by Tazzzilo** [comment]
I've created a pen:
https://codepen.io/anon/pen/yQEmdQ

The "Projects" Item is not visible when using class="collapse". 

Is therey any css workaround / update for a default collapsed item?

**Comment by olton** [comment]
Usev attribute data-collapse=true, not class

**Comment by Tazzzilo** [comment]
Thanks for the fast reply.
I've updates the pen but using this attribute don't have any influence. 
https://codepen.io/anon/pen/yQEmdQ
