### ISSUE TITLE
Wizard buttons always active with form validator

### ISSUE THREAD

**Issue by IvanVasquez** [olton/Metro-UI-CSS#1083]
I have a Wizard inside a form with the Metro validator and the control buttons aren't displaying correctly (after first click on next, all keep active)
Here's an example: http://jsbin.com/calonay/2/edit?html,js,output

Also, is there a way to hide the control buttons? I'm using $(".wizard-btn-help").hide();

**Comment by olton** [comment]
fixed in 4.1.18
