### ISSUE TITLE
calendarpicker,Date picker, preset value

### ISSUE THREAD

**Issue by nlared** [olton/Metro-UI-CSS#1084]
example
data-role="calendarpicker" value="1972/12/21" shows 1972/12/20

**Comment by olton** [comment]
This problem occurs if your local time zone is gmt -x. fix this problem in work.

**Comment by olton** [comment]
what is your timezone?

**Comment by nlared** [comment]
America/Monterrey*UTC-6*, UTC-5

2018-04-26 11:50 GMT-05:00 Sergey Pimenov <notifications@github.com>:

**Comment by olton** [comment]
Fixed, wait for 4.2.7 update
