### ISSUE TITLE
Activity overlay prb :/

### ISSUE THREAD

**Issue by hossemThecoder** [olton/Metro-UI-CSS#1087]
![capture](https://user-images.githubusercontent.com/18426424/39387814-1a26aca8-4a7c-11e8-9cc0-0e2562991560.PNG)
whene i try to show metro activity but i always get this prb !! this is the code btw
`	<button class="button"
        onclick="
            var activity = Metro.activity.open({
                type: 'square',
                overlayColor: '#fff',
                overlayAlpha: 1
            });
            setTimeout(function(){Metro.activity.close(activity)}, 5000)
        ">Open</button>`

**Comment by olton** [comment]
This new in 4.1.20
