### ISSUE TITLE
Unable to open Window

### ISSUE THREAD

**Issue by vivekSingh2984** [olton/Metro-UI-CSS#1088]
Hi Team,

I am Vivek, using metro 4 in my web application, but I am unable to open Window and set it ID, its always regenerated. I want to open Window box on base of Id as we open dialog box. and on close i dont want to remove DOM from page i just want hide.

**Comment by olton** [comment]
Create pen with your code on codepen.io

**Comment by vivekSingh2984** [comment]
Hi Olton,
Thanks for reply.
below is pen url.
https://codepen.io/viveksingh2984/pen/ervLZa?editors=1111


![2](https://user-images.githubusercontent.com/38847202/39465374-b5eea12e-4d40-11e8-83ac-46690ce07045.png)
![issue1](https://user-images.githubusercontent.com/38847202/39465375-b61de1f0-4d40-11e8-9edd-dcc4e570ae0a.png)

**Comment by vivekSingh2984** [comment]
Hi Olton,
Thanks for reply.
below is pen url.
https://codepen.io/viveksingh2984/pen/ervLZa?editors=1111
![2](https://user-images.githubusercontent.com/38847202/39465438-001c481e-4d41-11e8-96ee-4251fa5280f0.png)
![issue1](https://user-images.githubusercontent.com/38847202/39465439-004bf65e-4d41-11e8-96c4-349ba0c1e2dd.png)

**Comment by olton** [comment]
https://codepen.io/olton/pen/WJpgYm

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/desktop

**Comment by olton** [comment]
https://codepen.io/olton/pen/WJpgYm
Check if you are using the latest version (4.2.2).

**Comment by vivekSingh2984** [comment]
Hi Olton, 

Thank you for update 'window' plugin,

did you also changed in css?

because after adding latest metro.js window popup not seen as previous.

**Comment by olton** [comment]
Screenshot please
