### ISSUE TITLE
Want to use it on rails 5.1.4

### ISSUE THREAD

**Issue by ehsanatwork** [olton/Metro-UI-CSS#1091]
Hello,
can you please tell me how can i use metro ui in Ruby on Rails Project.
rails version is 5.1.4.

Thank You

**Comment by olton** [comment]
I personally never used Ruby on Rails. Sorry, but, maybe someone from the library users to help you. I myself would be interested to know this.

**Comment by ehsanatwork** [comment]
thank you @olton 
lets see is their any one who can help me.

thanks again
