### ISSUE TITLE
Form validator : reset ?

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1092]
Hello Olton,

Is there a way to reset form validator ?
I've got a form in a dialog  : when I click cancel (button type=reset) my dialog is closed and value reseted.
But if I call the form again it load with the last validator state.

**Comment by olton** [comment]
create example pen for your problem code on codepen.io

**Comment by Falconpage** [comment]
https://codepen.io/Falconpage/pen/dedVex

Click test then add a value to input name only then press the test button.
Form Validator display errors.
Press Cancel : form is closed and reseted.
Now load de form again : as you can see the validator is not reseted.

**Comment by olton** [comment]
https://codepen.io/olton/pen/jxZxpP

Let it be for now. In 4.2.6, I'll add the method to the validator

**Comment by olton** [comment]
### 4.2.6
+ [x] Validator: add func `reset` for reset field state
+ [x] Validator: add auto method `reset` for forms with role `validator`

**Comment by Falconpage** [comment]
Perfect, thanks ! Great work
