### ISSUE TITLE
Form Validator : can't use validator if not required

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1094]
In this example if you try to validate email input but do not want this input to be required it will be impossible to submit.
In a not required field the validate process have to be call only when the field is not empty.

https://codepen.io/Falconpage/pen/dedVex

Put a name, try to submit.

**Comment by olton** [comment]
What the value you use for email field?

**Comment by Falconpage** [comment]
No value because this is not a required field, in this example only the name is required.
But in the case the email I write an email I want it to be checked.

**Comment by Falconpage** [comment]
<input type="text" data-validate="required" name="nickname">
-> this field is required

<input type="text" data-validate="email" name="email">
-> this field is not required but have to be checked. The problem is that the validator have to check email format only if the field is not empty.

**Comment by Falconpage** [comment]
My workaround for this issue is to use a regex pattern adding ^$| to allow empty field.

Exemple for an email.
`data-validate='pattern=^$|^[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]{2,}\.[a-z]{2,4}$'`

**Comment by olton** [comment]
https://codepen.io/olton/pen/wjyYgM
Validator checks field, also if it empty

**Comment by olton** [comment]
if you need empty field and only email value if not empty, you must use a custom pattern or custom validation function.

**Comment by Falconpage** [comment]
Yes, why not checking the field only if the field is empty (when required is not present) ?

**Comment by olton** [comment]
I will think about this proposal

**Comment by Falconpage** [comment]
Thanks.

**Comment by olton** [comment]
### 4.2.6
+ [x] Validator: add func `reset` for reset fields state
+ [x] Validator: add func `reset_state` for reset field state
+ [x] Validator: add func `set_valid_state` for valid field state
+ [x] Validator: add func `set_invalid_state` for invalid field state
+ [x] Validator: add auto method `reset` for forms with role `validator`
+ [x] Validator: add option boolean `requiredMode` for form. If this option is `true`, all funcs works as `required`, else funcs works if field value is not empty.

**Comment by olton** [comment]
Functions mode
New in 4.2.6

By default, all validating functions work in required mode - field value cannot be empty and must have required value. You can change this behavior with special form attribute data-required-mode. If you set this attribute to false, functions will work only if field value not empty or with required function in the pair.

**Comment by Falconpage** [comment]
Great ! This make your form validator a complete solution.
Thanks again.

**Comment by olton** [comment]
4.2.6 released

**Comment by olton** [comment]
https://metroui.org.ua/validator.html#_validator_functions_mode
