### ISSUE TITLE
Resizable tools

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1100]
Like draggable tool, it may be usefull having resizable tool like this : 

http://docs.sencha.com/extjs/4.2.3/extjs-build/examples/resizer/basic.html

Do u think including it in Metro-UI ?

**Comment by olton** [comment]
https://codepen.io/olton/pen/BOpxGg

**Comment by arjarn** [comment]
Look great !

With Firefox 6.1.0.2 and Windows 10, when I click to resize, once mouse button up, resizing is always active and I can't validate the new size...

**Comment by olton** [comment]
Thanks, this fixed in 4.2.21

**Comment by olton** [comment]
Also in 4.2.21 I added new options for resizeable component:
`data-min-width`, `data-max-width`, `data-min-height`, `data-max-height`, `data-can-resize`
