### ISSUE TITLE
Floating action button

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1103]
Hi,

as Metro-UI is Mobile First, it may be great having Floating action button like in Core_CSS : https://coreui.net/docs.html#floatingaction  

Especially multi action button, its look'n'feel very nice and usefull in mobile app.

Do u think it may be possible in future ?

Thanks for your great working.

**Comment by arjarn** [comment]
Waooh nice !

Thanx :)

**Comment by olton** [comment]
added in 4.2.10
