### ISSUE TITLE
Notify System

### ISSUE THREAD

**Issue by deepikasharma810** [olton/Metro-UI-CSS#1104]
Hello,
Notify system is not working.
I have included metro.js, metro.min.js  and jquery-3.3.1.min.js, it gives no error but doesn't shows the Notify.
I have followed all the steps described.
Please help.

Deepika

**Comment by olton** [comment]
Create pen on codepen.io with your code

**Comment by olton** [comment]
https://codepen.io/olton/pen/NMZYyr

**Comment by olton** [comment]
https://metroui.org.ua/intro.html
