### ISSUE TITLE
Tiles Example: Touchpad Scroll Behavior

### ISSUE THREAD

**Issue by stevennt** [olton/Metro-UI-CSS#1106]
Regarding this Tiles example: Where can we change the touchpad scroll behavior? Right now scroll up-down becomes left-right. It is just very hard for users to use without a mouse.

In this same example, what can we change to have the full-responsive effect for phone? Currently it is not responsive.
Thanks.
https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/tiles

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/docs/examples/tiles/start.js#L25
