### ISSUE TITLE
Feature request: Datepicker check & close button position

### ISSUE THREAD

**Issue by jeorlie** [olton/Metro-UI-CSS#1107]
Greetings,
I'm testing your library especially the datepicker. I love it, but I can I request a feature or kindly tell me if such feature already exist. I'm been reading docs and found nothing.

**_Can you add option for the buttons where we can change position the button check and the close button on top._**

Upon testing, I encountered that I cannot select date when the screen is too small, the screen is blocking the check button on the datepicker.

NOTE:
This datepicker is inside the "charms" and fixed div; both having width set to 100%. This datepicker was position to the bottom and when you want to change the date, you can't since the okay/check button is hidden due to the screen being to small.

Is there a workaround here? I tried adding `<br>` to add more space but this is not working.

**Thank you.**

**Comment by olton** [comment]
I must see your problem visually. Please create a pen on the codepen.io with your problem code.

**Comment by olton** [comment]
Added to TODO for 4.2.10

**Comment by olton** [comment]
Temporary I added in 4.2.9 classes `.for-top` and `.for-bottom`. You can use it as:

if picker (date or time) placed on top of parent
```
<input type="text" data-role="timepicker" data-cls-picker="for-top">
```

if picker (date or time) placed on bottom of parent
```
<input type="text" data-role="timepicker" data-cls-picker="for-bottom">
```

**Comment by olton** [comment]
fixed
