### ISSUE TITLE
Calendar Picker not displaying correctly after a display hide/show. 

### ISSUE THREAD

**Issue by quinnpetersen** [olton/Metro-UI-CSS#1112]
With the project we're creating we have a filter that we can hide and show. After the initial load the calendar picker looks like this:
![capture15](https://user-images.githubusercontent.com/40033572/41315618-477c87d2-6e4d-11e8-8bfe-53cc9f186130.PNG)

After you select something it goes back to normal. Also, if you load the page without the hide/show it displays correctly or if you preload the value in the html. (Sadly we don't want to preload with a date.)

Any ideas on how to fix this?

**Comment by olton** [comment]
Create pen on codepen.io with your problem

**Comment by quinnpetersen** [comment]
Here it is!

https://codepen.io/ItsKevinMalone/pen/wXdOoP

Thanks for looking at this so quick!

**Comment by olton** [comment]
I fix this in next release. Temporary, You can use this style to fix it:
```
.calendar .days-row .day {
  height: 36px!important;
  line-height: 36px!important;
}
```

**Comment by quinnpetersen** [comment]
You're amazing, thanks for you help!!
