### ISSUE TITLE
App bar - Nested dropped down sub menus are not shown

### ISSUE THREAD

**Issue by MarcMegabyte** [olton/Metro-UI-CSS#1114]
Hi,

nested dropped down menus are working great in normal view.
But in mobile view (or resized browser) only the first dropdown menu is displayed.
It is clickable, but no content is shown. Is the number of submenus in mobile view limited?

[Example Pen](https://codepen.io/anon/pen/RJjzRv)

Kind regards,
Marc

**Comment by olton** [comment]
Thank you. I fix it in next release.
Currently use this additional styles:
```
.app-bar .d-menu .d-menu {
  left: 0;
}

@media all and (min-width: 768px) {
  .app-bar-expand-md .d-menu .d-menu {
    left: 100%;
  }
}
```

**Comment by MarcMegabyte** [comment]
Thank you for your quick response! That fix works perfect!
