### ISSUE TITLE
Selecting the value in Run time for select

### ISSUE THREAD

**Issue by aboodh95** [olton/Metro-UI-CSS#1116]
Hi

in case i did select the option using select plugin, it will not reflect on the ui once the user will open the select
![image](https://user-images.githubusercontent.com/12459798/41587815-287ef832-73c1-11e8-9de5-411493267f21.png)

`
 var select = $(selectWeeks).data('select');
            if (openEditRecord != "") {
                select.val(openEditRecord);
            }
`
![image](https://user-images.githubusercontent.com/12459798/41587897-56a48556-73c1-11e8-8f62-a35929dcd2b1.png)

i hope you get my point, because when the select will have too much options it will get confusing

**Comment by olton** [comment]
Thanks, method `val` in `select` has an error. I fix this error in 4.2.9

**Comment by aboodh95** [comment]
Thank you so much,

When the expected release date ?

**Comment by olton** [comment]
On this week
