### ISSUE TITLE
How to do removeClass on a Input at runtime

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1117]
Hi

I am trying to switch from Bootstrap4 to Metro 4

In BS I could do 
$("#usernameinput").removeClass("alert");
("#usernameinput").addClass("success");
(To change the border from red to green)

However, in Metro, this has no effect?

For <select> I found the trick of using .data() but can't find how to do it for Inputs?

**Comment by olton** [comment]
In Metro 4, if you use role for input `<input type="text" data-role="input">`, Metro create wrapper for input element. And all classes must be added to input wrapper.

https://codepen.io/olton/pen/xzYmRa

**Comment by openbuilds-engineer** [comment]
(: Sorted!!   Thanks sooo much!
