### ISSUE TITLE
Long Treeview list doesn't render probably

### ISSUE THREAD

**Issue by Tazzzilo** [olton/Metro-UI-CSS#1121]
Hello,
I've created a very long treeview list out of mysql database entries. 
When it's very large the parts out of the screen will not get rendered probably. But the HTML source code is correct. 
On the screenshot, you can easily see where the rendering is not working probably. It's the same problem in FF 60.x and IE11. It will shown probably, if you don't have the "creation delays" due to the database querries. 
Is there any workaround for the moment? 
![treeview_bug](https://user-images.githubusercontent.com/31939403/41723713-142dff3e-756c-11e8-994a-84e94b0aa556.png)

**Comment by olton** [comment]
create pen on codepen.io with your problem code
