### ISSUE TITLE
Hovering over another element with a "hint", closes the hint on slider, even if data-hint-always=true is set 

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1126]
Demo:
https://codepen.io/anon/pen/WyzLqj

Sliders show their Hint when the page loads, beautiful. 
But as soon as you hover the mouse over the Minimise or Maximise buttons on the top-right corner (window) the Hints on the Sliders, disappear

They only come back when page is refreshed

**Comment by olton** [comment]
Thanks. I fix it in 4.2.10

**Comment by openbuilds-engineer** [comment]
You are too awesome! Always quick as can be!

**Comment by olton** [comment]
fixed
