### ISSUE TITLE
Date in calendar picker not rendering correctly on chrome.

### ISSUE THREAD

**Issue by maartinez** [olton/Metro-UI-CSS#1127]
Hi, I have this input:

`<input id="date-from" type="text" data-role="calendarpicker" data-clear-button="true" data-locale="pl-PL" data-format="%d-%m-%Y" data-value="01-03-2018" value="01-03-2018">`

When page is opened in Firefox date looks ok: 01-03-2018
When page is opened in Vivaldi or Chromium month and date are changed: 03-01-2018
Metro UI ver 4.2.10.686

**Comment by olton** [comment]
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

**Comment by olton** [comment]
Read about dates in https://metroui.org.ua/calendar.html

**Comment by maartinez** [comment]
OK, so I found out that value must come in this format: 2018/03/01, not with "-". Data-format is changing than to 01-03-2018 and now it is rendered correctly everywhere. Sorry for that.
