### ISSUE TITLE
data-role="table" issues?

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1129]
Is it possible that a TABLE with data-role="table" does not use the classes applied to the TD tags?

And the sorting in a column containing formatted numbers, the attribute data-format="number" works only with the decimal and group separator for english / american? In Italy, we have the "," (comma) as the decimal separator and the "." (dot) as a separator of the thousands.

Finally, the colspan attribute is not recognized in the TFOOT section.

Thank you

https://codepen.io/TorakikiSan/pen/jKRpKo

**Comment by olton** [comment]
To add classes to the `td`, use attribute `data-cls-column="..."` for the `th` definition.
```
<THEAD>
<TR>
   <TH class="text-bold bg-teal fg-white">&nbsp;</TH>
   <TH class="sortable-column text-bold bg-teal fg-white">Macchina</TH>
   <TH class="text-bold bg-teal fg-white">Descrizione</TH>
   <TH data-cls-column="text-right" class="sortable-column text-bold bg-teal fg-white">Cloni</TH>
   <TH data-cls-column="text-right" class="sortable-column text-bold bg-teal fg-white">Dimensione</TH>
</TR>
```

**Comment by olton** [comment]
Features for the footer (colspan) and formatting I added into TODO for the 4.2.11

**Comment by TorakikiSan** [comment]
As usual, many thank's!

**Comment by TorakikiSan** [comment]
Little graphic issue: if I use the data-cls-column="text-right" attribute in the TH tag, the header text is also right-aligned, but it hides the "arrows" for sorting.

**Comment by olton** [comment]
Thanks

**Comment by olton** [comment]
Fixed, wait for 4.2.11

**Comment by olton** [comment]
I added 2 new attributes to `table`: `data-thousand-separator` and `data-decimal-separator`.

**Comment by olton** [comment]
![2018-07-04_20h34_04](https://user-images.githubusercontent.com/365108/42289667-a0b3ed4e-7fc9-11e8-9848-3494802bb988.png)

**Comment by TorakikiSan** [comment]
Great!

**Comment by TorakikiSan** [comment]
After other tests, can I suggest you two other attributes for the tag TABLE?

**data-money-symbol="€"** or "&amp;euro;" for **data-format="money"**

and

**data-date-format="%d/%m/%Y"** for date values

(of course, I wrote the names of the attributes just to give You an idea)

Thank's!

**Comment by olton** [comment]
attribute `data-format` I use only for right sorting, not for displaying.

**Comment by giuliohome** [comment]
> 
> 
> attribute `data-format` I use only for right sorting, not for displaying.

Sorry, is there a way to enter a custom sorting? For example by specifying a "_tag_" to interpret the cell (e.g. imagine I want to sort `"Jan 2019"`, `"Feb 2019"`, `"Mar 2019"`, I could tag them somehow as `"1 Jan 2019"`, `"1 Feb 2019"`, `"1 Mar 2019"`)
