### ISSUE TITLE
notify.create is not working

### ISSUE THREAD

**Issue by aboodh95** [olton/Metro-UI-CSS#1130]
Hi

i'm trying to call notify.create but nothing is happening, i'm suspecting the reason is i have tabs view, i already set the container to the main div (The parent) but still noting,
```
var notify = Metro.notify;
notify.create('The user who did the Check out is: ${editRecord.ets_CheckedOutBy.Name}, you need to ask him to check in so you can edit', "Warning", {
                            container: $(mainContainer),
                            keepOpen: true,
                            width: 400,
                            cls: 'warning'
                        });
```
the version i'm using is 4.2.8

**Comment by olton** [comment]
You must setup notify system before creating notifies into your own container:
```
Metro.notify.setup({
   container: $(".notifies")
});

function notify(){
    var notify = Metro.notify;
    notify.create('The user who did the Check out is: ${editRecord.ets_CheckedOutBy.Name}, you need to ask him to check in so you can edit', "Warning", {
        keepOpen: true,
        width: 400,
        cls: 'warning'
    });
}
```

**Comment by aboodh95** [comment]
Thanks that works and now it's appearing, but it's taking space from the view (it didn't cover the tab Container)
![image](https://user-images.githubusercontent.com/12459798/42273001-ef051094-7f98-11e8-9a4b-43aed2765465.png)

**Comment by olton** [comment]
Maybe need to add fixed or absolute position to your notifies container?

**Comment by aboodh95** [comment]
I add float-right to notify Container and the issue is solved 

Thanks
