### ISSUE TITLE
Understanding better data-role="table"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1132]
Please, look this codepen:

https://codepen.io/TorakikiSan/pen/jKRpKo

How can I have a table where I only care about sorting? No search, no pagination, no information, I would see all the lines (27 in this case). I tried different combinations of the attributes but I could not get the desired result.

Then, I defined the attribute

**data-cls-head="text-bold bg-steel fg-white"**

but, as you can see, in the header the color of the text is black, not white. Where am I wrong?

Thank's for all!

**Comment by olton** [comment]
https://codepen.io/olton/pen/pZzpqX

to set head cells color use attribute `data-cls-head-cell`
to view all rows use attribute `data-rows="-1"`
