### ISSUE TITLE
sidenav-m3 multiple  dropdown-toggle

### ISSUE THREAD

**Issue by loogn** [olton/Metro-UI-CSS#1134]
When sidenav-m3 has multiple dropdown-toggles, open the submenu and the next menu item icon is displayed incorrectly.

**Comment by olton** [comment]
Create pen on codepen.io

**Comment by loogn** [comment]
[ a pen](https://codepen.io/loogn/pen/rraLyz)

**Comment by olton** [comment]
@loogn  Thank you, I check it

**Comment by olton** [comment]
Fixed. Wait for 4.2.12 (today)

![2018-07-11_11h51_06](https://user-images.githubusercontent.com/365108/42560990-c2fbf1b2-8500-11e8-955b-d1ae45bb5edd.png)

**Comment by loogn** [comment]
@olton so cool，thanks!
