### ISSUE TITLE
custom tile size

### ISSUE THREAD

**Issue by georg90** [olton/Metro-UI-CSS#1135]
I'd like to know whats the best practice to use custom tile sizes.

I have a 1280x800px wide screen and I'd like to have an fullscreen 2x2 grid. I got this, using custom css to make the "large-tile" even larger e.g.

```
.tile-large {
      width: 640px !important;
      height: 400px !important;
    }
```

However, this isn't ideal, since all elements that use the fixed tile size as reference are off now (e.g. the  image set..)

Any best practices on this?

Thanks a lot!

**Comment by olton** [comment]
Tile sizes are implemented as they are described in the Microsoft Developers Guide. Custom sizes in Metro 4 are not provided. If you want to have your own tile sizes, you need to implement some subclasses of elements for these tiles.

**Comment by georg90** [comment]
thank you for your reply!
