### ISSUE TITLE
data-on-close-click wont work for windows

### ISSUE THREAD

**Issue by aeChriss** [olton/Metro-UI-CSS#1136]
If i use the "data-on-close-click" attrib for windows objects, the js crashed with the error:

**o.onCloseClick is not a function**

I removed the brackets from Line 297 (window.js) and all work finde...
`Utils.exec(o.onCloseClick(), [win], element[0]);`

**Comment by olton** [comment]
Thank you, I fix it today or tomorrow.

**Comment by olton** [comment]
fixed
