### ISSUE TITLE
Question: input data-role="search"

### ISSUE THREAD

**Issue by jcpc91** [olton/Metro-UI-CSS#1139]
👋🏽 !!
Question
I'm using intput data-role="search" and i need when user clicks on "X" button clear the results 
thanks

**Comment by ttujo** [comment]
<button onclick="document.getElementById('myInput').value = ''">Clear input field</button>

<input type="text" value="Blabla" id="myInput">
________________________________

**Comment by olton** [comment]
I don't quite understand your question. What does it mean to clear the search result?
You can use `custom buttons` for input to create your one specific action
