### ISSUE TITLE
Overlay Issues from Metro 3 to 4.0

### ISSUE THREAD

**Issue by Gurucharan** [olton/Metro-UI-CSS#1141]
Hex2rgba error. Bad Hex value Error: Hex2rgba error. Bad Hex value
    at Object.hex2rgba (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:46029)
    at Object._overlay (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:132690)
    at Object._build (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:131948)
    at Object._create (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:130995)
    at Object.init (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:130287)
    at HTMLDivElement.<anonymous> (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:5859)
    at Function.each (http://localhost:28003/Scripts/Lib/jquery-3.3.1.min.js?time=1531141025133:2:2573)
    at w.fn.init.each (http://localhost:28003/Scripts/Lib/jquery-3.3.1.min.js?time=1531141025133:2:1240)
    at w.fn.init.t.fn.(anonymous function) [as dialog] (http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:5812)
    at http://localhost:28003/Scripts/Lib/metro.min.js?time=1531141025133:7:5593
metro.min.js?time=1531141025133:7 Metro 4 Components Library - v4.2.12.688

**Comment by olton** [comment]
Show your code

**Comment by Gurucharan** [comment]
(function(n, t) {
    var i = function(i) {
        if (sessionStorage.setItem("bankingQAuthTokenUpdated", !1),
        i) {
            this.clientUserSessionItems = n('.clientUserSessionItems[updatekey="' + i + '"]');
            this.hdnApplicationLoadingUrl = n('input[name="ApplicationLoadingUrl"][updatekey="' + i + '"]');
            this.hdnApplicationHashChange = n('input[name="ApplicationHashChange"][updatekey="' + i + '"]');
            this.hdnUserTimeZone = n('input[name="UserTimeZone"][updatekey="' + i + '"]');
            this.hdnUserCulture = n('input[name="UserCulture"][updatekey="' + i + '"]');
            this.hdnUserSessionId = n('input[name="UserSessionId"][updatekey="' + i + '"]');
            this.hdnBankingQAuthToken = n('input[name="BankingQAuthToken"][updatekey="' + i + '"]');
            this.hdnApplicationTimeout = n('input[name="ApplicationTimeout"][updatekey="' + i + '"]');
            var f = location.pathname.toLowerCase()
              , u = this.hdnApplicationLoadingUrl.val()
              , r = {};
            if (r["/home/menu"] = "/home/menu",
            r["/home/header"] = "/home/header",
            r["/home/landing"] = "/home/landing",
            t.history && t.history.pushState) {
                f == u ? t.history.pushState("BankingQContext", document.title, "") : r[u] ? t.history.pushState("BankingQContext", document.title, "") : t.history.pushState("BankingQ-@hashChange", document.title, "#" + this.hdnApplicationHashChange.val());
                n(t).off("popstate");
                n(t).on("popstate", function() {
                    setTimeout(function() {
                        t.location.href = "/Account/Login"
                    }, 0)
                })
            }
        }
    };
    i.prototype = {
        update: function(n) {
            var t = this;
            n = n ? n : {
                TimeZone: t.hdnUserTimeZone.val(),
                Culture: t.hdnUserCulture.val(),
                SessionId: t.hdnUserSessionId.val(),
                AuthToken: t.hdnBankingQAuthToken.val(),
                ApplicationTimeout: t.hdnApplicationTimeout.val()
            };
            bankingQ != "undefined" && bankingQ.updateClientUserSession(n);
            t.clientUserSessionItems && t.clientUserSessionItems.length > 0 && t.clientUserSessionItems.remove()
        }
    };
    t.clientUserSession = i
}
)(jQuery, window);

**Comment by olton** [comment]
This code do not use Metro

**Comment by Gurucharan** [comment]
Sorry olton, here we use to display dialog,

 <div data-role="dialog" id="unhandledErrorMessageDialog" data-close-button="true" data-overlay="true" data-overlay-color="op-dark" data-overlay-click-close="true" top="50px" data-width="700">
        <div class="dialogHeader">
        </div>
        <div class="errorImage">
            <img src="~/Images/Cancel.png" />
        </div>
        <div class="errorText">Oops...</div>
        <br />
        <div class="errorText">
            An application error occurred.<br />BankingQ team will review the error received.
        </div>
        <br />
        <div class="errorText">
            Please try again. Thanks for your co-operation.
        </div>
        <br />
        <br />
    </div>

**Comment by Gurucharan** [comment]
Sorry olton, Here is the code we used to display the dialog

 <div data-role="dialog" id="unhandledErrorMessageDialog" data-close-button="true" data-overlay="true" data-overlay-color="op-dark" data-overlay-click-close="true" top="50px" data-width="700">
        <div class="dialogHeader">
        </div>
        <div class="errorImage">
            <img src="~/Images/Cancel.png" />
        </div>
        <div class="errorText">Oops...</div>
        <br />
        <div class="errorText">
            An application error occurred.<br />BankingQ team will review the error received.
        </div>
        <br />
        <div class="errorText">
            Please try again. Thanks for your co-operation.
        </div>
        <br />
        <br />
    </div>

**Comment by Gurucharan** [comment]
div data-role="dialog" id="unhandledErrorMessageDialog" data-close-button="true" data-overlay="true" data-overlay-color="op-dark" data-overlay-click-close="true" top="50px" data-width="700">
        <div class="dialogHeader">
        </div>
        <div class="errorImage">
            <img src="~/Images/Cancel.png" />
        </div>
        <div class="errorText">Oops...</div>
        <br />
        <div class="errorText">
            An application error occurred.<br />BankingQ team will review the error received.
        </div>
        <br />
        <div class="errorText">
            Please try again. Thanks for your co-operation.
        </div>
        <br />
        <br />
    </div

**Comment by Gurucharan** [comment]
Sorry olton, PFA. using this code to display application error dialog
[code.txt](https://github.com/olton/Metro-UI-CSS/files/2200495/code.txt)

**Comment by Gurucharan** [comment]
Problem is data-overlay-color="op-dark" is not recognized by metro 4.0 
can you give a reference of op-dark color in metro-UI

**Comment by olton** [comment]
https://metroui.org.ua/dialog.html
https://metroui.org.ua/dialog.html#_dialog_options

In Metro 4 dialog has a new structure and options. Example 

data-overlay-color | #000000 | Overlay color. Can be hex color value or transparent
-- | -- | --

**Comment by Gurucharan** [comment]
If i code  data-overlay-color="op-dark" the above error Hex2rgba is shown. But if I code the op-dark to #000000 then the error has gone and working fine.

**Comment by olton** [comment]
Please read doc for Metro4
