### ISSUE TITLE
Question about color module

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1142]
We can use Metro Color palette with name color (bg-cyan for example), I see palette standard had 140 colors with name too. I'm reading doc but haven't idea about using standard palette : attempting using bg-xxxxx but it doesn't working.

Can I using full 140 colors easily ?

Thanx for this great framework.

**Comment by olton** [comment]
Metro 4 colors, defined as `bg-*`, is a colors from the Metro colors palette described in Microsoft Developers Guideline

**Comment by olton** [comment]
To use others colors you must create classes for these colors
