### ISSUE TITLE
Feature Idea - File Browser

### ISSUE THREAD

**Issue by Chaoswriter96** [olton/Metro-UI-CSS#1146]
Hi!

I guess it could be a cool feature when Metro UI delivers the follow option for the File Browser.
At the moment the File Browser offers the a bar and a "data-caption"/Icon.
I think its could be cool when the File Browser offers the same function but just with an icon.

Idea when a file is picket:
The input field adds on the right site a little checkmark.

What you think?
Greets

**Comment by olton** [comment]
In 4.2.22 I add new mode `drop` for `input[data-role=file]`
![2018-09-13-21-01-48](https://user-images.githubusercontent.com/365108/45506568-4f691980-b798-11e8-8817-3b806cbb5ef0.jpg)

**Comment by Chaoswriter96** [comment]
Great work!
