### ISSUE TITLE
Feature Request: data-append (forms)

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1147]
(: Is there any way we can get a data-append (to compliment data-prepend) on forms?
Use case:
I am converting an old Bootstrap project where we have forms like [icon][input=number][mm/min]
I can prepend the icon like it used to be with data-prepend, but cannot append the mm/min like we had in Bootstrap ( see 'input-group-append' from https://getbootstrap.com/docs/4.1/components/input-group/

**Comment by olton** [comment]
in 4.2.15

![inputs-with-prepend-append](https://user-images.githubusercontent.com/365108/43204725-554b8076-902a-11e8-8ace-072c04b15075.png)

**Comment by olton** [comment]
### 4.2.15
+ [x] Input, Select, Textarea, File: add `data-append` attribute

**Comment by openbuilds-engineer** [comment]
Lovely!!! Pure awesome! You always get me out of a pinch (:
