### ISSUE TITLE
Using Switch as toggle for Collapse, doesnt update the switch

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1148]
Here's a Codepen (: https://codepen.io/anon/pen/pZrvPR

When you use a Switch as the toggle, it works, it toggles the Collapse. But the switch itself doesnt update its display / change position to the other side and doesnt turn dark like it should.  

Removing it as the ```data-toggle-element="#advanced0"``` from the collapse, the switch functions fine, but then of course the collapse isnt toggled.

**Comment by olton** [comment]
in 4.2.15

![switch-and-collapse](https://user-images.githubusercontent.com/365108/43223361-7ff49304-905b-11e8-9cd8-589b38101104.gif)

**Comment by olton** [comment]
You can get the develop from https://github.com/olton/Metro-UI-CSS/tree/4.2.15

**Comment by openbuilds-engineer** [comment]
Whoop whoop!  Perfect :D

**Comment by Gurucharan** [comment]
can we change the color of switch

**Comment by olton** [comment]
You can see how to change color for any Metro 4 components in https://github.com/olton/Metro-UI-CSS/blob/master/less/schemes/builder/builder.less

**Comment by Gurucharan** [comment]
can you please give lit bit idea how to use the color property. i have html, css files for a switch.
