### ISSUE TITLE
[Treeview] 'addTo' of undefined...

### ISSUE THREAD

**Issue by penyin** [olton/Metro-UI-CSS#1150]
how can i fix it...
https://imgur.com/a/5VtraCK

https://imgur.com/a/UhlmDLJ

**Comment by penyin** [comment]
I'm sorry...
I didn't have problems after I extracted the source and executed it.
https://imgur.com/a/OtWF2DB

maybe the problem in my project...

**Comment by olton** [comment]
Please, use codepen.io for your code. Do not put the code as a photo.

**Comment by penyin** [comment]
nothing...  i found the problem is in my project...

i'm sorry for open this issues.

**Comment by olton** [comment]
https://codepen.io/olton/pen/vaJVeL

**Comment by ssc1223** [comment]
> https://codepen.io/olton/pen/vaJVeL
Hi  @olton 
Is this still working? Nothing happened when I press Addnode or Add subnode.
So does the example on the official website : [https://metroui.org.ua/treeview.html#_treeview_add_node](url)

**Comment by olton** [comment]
@ssc1223 Thank you! I fix it in 4.2.42. The release will be today in the evening

**Comment by ssc1223** [comment]
> @ssc1223 Thank you! I fix it in 4.2.42. The release will be today in the evening

Hi @olton ,

Will the CDN be updated later? I found the version of CDN is still 4.2.41.

And the official website's example is showing correctly. Thank you!

**Comment by ssc1223** [comment]
> @ssc1223 Thank you! I fix it in 4.2.42. The release will be today in the evening

Hi @olton ,

Thank you so much, it works perfectly now :D
