### ISSUE TITLE
[QUESTION] Prevent Tile animation on nested component click

### ISSUE THREAD

**Issue by Alcasser** [olton/Metro-UI-CSS#1151]
Hi, nice project!

I was wondering if it's possible to avoid the tile animation when I click on a nested button.
I'm able to prevent the event propagation so that only the nested button handler is executed, but I would also need to prevent the animation.

Thanks!

**Comment by olton** [comment]
Thank you. At the moment, there is no such possibility. According to the Microsoft developers guide, Tile is an independent object that provides information and does not need to contain controls. This is how he works in Metro 4. In another job is not planned.
