### ISSUE TITLE
Treeview - render with collapsed nodes?  (Or possibly, I am being stupid (:  )

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1152]
In the Treeview component. 

I see from the examples, some ```<li>``` have  ```class="expanded"```  

But if you omit  ```class="expanded"```, it still renders as expanded initially? 
Is this a bug (if not have  class="expanded", then it should render as collapsed?)

Inspecting the element while clicking to expand/collapse I see  class="expanded" removed and added from the element, not sure why it doesn't initialize that way, or like I said in the title, maybe I'm being stupid and doing something wrong (: 

(Have to call toggleNode from JS in a document.ready for all the nodes I want to be collapsed by default) 

Use case:  I am rendering a document tree - that needs to be collapsed by default

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/js/plugins/treeview.js#L116

**Comment by openbuilds-engineer** [comment]
Sweet!   Sorry I missed it! 
https://metroui.org.ua/treeview.html doesnt reference data-collapsed=true anywhere (:
