### ISSUE TITLE
Closing dialog, children like radio/switch elements gets removed from view after dialog is already hidden

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1153]
Good morning, sorry to bother once more (: 

I think i am seeing a little bug, I have a simple dialog with a form.  When I close the form, it hides out nicely,  but some of the children elements like radios and switch, stay visible for a few hundred ms longer than the dialog.   Check the gif below to see it in action 

![elements slow to disappear](https://user-images.githubusercontent.com/31449271/43392545-46e7e164-93f4-11e8-8d2e-b9b9831cba64.gif)

**Comment by openbuilds-engineer** [comment]
(If you need sample code of the issue in action (Because it could very well be my mistake too hehe) see https://github.com/OpenBuilds/cam/blob/713b634640f38a7832dfb6396dd31ccfdc061f25/index.html#L527-L624

Happens on all my Dialogs though (: like this one too: 
![also on elements slow to disappear](https://user-images.githubusercontent.com/31449271/43392678-b72f367a-93f4-11e8-8c51-603c0ef10fcc.gif)

(Its subtle but my users do see it as a tiny glitch that those diappear after the dialog itself)

**Comment by openbuilds-engineer** [comment]
Realised I was being lazy by pointing you to my repo for code, sorry! 
Here's a Codepen instead https://codepen.io/anon/pen/gjoLZp (: Hopefully it helps, I realize you have a tonne for work, so hopefully a lighter example helps out! My bad (:

**Comment by olton** [comment]
The problem is due to the use of the `pos-fixed pos-top-center` classes. They define properties with the! `!mportant` suffix and override the behavior of the dialog when hiding.

**Comment by olton** [comment]
I added this to the TODO list, but I do not know in which release I will fix it.

**Comment by openbuilds-engineer** [comment]
Ok cool!   For now then i'll find a workaround to not need the pos-fixed! (I may open a seperate issue for that though, pos-fixed was a workaround for another issue) That should give you plenty of time to work on a fix - it's not urgent on my side  (: Thanks for your help

**Comment by olton** [comment]
This in 4.2.16 dialog with attribute `data-to-top="true"`

![2018-07-30_15h14_06](https://user-images.githubusercontent.com/365108/43396819-7fe8e604-940b-11e8-8c5e-608ddf78e189.gif)

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/4.2.16

**Comment by openbuilds-engineer** [comment]
Oh my word! You are too fast!   OK I'll close #1154 as that would solve it elegantly!

**Comment by openbuilds-engineer** [comment]
Thanks once again, tested with the dev tree 4.1.16 and both my issues is resolved! Closing this one!  Pure awesome!
