### ISSUE TITLE
Dialog with a collapse inside, pushes dialog-actions offscreen when collapse is expanded

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1154]
My initial problem was this one: 
https://codepen.io/anon/pen/djJWoK

Initially some of my dialogs upon opening renders small (not a lot of content, maybe 2 line form etc)
However many of those forms has a switch -> Advanced options,that toggles a collapse, that shows more of the form (not often needed, but there if a user needs more customization than the 2 line form provides) 
When I expand the collapse, it pushes the dialog-actions down and extends the dialog-content div vertically.   But the top of the dialog, stays where it was when it opened.   Because initially the dialog was small, the "top" of the dialog may be some ways down the screen already, so when the collapse expands, it pushes dialog-actions (and on longer forms or smaller screens, the bottom content on the dialog-content) off the screen (at the bottom)

![need idea](https://user-images.githubusercontent.com/31449271/43397041-d2e9aad0-9403-11e8-9e68-923a2137a1cf.gif)

I am not sure what the fix would be, perhaps the dialog should recenter itself vertically?  
I used ```pos-fixed pos-top-center``` class on the dialog to attempt to work around this (If its already at the top, and it expands downward, down really is the only way to go, and its the only place with available screen real-estate hehe)  but as mentioned in #1153 that breaks the hiding of the dialog because of the ```pos-fixed pos-top-center```

**Comment by olton** [comment]
read https://github.com/olton/Metro-UI-CSS/issues/1153

**Comment by openbuilds-engineer** [comment]
Closing this as the upcoming ```data-to-top="true"``` solved it elegantly! Thanks!
