### ISSUE TITLE
Unclear how to Dynamically make a window

### ISSUE THREAD

**Issue by jruiseco** [olton/Metro-UI-CSS#1157]
I am attempting to turn a div entry in the body into a window by adding data-role='window' as an attribute.

https://metroui.org.ua/windows.html

I simply add the attribute as follows

var h1 = $("#choose_project");
var att = document.createAttribute("data-role");     
att.value = "window";                          
h1.setAttributeNode(att);

I have verified that my html div has data-role='window' attribute. I have been unable to locate any examples for the create function of metro ui css.

I would really appreciate any clarity on the matter.

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/desktop

**Comment by olton** [comment]
The attribute `data-role="window"` must exist when element add to DOM
