### ISSUE TITLE
Datepicker error

### ISSUE THREAD

**Issue by raicho** [olton/Metro-UI-CSS#1158]
Hello masters... Today i found bug in datapicker... Chrome work perfect but mozilla show me : 
TypeError: n.find(...).addClass(...).position(...) is undefined  ...
Line 8323: //  scrollTop: y_list.find("li.js-year-real-" + y).addClass("active").position().top - (40 * o.distance)

**Comment by olton** [comment]
I do not observe any mistake. Check the version of Metro 4 and let me know the version of Mozilla (create print screen with console window)

![2018-08-02_11h45_38](https://user-images.githubusercontent.com/365108/43573181-ceef2ad4-9649-11e8-92f8-c38122d70ea4.png)

**Comment by raicho** [comment]
``[](url)

**Comment by raicho** [comment]
[https://image.ibb.co/kPoyyz/hehe.png](url)

**Comment by raicho** [comment]
``
![hehe](https://user-images.githubusercontent.com/5213769/43577371-85b73f4e-9600-11e8-99eb-9ee3c5fe8b4b.png)

**Comment by olton** [comment]
Please update Metro 4 to latest version 4.2.16

**Comment by olton** [comment]
![2018-08-02_13h05_58](https://user-images.githubusercontent.com/365108/43577549-ce4ed024-9654-11e8-9a7f-6dddb10a1973.png)

**Comment by raicho** [comment]
`
![hehe2](https://user-images.githubusercontent.com/5213769/43577681-5aa25112-9601-11e8-90ec-64d22ce34d80.png)
`

**Comment by raicho** [comment]
[
![hehe2](https://user-images.githubusercontent.com/5213769/43577699-691989e0-9601-11e8-9b01-03ce948cfcae.png)
](url)

**Comment by olton** [comment]
please create pen on codepen.io with your datepicker code

**Comment by raicho** [comment]
![hehe2](https://user-images.githubusercontent.com/5213769/43577784-a48ac85e-9601-11e8-9488-0262654db8d3.png)

**Comment by olton** [comment]
@raicho I do not see this error in myself, so if I do not see your code, I can not help you
