### ISSUE TITLE
Window resize not triggering

### ISSUE THREAD

**Issue by jruiseco** [olton/Metro-UI-CSS#1159]
When I make a window using the method outlined in https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/desktop

I am unable to resize the windows. I have confirmed that the windows are set to resizeable. My best guess is that the resize controls are outside of the window, since I cannot get the resize mouse icon to appear when I hover the bottom of the window.

![image](https://user-images.githubusercontent.com/37447593/43582720-531337de-962b-11e8-818e-721eaadc82bc.png)

**Comment by jruiseco** [comment]
I have confirmed that windows made statically in html resize and work well.

Any window made using the create function will not resize. It is draggable, and the maximize/close buttons do work.

Metro.window.create({
		width: 300,
		height:150,
		title: "Test",
		content: "rawwr"
	});

**Comment by olton** [comment]
https://codepen.io/olton/pen/ejrWzY

all work

**Comment by jruiseco** [comment]
Thank you for the quick reply. I really appreciate it.

**Comment by olton** [comment]
Maybe conflict with other frameworks?

**Comment by jruiseco** [comment]
Definitely looks that way.

I am currently unloading frameworks, going to narrow down exactly what is conflicting. Then make a list of stuff that doesn't break the metro ui framework from my project.

**Comment by jruiseco** [comment]
Ahh. It makes perfect sense. Jquery ui conflicts with it.

<script type='text/javascript' src="javascript_lib/jquery-ui.min.js</script>

Working libraries.

Threejs
octreejs
rainbow.js
jquery.layout
xml2json
editablegrid
handsontable

**Comment by jruiseco** [comment]
Thank you a lot.
