### ISSUE TITLE
DatePicker + VueJS

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1160]
Combine datepicker + vuejs
datepicker reset text when change other data vuejs

example [https://codepen.io/drodriguez/pen/NBzpXg](https://codepen.io/drodriguez/pen/NBzpXg)

i don't know why or how resolve.

thanks

**Comment by olton** [comment]
You need to ask the author for VueJS. I unfortunately do not know the architecture of this framework.

**Comment by dinami-k** [comment]
ok, thanks... the issue is only with datepicker... with input type="text" work fine...
I will try on vuejs debug mode and follow the stack trace

**Comment by atherosxd** [comment]
@dinami-k i have this same issue. The work around for me is that instead of using v-model, I use v-bind
