### ISSUE TITLE
data-role="table" issue

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1161]
Look at example

https://codepen.io/TorakikiSan/pen/jKRpKo

whitout the data-role="table" attribute, the script work fine (show an alert with the id), while with the attribute, doesn't work.

Thank's!

**Comment by olton** [comment]
Use:
```
$("table [id^='M_']").click(function() {...})
```

**Comment by TorakikiSan** [comment]
Unfortunately it does not work.

As soon as the table is displayed, the script works, but after changing the page or the number of rows displayed, this no longer works.

**Comment by olton** [comment]
```
$(document).ready(function() {

  $(document).on("click", "[id^='M_']", function() {
    var tMachine=$(this).attr("id");
    alert("Machine: "+tMachine);
   });
  
});
```

**Comment by TorakikiSan** [comment]
Work!

As usual, ty Olton!
