### ISSUE TITLE
Enhancement Request for Select and Table

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1165]
If implemented, I forget the "select2" and "dataTables" plug-ins.

select2:

1. manage the "multiple" attribute

2. possibility to add unlisted entries with "multiple" attribute (in "select2" parameter "tags: true")

dataTables:

1. possibility to display the table with a maximum height (fixed headers and footers, body with a side scroll bar, parameters "scrollY: 500" and "scrollCollapse: false")

2. possibility to block the first n-columns or the first n-rows

Am I asking too much? :-)

**Comment by olton** [comment]
Metro 4 only support CSS classes for select2 and dataTables. For other questions, contact the authors of these plugins.

**Comment by TorakikiSan** [comment]
Sorry Olton, but I did not explain myself.

The ones I wrote above are features that already have the two plug-ins and that I'd like to have implemented on MetroUI so I can avoid using select2 and dataTables just for that.

**Comment by olton** [comment]
Now in 4.2.18

![2018-08-11-21-46-50](https://user-images.githubusercontent.com/365108/43995114-d4d32108-9db0-11e8-8918-98531e1f43e9.gif)

**Comment by TorakikiSan** [comment]
Great!

Ty Olton!

**Comment by TorakikiSan** [comment]
I've just tried the two new "taginput" and "multiple" components. Awesome work Olton!

**Comment by TorakikiSan** [comment]
Can I change the color of the selected elements in "multiple" like the new "taginput" component?

**Comment by olton** [comment]
in 4.2.18 you must create your one style for:
```
.select {
    .selected-item {
        .title {...}
        .remover {...}
    }
}
```

in 4.2.19 (Develop) you can use attributes `data-cls-selected-item` and `data-cls-selected-item-remover`

**Comment by TorakikiSan** [comment]
If possible, could you add an attribute to the new "taginput" component to specify one or more keys that you can use to separate input values?

Eg

**data-tag-input-separator=" "** <- this is a space

because for me, pressing the space bar is faster in tag input.

Ty!
