### ISSUE TITLE
Horizontal Tabs

### ISSUE THREAD

**Issue by Gurucharan** [olton/Metro-UI-CSS#1167]
When i code for horizontal tab with data-expand="fs" the default tab is showing i.e collapsed. not the next one. please give a solution

**Comment by olton** [comment]
Check your Metro 4 version

**Comment by olton** [comment]
check your Metro 4 version, create pen on codepen.io with your problem code. create a screenshot for your browser with open developer console.

**Comment by Gurucharan** [comment]
/*
 * Metro 4 Components Library v4.2.14 build 691 (https://metroui.org.ua)
 * Copyright 2018 Sergey Pimenov
 * Licensed under MIT
 */

Can I know when can we get the stable build of Metro 4

**Comment by olton** [comment]
Update to latest

**Comment by olton** [comment]
Stable always in master branch, currently 4.2.17

**Comment by Gurucharan** [comment]
![issue](https://user-images.githubusercontent.com/3840626/43989961-ccc45ebc-9d71-11e8-99c5-5ea1d2cb3148.png)
![actual](https://user-images.githubusercontent.com/3840626/43989967-ec7a950a-9d71-11e8-8edd-8c592a9a2a7f.PNG)

**Comment by Gurucharan** [comment]
Thank you, Its due to version problem. now working!

**Comment by Gurucharan** [comment]
Can you give some js code examples to trigger tab event for horizontal tabs.
