### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Gurucharan** [olton/Metro-UI-CSS#1169]
Can you give some js code examples to trigger tab event ( to change selected tab from js) for horizontal tabs.

**Comment by olton** [comment]
https://codepen.io/olton/pen/ejXRLK

**Comment by olton** [comment]
In 4.2.19 I add methods to tabs component: `open(tab_number | tab_element)`, `prev()`, `next()`

**Comment by Gurucharan** [comment]
Thank you ! Updated to the latest.
