### ISSUE TITLE
could you help me with the overlay of 2 dialogues.

### ISSUE THREAD

**Issue by MartinXL122** [olton/Metro-UI-CSS#1170]
Hello, I'm sorry, you could help me with opening a second dialogue without eliminating the "overlay" of the previous one.

https://codepen.io/martinxl122/pen/OwGebe

**Comment by dinami-k** [comment]
I know it is not the best solution but work

the second dialogue open before first dialog close.... then, when first dialogue close remove the overlay for first and second dialogue..... if you put the second dialogue inside setTimeout it work, example


onclick: function(){
       **setTimeout(function(){**
                       Metro.dialog.create({
                       title: "Dialog 2",
                       content: "<div>This a dialog 2</div>",
                          actions: [
                              {
                                  caption: "Agree",
                                  cls: "js-dialog-close alert"
                                 
                              }

                          ]
                      });
   **}, 10);**

Example: [nested dialogues](https://codepen.io/drodriguez/pen/dqYydx)
