### ISSUE TITLE
Unknown color format

### ISSUE THREAD

**Issue by ibrahimch** [olton/Metro-UI-CSS#1172]
Hi folks, Whenever I set `header.app-bar` to transparent, or `rgba(0, 0, 0, 0.01)` or `rgba(0, 0, 0, 0)` it log a error in console "Unknown color format" can you please guide me how can I set it transparent please

**Comment by olton** [comment]
Create pen on codepen.io with your code

**Comment by ibrahimch** [comment]
Here is Pen
https://codepen.io/innocentabi/full/rZOxKB/

**Comment by ibrahimch** [comment]
Here is my css code
`body{
  background: url('https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg') !important;
  color: #fff !important;
}
.app-bar{
  background: transparent !important;
}`
And here is console error
![image](https://user-images.githubusercontent.com/20566432/44542089-4949c500-a725-11e8-899e-6356da3b9d9b.png)

**Comment by olton** [comment]
background for app-bar can't be `transparent`

**Comment by olton** [comment]
if you need transparency effect for app-bar, use CSS rule with `rgba(...)` color definition with alpha channel

**Comment by ibrahimch** [comment]
I tried this too, it returns same console error
https://codepen.io/innocentabi/full/rZOxKB/

**Comment by ibrahimch** [comment]
Thanks :)
