### ISSUE TITLE
data-role="table" : I need some explanations

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1173]
Look at example:

https://codepen.io/TorakikiSan/pen/jKRpKo

Need some explanations.

1. Is it possible to define the width of the column? (**style="width 3%;"** for example)

2. Check the behavior of **data-table-search-title** against **data-pagination-prev-title**. The first works as I thought, while the second does not. Where am I wrong?

Ty!

**Comment by olton** [comment]
1) Use attribute `data-size` for `th`
2) The question is not clear
