### ISSUE TITLE
Select Metro with "placeholder" and "clear button (optional)"

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1176]
I know it's not the best way but this shows the functionalities that I think would be good to add to select control in future versions:

the Funcionalities are:
* Placeholder with style.
* Clear Button
* Keep the same rules if select is required, etc, etc.

[codepen example](https://codepen.io/drodriguez/pen/oPXLKb)

Thanks a lot

**Comment by olton** [comment]
Adding a placeholder requires adding an additional custom option, this will change the standard select behavior since the user will not know about the existence of this option and will a misleads him.

**Comment by olton** [comment]
added in 4.3.0
