### ISSUE TITLE
Center Tiles in for smaller screens and keep responsiveness

### ISSUE THREAD

**Issue by Franklin89** [olton/Metro-UI-CSS#1177]
Is it possible to somehow center a tiles-grid? Specially when looking at it on a phone?
I tried with `ml-auto` and `mr-auto` but then the responsiveness is gone and it looks bad on a tablet. Any advice how to get this working.

```html
<div class="grid">
        <div class="tiles-grid">
            <div data-role="tile" data-size="small"></div>
            <div data-role="tile" data-size="small"></div>
            <div data-role="tile" data-size="small" class="col-1 row-2"></div>
            <div data-role="tile" data-size="small" class="col-2 row-2"></div>
            <div data-role="tile" data-size="medium"></div>
            <div data-role="tile" data-size="wide"></div>
            <div data-role="tile" data-size="large"></div>
            <div data-role="tile" data-size="medium"></div>
            <div data-role="tile" data-size="medium"></div>
            <div data-role="tile" data-size="wide"></div>
        </div>
    </div>
```

![image](https://user-images.githubusercontent.com/4151467/44597436-e7926500-a7cf-11e8-8ecf-3b7673da24b3.png)

Thanks!

**Comment by MoezDaoulatli** [comment]
Try this :

<div class="grid flex-align-center">
    <div class="tiles-grid ">
        <div data-role="tile" data-size="small"></div>
        <div data-role="tile" data-size="small"></div>
        <div data-role="tile" data-size="small" class="cell-1 row-2"></div>
        <div data-role="tile" data-size="small" class="cell-1 row-2"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="wide"></div>
        <div data-role="tile" data-size="large"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="wide"></div>
    </div>
</div>

**Comment by MoezDaoulatli** [comment]
<div class="grid flex-align-center">
    <div class="tiles-grid ">
        <div data-role="tile" data-size="small"></div>
        <div data-role="tile" data-size="small"></div>
        <div data-role="tile" data-size="small" class="cell-1 row-2"></div>
        <div data-role="tile" data-size="small" class="cell-1 row-2"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="wide"></div>
        <div data-role="tile" data-size="large"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="wide"></div>
    </div>
</div>

**Comment by Franklin89** [comment]
Thanks for getting back to me!

But using the `flex-align-center` leads to the same issue as using `ml-auto` and `mr-auto`. It will no longer be responsive if you run it on a bigger screen. It will always look like this: 

![image](https://user-images.githubusercontent.com/4151467/44617269-ec9ef500-a85f-11e8-824c-78df3cc6f90e.png)

But it is centered now. Is there a way to get the responsiveness back? :-)

**Comment by olton** [comment]
Use media points for your needs
```
<div class="d-flex flex-justify-center flex-justify-start-sm">
    <div class="tiles-grid tiles-group size-2 size-md-10">
        <div data-role="tile" data-size="small"></div>
        <div data-role="tile" data-size="small"></div>
        <div data-role="tile" data-size="small" class="col-1 row-2"></div>
        <div data-role="tile" data-size="small" class="col-2 row-2"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="wide"></div>
        <div data-role="tile" data-size="large"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="medium"></div>
        <div data-role="tile" data-size="wide"></div>
    </div>
</div>
```

**Comment by Franklin89** [comment]
Thanks for the support :-) it is getting there :-)

But now I have the next issue...the responsiveness works fine now. But when I view it on a small mobile screen, IPhone 6/7 the spacing on the right is not the same as on the left. :-/ event thought the `felx-justify-center` is set. It is a bit off to the left...

```html
<div class="d-flex flex-justify-center flex-justify-start">
    <div class="tiles-grid tiles-group size-2 size-md-4">
        <div class="tile bg-red" data-role="tile" data-size="medium" data-effect="animate-slide-left">
            <span class="branding-bar">@Localizer["My Trainings"]</span>

            <div class="slide"><p class="pos-absolute pos-center">18.09.2018</p></div>
            <div class="slide"><p class="pos-absolute pos-center">08:30 Uhr<br />Metsch</p></div>
        </div>
        <div class="tile bg-green" data-role="tile" data-size="medium">
            <span class="branding-bar">@Localizer["TTF School"]</span>
        </div>
        <div class="tile bg-green" data-role="tile" data-size="medium">
            <span class="branding-bar">@Localizer["Weather"]</span>
        </div>
        <a class="tile bg-green" data-role="tile" data-size="medium">
            <span class="branding-bar">@Localizer["Log Book"]</span>
        </a>
        <a class="tile" data-role="tile" data-size="wide">
            <span class="branding-bar">@Localizer["Gallery"]</span>
        </a>
        <a class="tile bg-green" data-role="tile" data-size="medium">
            <span class="branding-bar">@Localizer["TTF Program"]</span>
        </a>
        <a class="tile bg-green" data-role="tile" data-size="medium">
            <span class="branding-bar">@Localizer["Profile"]</span>
        </a>
    </div>
</div>
```

![image](https://user-images.githubusercontent.com/4151467/44618710-71e3d300-a87b-11e8-8602-df134df451d4.png)
