### ISSUE TITLE
popver with html content

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1179]
Hi... 

can i do a popover with html content like [popover example](https://codepen.io/diqidoq/pen/RRojxQ)

I tried but not work with Metro...

I want to do something like [expedia example](https://www.expedia.com/) when click Travelers option

Other observation: (it's a personal observation)
i think Metro could be change the popover after style (.neb::after) ... more soft, more like codepen example.

Thanks Master, you are the best.

**Comment by olton** [comment]
Hi, you can set HTML content for popover with attribute `data-popover-text="..."` and set `data-popover-hide="0"`. Popover will be closed if user click on it.

**Comment by olton** [comment]
in 4.2.27 you can add `close button` to popover with attributes `data-close-button="true" data-popover-hide="0"`
