### ISSUE TITLE
Number Spinner

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1180]
Hi... 

i suggest new feature: "Number Spinner" ... like https://bootsnipp.com/snippets/featured ... click-hold

properties: 
* minValue (optional) 
* maxValue (optional) 
* step (1 by default)

methods:
* getValue
* setValue

Thanks a lot

**Comment by olton** [comment]
New in 4.2.20
https://youtu.be/EmY82ei4omc

**Comment by dinami-k** [comment]
thanks a lot... i did a first test in codepen and look amazing :) 

i added change event and the event not work very well... its keep on cycle (value changed infinity)... what i do wrong

[First spinner test](https://codepen.io/drodriguez/pen/GXmWNO)

**Comment by dinami-k** [comment]
ok, changed alert to $(div).html(value) and work it

thanks

**Comment by dinami-k** [comment]
now i have a issue with dynamic controls (spinner and others):
I need value and control (for get id and custom attributes, etc) but i only have value control.

 [update codepen with two spinner ](https://codepen.io/olton/pen/KxmmNd)

Example: 
$('#test').append('<div id="spinner1" data-on-change="change"....
$('#test').append('<div id="spinner2" data-on-change="change"....

function change(val, elem){
     siwtch $(elem).attr(data-custom-attr)
       case abc:
         .......
      case xyz:
         ......


    $('#result').html('Spinner Value elem.ID #xyz is : ' + val);
}

**Comment by olton** [comment]
```
function change(val) {
  if (this.getAttribute('id') === 'spinner1') {
     // spinner 1
  } else {
     // spinner 2
  }
}
```

**Comment by olton** [comment]
In 4.2.20 I added events `data-on-plus-click`, `data-on-minus-click`, `data-on-button-click`
Events fired when user click plus or minus button. This functions receive next arguments: `current value`, `new value`, `new input value` for onPlusClick and onMinusClick and receive 4th argument `plus` or `minus` for event onButtonClick.

You can get develop branch from github
