### ISSUE TITLE
Animation does not work!

### ISSUE THREAD

**Issue by breket** [olton/Metro-UI-CSS#1183]
Hi,

I just copy an paste your code from https://metroui.org.ua/animation.html#sidenav
`<span class="mif-spinner ani-spin"></span>`
But icon does not animate.
In my index.html I import:
```
<!--Metro css-->
<link href="content/metro-all.min.css" rel="stylesheet" />
<!--Metro js-->
<script src="scripts/metro.min.js"></script>
```

**Comment by olton** [comment]
Add class `d-inline-block`

**Comment by breket** [comment]
TU! Now it works.
