### ISSUE TITLE
select multiple data-cls-selected-item & data-cls-selected-item-remover issue

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1184]
Look the example

https://codepen.io/TorakikiSan/pen/EeyWmp

the items already selected, have the correct colors as defined by the two new attributes, but if I add a new item this is colored with the default colors (white and gray) not those defined.

Thank you

**Comment by olton** [comment]
TU! Fixed in 4.2.20. You can get develop branch from github
