### ISSUE TITLE
Tips for data-role="calendarpicker"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1187]
* An attribute to exclude that day from the month (ex. **data-exclude-day="0"** for exclude all Sunday from month, or **data-exclude-day="0,1"** for exclude all Sunday and Monday)

* A compact version of the component: now it is nice and immediate to understand how to use it, but in some cases it is a bit too big (ex. use in a window instead a page)

* As in other components, the ability to decide where to "hook" the component at the field, to the right, left, above, below.

Thank's!

**Comment by aeChriss** [comment]
you can set a show-handler on the calendarpicker and inside the handler you can add/remove the class for open upside or downward.
```
function showHandler (evt,cal) {
  jQuery(cal).addClass('open-up');    // always open upside
  /* or */
  jQuery(cal).removeClass('open-up');    // always open downward
}
```

**Comment by dinami-k** [comment]
you can exclude specific dates [calendar_exclude](https://metroui.org.ua/calendar.html#_calendar_exclude)

for compact calendar, now i do (waiting future release):

data-show-header="false"
data-show-footer="false"

and

.calendar {
    font-size: 12px !important;
    display: block; /*or inline-block*/
    line-height: .5px !important;
}

**Comment by olton** [comment]
![2018-09-09-19-16-48](https://user-images.githubusercontent.com/365108/45266537-09911600-b465-11e8-997e-2b77ddbb77cb.jpg)

**Comment by olton** [comment]
Please create the one issue for each request
