### ISSUE TITLE
There will be the possibility to combine the dialog with the Infobox

### ISSUE THREAD

**Issue by MartinXL122** [olton/Metro-UI-CSS#1189]
Will there be the possibility to combine the dialogue with the Infobox or with other component types?

![dialogs](https://user-images.githubusercontent.com/22846255/45047490-c981fb80-b03e-11e8-9756-31230b26c14e.jpg)

**Comment by olton** [comment]
Dialog is s container. You can put into dialog any others components, include master component.

**Comment by olton** [comment]
https://codepen.io/olton/pen/XPgavm
