### ISSUE TITLE
Touch scrolling MetroUI 4

### ISSUE THREAD

**Issue by marajin** [olton/Metro-UI-CSS#1190]
Forgive me if I'm just being somewhat clueless about this, front end web dev is not exactly my forte but I am struggling a little with how to achieve this and I feel like it's not (yet) implemented in v4?

I had a check back at v3, and it appears you had a method of supporting this (as easily visible in the v3 'start screen' demo, however in v4 while you still have the horizontal scrolling via mouse wheel, touch devices do not appear to work (nor can I find any js or other references to touch in MetroUI4).

If it isn't implemented by default, do you plan to add it in the future?

**Comment by dinami-k** [comment]
Hi... your question is about Metro V3 [Start Screen Example](https://metroui.org.ua/v3/templates/start-screen.html)

Mouse Scroll horizontal???

In metro v4
[Examples](https://metroui.org.ua/examples.html)  (Start Page Example)
if you View Source 
      if (width >= 768) addMouseWheel();
 

var addMouseWheel = function (){
        $("body").mousewheel(function(event, delta, deltaX, deltaY){
            var page = $(".start-screen");
            var scroll_value = delta * 50;
            page.scrollLeft(page.scrollLeft() - scroll_value);
            return false;
        });
    };



You can test resize window like  [Start Page Resize](https://ibb.co/bY7rzp)  and scroll with mouse

**Comment by marajin** [comment]
No sir, my question is about having the ability to swipe on a touch screen device (i.e. android tablet) to horizontal scroll, the mouse wheel scroll I have working perfectly fine already.

**Comment by dinami-k** [comment]
ok ok.... 
i don't know if [Mouse wheel](https://metroui.org.ua/mouse-wheel.html) work in mobile.

**Comment by marajin** [comment]
No worries! Thanks for taking the time to try to help.

**Comment by olton** [comment]
fixed
