### ISSUE TITLE
Calendar - new attribute to exclude days

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1192]
A new attribute to exclude one o more days from the month (ex. data-exclude-day="0" for exclude all Sunday from month, or data-exclude-day="0,1" for exclude all Sunday and Monday)

Thank's

**Comment by TorakikiSan** [comment]
Thank's Olton!

**Comment by TorakikiSan** [comment]
I try your link:

`<div data-role="calendar" data-week-start="1" data-exclude-day="2,1"></div>` **Work!**
`<div data-role="calendar" data-week-start="1" data-exclude-day="2">`</div> **only one number, not, get error.**

Thank's!

**Comment by olton** [comment]
Thank you, fixed.
