### ISSUE TITLE
Need help on data-role="file"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1196]
Metro last version (**Metro 4 Components Library - v4.2.21.698**), jQuery 3.3.1 and everything else is configured as it should be.

https://codepen.io/TorakikiSan/pen/EeyWmp
Here the result is correct.

![file](https://user-images.githubusercontent.com/37299746/45411048-8691da80-b673-11e8-8c09-2781975f759b.jpg)
In the image above instead the result in my pc:

No icon in the input field, but the icons on the right are correct

What could be the problem?

**Comment by olton** [comment]
https://metroui.org.ua/file.html

**Comment by TorakikiSan** [comment]
Sorry Olton, I take example from 

https://metroui.org.ua/forms.html#_file

**Comment by olton** [comment]
I forgot to change :(

**Comment by olton** [comment]
https://builder.metroui.org.ua/ this is an alpha version, not for public in this time :)
