### ISSUE TITLE
Select Multiple: Fire OnChange event when removing tags? 

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1198]
Codepen: https://codepen.io/anon/pen/QVVXBG showing issue 

I LOVE the new Select Mutiple! Looks soooo good with the Tag style display!  Awesomeness
Just one tiny little (Either a bug or me being stupid again) 

If i use a <select multiple> without Metro, when I DESELECT an Item, the onchange="function()" gets called (for both adding and removing items from the selection as it should). 

When i use Metro's Select role , then the onchange only fires when Adding items to the selection, not when removing/Deselecting them.  In my use case, I need it to fire for both adding, and removing  

Regards and many thanks!

**Comment by olton** [comment]
Thanks, I fix it in 4.2.23. Currently you can use data-on-change attribute

**Comment by openbuilds-engineer** [comment]
Thanks!

**Comment by openbuilds-engineer** [comment]
tested and data-on-change does what I need for now - closing this (: thanks again!

**Comment by openbuilds-engineer** [comment]
Oooh I saw it mentioned on the changelog, but haven't had a moment to play
with it yet. I promise I'll make some time to check it out this week. I
also put in a request with Management to look at your sponsors page -
you've rolled so many rocks out of my way, holding thumbs. Ps: checkout
software.openbuilds.com - Metro Ui changing the face of CNC machining (;

**Comment by olton** [comment]
software.openbuilds.com > Wow! Great work!
