### ISSUE TITLE
Previous version metro not work

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1199]
Exmaple

JS
https://metroui.org.ua/metro/js/metro.js?ver=4.2.21

show 

/*
 * Metro 4 Components Library v4.2.22 build 699 (https://metroui.org.ua)
 * Copyright 2018 Sergey Pimenov
 * Licensed under MIT
 */

CSS
https://metroui.org.ua/metro/css/metro-all.css?ver=4.2.21

/*
 * Metro 4 Components Library v4.2.22 build @@build (https://metroui.org.ua)
 * Copyright 2018 Sergey Pimenov
 * Licensed under MIT
 */

current version 4.2.22 show appbar with hamburguer always and not show perfect in my production site

how can i do?

**Comment by olton** [comment]
Read changelog and docs for app-bar . I change setup expandable.

**Comment by olton** [comment]
use attributes `data-expand` and `data-expand-point`. For more details, read docs.
