### ISSUE TITLE
Streamer need float step value

### ISSUE THREAD

**Issue by marajin** [olton/Metro-UI-CSS#1200]
The Streamer Component will error due to not to being able to calculate the "leftOffset" if the start time of an event isn't divisible by the step and cannot gracefully fail over to subsequent events.

e.g. if I have a streamer time 08:00 to 16:00, with a step of 30 but the events have these times:

9:00 (this event works and is generated correctly)
9:50 (failure point)
11:10 (I presume this would also fail if it got that far)
12:00
14:00

however at a step of 10, it will work as expected.

**Comment by marajin** [comment]
Oh I should say, I had expected the behaviour of trying to align to the sub ticks drawn since it renders a 12 wide sub interval? And possibly a clamp to the nearest valid offset too if it can't be calculated smoothly?

**Comment by olton** [comment]
Currently, streamer works only with defined step

**Comment by marajin** [comment]
any plans to change that? It's kinda ugly needing a step of 10 across a full day with only 5 events (Well, 5 events per stream, 5 streams currently)

My thoughts would be to allow aligning an event start to the sub ticks and possibly make the size attribute of an event a float to preserve compatibility and still allow finer degree of control?

i.e. with 12 sub steps drawn, and a step of say.. 60.. my events could be drawn at 2 sub steps offset from the main step and then given a size of say.. 0.8 or 1?

I appreciate if you don't have time to add this functionality now, just a thought/question if you would consider it at some stage?

**Comment by marajin** [comment]
Well ok my brain just woke up and I realised that at 12 substeps it'd be like 0.833333333, which I appreciate is very awkward.

**Comment by marajin** [comment]
Alternatively.. give events an optional end time and calculate their sizing from that?

**Comment by olton** [comment]
I will think

**Comment by marajin** [comment]
Thanks, I appreciate it and I am loving working with Metro-UI! So thanks for all your hardwork to create a beautiful framework.
