### ISSUE TITLE
Calendar picker - add data-prepend

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1201]
Hi,

I've form with many input and I'm using data-prepend for label (like render clean and it usefull to gain place). In my form, I've 2 input with calendar picker. I attempt using data-prepend but not implemented it seem ^^

Could you add data-prepend (or perhaps give me tips to have unified form ?) ?

Thanx.

**Comment by olton** [comment]
Added in 4.2.23
![2018-09-18-23-15-55](https://user-images.githubusercontent.com/365108/45713887-d7846000-bb98-11e8-9cae-9bd41dfd43f2.jpg)

**Comment by arjarn** [comment]
Nice !
Thanx you for your job 👍
