### ISSUE TITLE
Slow calendar with IE

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1202]
Hi,

me again with calendar...
If I'm using IE 11 (v11.285.17134), calendar picker is very slow (in my page but also in Metro-UI guide).
When you're clicking in input, there's delay of 2 seconds before calendar appear.
It seem, there's also problem with calendar page : very long to display...

**Comment by olton** [comment]
Thank you, I fix it in 4.2.23. Wait for release or get develop branch from  https://github.com/olton/Metro-UI-CSS/tree/4.2.23

**Comment by arjarn** [comment]
Thanx you very much  👍

**Comment by olton** [comment]
Unfortunately, IE11 has problems with rendering calendars if there are a lot of them on the screen. I fix rendering for IE, but for a lot of calendars on the page, the problem remains.

**Comment by arjarn** [comment]
IE always pity for dev despite new version :-/
Unfortunately, I can't impose FF or Chrome for my site.
But if it's working for 2-3 calendars / page,  it's ok for me (and mostly users I think).
