### ISSUE TITLE
Select AngularJS compatibility

### ISSUE THREAD

**Issue by breket** [olton/Metro-UI-CSS#1203]
Trying to use select element with AngularJS but getting issue with empty select after receiving data over AJAX request 100 ms later after rendering the page.  
Initial object state: 
users = [];

after 100 ms users has a value [{"sid":"12345", "name":"test user"}]

But Select stays empty (does not refresh data automatically)

`
<select id="modusers"
             data-role="select"
             data-prepend="<span class='mif-users'></span>"
             class="pb-1">
            <option ng-repeat="user in users" value="{{user.sid}}">{{user.name}}</option>
</select>
`

**Comment by ShiruJan** [comment]
Hi breket,
Could you solve the problem?
I am developing it with angular, but when filling the control, the data is not displayed.

**Comment by breket** [comment]
As the developer of MetroUI said: "At the moment there is no financial opportunity to fully support Angular and React". Also I am using Metro v3 as it also supports Angular

**Comment by ShiruJan** [comment]
god, could you send me the link to download Metro v3?
tnks!

**Comment by breket** [comment]
https://metroui.org.ua/v3/

**Comment by ShiruJan** [comment]
thank you!
