### ISSUE TITLE
Calendar Picker - add option to allow null/undefined values

### ISSUE THREAD

**Issue by atherosxd** [olton/Metro-UI-CSS#1206]
add option to allow null/undefined values upon initialization, this is useful if the input is optional/nullable.

**Comment by olton** [comment]
Added in 4.2.23, You can user empty value
```
            <input id="data1" name="data1"
                   data-role="calendarpicker"
                   data-format="%d/%m/%y"
                   data-input-format="%d/%m/%y"
                   value=""/>

```

**Comment by olton** [comment]
in 4.2.24
+ [x] Calendar picker: add attribute `data-null-value`. If this attribute false and value empty, used current date
