### ISSUE TITLE
Toolbar: Draggable groups, and Vertical Option

### ISSUE THREAD

**Issue by petervanderwalt** [olton/Metro-UI-CSS#1207]
Hey, so i think we can all agree Ribbon Menu is the most beautiful menu ever created (:
But we have a couple application needs I am hoping we can discuss (:

1.  Draggable groups
So in many applications, there's dockable toolbars, that you can move / reposition / even add/replace - I'm sure you know what I mean.   Would be awesomely cool if the existing class=group could have a data-movable tag or something, which then makes them able to do this (gif below)

![movable groups](https://user-images.githubusercontent.com/31449271/45837552-e3466280-bd0f-11e8-9ed8-35445b0bfbfb.gif)

2.   The styling of Ribbon menu looks sooo good, I really dont want to use Sidebar or Side Navigation as its too bulky - any chance we can someday have a "vertical ribbon menu" - doesn't even need to be  ribbon menu itself (tabs on a vertical doesnt make sense. Or does it? (hmmm now that i think about it, right angle tabs along the screen edge... maybe)) - even just a container all along the side where I can use the familiar and beautiful ribbon-button, ribbon-icon-buttons etc would work.  We are looking to add a sidebar for some tools like this: 

![sidebar](https://user-images.githubusercontent.com/31449271/45837755-5a7bf680-bd10-11e8-9aef-1d8283443589.PNG)

**Comment by openbuilds-engineer** [comment]
I created a simple implementation of the sidebar https://codepen.io/petervanderwalt/pen/rqbKWo to continue with the project I have to do (: - sharing just in case it helps someone.

**Comment by olton** [comment]
in 4.2.27 I fix vertical layout
![2018-10-29-18-46-39](https://user-images.githubusercontent.com/365108/47665940-097ede00-dbab-11e8-9ebd-61e24fa408e1.jpg)

**Comment by olton** [comment]
You can put `toolbar` into your side container

**Comment by olton** [comment]
You can use the drag-items component to organize drag-and-drop and rank toolbars within specific containers.
