### ISSUE TITLE
disabled calendarpicker white text is unreadable

### ISSUE THREAD

**Issue by atherosxd** [olton/Metro-UI-CSS#1208]
if the calendarpicker was set to disable the font changes from black to white which is somewhat unreadable  or this is intentional? gray bg and white text doesn't seem to match.

Also fg-black on the class of the calendar doesn't seem to work either.
Edit: this is probably just me. I forgot that my screen have unusually high contrast

**Comment by olton** [comment]
Thank you. Color for disabled input changed to darkGray
