### ISSUE TITLE
TreeView:  Setting lower-level checkboxes programatically, the parent checkbox doesnt reflect the change (only when you click children with the mouse)

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1209]
Kinda hard to explain, I made a codepen: https://codepen.io/anon/pen/wEOxNx

Expected behaviour:
Clicking Doc1 -> Layer1 gets the [square in checkbox] to show some children are selected [WORKS OK]
Clicking Doc1,2,3 -> Layer1 gets the [checkmark in checkbox] to show all children are selected [WORKS OK]
Setting Doc1 Programatically -> Layer1 gets the [square in checkbox] to show some children are selected [DOES NOT UPDATE]
Setting Doc1,2,3 Programatically -> Layer1 gets the [checkmark in checkbox] to show all children are selected [DOES NOT UPDATE]

**Comment by olton** [comment]
```
    var tree = $('#doctree').data('treeview');
    setTimeout(function() {
        var check = $('#checkbox2');
        check.prop('checked', true);
        tree._recheck(check);
    }, 1000);
    setTimeout(function() {
        var check = $('#checkbox3');
        check.prop('checked', true);
        tree._recheck(check);
    }, 2000);
    setTimeout(function() {
        var check = $('#checkbox4');
        check.prop('checked', true);
        tree._recheck(check);
    }, 3000);
```

**Comment by openbuilds-engineer** [comment]
Sweeeet! Works perfectly for me now! Sorry, my bad!
