### ISSUE TITLE
Select -> Multiple: Doesnt close itself if you click another button

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1210]
![select-multiple doesnt close itself](https://user-images.githubusercontent.com/31449271/45897125-8e215400-bdd6-11e8-9a1e-003accc6872b.gif)

Gif shows the issue: 
If I open a Select-> Multiple - it stays open, when I click any other other Buttons on the page.  It only closes when I either click on the Select->Multiple again, or click on any other page element (like the page itself). 

Expected behaviour: Clicking a button should also close the select->multiple

**Comment by olton** [comment]
All work fine for me. Check Metro version

![select-dropdown](https://user-images.githubusercontent.com/365108/45914671-daa97580-be50-11e8-834b-2c0a3a5f17d2.gif)

**Comment by olton** [comment]
Each component is responsible only for its brethren. Dropdown button does not affect the behavior of select

**Comment by olton** [comment]
I found the problem, I'll try to fix it today
