### ISSUE TITLE
Form elements not working with jquery .load

### ISSUE THREAD

**Issue by cristhiansj** [olton/Metro-UI-CSS#1211]
Hello everyone.

I have a main.php file, there is loaded metro js and css files plus jquery, form elements here works correctly.

On main.php i have a dialog, there i load form.php with ajax and open using:

> \<div class="dialog rounded" data-role="dialog"  data-actions-align="right" data-default-action="false" id="dialogProducto">
> \</div>

> $('#dialogProducto').load(base_url + 'inv/producto/form', {"do": "new"});
> Metro.dialog.open('#dialogProducto');

Dialog shows up correctly and data is processed,  but Metro form elements inside the dialog with data-role="input" or data-role="select", for example, doesn't work.

![load](https://user-images.githubusercontent.com/12085431/45912222-5b318d00-bde3-11e8-88b3-b251fa9372be.png)

I tested it calling the form alone including metro css and js files on the file without jquery.load and works correctly.

![test](https://user-images.githubusercontent.com/12085431/45912223-61c00480-bde3-11e8-878e-bb8ae8359de0.png)

Also, i tested loading the form on a plain <div> element but it shows like the dialog.

I hope someone can help me, i don't want to use iframes again, thank you so much.

**Comment by olton** [comment]
create pen on codepen.io

**Comment by olton** [comment]
I recommended use `Metro.dialog.create(...)`  method for using in your case:
https://metroui.org.ua/dialog.html#_dialog_actions

**Comment by olton** [comment]
Create a pen on codepen.io with your code
