### ISSUE TITLE
Select - Two additional classes

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1212]
If possible, can You add two additional classes for the SELECT field?

Ex.

**data-cls-selected** for the item currently selected (now light Cyan)

and

**data-cls-item-selection** for the bar selection (now gray)

Ty!

**Comment by TorakikiSan** [comment]
Don't work?

https://codepen.io/TorakikiSan/pen/EeyWmp

**Comment by olton** [comment]
selected item exists only for select with multiple, for the single select box - select-input

**Comment by TorakikiSan** [comment]
For example:

![untitled - 1](https://user-images.githubusercontent.com/37299746/45931463-ceb3d580-bf6e-11e8-80cf-bfb54dc2d5ff.jpg)

I hope I have explained better :-)

**Comment by olton** [comment]
To change hover state for option:
```
<select data-role="select" data-cls-option="bg-red-hover fg-white-hover">
  <option value="1">Item 1</option>
  <option value="2">Item 2</option>
  <option value="3">Item 3</option>
</select>
```

**Comment by olton** [comment]
I add attribute `data-cls-option-active` in 4.2.24, data-cls-selected I will not add
