### ISSUE TITLE
setToday empty == invalid Date == throw error

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1215]
Inside setToday
at line 5918 of metro.js v=4.2.23

_if (Utils.isNull(val)) {
            val = new Date();
}_

if val == "" (empty)  
then 
new Date(val) == _invalidDate_

I suggest use !isValue

_if ( !Utils.isValue(val)) {
    val = new Date();
}_

**Comment by olton** [comment]
What the component? What the code firing error?

**Comment by olton** [comment]
Thank you, fixed in 4.2.24
