### ISSUE TITLE
Problems with overly when using 2 dialog

### ISSUE THREAD

**Issue by ShiruJan** [olton/Metro-UI-CSS#1218]
Hi team,

When i use 2 dialgos, i close the second but i lose the overlay of the first dialog.

Open first dialog:
![captura de pantalla 2018-09-27 a la s 11 36 10](https://user-images.githubusercontent.com/11635458/46160964-cb0f9f80-c249-11e8-8f0e-fc63e253b902.png)

Open second dialog:
![captura de pantalla 2018-09-27 a la s 11 36 17](https://user-images.githubusercontent.com/11635458/46160982-d5ca3480-c249-11e8-837d-085bc67c2a06.png)

Close the second dialog and lost the overlay:
![captura de pantalla 2018-09-27 a la s 11 36 25](https://user-images.githubusercontent.com/11635458/46161007-e1b5f680-c249-11e8-8901-13deb85cf09f.png)

Any solution?
Thank you.

**Comment by olton** [comment]
In Metro 4, all dialogs are use one global overlay

**Comment by ShiruJan** [comment]
Thank you for your response olton,

In this case, i should avoid using two dialogs at the same time, right?
Is there no solution?

Thank you.

**Comment by dinami-k** [comment]
Hi ShiruJan, please view this post [two overlays](https://github.com/olton/Metro-UI-CSS/issues/1170)

**Comment by olton** [comment]
in 4.2.24, I was add an attribute `data-leave-overlay-on-close='true|false'`. When `true`, overlay stay after dialog close.

**Comment by olton** [comment]
Also, you can use events `onShow` and `onClose` to create and remove your own overlay

**Comment by ShiruJan** [comment]
Perfecto, thank you!
