### ISSUE TITLE
checkbox performance

### ISSUE THREAD

**Issue by Gurucharan** [olton/Metro-UI-CSS#1219]
checkbox performance is very sluggish when the data is large. Is there any way to load the checkbox item one by one to reduce the initial user experience.

**Comment by olton** [comment]
examples, statistics, performance charts?

**Comment by Gurucharan** [comment]
hi, we are going for data virtualization mechanism for performance.
Is there any way to read the metro checkbox state (checked or unchecked) through javascript?

**Comment by olton** [comment]
```
<input type="checkbox" data-role="checkbox" id="chk">

var checked = $("#chk").is(":checked")...
var checked = document.getElementById("chk").checked...
```
