### ISSUE TITLE
There seems to be a problem with the _createNode code in listview.

### ISSUE THREAD

**Issue by itsurea** [olton/Metro-UI-CSS#1220]
`if (Utils.objectLength(o.structure > 0)) $.each(o.structure, function(key, val){
            if (data[key] !== undefined) {
                $("<div>").addClass("node-data item-data-"+key).addClass(data[val]).html(data[key]).appendTo(node);
            }
        });`

I think `'Utils.objectLength(o.structure > 0)'` should be `'Utils.objectLength(o.structure) > 0'`.

In the current version, the structure value does not work properly with the add function.

**Comment by olton** [comment]
Thank you, fixed in 4.2.24
