### ISSUE TITLE
Timepicker - Extra leading 0 if value was set using val(t)

### ISSUE THREAD

**Issue by atherosxd** [olton/Metro-UI-CSS#1221]
when setting the value of time picker, the timepicker will all have extra leading 0, e.g 000:000:000 instead of 00:00:00. 
also happens when manipulating the data-value attribute
![timepicker](https://user-images.githubusercontent.com/21239592/46243311-79ac0f80-c405-11e8-8361-1cfc1cc0881a.png)

**Comment by olton** [comment]
How you define timepicker?

**Comment by atherosxd** [comment]
i set the value(string) using the method val() 
below are the input
`<input type="text"  id="bookingDuration" data-role="timepicker" data-value="0" ref="bookingDuration">`

and how I set the value
`$('#bookingDuration').data('timepicker').val(this.PatronBooking.Duration);`

**Comment by olton** [comment]
Thank you, fixed in 4.2.24
