### ISSUE TITLE
AngularJS compatible?

### ISSUE THREAD

**Issue by breket** [olton/Metro-UI-CSS#1223]
I am using MetroUI v.4 parallel with AngularJS.

On Select Element I try to capture an event "on item select"
HTML
`
<select id="userTitle"
             data-role="select"
             data-prepend="<span class='mif-organization'></span>"
             data-on-item-select="{{onTitleChange}}"
             class="pb-1">
            <option value="" selected>none</option>
</select>
`
JS
`
$scope.onTitleChange = function (val, option, item) {
        console.log(val, option, item);
}
`

...but it does not work. I tried several another parameters in HTML such as 
data-on-item-select="onTitleChange" 
or 
data-on-item-select="{{onTitleChange()}}" 
and 
data-on-item-select="{{onTitleChange(val, option, item)}}"

but I receive JS errors...

Is MetroUI v.4 compatible with AngularJS?

Regards...

**Comment by olton** [comment]
At the moment there is no financial opportunity to fully support Angular and React
