### ISSUE TITLE
Horizontal menu with data-role = "appbar"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1224]
I used the first example of the Metro-UI documentation on data-role = "appbar" to create a horizontal menu.

This is the result

https://codepen.io/TorakikiSan/pen/EeyWmp

Experiment failed :-)

Where did I go wrong?

**Comment by olton** [comment]
Use attribute `data-expand` or `data-expand-point`

**Comment by TorakikiSan** [comment]
Perfect!

Thank's!
