### ISSUE TITLE
Dear friends! Project needs your support!

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#1225]
# Metro 4 always will be FREE!

Dear friends! Despite the fact that the project does not have financial support, I decided on how Metro 4 will be licensed further:

**Metro 4 will remain free and open source for everyone!**

1) For those who want quick support and assistance in creating pages and additional components, there will be a special paid license!
2) Also, a paid license will be introduced for the Metro 4 version for Vue, React, Angular!

Sincerely Sergey (aka olton) Pimenov.

## For support, you can become a Patron on: 
<a href="https://www.patreon.com/bePatron?u=8975658">Patreon</a>
<a href="https://opencollective.com/metro4">Open Collective</a>

## Direct support over SWIFT
For the Swift payments detail see below.

**Comment by arjarn** [comment]
I'm sad to learn your health problem and understand your decision, unfortunately lot of similar project are same problems :-/
Why not having unique and low subscription for non commercial project and mensual subscription for commercial ?
Or perhaps having "personal edition" with limited features ?

**Comment by olton** [comment]
Metro 4  free For open source and non commercial projects

**Comment by TorakikiSan** [comment]
I'm sorry for your health problems.

I have no resources to become a Patreon, I enjoy writing code for personal use, but I can make a small donation if you tell me how!

**Comment by olton** [comment]
@ShiruJan Dear friend! Thank you for your post, by, Unfortunately, PayPal does not work in Ukraine. I have an account with Patreon (https://www.patreon.com/metroui) and Payoneer.

**Comment by olton** [comment]
@ShiruJan I hope that I will be able to catch the attention of the community and collect some amount and not introduce a commercial license. But, you can always write to me and I will consider in private the possibility of granting a free license to a commercial project for development and the possibility of subsequent remuneration.

**Comment by olton** [comment]
Thank you @TorakikiSan for your support !

**Comment by mhcifci** [comment]
You have Bitcoin Eth and etc?

**Comment by olton** [comment]
Bitcoin | 1HBdvWjUQ6ynKCQkoUgoU2p27N4jqBvu5r
Bitcoin Cash | qrmyju273z03auqp7mnl0wz0rxgwh7g6wyge94ghl6
Ethereum | 0xEb460Dd78c732cCDDaD2454c2bf885604D5ac11b
ETH Classic | 0x41B40cE98369d675f6E13CC05a8beA5727E4858c
Litecoin | LdQSPR6bHHfru72GPjxgrc7rb69GykRba4
Decred | DsWcnMjiqruRPhsBTQ1ddJcwAvi4je5wgG7
Dash | XtvG52j9Mkh5bkDFvNJN4oMxqs42jeJ25i
Zcash | t1UQkR7vwTWqtRan1EnCvcLj8MeKWgKvyDi

**Comment by olton** [comment]
@mhcifci Yes, I have crypto coin wallets

**Comment by openbuilds-engineer** [comment]
Can we do Paypal donations? (:

**Comment by openbuilds-engineer** [comment]
Also sorry to hear about your Health!   Hope you do better soon!   You'll be in our thoughts! 
We have been working on plans to help out with the financial side too, soon! 

There is just no equivalent! Metro KILLED bootstrap, and every time I get back on the documentation, theres new components.   Not just, ahh another component... No another AWESOME most beautifully designed component... We love you man~!

**Comment by olton** [comment]
Unfortunately, only one person responded to my request for financial assistance to the project. Thank you TorakikiSan. I really do not want to enter a paid subscription, but most likely this will have to be done for commercial projects and closed source projects.

**Comment by openbuilds-engineer** [comment]
(: Wheels of corporate rolls slowly (: - i hope it gets momentum!

**Comment by dagnelies** [comment]
Indeed, I wouldn't give up just yet. These things take time and some more patience is problably worth it!

**Comment by olton** [comment]
### Metro 4 will remain free and open source for everyone!
For those who want quick support and assistance in creating pages and additional components, there will be a special paid license! 
Also, a paid license will be introduced for the Metro 4 version for Vue, React, Angular!

**Comment by triplebeta** [comment]
Very good news Sergey, thanks for creating and maintaining Metro4 and your
relentless effort to support the community around it! Much appreciated!

I already use your library for some years for a simple website. Is there a
way I can make some donation to support your effort?

Cheers,
Jeroen Bijleveld

Op vr 21 dec. 2018 12:04 schreef Sergey Pimenov <notifications@github.com:

**Comment by olton** [comment]
@triplebeta Yes, of course, you can make a donation. I will be very happy about this, thanks!

**Comment by triplebeta** [comment]
Hi Sergey, thank you, you did an awesome job building and maintaining the
Metro library and I'm happy to be able to support your work.

For me no need to be listed as a supporter but if it's helpful for you then
feel free to add a link to my site www.triplebeta.nl (logo is on the first
tile).

Best wishes and have a great 2019! 👍

Cheers,
Jeroen

Op wo 26 dec. 2018 15:22 schreef Sergey Pimenov <notifications@github.com:

**Comment by olton** [comment]
From Monday (21 jan) I go to the hospital for 10 days. Unfortunately, heart problems have resumed. At this time period, updates and fixes will not be. If someone wants to help me with finances for treatment, I will be very grateful. Thanks, my friends.

**Comment by TorakikiSan** [comment]
In Italy we usually say "in bocca al lupo"!

Good luck Olton!

**Comment by openbuilds-engineer** [comment]
Sorry to hear the news!  We'll keep you in our thoughts and hope for the best!

**Comment by kram242** [comment]
Hello Sergey, the OpenBuilds Team would like you to know that you are in our thoughts and prayers and that it is an honor to be able to give back to you for all the work you have done to help others.
Get well soon my friend.

**Comment by olton** [comment]
Dear friends from OpenBuild Teams! Thank you for your help! It is very important for me to know that my work is beneficial. It is very expensive to treat in Ukraine and your help will help me a lot! Even my heart beat smoother!

**Comment by olton** [comment]
**Metro 4 code lines stats:**
- javascript - 20 227
- less - 16 696
- compiled css - 49 398
- docs html - 41 349

**Comment by olton** [comment]
Dear friends from OpenBuild Teams! Your support on Patreon is a declined. Why?

**Comment by openbuilds-engineer** [comment]
Hi Sergey

I'll ask finance to look into it, but just a heads up (:  a PM might be more appropriate for payment issues - out here in thread it kinda feels like a name and shame

**Comment by olton** [comment]
Metro 4 now has a **GOLD SPONSOR** and this is the company [OpenBuilds](https://openbuilds.com/). Thank you, my friends!

**Comment by olton** [comment]
Metro 4 now has a **SILVER SPONSOR** and this is the company [Infinity Tech Systems](http://www.infinitytechsystems.com/). Thank you, my friends!

**Comment by olton** [comment]
Dear friends from OpenBuilds and Infinity Tech Systems! With your donations, I bought medicine and a course of therapeutic massage. Thanks.
