### ISSUE TITLE
Binding Table Component using Vue js

### ISSUE THREAD

**Issue by Jochii12** [olton/Metro-UI-CSS#1227]
Hello sir can i bind  table componend data-source using vue js ?
uhmm i got some error. " Data for table is not a object "

when i use source only as i bind it, there is no data showing. 

also i tried simple table 

 <table class="table striped mt-4" data-role="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                </thead>
                <tbody>
                    <tr v-for="category in categories" :key="category.id">
                        <td v-text="category.id"></td>
                        <td v-text="category.categoryName"></td>
                        <td v-text="category.desc"></td>
                        <td>
                            <button class="button flat-button info mr-3" @click="editData(category.id)">Edit</button>
                            <button class="button flat-button alert" @click="deleteData(category.id)">Delete</button>
                        </td>
                    </tr>
                </tbody>
            </table> 

the ui show 2 search and 2 show Entries.

then i go back to simple table hahaha. without  data-role="table" tag.

Thank you sir.

**Comment by olton** [comment]
If you use `data-source` for the table, the server must send data as a JSON object. Example https://metroui.org.ua/data/table.json

**Comment by Jochii12** [comment]
yes sir. but im using data component from vue .. is this possible that i can bind data from table ? 
your table is very cool and simple flat.. i very like .

**Comment by olton** [comment]
maybe this https://metroui.org.ua/vuejs.html help to you

**Comment by Jochii12** [comment]
i ll give it a try

**Comment by Jochii12** [comment]
hello sir. somehow i found a way heheh maybe i can share to every here.
Here's the code sir.
<div class="mt-5">
<table class="table" data-role="table">
<thead>
<tr>
<th>Id</th>
<th data-cls-column="bg-cyan fg-white text-center">Name</th>
<th data-cls-column="bg-cyan fg-white text-center">Description</th>
<th></th>
</tr>
</thead>
<tbody>
<tr v-for="category in categories" :key="category.id">
<td v-text="category.id"></td>
<td v-text="category.categoryName"></td>
<td v-text="category.desc"></td>
<td>
<button class="button flat-button info mr-3" @click="editData(category.id)">
Edit</button>
<button class="button flat-button alert" @click="deleteData(category.id)">
Delete</button>
</td>
</tr>
</tbody>
</table>
</div>


Thanks you very much sir for your time

**Comment by Jochii12** [comment]
hello sir. somehow i found a way heheh maybe i can share to every here.
Here's the code sir.
`<div class="mt-5">
<table class="table" data-role="table">
<thead>
<tr>
<th>Id</th>
<th data-cls-column="bg-cyan fg-white text-center">Name</th>
<th data-cls-column="bg-cyan fg-white text-center">Description</th>
<th></th>
</tr>
</thead>
<tbody>
<tr v-for="category in categories" :key="category.id">
<td v-text="category.id"></td>
<td v-text="category.categoryName"></td>
<td v-text="category.desc"></td>
<td>
<button class="button flat-button info mr-3" @click="editData(category.id)">
Edit</button>
<button class="button flat-button alert" @click="deleteData(category.id)">
Delete</button>
</td>
</tr>
</tbody>
</table>
</div>`


Thanks you very much sir for your time

**Comment by Jochii12** [comment]
hello sir. somehow i found a way heheh maybe i can share to every here.
Here's the code sir.
<div class="mt-5">
<table class="table" data-role="table">
<thead>
<tr>
<th>Id</th>
<th data-cls-column="bg-cyan fg-white text-center">Name</th>
<th data-cls-column="bg-cyan fg-white text-center">Description</th>
<th></th>
</tr>
</thead>
<tbody>
<tr v-for="category in categories" :key="category.id">
<td v-text="category.id"></td>
<td v-text="category.categoryName"></td>
<td v-text="category.desc"></td>
<td>
<button class="button flat-button info mr-3" @click="editData(category.id)">
Edit</button>
<button class="button flat-button alert" @click="deleteData(category.id)">
Delete</button>
</td>
</tr>
</tbody>
</table>
</div>


Thanks you very much sir for your time

**Comment by Jochii12** [comment]
hello sir. somehow i found a way heheh maybe i can share to every here.
Here's the code sir.

 <div class="mt-5">
<table class="table" data-role="table">
<thead>
<tr>
<th>Id</th>
<th data-cls-column="bg-cyan fg-white text-center">Name</th>
<th data-cls-column="bg-cyan fg-white text-center">Description</th>
<th></th>
</tr>
</thead>
<tbody>
<tr v-for="category in categories" :key="category.id">
<td v-text="category.id"></td>
<td v-text="category.categoryName"></td>
<td v-text="category.desc"></td>
<td>
<button class="button flat-button info mr-3" @click="editData(category.id)">
Edit</button>
<button class="button flat-button alert" @click="deleteData(category.id)">
Delete</button>
</td>
</tr>
</tbody>
</table>
</div>


Thanks you very much sir for your time
