### ISSUE TITLE
Problem with jQuery

### ISSUE THREAD

**Issue by deepikasharma810** [olton/Metro-UI-CSS#1229]
Hello,

I got a problem with including the jQuery in our project.
When I include a reference from the server everything works without any problems.

For example

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>

When I include the local reference nothing work(path exist and the file is in the directory).

For example 

<script src="metro4/js/jquery-3.3.1.min.js"></script>
<script src="metro4/metro/js/metro.min.js"></script>

When I run it with the local script i get some errors.

![image](https://user-images.githubusercontent.com/38650086/46716558-d230a780-cc64-11e8-8d7e-b3b8d931b435.png)

Any suggestion why this doesn't work?

Best Regards,

Deepika

**Comment by olton** [comment]
Check path to jquery
