### ISSUE TITLE
Table draw stops after approx 200-250 records

### ISSUE THREAD

**Issue by Egregius** [olton/Metro-UI-CSS#1230]
Hi,

I'm having issues with a table. 
As seen in the screenshot the tables stops after approx 200-250 rows. For the last printed row the last 2 columns are empty altough they contain data. 
When looking at the source of the page all 500 rows are there, just not visible in the browser.
This only happens in Chrome. In Firefox the table is rendered completely. 

Any ideas?

![screenshot at okt 15 01-27-28](https://user-images.githubusercontent.com/7478797/46923561-b2f59980-d019-11e8-85ff-17b8bb68daf6.png)

**Comment by olton** [comment]
Show your browser console log

**Comment by Egregius** [comment]
Hi,

Only the violation is shown, but that one is also there on pages that don't have a table. The violation is caused by the metro.js script.

![image](https://user-images.githubusercontent.com/7478797/46924543-31583880-d026-11e8-96e9-635daa00febd.png)

**Comment by Egregius** [comment]
My data is good, it shows perfectly when viewing the page source. All table rows and shown and they all have identical markup. In Firefox all rows are shown, but not in Chrome. Chrome stops around 200 rows, but never the exact same amount. Like something is triggered to fast, or takes to long. 
The whole PHP and SQL execution time is less than 200msecs, don't think that that could be the problem.

**Comment by dagnelies** [comment]
Providing an online example illustrating your problem would be helpful.

**Comment by Egregius** [comment]
Thanks for replying. 
I made a codepen at [https://codepen.io/egregius/pen/oaoNLO](https://codepen.io/egregius/pen/oaoNLO) and tested it in Chrome on macOS and Windows. 
Both don't show all 300 records.

**Comment by dagnelies** [comment]
It looks like a Chrome bug. The "init" function is apparently being called too early,  resulting in the HTML content being only partially loaded when jquery/metro are initialized. Try importing the scripts at the end of the page instead.

**Comment by Egregius** [comment]
Thank you for that! Problem solved!
Moved my js file to the footer and now the table draws perfectly. 
Had to alter some other stuff tough that got broken with this move, but everything's ok now.
