### ISSUE TITLE
form validator function suggestion

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1232]
form validator events
original：
onValidateForm(el)	  data-on-validate-form	    form	      Event generate if form passed validation

Change to：
onValidateForm(el, data)
Gets the name and value of all form elements.

advantage：
1 Convenient ajax calls
2 don't have to get the data by hand

When the parameter “data” is called：
data >>>>>{"username":"dack","password":"123456"}
data.username>>>>>dack
data.password>>>>>123456

**Comment by olton** [comment]
in 4.2.28
+ [x] Validator: add argument `data` to events `data-on-validate-form`, `data-on-error-form`. Data is a `object` and contains pairs: `input-name: input-value`

**Comment by chongzia** [comment]
收到了 感谢

**Comment by olton** [comment]
@chongzia  English, please

**Comment by chongzia** [comment]
thank you
The most powerful olton
