### ISSUE TITLE
Desktop Demo not working correctly.

### ISSUE THREAD

**Issue by hykilpikonna** [olton/Metro-UI-CSS#1233]
https://metroui.org.ua/examples/desktop/desktop.html

When I open any window, it says "Uncaught TypeError: Cannot read property 'offsetHeight' of undefined" on the console. And nothing would show up.

Browser: Chrome 69.0.3497.100

![image](https://user-images.githubusercontent.com/22280294/47257577-a8923000-d45d-11e8-8361-f88797216051.png)
![image](https://user-images.githubusercontent.com/22280294/47257556-71238380-d45d-11e8-91cc-e2c5b6fc0e4d.png)

**Comment by olton** [comment]
Fixed in 4.2.26, wait for release or download develop branch

**Comment by hykilpikonna** [comment]
Ok, thanks <3
