### ISSUE TITLE
Table component, a several questions want to know .I hope author can give me alittle init

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1234]
1 How do set the request type, post or get

2 How do I access the server。 Follow the documentation action ，Did not get the results ，Nothing is displayed
![image](https://user-images.githubusercontent.com/22745515/47261598-1f363880-d505-11e8-96be-6d2c0f88a348.png)

3 Table output  whether can support json arrays

Thank you    I'm sorry to trouble you    Hope to get the answer

**Comment by dagnelies** [comment]
Quoting the docs:
    
    <table class="table striped table-border mt-4"
       data-role="table"
       data-source="data/table.json">
    </table>

    To use external source, you must create JSON data in specific format. Example of JSON file.

    {
        header: [...],
        data: [...]
    }

You are using `data-view-...` is to load/save a specific layout for the table's columns, as well described in detail in the docs https://metroui.org.ua/table-component.html#_table_inspector

**Comment by olton** [comment]
for `data-view-*` https://metroui.org.ua/table-component.html#_table_inspector
