### ISSUE TITLE
start page issue

### ISSUE THREAD

**Issue by hxffelixho** [olton/Metro-UI-CSS#1237]
I found there was a format issue in start page when I add tiles with js.
[start - Copy.zip](https://github.com/olton/Metro-UI-CSS/files/2509228/start.-.Copy.zip)

**Comment by hxffelixho** [comment]
Sorry, I'm not familiar with codepen, can you please help to create? I already upload the code.

**Comment by olton** [comment]
I don't have time to download and deploy user code, for all users an equal rules: https://github.com/olton/Metro-UI-CSS/blob/master/CONTRIBUTING.md#issues-guidelines

**Comment by hxffelixho** [comment]
https://codepen.io/FelixHo/pen/xyQVwr
the tiles are smaller than not involve start.css and start.js

**Comment by olton** [comment]
remove style:
```
[class*=tile-] {
  transform: scale(0.8);
}
```
