### ISSUE TITLE
FORM: extend .input-large to all input type field

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1241]
Is it possible extend the class .input-large to all Metro's FORM fields type (SELECT, TAGINPUT, SPINNER etc.) and add a new class .input-small?

Thanks!

**Comment by olton** [comment]
in 4.2.27
![2018-10-29-11-51-41](https://user-images.githubusercontent.com/365108/47642322-08c95600-db71-11e8-9279-3e138290ebf7.jpg)

**Comment by TorakikiSan** [comment]
Thank's!
