### ISSUE TITLE
Table "setData(...)" would be nice.

### ISSUE THREAD

**Issue by dagnelies** [olton/Metro-UI-CSS#1242]
In a table, it would be nice if you could directly set the data per scripting, like `setData(headers, items)` and `setItems(items)`.

Since such data can already be loaded from a URL and shown, I guess isolating the piece of code do redraw the table with new data should be manageable.

That would be welcome.

**Comment by olton** [comment]
in 4.2.27
+ [x] Table: add method `setData(obj)` 
+ [x] Table: add method `setHeads(obj)`, `setHeadRow(obj)`  
+ [x] Table: add method `setItems(obj)`

**Comment by dagnelies** [comment]
Great, thanks!
