### ISSUE TITLE
Feature request: Enhance Splitter to store positions to localstorage so users setup stays consistent after refresh

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1243]
Not a high priority, but i figured it could be a cool enhancement.  

If a user is finished using the new (AWESOME as it is!) splitter to setup the workspace to their liking, after a refresh, its back to defaults. I think it could be cool to have it remember the splitters new positions (:

Hope you have a good one!

**Comment by olton** [comment]
in 4.2.27
+ [x] Splitter: add attribute `data-save-state`, required element `ID`. If `true`, panes sizes stored into `Storage`
