### ISSUE TITLE
"windows" call my function when click close btn

### ISSUE THREAD

**Issue by penyin** [olton/Metro-UI-CSS#1244]
i know have "data-close-action" can call my function,

but i need not to empty the window,

because i used vue js

i gived v-if to show or hide.

i try to edit metro.min.js  :: "t.remove():e.hide()" -> "1:1"

but i think it's not good solutions.

**Comment by penyin** [comment]
i find i can used "Drag element" to do this.
i try it.

**Comment by olton** [comment]
You can use the attribute `onCloseClick` to define the event for the close button.

**Comment by penyin** [comment]
thank you, i will try this.
