### ISSUE TITLE
SideBar not 100% height 

### ISSUE THREAD

**Issue by Jochii12** [olton/Metro-UI-CSS#1249]
![image](https://user-images.githubusercontent.com/35551627/48107472-c1cb1700-e27a-11e8-91a8-a98cac5f47cb.png)

Hello sir here my code . the sidebar is not full height

![image](https://user-images.githubusercontent.com/35551627/48107429-8d575b00-e27a-11e8-9c8b-c2dd7495806a.png)

**Comment by Jochii12** [comment]
i tried adding style height 1000px and its work but not complete fix :(  in asside markup

**Comment by olton** [comment]
Create pen on codepen.io

**Comment by Jochii12** [comment]
https://codepen.io/LeoKi12/pen/yQYqWM

but it working here im using vue js .. so i dont know how i will import jquerry in vue..

**Comment by olton** [comment]
https://metroui.org.ua/vuejs.html

**Comment by Jochii12** [comment]
i already implement sir.. but it seem the jquerry is required

**Comment by olton** [comment]
jQuery not a part of Metro 4. Read offsite http://jquery.com/ for using jquery with Vue
