### ISSUE TITLE
Popover never close

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1251]
Hello Olton,

Sorry another issue with Popovers : a popover never close after display (try with your demo page here after a complete clear of the cache)

https://metroui.org.ua/popovers.html

**Comment by Falconpage** [comment]
Ok thanks.
Something related with "Uncaught ReferenceError: popovered is not defined" ?

**Comment by olton** [comment]
Thanks, I fix it in 4.2.28, Download then develop branch or wait for the release on 11/11

**Comment by Falconpage** [comment]
Tested : it works.
Have a good evening.
