### ISSUE TITLE
Vertical Menu issue

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1252]
Hello,

Vertical Menu with dropdown doesn't work :

https://metroui.org.ua/menu.html# -> Vertical menu section.
Click on community  (Alt+F1) and see the issue

**Comment by olton** [comment]
thanks, fixed

**Comment by Falconpage** [comment]
Great job 👍

**Comment by Falconpage** [comment]
Tested : it works.
Have a good evening.
