### ISSUE TITLE
MetroUI library link in codepen.io

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1253]
I configured the JS section adding

https://cdn.metroui.org.ua/v4/js/metro.min.js

but in console I see:

Metro 4 Components Library - v4.2.26.704

it's correct?

**Comment by olton** [comment]
clear cache

**Comment by olton** [comment]
Ctrl+F5 can help

**Comment by olton** [comment]
![2018-11-08-23-22-00](https://user-images.githubusercontent.com/365108/48228172-1ec6ea00-e3ad-11e8-8e0d-98dfa18f79c0.jpg)
