### ISSUE TITLE
FORM: strange behavior

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1254]
In this case, it is really difficult to reproduce the problem with codepen.io

https://codepen.io/TorakikiSan/pen/EeyWmp

I have a page with a FORM to which the behavior is changed ("action" attribute) according to the button pressed.

With the .click() event, the corresponding code is called in jQuery and the value of the "action" attribute is dynamically changed and everything works correctly.

This is no longer true if I add the data-validator and data-requested-mode attributes to FORM because I would like to check the value of the fields entered, the page called is always itself, as if the "action" attribute was not recognized.

I have to use a different code from this?

```
     $("#SEARCH").attr("action", "mame.test2.htm")
                 .attr("target", "_blank")
                 .click();
```

**Comment by olton** [comment]
Maybe `$('#SEARCH').attr().attr().submit()` ?

**Comment by TorakikiSan** [comment]
Neither with .clik() nor with .submit() works

If the page is called (for example) mame.htm, the server loads another mame.htm in a new browser tab (this is because the attribute action="", if I remember correctly, not specifying a value, loaded itself)

**Comment by olton** [comment]
check the values of the input fields, they must meet the verification conditions, otherwise the form will not be sent

**Comment by TorakikiSan** [comment]
Of course those values are just for example. The problem occurs when you enter correct values and press one of the two buttons.

**Comment by olton** [comment]
try 4.2.29

**Comment by olton** [comment]
https://sandbox.org.ua/olton/debug/eoDZKawEn6

**Comment by TorakikiSan** [comment]
The problem of the SUBMIT button seem solved, but now the fields are always mandatory. If you check the JS script, in case of $("#TYPE").val()==3 the MACHINE field may be empty, but now it is always requested, as if there was the attribute data-validate="required". This also happens if you add the attribute data-required-mode="false" to the FORM tag. About data-validate="required": is it possible to change the CSS? The dotted border .... ;-)

**Comment by olton** [comment]
remove `required` and `$("#TYPE").val()==2`

**Comment by olton** [comment]
your select not have option with value == 3

**Comment by TorakikiSan** [comment]
I feel so stupid ....
