### ISSUE TITLE
Popover show event 

### ISSUE THREAD

**Issue by nkiruhin** [olton/Metro-UI-CSS#1258]
Hi. Popover event "onShow" not work. Event onHide work fine. 
![popover](https://user-images.githubusercontent.com/39044526/48465169-5c87a080-e7fb-11e8-841c-e511270ef9b7.jpg)

**Comment by olton** [comment]
Thanks, fixed in 4.2.29
demo from develop branch https://sandbox.org.ua/olton/code/kr6b94w2yz

**Comment by nkiruhin** [comment]
Ok. Thanks!!!
