### ISSUE TITLE
Notify duration is not working

### ISSUE THREAD

**Issue by msouzarunner** [olton/Metro-UI-CSS#1259]
Changing the time parameter has no effect whatsoever, could you take a look or guide me how to solve it?

**Comment by olton** [comment]
https://sandbox.org.ua/olton/code/9zjmNDbXV4

**Comment by msouzarunner** [comment]
I was using it this way, passing the parameter inside the notify.create
		notify = Metro.notify;
		notify.create(message, '' , {
                        duration: 3000,
			width: 250,
			cls: classe
		});	}

but now putting in the notify.setup worked, grateful for the help

		notify = Metro.notify;
		notify.setup({
			duration: 3000
		});
		notify.create(message, '' , {
			width: 250,
			cls: classe
		});	}
