### ISSUE TITLE
Is dialog can be draggable ?

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1270]
Hello Olton,

Is there a way to make dialog draggable ? I have tried placing my dialog div section into 
`<div data-role="draggable" data-drag-element=".drag-element" class="w-25"></div>`
with drag-element class to the dialog title without success.

**Comment by olton** [comment]
Use `predefined` dialog with an additional role `draggable`
https://sandbox.org.ua/olton/code/nyAbpzmp0R

**Comment by Falconpage** [comment]
Thanks a lot for your help, I think this example have to be in the dialog component guide.
