### ISSUE TITLE
onShow parameter of dialog does not work

### ISSUE THREAD

**Issue by msouzarunner** [olton/Metro-UI-CSS#1271]
I put a function in the onShow parameter of the dialog and it is executed before the dialog appears, should not it be later?

**Comment by msouzarunner** [comment]
I need to put a datatable inside the dialog and need to run the $('#example').dataTable() command in the onShow parameter, or have another way of doing this?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/CONTRIBUTING.md#issues-guidelines

**Comment by olton** [comment]
All works fine https://sandbox.org.ua/olton/code/yExZ09mP2M

**Comment by msouzarunner** [comment]
Instead of using the datatable, I set up the MetroUI 4 plugin table and it works perfectly for my application. Looking at the example https://metroui.org.ua/examples/table/table-inspector-exprot-custom-func.html
