### ISSUE TITLE
Sidebar does not close

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1273]
With the last Metro relaese 4.2.30. Look the page at 

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

If I open the sidebar, then, by clicking on the white arrow at the top, the sidebar no longer closes.

Did I do something wrong in the code?

Thank's!

**Comment by olton** [comment]
All works, Check z-index for white arrow
