### ISSUE TITLE
Problem using select data-role in table control

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1275]
Hello Olton,

I hope your are well.
Tonight an issue using "select" data-role in a table control.

Here the code pen to see : https://codepen.io/Falconpage/pen/OaBrmK

With select data-role the select area cannot be display
Without select data-role it is OK.

I tried playing with z-index without success.

**Comment by olton** [comment]
use attribute `data-cell-wrapper="false"` for table

**Comment by Falconpage** [comment]
https://codepen.io/Falconpage/pen/OaBrmK, demo3 with the fix : it's OK
If I'm correct this is the css rule "overflow: hidden;" that cause this problem in my code ?
Thanks again spending time to this.
Have a great day Olton !
