### ISSUE TITLE
Close app-bar-menu with API?

### ISSUE THREAD

**Issue by JohnArcher** [olton/Metro-UI-CSS#1276]
Hi!

Is it possible to close an app-bar-menu (like shown here https://metroui.org.ua/app-bar.html#_appbar_menu) via an API call, e.g. `.close()`? Similar to these methods: https://metroui.org.ua/dropdown.html (scroll to the end).

Thanks in advance!

**Comment by olton** [comment]
if the menu has a dropdown role, you can use dropdown API to manipulate it

**Comment by JohnArcher** [comment]
This is what I tried. This is my code:

```HTML
<ul class="app-bar-menu ml-auto">
    <li class="ttt">
        <a href="#" class="dropdown-toggle">Main Entry</a>
        <ul class="d-menu put-right" data-role="dropdown">
            <li><a href="#">Sub Entry 1</a></li>
            <li class="divider bg-lightGray"></li>
            <li><a href="#">Sub Entry 2</a></li>
        </ul>
    </li>
</ul>
```

Now I am unsure on how to get this object via JavaScript. The examples on the documentation site for "dropdown" is a bit unclear. I used this which does not work:

```javascript
var dropdown = $('.ttt').data('dropdown');
```

Thanks for your help!

**Comment by olton** [comment]
var dropdown = $('ul').data('dropdown');
dropdown.close();

**Comment by JohnArcher** [comment]
Thanks and sorry at the same time. :-) I confused myself. :-) As I said I wanted to close the app-bar-menu, not a dropdown inside this bar. Especially I want to do it in responsive mode. Now it works that I can close the app-bar-menu - but the icon on the right does not change from arrow down to hamburger.

I created a codepen to show you what I mean: https://codepen.io/JohnArcher/pen/MzZmoO

Now, resize the browser so the hamburger menu is created on the right. 
Click the hamburger icon (list gets opened).
Now click on the app icon on the left. 
The menu is closed thanks to your help but the arrow down icon is still shown.

Do I have to manually change the classes for the hamburger icon (deleting '.hamburger.menu-down.active'?)? Or is it possible that you can handle that in your core?

**Comment by olton** [comment]
var appbar = $(el_appbar).data('appbar');
appbar.close()

**Comment by JohnArcher** [comment]
Very nice, thanks, this works! I altered my codepen examples for others as a reference.

Maybe you can add this to the appbar doku that and how to close it?
