### ISSUE TITLE
Windows XP + Firefox 52.9.0

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1278]
In my son's old PC there is still Windows XP and Firefox as a browser. I can not update it to Windows10 because it is too old and the ram (only 1gb) is not enough. By connecting to my server, I get this error:

Metro 4 Components Library - v4.2.30.709   metro.min.js:7:4889
Error: Unknown color format!  metro.min.js:7:17251
	v.toRGB http://mame/js/metro.min.js:7:17251
	v.isDark http://mame/js/metro.min.js:7:19540
	v.isLight http://mame/js/metro.min.js:7:19622
	Q._createStructure http://mame/js/metro.min.js:7:66923
	Q._create http://mame/js/metro.min.js:7:66559
	Q.init http://mame/js/metro.min.js:7:65597
	S.plugin/x.fn[t]/< http://mame/js/metro.min.js:7:7119
	.each http://mame/js/jquery-3.3.1.min.js:2:2571
	w.prototype.each http://mame/js/jquery-3.3.1.min.js:2:1238
	S.plugin/x.fn[t] http://mame/js/metro.min.js:7:7084
	S.initWidgets/</< http://mame/js/metro.min.js:7:6903
	map self-hosted:275:17
	S.initWidgets/< http://mame/js/metro.min.js:7:6801
	.each http://mame/js/jquery-3.3.1.min.js:2:2571
	S.initWidgets http://mame/js/metro.min.js:7:6767
	S.observe/</< http://mame/js/metro.min.js:7:5679
	map self-hosted:275:17
	S.observe/< http://mame/js/metro.min.js:7:5188

Thank's!

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS#browser-compatibility

**Comment by olton** [comment]
Guaranteed support 2 last version of the browsers!

**Comment by olton** [comment]
The old version of the browsers and OS not will be supported

**Comment by olton** [comment]
https://metroui.org.ua/browsers.html
