### ISSUE TITLE
Sidebar how to create submenu under menu?

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1279]
hi~
How should I use a second or third-level menu when I need to wear it in the process of using it?

**Comment by chongzia** [comment]
![image](https://user-images.githubusercontent.com/22745515/49339419-5b17fe00-f66c-11e8-94c8-ca420859894c.png)

**Comment by olton** [comment]
https://sandbox.org.ua/olton/code/KN1bD4bkzD

**Comment by olton** [comment]
![sidebar-on-right](https://user-images.githubusercontent.com/365108/49342492-be9e2d80-f664-11e8-9173-7abd3b4a38bd.gif)

**Comment by chongzia** [comment]
so quickly~~！？！！？！！
In any case      can be improved   很满足和快乐!

**Comment by chongzia** [comment]
谢谢

**Comment by tefod-zz** [comment]
Could you adapt as well the shifting content if the sidebar is on the right side?
Suggestion (tested):
![image](https://user-images.githubusercontent.com/3308645/208111636-62ba7588-e17a-4eeb-9aa0-85b74bd836d4.png)
