### ISSUE TITLE
Calendar - add week numbers

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#1282]
Add showing week numbers and event for week numbers clicks.

**Comment by olton** [comment]
### 4.2.31
+ [x] Calendar: add attribute `data-show-week-number="true|false"` 
+ [x] Calendar: add attribute `data-week-number-click="true|false"` 
+ [x] Calendar: add event `data-on-week-number-click="..."` 

![calendar-week-numbers](https://user-images.githubusercontent.com/365108/49464544-cd6f1680-f803-11e8-93c6-ab127a916f46.gif)

**Comment by aeChriss** [comment]
Dear olton,

please, can you add showWeekNumber to the CalendarPickerDefault Options and Transfer the showWeekNumber calendarPicker Option to the calendar-object (around line 6542 in the merged Version), so the calenderpicker can have week numbers to?

thanks and have a nice day
   chriss
