### ISSUE TITLE
There are several features that a navigation class should do have

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1283]
I'm using metroui to build my own small website, but I haven't used it on my work project yet.
I've been looking at this framework for a long time
At present, the system of this framework has been more and more perfect
I think the author should make some major adjustments and more complete changes to the menu.
1.about Material Tabs、Side bar、Bottom navigation  and so forth，
These navigation contents should have a unified spatial level after they are separated from the document stream.
I think they should occupy the same space with each other, and they should have a fixed dynamic and immovable position. This should be very important on mobile devices ，at least I thought it did.
for example：
![image](https://user-images.githubusercontent.com/22745515/49606320-022ec980-f9ce-11e8-881f-16d4e3d81acb.png)
![image](https://user-images.githubusercontent.com/22745515/49606412-45893800-f9ce-11e8-98e2-14bc3988ecfc.png)
head nav
It can be said tha，It needs to be like this.
But bottom navigation，it also deviates from its original position.
Although we can fix it with JS，but it is still troublesome, compared with framework solution, it is not efficient and not convenient.
I think any kind of head navigation or bottom navigation，when the screen scrolls，they should have a property that keeps the location constant。Head should have optional options

2. About after leaving the document stream，side bar in the same space, 
Head navigation and tail navigation extrusion should squeeze the use space of sidebar
This should also be an option
![image](https://user-images.githubusercontent.com/22745515/49607535-2dff7e80-f9d1-11e8-8a20-c755a02f1d76.png)

maybe I think these things are wrong

3 .about navigation of tab components
I think data, or some small functions of a uniform nature
Should have strong storage bag characteristics and show characteristics
![image](https://user-images.githubusercontent.com/22745515/49609754-6b670a80-f9d7-11e8-8c65-3107235f98e4.png)
![image](https://user-images.githubusercontent.com/22745515/49609585-ec71d200-f9d6-11e8-9e3a-1ad23c0618c5.png)
![image](https://user-images.githubusercontent.com/22745515/49609619-fe537500-f9d6-11e8-94ae-f087af024f15.png)

Tabs have titles and options so that navigation can place things of the same kind together with archives.

**Comment by olton** [comment]
in 4.2.31
+ [x] Z-index: set equal z-index for `appbar`, `bottomnav`, `bottomsheet`, `tabsmaterial`

**Comment by olton** [comment]
Hi. Please use the forum (https://forum.metroui.org.ua) for discussing and proposal. Issues tracker use only as a bug tracker.
