### ISSUE TITLE
Half star fill for rating?

### ISSUE THREAD

**Issue by wesnell07** [olton/Metro-UI-CSS#1284]
Hi just a quick question and thank you for such an awesome framework! Does the rating component support half fill of stars? On e.g 3.5 or 4.5 etc?

**Comment by wesnell07** [comment]
Hi there :)
just asking, would this be too much of an unneccessary thing to add/enhance? should i look at another
alternative for half-star rating? like maybe the icons?

Thanks so much once again.

Have a great day

**Comment by olton** [comment]
Planned in Jan-Fab 2019

**Comment by wesnell07** [comment]
hi there

is there any feedback on this possible feature? :)

Thanks again :)

**Comment by olton** [comment]
https://sandbox.org.ua/olton/code/OVbpxnTJbR

**Comment by wesnell07** [comment]
this is purely amazing! Thank you for such an awesome framework

**Comment by olton** [comment]
Feature added in 4.2.40 for static rating
