### ISSUE TITLE
Lists use doubt and proposal

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1285]
When using Lists，the intuitive feeling is,the author wants to rely on ul and li tags,solve multiple data display in a small area，As well as Solve mobile terminal device page data display.
It should be a standardized solution for data display within the framework proposed by the author.

But because lists are the same as tables,
They all belong to the content closest to the user's display requirements and operational requirements.
The key requirement for tables is operation
The key requirement for lists is display
But the display data  same as the operation，there are too many problems to consider.
If the author is willing to continue to standardize the content of the framework structure,some enhancements to the list display data are expected.
such as Insert and delete and insert and delete animation effects or random Display of Lists
For example, the number of pictures displayed in the control list should not exceed three.
1 2 3 pictures should have different styles in real time to avoid the monotony of the page list.
And so on

Or cancel the list component.  because Its user behavior is too much.
There are too many things to consider for a complete solution

**Comment by chongzia** [comment]
Users'display needs can be categorized, but using a list, the writing is too complicated.
It's much simple to make plug-ins separately after categorization.

**Comment by olton** [comment]
Hi. Please use the forum (https://forum.metroui.org.ua) for discussing and proposal. Issues tracker use only as a bug tracker.
