### ISSUE TITLE
Suggestion for the "builder"

### ISSUE THREAD

**Issue by dagnelies** [olton/Metro-UI-CSS#1290]
Hi Olton,

First off, thanks for this great framework. Here comes one more suggestion 😉 

I think a great feature for the "Builder" part of the nice (nice work btw). Would be to add few options for the main less variables, like primary/secondary colors and base font type/size. This would already offer a nice customization possibility for themes.

**Comment by olton** [comment]
Please create issue for Builder https://github.com/olton/Metro4-Builder

**Comment by olton** [comment]
I think about it, thank you.
