### ISSUE TITLE
Version 4.3.x will be without jQuery!

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#1293]
Version 4.3.x will be without jQuery! At the moment I am doing a lightweight jQuery replacement. You can get acquainted with it at https://github.com/olton/m4q

**Comment by olton** [comment]
Dear friends! I need help in testing M4Q!

**Comment by olton** [comment]
If you want to have Metro 4 without jQuery dependency, please stars a project M4Q on GitHub.
https://github.com/olton/m4q

**Comment by olton** [comment]
![m4-index-appbar-no-jquery](https://user-images.githubusercontent.com/365108/50541411-208f7b80-0bae-11e9-8674-a951bae20852.gif)

**Comment by olton** [comment]
# Already fixed for M4Q

### Core
= [x] Metro.js

### Utils
- [x] Animation
- [ ] Colors
- [ ] Easing
- [ ] Export
- [ ] Extensions
- [ ] i18n
- [ ] md5
- [ ] Storage
- [ ] Tpl
- [x] Utilities

### Plugins
- [x] Accordion
- [x] Activity
- [x] App-bar (no dropdown)
- [x] Audio
- [x] Bottom sheets
- [x] Bottom group
- [x] Calendar
- [x] Calendarpicker
- [x] Carousel
- [x] Charms
- [x] Checkbox
- [x] Clock
- [x] Collapse
- [x] Countdown
- [x] Counter
- [x] Cube
- [x] Datepicker
- [x] Dialog
- [ ] Donut
- [ ] Draggable
- [ ] Dropdown
- [ ] File
- [ ] Gravatar
- [ ] Hints
- [x] HTML container
- [ ] Image comparer
- [ ] Image magnifier
- [ ] InfoBox
- [ ] Input
- [ ] Input Material
- [ ] Keypad
- [ ] List
- [ ] ListView
- [ ] Master
- [ ] NavView
- [ ] Notify
- [ ] Panel
- [ ] Popovers
- [x] Progress
- [ ] Radio
- [ ] Rating
- [ ] Resizable
- [ ] Ribbon Menu
- [ ] Ripple
- [ ] Select
- [ ] Sidebar
- [x] Slider
- [ ] Sorter
- [ ] Spinner
- [ ] Splitter
- [ ] Stepper
- [ ] Streamer
- [ ] Switch
- [ ] Table
- [ ] Tabs
- [ ] Tabs Material
- [ ] Tag input
- [ ] Textarea
- [ ] Tiles
- [ ] Timepicker
- [ ] Toast
- [ ] Touch
- [ ] TreeView
- [ ] Validator
- [ ] Video
- [ ] Window
- [ ] Wizard

### Unsupported
- [ ] Hot keys
- [ ] Mousewheel
- [ ] Scroll events

**Comment by arjarn** [comment]
I can't see metro-m4q branche today (last days, I'm trying it).
Is it always in your project to have metro without Jquery ?

**Comment by olton** [comment]
Branch moved to private repo

**Comment by arjarn** [comment]
OK happy to know it's alive.

**Comment by olton** [comment]
- Repo: https://github.com/olton/Metro4-M4Q
- Ready list: https://github.com/olton/Metro4-M4Q/blob/master/READY_FOR_M4Q.md

**Comment by olton** [comment]
I was asked me if will would be possible to use jQuery with Metro4 after switching over to using M4Q abstraction. Yes of course. The abstraction layer M4Q will be encapsulated inside Metro 4 and will not occupy the global $ variable!

**Comment by olton** [comment]
If you want to use jQuery to access the API in Metro 4 (4.3.x), you need to add a meta tag `<meta name="metro4:jquery" content="true">` in the page header and connect jquery. After that, you can access the API components and initialize them using jQuery:

#### Initialising
```
<div id="a1" data-one-frame="true">
...
</div>

$("#a1").accordion();
```

#### API
```
<div data-role="accordion" id="a1" data-one-frame="true">
...
</div>

var accordion = $("#a1").data("accordion");
```

**Comment by olton** [comment]
Hi, my friends!
I'm finished a Metro 4 without jQuery (v 4.3.0). Beta 1 now available from GitHub and Metro 4 CDN

**Comment by olton** [comment]
#### Javascript
```
https://cdn.metroui.org.ua/v4.3.0/js/metro.js
```
#### CSS
```
https://cdn.metroui.org.ua/v4.3.0/css/metro-all.css
```

**Comment by shajeeck** [comment]
How to get control events working with metro ui M4Q (4.3) without jQuery? 
By the way i am using angular2+ with M4Q, will it make a difference?

Thanx for this awesome library!

**Comment by olton** [comment]
@shajeeck Maybe I misunderstood the question, m4q contains methods for working with events https://github.com/olton/m4q#events
`$( ... ).on(event_name, callback);`
```
$("a").on("click", function(e){
     ... your code here ...
});
```
or
`$( ... ).on(event_name, delegates, callback)`
```
// for li > a
$("li").on("click", "a", function(e){
     ... your code here ...
});
```

**Comment by shajeeck** [comment]
thanx for your reply!

How can i subscribe to custom events of  components like onUp(list, select),  onItemDeselect(option) for 'select' component using m4q?

using data-on-item-deselect as attribute doesn't seem to work in angular2+

**Comment by olton** [comment]
@shajeeck You can create service function and set it a name for required attribute name. No need interact with m4q.
```
<select data-role="select" data-on-item-select="itemSelect">...</select>
```
```
function itemSelect(val, option, item){
    ...
}
```

**Comment by olton** [comment]
@shajeeck Direct subscribe to special events of components currently not present. But, maybe I'll add them soon. I think about it.

**Comment by shajeeck** [comment]
@olton  I tried this but it doesn't work in angular2+. The function doesn't seem to run, may be because how angular2+ works.

**Comment by olton** [comment]
@shajeeck to access to component API (without jquery) you must use the same method as with a jquery:
```
<select id="sel1" data-role="select" data-on-item-select="itemSelect">...</select>
```
```
var select = $("#sel1").data("select");
select.disable();
```

**Comment by shajeeck** [comment]
@olton methods does seem to work using 
`var select = $("#sel1").data("select");
select.disable();` in angular2+.
 Any work around to subscribe special events ??

**Comment by olton** [comment]
@shajeeck contact to https://github.com/morrisjdev/ng-metro4 author. Maybe Morris can help you.
