### ISSUE TITLE
Width of ribbon-toggle-group

### ISSUE THREAD

**Issue by Fredo70** [olton/Metro-UI-CSS#1296]
Version 4.2.33
File ribbon-menu.js
Line 75
```javascript
g.css("width", Math.ceil(gw * btns.length / 3) + 4);
```
The number of buttons has to be multiple of 3. Otherwise the width will not fit.
Should be change to:
```javascript
g.css("width", gw * Math.ceil(btns.length / 3) + 4);
```

**Comment by olton** [comment]
Thank you. Fixed in 4.2.35
