### ISSUE TITLE
Can have table support the response?

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1299]
Can you have table components support responses?

In the process of using the table, it is not friendly to support the response, which is very inconvenient to use, and the process of making the table itself is very cumbersome.must carefully consider which fields must be left behind and which fields should be cancelled.

On mobile devices, if table responses are not supported, there is too little content to present.

Hope the table has a friendly response style

**Comment by olton** [comment]
In the near future, I do not plan to add responsiveness for the table. Maybe in 4.3.1, after removing jQuery dependency.

**Comment by chongzia** [comment]
Hope you write M4Q, has rich functions, simple writing format, elegant implementation scheme。
Table response...... T_T
Most of my project development is on the mobile side, and very few on the PC side.
