### ISSUE TITLE
function pageHeight()   report an error

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1300]
index:137 Uncaught ReferenceError: pageHeight is not defined
    at index:137
(anonymous) @ index:137
index:130 Uncaught ReferenceError: pageHeight is not defined
    at window.onload (index:130)
window.onload @ index:130
load (async)
(anonymous) @ index:127

**Comment by chongzia** [comment]
https://sandbox.org.ua/dreamcc/code/4domo4zwNq

**Comment by olton** [comment]
use `Metro.utils.pageHeight()`

**Comment by olton** [comment]
All special utilities functions stored in Metro.utils object. https://metroui.org.ua/functions.html
