### ISSUE TITLE
Sidebar bug in Google Chrome

### ISSUE THREAD

**Issue by Chaoswriter96** [olton/Metro-UI-CSS#1301]
Hi Sergey!

I have since the two last builds a bug with the jQuery.
My tested object is the Sidebar with shifting content. When I try to open the sidebar it works as usual, but as soon I open it the "close" button disappears. 

Important:
I have tested the bug on Edge, Chrome and Firefox.
Only in Google Chrome I get that bug. 

I have tested it with your latest build.

![image](https://user-images.githubusercontent.com/22352687/50726041-ac059100-1107-11e9-82e9-d25d73c3b9d7.png)

**Comment by olton** [comment]
Update Metro4 to latest
