### ISSUE TITLE
Defect on tabs

### ISSUE THREAD

**Issue by avogax** [olton/Metro-UI-CSS#1303]
Hello,

there seems to be a defect on tabs. When the user clicks on a tab the following code gets executed:

```
20792   _open: function(tab){
20793       var that = this, element = this.element, o = this.options;
20794       var tabs = element.find("li");
20795       var expandTitle = element.siblings(".expand-title");
20796
20797
20798       if (tabs.length === 0) {
20799           return;
20800       }
20801
20802       this._collectTargets();
20803
```

Inside the method **_open** the variable **this._targets** contains all the targets of the tabs and inside the call to **this._collectTargets();** it gets duplicated: its size doubles every time a tab is clicked.

I think that you call collectTargets every time a tab is clicked to eventually take care of tabs dinamically added so maybe you should empty **this._targets** before calling collectTargets .

**Comment by olton** [comment]
Thanks, fixed
