### ISSUE TITLE
CDN appears to be down

### ISSUE THREAD

**Issue by dagnelies** [olton/Metro-UI-CSS#1304]
Hi @olton,

The CDN links appear to be down.

    GET https://cdn.metroui.org.ua/v4/css/metro-all.min.css => net::ERR_CONNECTION_TIMED_OUT

    GET https://cdn.metroui.org.ua/v4/js/metro.min.js => net::ERR_CONNECTION_TIMED_OUT

**Comment by olton** [comment]
All works for me

**Comment by dagnelies** [comment]
It's working again. Perhaps it was some temporary failure.
