### ISSUE TITLE
Spinner on touch device

### ISSUE THREAD

**Issue by aboodh95** [olton/Metro-UI-CSS#1307]
Hi,

the Spinner control on a touch device is acting fastly and the number will jump tow steps in one click, is there a way to avoid that

**Comment by aboodh95** [comment]
Hi,

This is an example of the issue [https://drive.google.com/open?id=1JNP5JKfydCEmhd32eWRkAMTRvsn7LtMz](url)

**Comment by olton** [comment]
Thanks, I fix it on this weekend. Currently I am in a hospital.

**Comment by aboodh95** [comment]
I'm sorry for that, and i hope for your speedy recovery
