### ISSUE TITLE
CalendarPicker selection not updating complete selection when using .val()

### ISSUE THREAD

**Issue by morrisjdev** [olton/Metro-UI-CSS#1308]
When calling .val('02/03/2019) on a calendarpicker that already was used to select another date does not update all selection.

Steps to reproduce:
1. Create a CalendarPicker
2. Select a date
3. Call .val('new date') with a  different date in the same month on the picker
4. Click on the picker

![unbenannt](https://user-images.githubusercontent.com/20016673/52072524-6bbdf500-2585-11e9-8a5e-b0464ddbf7b4.PNG)

**Comment by olton** [comment]
Thanks, I fix it after leave a hospital 3-5 days.
