### ISSUE TITLE
autocomplete on input does does not trigger change

### ISSUE THREAD

**Issue by morrisjdev** [olton/Metro-UI-CSS#1310]
When using other components that are listening for onchange on the input nothing gets triggered when an item is selected in the autocomplete results.

Can you please add the line:
`element.trigger('change');`
in input.js in line 323.

![code](https://user-images.githubusercontent.com/20016673/52110754-e62c5a80-2601-11e9-9a57-5b6914c20f9e.PNG)

Sorry that I have not the time to fix it myself and make a pull request.

**Comment by olton** [comment]
Thanks, I fix it after leave a hospital on 3-5 days
