### ISSUE TITLE
Stop working close/minimize/maximize buttons in window control in Opera

### ISSUE THREAD

**Issue by nike80** [olton/Metro-UI-CSS#1312]
After 4.2.35 update

1. Stop working close/minimize/maximize buttons in window control.

at Opera browser 56.0.3051.99
and last Opera browser 58.0.3135.53
tested.

Go desktop sample and try it.

2. In onDragStop(pos, el) windows callback
el === undefined

in all browsers

**Comment by olton** [comment]
Thanks. Problem found in `draggable` component.

**Comment by nike80** [comment]
OK. the metro great!

I tryed connect you by Skype some days ago.
Please, go online.

**Comment by olton** [comment]
I will fix it soon. For now, you can specify data-drag-element = ".window-caption .icon, .window-caption .title"

**Comment by olton** [comment]
and add next style to improve:
```
.window-caption .icon {
    width: 36px;
    height: 36px;
    text-align: center;
    flex-shrink: 0;
}

.window-caption .icon * {
    line-height: 36px;
    max-height: initial;
}

.window-caption .title {
    width: 100%;
}
```
