### ISSUE TITLE
checkbox in listview: when selecting root trigger change on descendants

### ISSUE THREAD

**Issue by morrisjdev** [olton/Metro-UI-CSS#1313]
Can you add another element.trigger('change'); in listview.js in lines 344 and 348.

![unbenannt](https://user-images.githubusercontent.com/20016673/52338434-b10d7700-2a0a-11e9-90cb-02fac86af916.PNG)

I need all of those triggers to react on changes in Angular. 

PS: The implementation of Metro 4 for Angular is going forward.

**Comment by olton** [comment]
Added in 4.2.36
