### ISSUE TITLE
data-role="table" not listing all items

### ISSUE THREAD

**Issue by david00raiser** [olton/Metro-UI-CSS#1314]
Hi, i'm trying to list a total > 1000 items in a table, but it only displays a maximum of 681, i don't know why but if i remove the attribute (data-role) it displays all items, but with a non working table obviously.

What can it be?

![image](https://user-images.githubusercontent.com/47394705/52358662-6a1d8280-2a06-11e9-9d1d-5329c416b479.png)

**Comment by olton** [comment]
In this example, a table works with 100 000 records https://metroui.org.ua/examples/table/table-100K.html.
Check your data file for the table.
