### ISSUE TITLE
Buttons (clo, min, max) don't work on Windows (on tag v4.2.35)

### ISSUE THREAD

**Issue by araguacaima** [olton/Metro-UI-CSS#1315]
Hi folks...

It seems the last tag released has a little issue with windows buttons. 

I have used successfully the library with tag v4.2.34 before, but after migrated to the last one (master = tag v4.2.35), buttons don't work.

Here, some evidences..

**tag v4.2.34**

![000035](https://user-images.githubusercontent.com/979801/52429397-93531700-2ac9-11e9-9f2c-3667a8701a20.png)
![000037](https://user-images.githubusercontent.com/979801/52429399-951cda80-2ac9-11e9-820d-7d4f63c58ef0.png)
![000038](https://user-images.githubusercontent.com/979801/52429403-977f3480-2ac9-11e9-812a-36552b91be36.png)
![000039](https://user-images.githubusercontent.com/979801/52429405-9948f800-2ac9-11e9-8cc6-b4a5b4853489.png)

**tag v4.2.35**
![000040](https://user-images.githubusercontent.com/979801/52429413-9e0dac00-2ac9-11e9-966c-7f6a41754901.png)

Best regards team!

**Comment by olton** [comment]
This fixed in 4.2.36

**Comment by olton** [comment]
demo for 4.2.36 https://metroui.org.ua/feature-demo/desktop/

**Comment by araguacaima** [comment]
Excellent Sergey (@olton). Obviously you have all of this under control. In the meanwhile I had to point to version 4.2.34, because version that was in CDN still had the problem. I'll wait patiently you merge those changes in master branch, and such update is present in the CDN too in order to switch back my code to:

`<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro.min.css">`
`<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>`

I really appretiate your help!
