### ISSUE TITLE
Change selected option in runtime

### ISSUE THREAD

**Issue by XharkTR** [olton/Metro-UI-CSS#1317]
```html
<select id="selectComponente"
            data-role="select"
            data-cls-option="bg-lightAmber-hover">
```

I not able to change the value of that select in runtime.
My best try:

```js
function rowOnClick(row){
  cells = row.getElementsByTagName("td")
  var select = $("#selectComponente");
  select.val(cells[2].innerHTML)
}
```
That works, if i remove the `data-role="select"`, but of course i dont want to do that

**Comment by olton** [comment]
```
var select = $("#selectComponente").data("select");
select.val(new_value);
```
https://sandbox.org.ua/olton/code/PMzmXeewlW

**Comment by XharkTR** [comment]
With `var select = $("#selectComponente").data("select");` im getting a `TypeError: select is undefined` but with `var select = $("#selectComponente")`, I don't. Still not working either way.

**Comment by olton** [comment]
You must include Metro 4 into your page

**Comment by XharkTR** [comment]
I did. The problem was the order with jquery. Thans for the help :)

**Comment by 3asit** [comment]
if multiselect attribute is added to the select; i get again `select is undefined` 
So i am unable to set the selected items.

**Comment by Manyletoulousain** [comment]
ok I fount out

this is ok
   <script src="/js/jquery-3.5.0.js"></script>
   <script src="/Metro-UI-CSS-master/build_v4.3.6/js/metro.js"></script>

this does not work
   <script src="/Metro-UI-CSS-master/build_v4.3.6/js/metro.js"></script>
   <script src="/js/jquery-3.5.0.js"></script>

**Comment by olton** [comment]
create your problem code example on codepen.io please

**Comment by Manyletoulousain** [comment]
if you load jquery.js after loading metro.js, this: var select = $("#selectComponente").data("select") does not work.

if you load jquery.js before loading metro.js, it is working very well

**Comment by olton** [comment]
use `Metro.getPlugin(selector, pluginName)`, and load jQuery **BEFORE** Metro.
```
var select = Metro.getPlugin("#selectComponente", "select");
```
