### ISSUE TITLE
onDragMove/o.onDragStop callback call error

### ISSUE THREAD

**Issue by nike80** [olton/Metro-UI-CSS#1320]
Not all params passed in user's callbacks onDragMove/onDragStop.

10123 codeline
Utils.exec(o.onDragMove, [position], elem);

10141 codeline
Utils.exec(o.onDragStop, [position], elem);

But must be as in previous version:

Utils.exec(o.onDragMove, [position, elem]);
Utils.exec(o.onDragStop, [position, elem]);

So, in user's callbacks

onDragStop(pos, el)
{
el === undefined
// AND EXCEPTIONS HERE
}

**Comment by olton** [comment]
Use `this` to access to element

**Comment by nike80** [comment]
OK, but how about backward compatibility?

**Comment by olton** [comment]
bad code will not be saved even to the detriment of backward compatibility.
