### ISSUE TITLE
Window not dragable if the title in window is empty string (v4.2.36.717)

### ISSUE THREAD

**Issue by nike80** [olton/Metro-UI-CSS#1321]
1. Open Desktop sample
2. Go to Elements in browser debug tools and select any window
3. Delete a text from window's title and try move (drag) window

If return a text in the title - the window will be movable again.

**Comment by olton** [comment]
For windows draggable element set to icon, title

**Comment by olton** [comment]
This is done because of the problems of dragging and the operation of the system buttons: issues #1312 , #1315

**Comment by olton** [comment]
If you need an empty title, set for title `&nbsp;` - non-breakable space or you can change this behavior with attribute `data-dreaggable-element`
