### ISSUE TITLE
update drag icon desktop , min window taskbar

### ISSUE THREAD

**Issue by khanhnam99** [olton/Metro-UI-CSS#1322]
update drag icon desktop, min window taskbar when click min window

**Comment by olton** [comment]
Your question is not clear

**Comment by khanhnam99** [comment]
![capture](https://user-images.githubusercontent.com/575720/52701038-dcb0d400-2fab-11e9-9448-9a13e4436f15.PNG)
how show icon on desktop?

**Comment by khanhnam99** [comment]
when click minium window ,hidden on desktop, toggle on taskbar is show
![capture](https://user-images.githubusercontent.com/575720/52701238-5779ef00-2fac-11e9-9c67-4caadf6ce8a9.PNG)
