### ISSUE TITLE
how show icon on desktop

### ISSUE THREAD

**Issue by khanhnam99** [olton/Metro-UI-CSS#1323]
how show icon on desktop?
![52701038-dcb0d400-2fab-11e9-9448-9a13e4436f15](https://user-images.githubusercontent.com/575720/52701409-c5261b00-2fac-11e9-8063-919ec891fadd.PNG)

when click minium window ,hidden on desktop, toggle on taskbar is show
![capture](https://user-images.githubusercontent.com/575720/52701350-a0ca3e80-2fac-11e9-9f01-22948940125f.PNG)

**Comment by khanhnam99** [comment]
like

https://desktop.sonspring.com/

**Comment by olton** [comment]
That you have to come up with yourself. This is just a demonstration of windows.
