### ISSUE TITLE
Metro 4 in Action!

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#1324]
To show the possibilities of `Metro 4`, I open the section `"Metro 4 in Action!"`. Leave in this thread links to pages of sites that you would like to see cloned using `Metro 4`.

**Comment by olton** [comment]
## For example:

#### Image
![2019-02-03 2](https://user-images.githubusercontent.com/365108/52881218-b2f2db00-316c-11e9-813e-aca4acf11c6f.png)

#### Original 
`https://mirohost.net`

#### Clone
`https://metroui.org.ua/examples/clones/mirohost.net/`

**Comment by JohnArcher** [comment]
That is truely a cool idea! You rock, mate! I hope you can get more attraction with this. I will think about what site would be nice to clone ... What about a metro styled GitHub clone?

**Comment by olton** [comment]
@JohnArcher https://metroui.org.ua/examples/github/github.html

**Comment by olton** [comment]
## GitHub

#### Image
![2019-02-16](https://user-images.githubusercontent.com/365108/52896582-dea8ac00-31d2-11e9-8f85-b31bb55db0f3.png)

#### Original
[https://github.com/olton/Metro-UI-CSS](https://github.com/olton/Metro-UI-CSS)

#### Clone
[https://metroui.org.ua/examples/clones/github.com/](https://metroui.org.ua/examples/clones/github.com/)

**Comment by Ossadex** [comment]
https://adminlte.io/themes/AdminLTE/index2.html

**Comment by olton** [comment]
## Admin LTE
![admin-lte-clone](https://user-images.githubusercontent.com/365108/53697448-ddce6780-3dd9-11e9-90bb-d4b9134b1657.jpg)
#### Original
https://adminlte.io/themes/AdminLTE/index2.html
#### Clone
https://metroui.org.ua/examples/clones/admin-lte/

**Comment by olton** [comment]
## AiSTANT
![2019-03-12 (1)](https://user-images.githubusercontent.com/365108/54194043-02a29900-44c4-11e9-8539-655e6bbc354f.png)

#### Original 
https://aistant.com/

#### Clone
https://metroui.org.ua/examples/clones/ainstant.com/
