### ISSUE TITLE
app-bar hide buttons dynamic

### ISSUE THREAD

**Issue by JeroenvO** [olton/Metro-UI-CSS#1327]
In metro-v3 the buttons in an app-bar moved inside a hamburger-menu one-by-one when the screen gets smaller, in metro-v4 all buttons disappear at once on a fixed screen width using media-queries.
The new way is less responsible and lets items overflow outside the screen when the media-query width is set too small.
Would it be possible to move buttons from the appbar to a hamburger menu dynamical on resize?

**Comment by olton** [comment]
At this stage, I do not plan to change the behavior of the app-bar in Metro 4. Maybe in later releases.
