### ISSUE TITLE
feature request:  Vertical icons view (column wise) in ListView

### ISSUE THREAD

**Issue by shajeeck** [olton/Metro-UI-CSS#1330]
In ListView with 'icons' view, icons are filled horizontally first (row wise) before coming to next line. An extra view option for vertically arranging icons (column wise) will be great as in usual windows desktop icon arrangement. 

![](https://www.tech-recipes.com/wp-content/uploads/desk11.png)

**Comment by olton** [comment]
### 4.2.38
+ [x] ListView: add class `.vertical-layout` for `icons-*` view mode

**Comment by shajeeck** [comment]
@olton great! How often will u update the css in metro m4q? or can we use the css from this project same with metro m4q alpha version?

**Comment by olton** [comment]
@shajeeck `Metro 4 - M4Q` Updated, In next time, please, create issues for `Metro 4 - M4Q` in this https://github.com/olton/Metro4-M4Q repo
