### ISSUE TITLE
TreeView: Clicking on node does not collapse child nodes on first click

### ISSUE THREAD

**Issue by mahichr** [olton/Metro-UI-CSS#1332]
Hi,
In the TreeView component when I click on an opened node for the first time, the icon changes to collapse icon arrow but the child nodes do not collapse. When I click on the parent node second time it works as expected but the collapse arrow icon is not in sync.

https://metroui.org.ua/treeview.html

![image](https://user-images.githubusercontent.com/8164517/53596214-3816c080-3b6d-11e9-9e04-fc8b4d9cbf24.png)

**Comment by olton** [comment]
Thanks, fixed in 4.2.38

**Comment by mahichr** [comment]
@olton  Looks like this issue have resurfaced again. Can you please check.

**Comment by olton** [comment]
@mahichr where you find an error?

**Comment by olton** [comment]
Node open/close when user double click on node name or click on toggle
