### ISSUE TITLE
Why is this happend??? With electron...

### ISSUE THREAD

**Issue by Tonysmark** [olton/Metro-UI-CSS#1334]
I'm using the latest electron and metro4 package
![image](https://user-images.githubusercontent.com/22767695/53863135-59235980-4024-11e9-919c-633571588b8d.png)
and I hope to see this in my window and I'm pretty sure I can use it in my browser,
![image](https://user-images.githubusercontent.com/22767695/53863844-1c586200-4026-11e9-95e4-307aaa13e10b.png)
![image](https://user-images.githubusercontent.com/22767695/53863926-4742b600-4026-11e9-9f47-ada9ca693483.png)

but when I using electron.....well things are getting bad.
![image](https://user-images.githubusercontent.com/22767695/53864013-73f6cd80-4026-11e9-9a29-c00f8bee24a6.png)

I'm confused....How cloud this happend???

**Comment by olton** [comment]
Metro 4 required jQuery

**Comment by Tonysmark** [comment]
I've linked jquery already,right after metro.js

**Comment by Tonysmark** [comment]
![default](https://user-images.githubusercontent.com/22767695/53864839-7a864480-4028-11e9-9c67-41aea6c4f1b8.png)
where are U looking at????

**Comment by olton** [comment]
jQuery must be include *before* metro

**Comment by Tonysmark** [comment]
![image](https://user-images.githubusercontent.com/22767695/53866564-cd61fb00-402c-11e9-91bc-9bd954b7f8d1.png)
That is exactly what I'm I doing after I using electron.

**Comment by olton** [comment]
On your third screen I see "jQuery is not defined"

**Comment by olton** [comment]
add jquery to `dependencies`, before `metro`

**Comment by Tonysmark** [comment]
I did it again, and fine on chrome
![image](https://user-images.githubusercontent.com/22767695/53871099-82e57c00-4036-11e9-83fc-7d1249ab14c6.png)
but not so lucky on electron
![image](https://user-images.githubusercontent.com/22767695/53871170-a7415880-4036-11e9-96eb-9b3baae782ef.png)
there must be some problem otherwise i't couldn't run on chrome so good.

**Comment by olton** [comment]
https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined

**Comment by olton** [comment]
https://ourcodeworld.com/articles/read/202/how-to-include-and-use-jquery-in-electron-framework

**Comment by Tonysmark** [comment]
I'm suck a rookie, so embarrassing....... Problem no more thanks a lot !!!!
