### ISSUE TITLE
Maybe silly question about class="table"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1335]
https://codepen.io/TorakikiSan/pen/jJymZV

I'm a little confused about how to change the appearance of a table with the various data-cls- * attributes

I would like, for example, the header with the background bg-olives and the text fg-white, so I defined data-cls-head = "border-none bg-olives fg-white" but fg-white does not seem to work.

And with the same colors (bg-olive text-bold fg-white) I would also like the various fields for searching (Search) for pagination, etc. invo that the gray color as the background and the black for the characters, but I could not find the command data-cls- * suitable.

Finally, what is the difference between data-cls-head, data-cls-head-cell and data-cls-head-row? In which section of the table do they apply? TABLE, THEAD or TH?

Where could I find many examples of tables created with MetroUI?

Thank you!

**Comment by olton** [comment]
Thanks, was an error in service function, fixed in 4.2.39

**Comment by TorakikiSan** [comment]
Now data-cls-head-cell works fine. Thank's Olton!

But is it possible to change class (foreground and background) to the various fields Search, Rows, Pagination etc.? data-cls-search = "bg-olive text-bold fg-white" does not seem to work. See this example:

![untitled - 1](https://user-images.githubusercontent.com/37299746/53902137-d361d700-4040-11e9-8833-453078cf3f7d.jpg)

Thank's for all! ;-)

**Comment by olton** [comment]
Search is a complex element attribute `data-cls-search` implements to main search container. To change inner element you must create your own special class. Example:
```
.my-search-class .input .prepend{
  background: olive;
  color: #fff;
}
```
https://sandbox.org.ua/olton/code/oaQm50YZDd

**Comment by TorakikiSan** [comment]
Thank's Olton!

Why with Codepen doesn't work?

https://codepen.io/TorakikiSan/pen/jJymZV

**Comment by olton** [comment]
I don't know why codepen not working properly

**Comment by olton** [comment]
Custom class for search doesn't work properly for custom search wrapper.

**Comment by olton** [comment]
fixed in 4.2.39

**Comment by TorakikiSan** [comment]
Great!

**Comment by TorakikiSan** [comment]
Perfect! It works perfectly

**Comment by Ji-Cey** [comment]
Hi, it is possible to change prepend text on data-cls-search option on table component ?
