### ISSUE TITLE
headers (h1,h2,h3...) should have a top margin by default

### ISSUE THREAD

**Issue by dagnelies** [olton/Metro-UI-CSS#1342]
By default, when you place several headers and paragraphs in a "normal" page like this...

```
<h1>Section</h1>
<p>bla bla bla</p>

<h1>Section</h1>
<p>bla bla bla</p>

<h1>Section</h1>
<p>bla bla bla</p>
```
Take a look here: https://codepen.io/anon/pen/GebKdY

This looks quite odd because all headers "stick" to the top paragraphs/div/whatever. By default, they have only a bottom margin and no top margin. IMHO it would be more convenient/nicer if it was the opposite, with headers having a top margin by default.

**Comment by olton** [comment]
Thanks, It makes sense. I will change it in 4.2.40

**Comment by olton** [comment]
For display*
```
margin: 20px 0;
```
For headers
```
.leader, .h1, h1,
.sub-leader, .h2, h2,
.header, .h3, h3,
.sub-header, .h4, h4,
.alt-header, .h5, h5,
.sub-alt-header, .h6, h6 {
    ...
    margin: 1rem 0;
    ...
}
```
