### ISSUE TITLE
data-on-select="..." not triggering in file drops

### ISSUE THREAD

**Issue by dagnelies** [olton/Metro-UI-CSS#1344]
Using this component:

https://metroui.org.ua/file.html#_file_drop

the data-on-select="..." is not triggering properly

- Chrome: nothing happens
- Edge: produces following error "Assignment to read-only properties is not allowed in strict mode"
- Firefox: works! Yay!

**Comment by olton** [comment]
Fixed in 4.2.40 for Chromium browsers. For EDGE fix impossible, I will not deduce library from the strict mode for Edge.

**Comment by dagnelies** [comment]
I can confirm it works on chrome with `<script src="https://cdn.metroui.org.ua/v4-dev/js/metro.min.js"></script>` ...bad luck for edge :( ...I can understand.
