### ISSUE TITLE
Table Overflow

### ISSUE THREAD

**Issue by X-lem** [olton/Metro-UI-CSS#1345]
I've noticed that I am unable to control the overflow or width of a table. It seems the Metro 4 CSS is overwriting my inline styles. Is there a solution to this or is this a bug?

![image](https://user-images.githubusercontent.com/6555273/55500834-f8c11100-55fd-11e9-9987-99b0b6be62b1.png)

**Comment by olton** [comment]
use attribute `data-horizontal-scroll="true"`
