### ISSUE TITLE
Some questions about data-role="navview"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1347]
Look at 

https://codepen.io/TorakikiSan/pen/jJymZV

It's possibile:

1. Set to fg-white the default-icon-menu?

2. Set the height of the NavView equal to the avilable screen height?

3. Set the NavView over (z-index?) the rest of screen (where there is the table) or the table must be include in the navview-content?

Thank's!

**Comment by olton** [comment]
1) default-icon-menu is an image,  converted to base64. You can use any font icon to replace it. Example:
`<span class='mif-menu fg-white'></span>`
2) To set full height use classes `h-vh-100`, `h-100` to `navview` and parents
3) Maybe need put table into navview-content block?

**Comment by TorakikiSan** [comment]
Perfect!

Thank's!
