### ISSUE TITLE
file browser width Display problem under inline-form

### ISSUE THREAD

**Issue by lx1054331851** [olton/Metro-UI-CSS#1352]
Use the following code:
```html
<form action="" class="inline-form">
        <input style="min-width: 400px" type="file" data-role="file" data-button-title="<span class='mif-folder'></span>">
        <button class="button success">上传</button>
</form>
```
The file browser display not right, as below:
![image](https://user-images.githubusercontent.com/12423206/55723148-d33b6980-5a3a-11e9-9e72-6646828f2869.png)
The file browser component is so small!
It's css showed as below:
![image](https://user-images.githubusercontent.com/12423206/55723257-2c0b0200-5a3b-11e9-95c6-29ff500e62b2.png)

**Comment by olton** [comment]
create a class with `min-width` property and add it to component with attribute `data-cls-component`
