### ISSUE TITLE
d-none-[sm,md,xl,xxl] do not work correct?

### ISSUE THREAD

**Issue by phucvinh52** [olton/Metro-UI-CSS#1353]
Hi team,
First I thank team for your metroui is beauty css framework.
I'm beginer with metroui.

My problem is d-none-[sm,md,xl,xxl] do not work.

i have a example be like:
```
<span class="d-none-sm">
    <ul class="h-menu bg-cyan fg-white">
        <li><a href="#"><span class="icon mif-home"></span> Home</a></li>
        <li>
            <a href="#" class="dropdown-toggle">Tools Support</a>
            <ul class="d-menu" data-role="dropdown">
                <li><a href="#">Tool A</a></li>
                <li><a href="#">Tool B</a></li>
                <li class="divider"></li>
                <li><a href="#">Offset</a></li>
            </ul>
        </li>
        <li><a href="#">Tutorials</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
</span>
```

and when i run it. with screen sm my menu show and other screen my menu is hidden.
Please help me.
Thanks all.

**Comment by olton** [comment]
`d-none-*` works with rule `from`. In your example menu shown with screen size from 0 to sm (576px) and not for larges. Maybe you need rule `<span class="d-none d-block-sm">`?

**Comment by phucvinh52** [comment]
thank you very much @olton
