### ISSUE TITLE
Chat component

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1355]
Hi,

attempting to see documentation for Chat component :

`TypeError: aDays[nDay] is undefined at metro.js:2118:13`

**Comment by olton** [comment]
I don't see an error

![2019-04-16](https://user-images.githubusercontent.com/365108/56190246-76d7db80-6032-11e9-8030-406a26fe141f.png)

**Comment by olton** [comment]
Ok, thanks, I found bug

**Comment by olton** [comment]
fixed
