### ISSUE TITLE
Feature Enhancement Request:  Hotkeys: Support HTML5 Gamepad

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1356]
Hi Olton!  Hope you are doing better! 

I was doing some work with the awesome Hotkeys component https://metroui.org.ua/hotkeys.html and in my use case found a cool idea that would be awesome to add:  How about support Gamepad events too? https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

Something like:  

```
<button class="button"
        data-hotkey="gamepad2"
        onclick="alert('Gamepad 2 clicked!')">Press Gamepad Button 2</button>
```

(If you need gamepad hardware for testing let me know)

**Comment by olton** [comment]
ie11 does not support gamepad :(

**Comment by openbuilds-engineer** [comment]
ahh man!  Forgot about ol' IE for ruining everything (;

My app runs in Electron (Chromium) so no need to worry about IE but i understand for the bigger project to accept it it needs to work with IE too, so I am happy to close the issue.  Someday!
