### ISSUE TITLE
Amazing Lib, but for jQuery

### ISSUE THREAD

**Issue by David-Carty** [olton/Metro-UI-CSS#1362]
Is there any future plan to drop jQuery, in favour of vanilla JS?  Love the style and attention to details.

**Comment by olton** [comment]
https://github.com/olton/Metro4-M4Q

**Comment by olton** [comment]
See branch 4.3.0. Now in develop, and without jquery!

**Comment by michaelongithub** [comment]
Great ! 
Plans to move to Typescript ?

**Comment by olton** [comment]
@michaelongithub Not now. Currently, I began Metro 4 for React.
