### ISSUE TITLE
Another data-role="navview" doubt

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1363]
In the **&lt;DIV class = "navview-content"&gt;** section is there the possibility of having the vertical scrollbar working for this DIV?

I tried &lt;DIV style = "overflow-y: scroll; max-height: 2000px;"&gt; and with &lt;DIV style = "overflow-y: auto; max-height: 2000px;"&gt; but neither of them works.

Thank you!

**Comment by olton** [comment]
Set height to 100% and overflow: auto for navview-content, and put your scrollable content into navview-content block

**Comment by TorakikiSan** [comment]
Perfect!
