### ISSUE TITLE
Treeview data-on-collapse-node broken after 4.2.40

### ISSUE THREAD

**Issue by smx-smx** [olton/Metro-UI-CSS#1364]
Since 4.2.41, data-on-collapse-node is invoked with incorrect parameters

- the first argument (clicked node) isn't a jQuery object anymore
- the second argument (the treeview) is undefined

Downgrading to 4.2.40 brings back the correct behaviour

**Comment by olton** [comment]
First argument - node as HTMLelement, function context is a treeview this == treeview

**Comment by smx-smx** [comment]
this == Window for me

html:
```html
<ul id="treeview" data-role="treeview" data-on-collapse-node="onNodeExpanded" data-on-node-click="onNodeClicked">
</ul>
```

```js
function onNodeExpanded(node){
    //node == HTMLelement
    //this == Window object
}
```

But in 4.2.40 i could do this
```js
function onNodeExpanded(node, tree){
   //node == jQuery.fn.init [li.expanded, prevObject: jQuery.fn.init(1)]
   //tree == jQuery.fn.init [ul#treeview.treeview]
   //this == Window object 
}
```

**Comment by olton** [comment]
I change it for the features

**Comment by olton** [comment]
I specially changed it for future extensions. Example: remove jQuery dependencies

**Comment by olton** [comment]
```
<ul data-role="treeview" data-on-expand-node="nodeExpand">
    <li data-icon="<span class='mif-star-full'></span>" data-caption="Favorites">
        <ul>
            <li data-icon="<span class='mif-library'></span>" data-caption="Projects"></li>
        </ul>
    </li>
   ...
</ul>
```

```
function nodeExpand(node){
  console.log(node); // li
  console.log(this); // ul
}
```

**Comment by olton** [comment]
True, your comment helped to reveal another problem: expand and collapse calls are confused. Thank you!

**Comment by smx-smx** [comment]
No problem 🙂 
Thank you for this great library and your prompt reply
