### ISSUE TITLE
How to use data-actions	in Dialog

### ISSUE THREAD

**Issue by smx-smx** [olton/Metro-UI-CSS#1365]
According to the documentation, `data-actions` can be set to an object that describes the dialog actions.

Documentation says the default is `{}`, but i think it's actually `[]` as we're supposed to pass an array of actions.

I tried setting it in the html (data-action attribute) and doing it in code via ```dialog.data('actions', ...)```

The problem is that the code seems to interpret the attribute as a string (missing JSON.parse?) and is as such unusable.

The workaround is to pass them in `Metro.dialog.create`, which means actions can only be tied to dynamically created dialogs

Am i missing something?

**Comment by olton** [comment]
https://metroui.org.ua/dialog.html#_dialog_actions
Actions must be defined before and contain an array of actions described as an object.

**Comment by smx-smx** [comment]
Which means it can only be used via `Metro.dialog.create` and not via `data-actions`?

If you create a global variable , say `myActions`, and then write `data-actions="myActions"`, that will not work and you will see `Cannot use 'in' operator to search for 'length' in myActions`

In other words, it's not clear how to use the `data-action` attribute. I tried setting it to an inline array, an inline object and a variable name. None worked.

**Comment by olton** [comment]
HTML attribute data-actions currently not supported, you can use the predefined method for creating dialog if you don't use Metro.dialog.create
https://metroui.org.ua/dialog.html#_dialog_create_predefined

**Comment by olton** [comment]
In 4.2.43
[x] Dialog: add attribute `data-actions` for predefined dialog
```
    <div class="button" onclick="Metro.dialog.open('#dialog1')">Open dialog</div>

    <script>
        var dialogActions = [
            {
                caption: "Agree",
                cls: "js-dialog-close alert",
                onclick: function(){
                    alert("You clicked Agree action");
                }
            },
            {
                caption: "Disagree",
                cls: "js-dialog-close",
                onclick: function(){
                    alert("You clicked Disagree action");
                }
            }
        ];
    </script>
    <div data-role="dialog" data-actions="dialogActions" id="dialog1">
        <div class="dialog-title">Use Windows location service?</div>
        <div class="dialog-content">
            Bassus abactors ducunt ad triticum.
            A fraternal form of manifestation is the bliss.
        </div>
    </div>
```

**Comment by olton** [comment]
You can test in with https://github.com/olton/Metro-UI-CSS/tree/4.2.43
