### ISSUE TITLE
Method in component not working

### ISSUE THREAD

**Issue by g3rrydanc3** [olton/Metro-UI-CSS#1368]
I have the exact same problem with this [example](https://codepen.io/olton/pen/NRozKL) (found it on google)
Press the button and nothing happen.

> "Metro 4 - v4.2.43. Built at: 19/05/2019 22:19:38"
> $(".slider").data('slider')
> undefined

**Comment by olton** [comment]
https://codepen.io/olton/pen/arVZqb

**Comment by olton** [comment]
All classes moved to the slider container (input parent element). So when you call `$('.slider').data('slide')` you get `undefined`
