### ISSUE TITLE
Select: Truncates longer Options

### ISSUE THREAD

**Issue by openbuilds-engineer** [olton/Metro-UI-CSS#1369]
![Screenshot 2019-05-21 at 06 19 20](https://user-images.githubusercontent.com/31449271/58099707-0cfea480-7b91-11e9-8237-398920989ceb.png)

I 100% admit I may just be stupid, but is there a way to have the dropdown on select as wide to fit the longest option name so it doesn't get truncated? (:

**Comment by olton** [comment]
At this time select has not attribute for automatic  set width

**Comment by openbuilds-engineer** [comment]
Ahh OK so at least its not just me being stupid (:   Is it possible to ask for that in future?

**Comment by olton** [comment]
You can use templates for options and add title attribute to template https://metroui.org.ua/select.html#_select_template

**Comment by olton** [comment]
> Ahh OK so at least its not just me being stupid (: Is it possible to ask for that in future?

I'll think about whether it can be done without much effort.

**Comment by openbuilds-engineer** [comment]
(: no rush, templates will work for now
