### ISSUE TITLE
Amazing v4.3 !

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1370]
I'm coming back to Metro UI v4.2 with jquery for my project cause this version having lot of goodies even if tests I made with m4q are very exciting for me :) 

I'm curious so I'm testing v4.3, remove Jquery and ... 
Almost 90% of my project working !
I'm using Jquery code but well supported : only $(...).load and other littles things to rewrite.
I'm using too TweenMax (for animations) and Vegas (for sliders) and all is perfect !
It's a quick test but very promising and exciting : I'm using this version and waiting final 4.3

Thanx for this great work !

**Comment by olton** [comment]
`$(...).load(url, data, options)` added to `m4q`

**Comment by arjarn** [comment]
Thanx even rewriting this with post is very easy ;)
It seem $("> .myclass") syntax for selector is not supported with m4q.
Could you add this in future ?

**Comment by olton** [comment]
m4q use `querySelectorAll` for selecting elements. So, CSS extension such as in jquery not supported. Maybe you can use `$("* > .myclass")` ?

**Comment by arjarn** [comment]
Well done !
It's working with $("* > .myclass")

**Comment by olton** [comment]
Documentation for the m4q is done and added to main Metro 4 docs. You can get branch 4.3.0 and expand locally the documentation from the docs folder. On the official site, docs for the m4q will be added after 4.3.0 release.

**Comment by olton** [comment]
Vegas now built into Metro 4 (4,3,7) as an internal component with role `vegas`. Example https://pimenov.com.ua/demo/vegas/
