### ISSUE TITLE
Date Picker Initial Value

### ISSUE THREAD

**Issue by masiqbal** [olton/Metro-UI-CSS#1372]
https://metroui.org.ua/datepicker.html

Problem: The initial value of data picker is always 1 day left behind. 

My time zone is: GMT+8
My current date: May 29, 2019
My current time is: 00:37:10
When I do not fill the data-value attribute, the initial date picker produced value is: May 28, 2019 (it is supposed to be May 29, 2019)

When I fill the data-value='2019-04-01',  the initial date picker produced value is: March 31, 2019 (it is supposed to be April 01, 2019)

Is it the timezone problem? How to fix it?

Thank you.

**Comment by olton** [comment]
Thank you, I check it tomorrow

**Comment by olton** [comment]
I fix it, Please check it

**Comment by masiqbal** [comment]
Thank you very much.
