### ISSUE TITLE
4.3 alpha 2

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1373]
I'm testing alpha 2 on my project (with your new package).
I've lot of disturbing comparing to alpha 1.
For information, no news in my project, simply upgrade.

Several errors appear. I know it's not easy without examples but hard for me to make it...
It seem to be m4q problems..

Error can be reproduced with Sidebar example : 

TypeError: $(...).css is not a function : line 20307 is metro.js
  =>   $(this).css({left: 0}, o.duration);

Not sure but perhaps error with List components : 

TypeError: element.val(...).trim is not a function : line 15311 in metro.js
  =>  if (!Utils.isValue(element.val().trim())) {

Hope you found issues with my information...

**Comment by olton** [comment]
Thank you, I lost `use strict` when building release.

**Comment by olton** [comment]
Please test alpha 3
