### ISSUE TITLE
Dialog not responsive 

### ISSUE THREAD

**Issue by MicroAsif** [olton/Metro-UI-CSS#1375]
I made a form inside dialog and seems like it's broken in mobile device, any idea how to make dialog responsive or scroll-able  ?

**Comment by olton** [comment]
You have to adjust the size of the dialogue itself through the classes.

**Comment by MicroAsif** [comment]
okay i will try that one, is there any way make dialog scroll able ?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1006
