### ISSUE TITLE
Calendar locale

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1376]
I'm using calendar picker like this : 

```
<input id="mdatedeb" data-role="calendarpicker" 
                 data-input-format="dd/mm/yyyy" value="25/10/2019"
                 data-format="%d %B %Y" />
```
and adding <meta name="metro4:locale" content="fr-FR"> in header.

When my page is displaying, date are in US mode but if I display calendar, it's french mode (if I choose another date, date is in french mode too).

Perhaps I'm missing something ?

**Comment by olton** [comment]
data-locale attribute ?

**Comment by arjarn** [comment]
I've : 

<meta name="metro4:locale" content="fr-FR">

**Comment by olton** [comment]
By default, calendar picker use METRO_LOCALE global var, This variable init from meta tag `metro4:locale`.
Use `data-locale="en-US"` attribute for calendar picker to set to en-US

**Comment by arjarn** [comment]
In fact, I want FR calendar, it's why I'm using metro4:locale with fr-FR value.
But when my page is displaying (with default values set for calendar), calendar format is en-US

My draft page : [](https://sandbox.org.ua/arjarn/code/azbM3YfemW)

**Comment by olton** [comment]
I see: initial value in US, after select date - in FR. Ok, I check it.

**Comment by olton** [comment]
I fix it
