### ISSUE TITLE
about visible and hidden

### ISSUE THREAD

**Issue by leffss** [olton/Metro-UI-CSS#1377]
in bootstrap’s grid system，i can use .visible-xs  or .hidden-xs to control something display in In different breakpoints . so , metro ui css can do like that?

**Comment by olton** [comment]
https://metroui.org.ua/display.html

**Comment by leffss** [comment]
> https://metroui.org.ua/display.html

I have already read this doc，now i want something just not display in cell-sm，but i do not know how to write the code, could you give me a simple example?  thinks!!!

**Comment by olton** [comment]
`<div class="d-none d-block-sm">...</div>` - display block **from** `sm`
`<div class="d-none-md">...</div>` - display block **from** 0 to `sm`, but hide for md and higher

https://metroui.org.ua/media.html

**Comment by leffss** [comment]
> `<div class="d-none d-block-sm">...</div>` - display block **from** `sm`
> `<div class="d-none-md">...</div>` - display block **from** 0 to `sm`, but hide for `md` and higher
> 
> https://metroui.org.ua/media.html

### Thinks very much, it works.
