### ISSUE TITLE
multi-action bug in grid row

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1379]
https://codepen.io/taurenshaman/pen/LooLPj
When collapsed: still see part of a icon of action item
When expanded: looks like not enough space?

Thank you very much!

**Comment by olton** [comment]
remove `style="text-align: center;"`

**Comment by taurenshaman** [comment]
> remove `style="text-align: center;"`

So how to make the cell be center?
The class name "flex-justify-center" in row not working.
(Ref: https://metroui.org.ua/grid.html#_alignment_columns_h)

**Comment by olton** [comment]
1) alignment column classes work for cells, but not for cells inner data
2) https://sandbox.org.ua/olton/code/2Qm51rHqm5 (center multi-action button in cell)
