### ISSUE TITLE
metro 4 not supporting arabic language {backwards}

### ISSUE THREAD

**Issue by hossemThecoder** [olton/Metro-UI-CSS#1380]
![Capture](https://user-images.githubusercontent.com/18426424/59119496-3d955b00-8953-11e9-8c3b-706e499bf06b.PNG)
this shouldn't look like this, it should look like this
![qd](https://user-images.githubusercontent.com/18426424/59119611-864d1400-8953-11e9-9ecd-089d20708f70.PNG)

**Comment by olton** [comment]
Add attribute dir="rtl"
