### ISSUE TITLE
Simple Tables Overflow in fixed sized Charm

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1384]
I'm using [simple table](https://metroui.org.ua/tables.html) in a fixed sized charm( width: 500-600px;).
when the content length is long, the table will overflow.
https://codepen.io/taurenshaman/pen/OebBWM

I searched the code of options table in any document page. But got nothing.
e.g. https://metroui.org.ua/charms.html
the options table has no more settings:
`<table class="table cell-border table-border options-table">`

I also tried setting width and text-ellipsis of each td (thead/tbody), but not working:
```
<tr>
<td title="{{keyTitle}}" style="width: 100px;">{{keyTitle}}</td>
<td title="{{title}}" style="width: 120px;"class="text-ellipsis">{{title}}</td>
<td title="{{uri}}" style="width: 350px;"class="text-ellipsis"><a href="{{uri}}">{{uri}}</a></td>
<td style="width: 30px;"><button class="button alert cycle mini outline" on-click="['deleteItem', '{{key}}', '{{uri}}']"><span class="mif-cross"></span></button></td>
</tr>
```

how does the text wrapped in your options table?
![options-table](https://user-images.githubusercontent.com/1308706/59813111-ddcf8480-9342-11e9-9c16-af299189417c.png)

Thank you very much!

**Comment by taurenshaman** [comment]
#1345 
simple table has no "data-horizontal-scroll" option

**Comment by olton** [comment]
This option present only for table with data-role=table

**Comment by olton** [comment]
Put table into container with overflow visible, and set for table style width: auto

**Comment by taurenshaman** [comment]
Done.
Thank you~
