### ISSUE TITLE
DatePicker data-format Observe

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1385]
How can i change attribute format at runtime and picker will be updated?
I have a multi language page and i need the selected value will be updated when user change language.

Thanks

**Comment by olton** [comment]
Did you mean the `locale` attribute?

**Comment by olton** [comment]
In 4.2.46 I added observation for attribute `data-locale`

**Comment by olton** [comment]
In 4.2.46 I added observation for attribute `data-format`
