### ISSUE TITLE
Setup Notify container

### ISSUE THREAD

**Issue by txhai** [olton/Metro-UI-CSS#1386]
Hello authors,
I tried to set up the notify's container by the guide and your answer:
```
Metro.notify.setup({
   container: $(".notifies")
});
```
_Originally posted by @olton in https://github.com/olton/Metro-UI-CSS/issues/1130#issuecomment-402440002_

But it seems that nothing happens. I see in the `notify.js`, there is no reference to `this.options.container`:
https://github.com/olton/Metro-UI-CSS/blob/4ef7883ac79b247f30d350c174fd59089aa1ee5e/js/plugins/notify.js#L25-L34
https://github.com/olton/Metro-UI-CSS/blob/4ef7883ac79b247f30d350c174fd59089aa1ee5e/js/plugins/notify.js#L100-L103

I found out I can set the container directly by `Notify.container = $(...)`. But I think I should let you know.

Btw, Metro UI is so great, thank you 👍 .

**Comment by olton** [comment]
Thank you, This is true, I really changed behavior for defining notifies container. Now you must use `Metro.notify.container` property to setup it.
