### ISSUE TITLE
Carousel | Set a specific size

### ISSUE THREAD

**Issue by Chaoswriter96** [olton/Metro-UI-CSS#1394]
Hi olton

I tried the carousel and I missed a "comfort" function with the sizing. 
For example:
Is it possible to set a size like "height: 50px; width: 100%;"?

I saw I can set sizes like 16/9 or an height with data-height="50px" for example. 
But when I want to use a slide with data-cover it doesnt autoscale to the data-height="50px".

Do you I may do a mistake?
My version of MetroUI: 4.2.47

Thanks!

**Comment by olton** [comment]
show your carousel code

**Comment by Chaoswriter96** [comment]
```
<div data-role="carousel" data-effect="slide" data-bullets="false" data-controls="false" data-auto-start="true" data-height="60px"> 
            <div class="slide d-flex flex-justify-center flex-align-center" data-cover="admin/images/SFV_60px.jpg" data-period="5000">SFV</div>  
            <div class="slide d-flex flex-justify-center flex-align-center" data-cover="admin/images/MFV_60px.jpg" data-period="5000">MFV</div> 
    </div>
```

**Comment by olton** [comment]
data-height="60"

**Comment by olton** [comment]
> Is it possible to set a size like "height: 50px; width: 100%;"?
```
<div data-role="carousel" data-height="50">
...
</div>
```

**Comment by olton** [comment]
Each slide with `data-cover` attribute receive `backgroundSize: "cove"` https://github.com/olton/Metro-UI-CSS/blob/master/js/plugins/carousel.js#L208. Please send me to email sergey@pimenov.com.ua your images for your carousel slides

**Comment by olton** [comment]
4.2.48
+ [x] Carousel: moved style props for slide background image from js to css

Now you can define your own style with:
```
.carousel .slide {
...
}
```

**Comment by Chaoswriter96** [comment]
Will try it later (sry for the long response)
