### ISSUE TITLE
autocomplete input

### ISSUE THREAD

**Issue by drill95** [olton/Metro-UI-CSS#1398]
Hello,
do you know tell me if it is planned to add a autocompletion <input> with a json data like this http://easyautocomplete.com ?
many thanks.

**Comment by olton** [comment]
I'm currently busy developing a version for react.  Functional changes in the current version I make only by order of existing sponsors.

**Comment by drill95** [comment]
Many thanks, for your time and for this tool metro ui

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1682
