### ISSUE TITLE
Advice of enhancement to Chat component

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1401]
**Scenario**: 
There is a list of dialog content in the DB, e.g. interview. 

**Requirement**: 
There should be a way to display the chat flow with no input/update support. They are Readonly.

**Advice**: 
1.  Maybe there can be another DialogFlow or ChatFlow component, an evolution from existing Chat.  
2.  Give some options to hide the input and send button to Chat.

Thank you for your time!

**Comment by taurenshaman** [comment]
Disable input and button using css, but which cannot disable the clear-button:  
```
/* http://jsfiddle.net/d1vuqzjo/ */
input.disabled-input {
  pointer-events:none;
  opacity:0.5;
}

button.disabled-button{
  pointer-events:none;
  opacity:0.5;
}
```

Example: https://codepen.io/taurenshaman/pen/ZEzjqVz

**Comment by olton** [comment]
In 4.3.0
+ [x] Chat: add attribute `data-readonly` and method `toggleReadonly`
