### ISSUE TITLE
Table initialization

### ISSUE THREAD

**Issue by liKe2k1** [olton/Metro-UI-CSS#1404]
Hi,

I got some trouble with the Table Component.

Is there a way to initialize the table via JS? Like Metro.Table.create() ?

Or is there a way to reload the table from HTML DOM? 

I insert rows directly to the DOM but the Component doesn't show this items. (This way can't be migrated to setItems or loadData)

Thanks

**Comment by olton** [comment]
1) You can init table component in functional style `$(table).table({...})`
2) In this version, you can't add rows at runtime, only delete `deleteItem(fieldIndex, checkValue)` or update `updateItem(key, field, value)`.
3) In this version, you can reload data with a method `loadData(sourceLink, true)` or `setData(obj)` or `setItems(obj_for_data_only)`

**Comment by liKe2k1** [comment]
Thanks for your reply. $(table).table({...}) works as expectet.
