### ISSUE TITLE
Dark table and dark letters for tfoot

### ISSUE THREAD

**Issue by cizordj** [olton/Metro-UI-CSS#1407]
Hello, I'm using MetroUI v4.2.49 and some CSS schemes to make my table look pretty.

![Capturar](https://user-images.githubusercontent.com/32869222/64982198-f4c73980-d893-11e9-9d59-f6d6453242d4.PNG)

I am having a dificulty with the **tfoot** tag, I can't manage to make it look lighter when I use dark themes, such as dark red and darcula.

![Capturar1](https://user-images.githubusercontent.com/32869222/64982365-6a330a00-d894-11e9-97aa-b092d88fc885.PNG)

When I use brighter themes it looks normally.

![Capturar3](https://user-images.githubusercontent.com/32869222/64982865-8f744800-d895-11e9-8d9d-9a5cc3592803.PNG)

This is the source code I've been using for learning purposes, based on that example from MetroUI website.

I tried using **background-color** and **color** styles in order to change the letters' color, but no success.
What can I do now?

**Comment by olton** [comment]
Add this
For darcula:
```
<style>
        .table tfoot {
            border-bottom-color: #585b5d;
        }

        .table tfoot th {
            color: #bbbbbb;
        }
    </style>
```
For dark red:
```
    <style>
        .table tfoot {
            border-bottom-color: #730014;
        }

        .table tfoot th {
            color: #bbbbbb;
        }
    </style>
```

**Comment by olton** [comment]
I added these styles in 4.3.0

**Comment by cizordj** [comment]
Now I got how it's designed, thank you so much for your help.
