### ISSUE TITLE
nodeType - error

### ISSUE THREAD

**Issue by dbaum24** [olton/Metro-UI-CSS#1409]
Hi,

since today, I have this error-Message:

Uncaught TypeError: Cannot read property 'nodeType' of null
    at new C.init (metro.js:3418)
    at C (metro.js:557)
    at Object._createContainer (metro.js:18500)
    at Object.setup (metro.js:18480)
    at metro.js:18603
    at metro.js:11
    at metro.js:7

I have do nothing at my code. Can you help me please?
Thx!

**Comment by olton** [comment]
Show your code that causes this error

**Comment by mulder37** [comment]
​Same problem here...
The error occures on initiation I think, as it does not need any metro elements to be present.
Hope this helps. And thanks! Love your product.

Cheers. M


HTML:

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>Untitled Document</title>
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro.min.css">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-colors.min.css">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-rtl.min.css">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-icons.min.css">
<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>
</head>
<body>
</body>
</html>


CONSOLE OUTPUT:

Uncaught TypeError: Cannot read property 'nodeType' of null
    at new C.init (metro.js:3418)
    at C (metro.js:557)
    at Object._createContainer (metro.js:18500)
    at Object.setup (metro.js:18480)
    at metro.js:18603
    at metro.js:11
    at metro.js:7
C.init @ metro.js:3418
C @ metro.js:557
_createContainer @ metro.js:18500
setup @ metro.js:18480
(anonymous) @ metro.js:18603
(anonymous) @ metro.js:11
(anonymous) @ metro.js:7
