### ISSUE TITLE
Table Component locales

### ISSUE THREAD

**Issue by IvanVasquez** [olton/Metro-UI-CSS#1410]
Is there a way to set the text of a table component:
> Search
> Show entries
> Showing n to n of n entries
> Prev & Next

Metro 4 - v4.3.0. Built at: 22/09/2019 21:20:12

**Comment by olton** [comment]
Use attributes:
+ `data-table-rows-count-title` - Show entries:
+ `data-table-search-title` - Search:
+ `data-table-info-title` - Showing $1 to $2 of $3 entries
+ `data-pagination-next-title` - Next
+ `data-pagination-prev-title` - Prev
+ `data-all-records-title` - All
+ `data-inspector-title` - Inspector
+ `data-empty-table-title` - Nothing to show

**Comment by olton** [comment]
For global setup: https://metroui.org.ua/global-setup.html
