### ISSUE TITLE
Request: Add Disabled Option to Select

### ISSUE THREAD

**Issue by MELindley** [olton/Metro-UI-CSS#1413]
Hi, it would be great to be able to add a disabled option in the Metro_4 select, currently the disabled attribute seems to be ignored when building the replacement select. 

Thanks for your work on this great library !

**Comment by olton** [comment]
added in 4.3.1. You can use `disabled` attribute for option:
```
<select id="my-select" data-role="select" data-add-empty-value="true" data-placeholder="Select value..." data-empty-value="-1">
    <option value="1">Value 1</option>
    <option value="2" disabled>Value 2</option>
    <option value="3">Value 3</option>
    <option value="4">Value 4</option>
</select>
```

**Comment by CEVR88** [comment]
Hi

> 

Hi, but, the select element, by itself, can´t be disabled? I don´t want the user can be able to dropdown the select until it double clicks on it.
