### ISSUE TITLE
Metro.js - Unable to get property 'trim' of undefined or null reference

### ISSUE THREAD

**Issue by tpena54** [olton/Metro-UI-CSS#1414]
Hello! Pretty new to using Metro 4. I am utilizing the keypad function and up until the last few days, was working great. Now today I am getting an error saying "Unable to get property 'trim' of undefined or null reference". Here is how initialize my form. I am using IE 11 (required by the application utilizing this keypad). 

```

<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>

```
omitted other non-related code

```

<form name="StoreID" action="" method="get">
			<input type="image" src="../Media/searchgo-2019.png" value="Search" name="Search" onclick="checkStore(event, this.form, 'true'); $('#inputStore').data('keypad').val('')" style="position: absolute; left: -85px; top: 0;">
		    <div class="input keypad info" style="position: relative; top: 40px; left: 30px; border:none; outline: none; width:138px; height:0;">
                <input type="text" id="inputStore" name="inputStore"
		    	data-role="keypad"
		    	data-position="right"
		    	data-length="5"
		    	data-key-size="75"
		    	data-open="false"
		    	data-cls-keypad="info"
		    	data-cls-backspace="bg-darkgray fg-white"
		    	data-cls-clear="bg-red fg-white"
		    	maxlength="5" size=5 onkeypress="keypress(event, this.form); $('#inputStore').data('keypad').val('')" style="position: absolute; border: none; outline:none; font-size: 40px; left: -8px; width: 150px; height:50px; top: -22px; color: #ff9822;" autofocus>
            </div>
		</form>
```

Any help would be greatly appreciated!

**Comment by olton** [comment]
This possible if you use jQuery. Return to 4.2.49 or use 4.3.1 from github or dev cdn or wait for release 4.3.1

**Comment by tpena54** [comment]
Ah go it. Yes I do use jQuery. I tried to revert to 4.2.x using the following but it appears that v4.2.x/js/metro.min.js throws a 404 error. Am I using that correctly?

<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.2.x/css/metro-all.min.css">
<script src="https://cdn.metroui.org.ua/v4.2.x/js/metro.min.js"></script>

**Comment by olton** [comment]
https://cdn.metroui.org.ua/v4.2.49/js/metro.min.js

**Comment by tpena54** [comment]
actually i am using that incorrectly.

**Comment by tpena54** [comment]
you beat me to it. awesome support! Thank you!!

**Comment by olton** [comment]
Please create an example with your problem code on codepen.io
