### ISSUE TITLE
MetroUI Calendarpicker issue

### ISSUE THREAD

**Issue by domi4970** [olton/Metro-UI-CSS#1415]
Hello, since 2 days ago, I started to have trouble with calendarpickers. Arrows (left and right) for month and year changing are not working anymore. The calendar closes unexpectedly when clicking on them.
Also visible on your demo page: https://metroui.org.ua/calendarpicker.html

On my side, I get also this JS error when clicking the arrows:
VM74 metro.min.js:7 Uncaught TypeError: Cannot read property 'close' of undefined
    at HTMLDivElement.<anonymous> (VM74 metro.min.js:7)
    at VM74 metro.min.js:7
    at C.init.forEach (<anonymous>)
    at Function.C.each (VM74 metro.min.js:7)
    at HTMLSpanElement.<anonymous> (VM74 metro.min.js:7)
    at HTMLDocument.func_event_click_4 (VM74 metro.min.js:7)

**Comment by olton** [comment]
Fixed in 4.3.1

**Comment by domi4970** [comment]
Hi, how to use this 4.3.1 version ? 
https://cdn.metroui.org.ua/v4.3.1/js/metro.min.js ?

**Comment by olton** [comment]
You can download branch from github or use from cdn as v4-dev or wait for release

**Comment by domi4970** [comment]
Ok thx for the quick support.
