### ISSUE TITLE
Trigger Not Passing Data, Conflict with CustomEvent?

### ISSUE THREAD

**Issue by obsidience** [olton/Metro-UI-CSS#1416]
https://codepen.io/obsidience/pen/mdboagX

Hi there,

In the above Codepen, clicking on a menu item should trigger an event passing in custom data that will then show an alert with e.data however e.data is getting lost.

In looking at the code, I believe that part of the issue is that [an existing Web API object for CustomEvent already exists in the browser](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent).  

Because it's using the built-in Web API version of CustomEvent, there is no constructor that accepts "data" and is therefore failing to pass it:

`        var e = new CustomEvent(name, data || {});
`

Help appreciated!

**Comment by olton** [comment]
```
$(window).on("myEvent", function(e) {
  alert("e.data is: " + e.detail);
});

function tabChanged(tab, elem) {
  $(window).fire("myEvent", {foo: "foo"});
}
```

**Comment by obsidience** [comment]
Works great, sorry for the confusion!

**Comment by olton** [comment]
Method `trigger` was stored for compatible with jquery calls. In Metro4 best for use method `fire`.
https://github.com/olton/m4q/blob/0477e9a0f6af36124bb0862bacbfb833d99beca2/src/events.js#L286

**Comment by obsidience** [comment]
Gotchya, thanks for the clarification!
