### ISSUE TITLE
Anchors should work with "data-hotkey" attribute

### ISSUE THREAD

**Issue by docoliver** [olton/Metro-UI-CSS#1420]
As of now, an `onclick` attribute is required for all elements with the attribute `data-hotkey` in order for the hotkey to actually work.

You can't set hotkeys for links unless you add `onclick="window.location.href='website.com'"` as an attribute. I think this is tedious and the `data-hotkey` should look for the `href` attribute on an anchor, and once the specified hotkey is pressed, the redirect is triggered.

**Comment by olton** [comment]
Hi, thx for this report. I added this feature in 4.3.2. You can test it from GitHub 4.3.2 branch or get from CDN for develop branch.
