### ISSUE TITLE
va-middle problem of a paragraph

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1423]
Hi, I create a axis visualization, but the content of `<p>` is always on the top.  
I have tried:  

1. `<p class="text-center va-middle">` (https://metroui.org.ua/typography.html#_vertical_alignment)
2. add h-100: `<p class="h-100 text-center va-middle">` 
3. make the cell vertical middle: https://metroui.org.ua/grid.html#_alignment_columns_v 

Code: https://codepen.io/taurenshaman/pen/xxKvqgJ

Thank you very much!

**Comment by olton** [comment]
`va-*` - `vertical-align` - work only with `inline`, `inline-block` and `td, th` elements

**Comment by olton** [comment]
You can use flex model to align subelements:
```
<p class="d-flex flex-justify-center flex-align-center">...</p>
```

**Comment by taurenshaman** [comment]
I update the code (local and codepen), but not work: https://codepen.io/taurenshaman/pen/xxKvqgJ

Here is a screenshot from local:
![p-center](https://user-images.githubusercontent.com/1308706/66181127-3cc2ca80-e6a2-11e9-9e9d-9784a6ca9e8b.png)


Thanks for your time!

**Comment by olton** [comment]
https://codepen.io/olton/pen/WNNegXQ
