### ISSUE TITLE
Table not displaying new rows

### ISSUE THREAD

**Issue by CoveTechnologyAus** [olton/Metro-UI-CSS#1426]
I am using Metro-UI table (data-role="table") and have found if I add rows dynamically the table does not display the new rows.
If I bring it back to a normal table (without data-role="table") then the new rows display fine.

Essentially I am adding the rows like this:
```
        <table class="table striped table-border row-border" data-role="table" data-rows="5">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Book Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in BookList)
                {
                    <tr>
                        <td>@book.Id</td>
                        <td>@book.Name</td>                       
                    </tr>
                }
            </tbody>
        </table>
```
Is there a way to force the table to redraw after I add a row (i.e. add a new book to BookList)
I am guessing it is because in the background the Metro-UI table is being refreshed / managed by the Metro-UI JavaScript that seems to ignore the new rows once the table is initially created.

In the case of just a normal `<table></table>` then it just redraws each time I add a row...

In essence I am just looking for a way for the table to refresh / redraw.

Thanks in advance.

**Comment by olton** [comment]
in the current version, the table does not support the dynamic addition of rows

**Comment by CoveTechnologyAus** [comment]
@olton thanks for the speedy reply, that is a shame though.
I will have to see if I can work around it.

I appreciate you taking the time to answer.

**Comment by olton** [comment]
I do not consider my work a shame!

**Comment by olton** [comment]
New in 4.3.2
+ [x] Table: add methods `addItem([...], redraw)`, `addItems([...], redraw)`, issue #1426

```
var row = ['book_id', 'book_name'];
var redraw = true;
var table = Metro.getPlugin('el', 'table');
table.addItem(row, redraw);
```
or
```
var rows = [
    ['book_id_1', 'book_name'], 
    ['book_id_2', 'book_name']
];
var redraw = true;
var table = Metro.getPlugin('el', 'table');
table.addItems(rows, redraw);
```

**Comment by alefab** [comment]
Hello, sorry to ask but in the sample
`var table = Metro.getPlugin('el', 'table');`
What are supposed to be 'el' and 'table' ?

**Comment by olton** [comment]
`el` - table selector, `table` - constant, identifies which role to use to get the plugin. Example:
```
<table data-role="table" id="table1">...</table>

var table = Metro.getPlugin('#table1', 'table');
```
now table contains component `table`, and you can use component API

**Comment by alefab** [comment]
Thanks, it's working now. Is there a way to fully clean the rows of the table also ?
I have tried to look at the source near addItem() but don't find any revelant method to do it.

**Comment by olton** [comment]
Hack
```
function clearTable() {
    var table = Metro.getPlugin("#t1", "table");
    table.items = [];
    table.draw();
}
```

**Comment by alefab** [comment]
Thanks again, working perfectly.

**Comment by olton** [comment]
I added method `clear()` in 4.3.3

**Comment by olton** [comment]
In 4.3.3 to clear table you can call the method clear:
```
var table = Metro.getPlugin(...)
table.clear();;
```
