### ISSUE TITLE
Ajax requests not setting additional HTTP headers

### ISSUE THREAD

**Issue by mclytar** [olton/Metro-UI-CSS#1427]
When performing an Ajax request, additional HTTP headers are discarded; in particular, the following code does not set the header `X-My-HTTP-Header` (checking in Chrome's Developer Tools, the header does not appear).
```js
$.ajax({
    method: "GET",
    url: "/example",
    headers: {"X-My-HTTP-Header": "HelloHeader"}
});
```

After some debugging, I discovered that the problem may be a wrong call to `$.each` in line 1874 of [this file](https://cdn.metroui.org.ua/v4/js/metro.js) (or, if I understand correctly the project building process, in line 1859 of [m4q.js](https://github.com/olton/Metro-UI-CSS/blob/master/source/m4q/m4q.js)). The particular portion of code is
```js
if (p.headers) {
    $.each(function(k, v){
        xhr.setRequestHeader(k, v);
        headers.push(k);
    });
}
```
Adding the missing `p.headers` in the `$.each` function call would solve the problem:
```js
if (p.headers) {
    $.each(p.headers, function(k, v){
        xhr.setRequestHeader(k, v);
        headers.push(k);
    });
}
```

**Comment by olton** [comment]
Thanks. You right, i fix it today
