### ISSUE TITLE
How can i use Metro4 with npm and Vuejs?

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1434]
After NPM install Metro4... what the best aproach to use Metro4 (styles and javascript) in my project?

**Comment by olton** [comment]
You better ask this question on stackoverflow.

**Comment by txhai** [comment]
I have successfully integrated **Metro UI 4** to my Vue project, very easy.
`npm install metro4@latest`
Then `import` it to the webpack entry
```
import 'metro4';
import 'metro4/build/css/metro-all.min.css'
```
Finally, follow the author's guide: 
[How to use Metro 4 with VueJS framework.](https://metroui.org.ua/vuejs.html)
