### ISSUE TITLE
Where is the docs folder?

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#1435]
The `docs` moved to separate repository [Metro4-Docs](https://github.com/olton/Metro4-Docs)

**Comment by GjBrutello** [comment]
Большое спасибо! А то с сайта metroui.org.ua/examples.html не работают ссылки на исходники примеров:https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/forms > 404

**Comment by olton** [comment]
@GjBrutello Спасибо, ссылки исправил.
