### ISSUE TITLE
.attr() problem

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1437]
Hi Olton!

Another problem with Metro 4.3.2

[https://codepen.io/TorakikiSan/pen/jJymZV](url)

When click on green button, this call a page like:

`/machine.php?machine=undefined`

instead of

`/machine.php?machine=mrdo`

Where is the mistake?

Thank's

**Comment by olton** [comment]
Button contain span, so `$(this).closest('button').attr("data-machine")`

**Comment by TorakikiSan** [comment]
Yes, works!

Thank's!

**Comment by olton** [comment]
@TorakikiSan Hi! In m4q 1.0.3 and Metro 4.3.3 I fixed this behavior. Now
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Test events</title>
</head>
<body>
<button>Clear</button>
<button><span>Span</span></button>

<script src="../build/m4q.js"></script>

<script>
    $("button").on("click", function(e){
        console.log(this);
        console.log(e.target);
    });
</script>
</body>
```
When first button click - this==button, e.target==button
When second button click - this==button, e.target==span

**Comment by TorakikiSan** [comment]
Thank you again!

**Comment by TorakikiSan** [comment]
Install new Metro 4.3.3 and boths **$(document).ready** and **.attr()** works perfect! Thank's!
