### ISSUE TITLE
input type select the contents of the text field.

### ISSUE THREAD

**Issue by dinami-k** [olton/Metro-UI-CSS#1438]
How can i select the contents of the text field, like this: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_text_select

With Metro input.select() change input text to dropdown

**Comment by olton** [comment]
show the full context of your code

**Comment by dinami-k** [comment]
https://codepen.io/drodriguez/pen/gOOgqaO

**Comment by olton** [comment]
https://codepen.io/olton/pen/KKKaJNm
`$('#test')[0].select();`
