### ISSUE TITLE
metro select not properly vue js method or model

### ISSUE THREAD

**Issue by saifalbd** [olton/Metro-UI-CSS#1439]
not working in vue js 

<select data-role="select" @change="demoCk"> // v-model="modelName"
  <option value="1" data-template="<span class='mif-amazon icon'></span> $1">Select One</option>
  <option value="1" data-template="<span class='mif-amazon icon'></span> $1">Select Two</option>
</select>

**Comment by olton** [comment]
https://metroui.org.ua/vuejs.html

**Comment by wxiaoer** [comment]
Hi sir, i did init operation, but in timepick component, vue model bind still doesn't work,can you help me fix this bug?
