### ISSUE TITLE
table response

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1440]
Mobile device table response style scheme should be included in the framework
At present, the form CSS in the framework cannot support the form response
My own table response scheme doesn't work well with the framework

**Comment by olton** [comment]
The library solution should satisfy most needs. At the moment I do not have such a solution. You can use the data-horizontal-scroll and data-horizontal-scroll-stop attributes to create horizontal scrolling of the table under given conditions.
