### ISSUE TITLE
New object: slider with more than one cursor

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1441]
Hi Olton!

![slider](https://user-images.githubusercontent.com/37299746/67395407-3d19fb80-f5a6-11e9-9418-4d8c5200bdf3.jpg)

It would be interesting to implement a new slider with more than one cursor. For example, in the image, a slider with two cursors to establish a minimum and a maximum value. For the selected values, it would be enough to separate them with a comma as in the data-role = "taginput". In the example

$("#YEAR").val() would be equal to "1965,2000"

What do you think about it?

**Comment by olton** [comment]
![doubleslider](https://user-images.githubusercontent.com/365108/67620612-7609d880-f811-11e9-8880-31d0638aaeb5.gif)

**Comment by olton** [comment]
@TorakikiSan added in 4.3.3

**Comment by TorakikiSan** [comment]
Awesome! Thank's

**Comment by TorakikiSan** [comment]
Hi Olton, I found minor issues

(I'm sorry but I can't reproduce the page correctly on codepen also specifying the correct CSS and JS files (v4.3.3))

I'm using

```
Metro 4 - v4.3.3. Built at: 29/10/2019 17:27:38 metro.js:3793:16
m4q - v1.0.3. Built at 29/10/2019 16:21:57 metro.js:3794:16
```

The code:

```
<DIV class="container">

<FORM id="SEARCH" method="post" data-role="validator" data-on-before-submit="onBeforeSubmit" action="/search.cabinet.php">

<DIV class="row mb-2">
   <DIV class="cell-sm-12">
      <LABEL class="text-bold fg-steel" for="YEAR">Year</LABEL>
      <INPUT id="YEAR" name="year" data-role="doubleslider" data-min="1948" data-max="2017" data-hint-always="true" data-hint-position-min="top" data-hint-position-max="bottom" data-cls-complete="fg-steel" value="1980, 1984" />
   </DIV>
</DIV>
<DIV class="row mb-2">
   <LABEL class="text-bold fg-steel" for="YEAR">Year</LABEL>
   <DIV class="cell-sm-12">
   <INPUT data-role="doubleslider"
          data-value-min="20"
          data-value-max="80"
          data-hint-always="true"
          data-hint-position-min="bottom"
          data-hint-position-max="top"
          data-show-min-max="true"
          data-cls-backside="bg-dark"
          data-cls-marker="bg-blue border-50 custom-marker"
          data-cls-hint="bg-cyan custom-marker shadow-2"
          data-cls-complete="bg-red"
          data-cls-min-max="text-bold" />
   </DIV>
</DIV>

<HR class="bg-steel fg-white">

<DIV class="row mb-2">
   <DIV class="cell-sm-8">
      <BUTTON id="SUBMIT" class="button bg-steel bg-lightSteel-hover text-bold fg-white"><SPAN class="icon mif-search"></SPAN> Cerca</BUTTON>
   </DIV>
</DIV>

</FORM>

</DIV>
```

* As soon as the page is loaded this is what I see this:

![doubleslider1](https://user-images.githubusercontent.com/37299746/67842065-bd39e700-faf9-11e9-9cd2-0fe739b573b9.jpg)

the slider is drawn off screen and in the first the values of value = "1980, 1984" are not selected

* As I move one of the cursors, the slider is correctly redrawn.

![doubleslider2](https://user-images.githubusercontent.com/37299746/67842412-6b459100-fafa-11e9-80ca-77dedf0d7616.jpg)

Thank's!

**Comment by olton** [comment]
To setup value, you must use data-value-min and data-value-max, not value

**Comment by TorakikiSan** [comment]
If I add data-value-min="1980" and data-value-max="1984" this is I see:

![doubleslider3](https://user-images.githubusercontent.com/37299746/67843124-aac0ad00-fafb-11e9-90bd-dac01abbc193.jpg)

**Comment by olton** [comment]
All works fine for me
https://codepen.io/olton/pen/bGGoayv

**Comment by TorakikiSan** [comment]
[https://codepen.io/TorakikiSan/pen/EeyWmp]

Very strange. I can't understand where the problem is!

My example also works on codepen, locally (Firefox 70 x64bit) not.

**Comment by olton** [comment]
![2019-10-30-12-49-51](https://user-images.githubusercontent.com/365108/67851810-e10a2680-fb13-11e9-9d79-58098dda6330.png)

**Comment by olton** [comment]
![2019-10-30-12-50-10](https://user-images.githubusercontent.com/365108/67851821-e5ceda80-fb13-11e9-885f-f40523bc412c.png)

**Comment by TorakikiSan** [comment]
Found problem! (or probabily my mistake :-) )

I put metro.js at the beginning of the page with

```
<HEAD>
<META name="metro4:init" content="true">
<META name="metro4:locale" content="it-IT">
<META name="metro4:week_start" content="1">
<SCRIPT type="text/javascript" src="https://cdn.metroui.org.ua/v4.3.3/js/metro.min.js"></SCRIPT>
</HEAD>

```
If i put metro.js at the bottom, before the </BODY> tag, this works fine!

Question: this line is used to initialize metro if loaded at the top of the page?

`<META name="metro4:init" content="true">`

Thank's!

**Comment by olton** [comment]
If you put metro.js in the head, you must add meta tag `<meta name="metro4:init:mode" content="contentloaded">`, or update to latest. In latest this tag has default value `contentloaded`

**Comment by olton** [comment]
if you set `metro4:init` to `false`, Metro can't be initiated automatically. You must init Metro4 manually with `Metro.init()` method.

**Comment by TorakikiSan** [comment]
```
Metro 4 - v4.3.3. Built at: 30/10/2019 11:33:21 metro.js:3793:16
m4q - v1.0.3. Built at 29/10/2019 16:21:57 metro.js:3794:16

```
Put in `<HEAD>` section

```
<META name="metro4:init:mode" content="contentloaded">
<META name="metro4:locale" content="it-IT">
<META name="metro4:week_start" content="1">
<SCRIPT type="text/javascript" src="/js/metro.min.js"></SCRIPT>
<LINK rel="stylesheet" href="/css/metro-all.css" />
```

but the result it's the same!

![SharedScreenshot](https://user-images.githubusercontent.com/37299746/67860546-6b578800-fb1e-11e9-8dc8-1dcd9921bd24.jpg)

**Comment by olton** [comment]
![2019-10-30-15-19-16](https://user-images.githubusercontent.com/365108/67861344-b4143e80-fb28-11e9-8b00-7e7068bf05f6.png)

**Comment by TorakikiSan** [comment]
Perfect, works!

Another my (REALLY STUPID) mistake :-( , I load JS before the CSS instead the CSS and then JS!

**WRONG!!!!**

```
<SCRIPT type="text/javascript" src="/js/metro.min.js"></SCRIPT>
<LINK rel="stylesheet" href="/css/metro-all.css" />

```
**CORRECT!**

```
<LINK rel="stylesheet" href="/css/metro-all.css" />
<SCRIPT type="text/javascript" src="/js/metro.min.js"></SCRIPT>

```
