### ISSUE TITLE
Doc issue ? : How to disable an element

### ISSUE THREAD

**Issue by alefab** [olton/Metro-UI-CSS#1444]
The online doc give the following sample :
```
<script>
    function toggleInputState(el){
        var i = $('#disable_enable_input_runtime');
        $(el).is(':checked') ? i.attr('disabled', false) : i.attr('disabled', true);
    }
</script>
```
But setting the attribute to false is not working, the attribute has to be removed with       `i.removeAttr('disabled');`

**Comment by olton** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="//cdn.metroui.org.ua/v4/css/metro-all.css?ver=@@b-version" rel="stylesheet">

    <title>% - Metro 4 :: Popular HTML, CSS and JS library</title>
</head>
<body class="m4-cloak">
<div class="container mt-20">
    <div class="mb-10">
        <input type="checkbox" data-role="checkbox" data-caption="Disable input" onclick="toggleInput()" id="checkbox">
        <input type="checkbox" data-role="checkbox" data-caption="Enable input" onclick="toggleInput2(this)" id="checkbox2" checked>
    </div>
    <input type="text" data-role="input" id="input">
</div>
    <script src="//cdn.metroui.org.ua/v4/js/metro.js?ver=@@b-version"></script>
<script>
    function toggleInput(){
        var checkbox = document.getElementById("checkbox");
        var input = document.getElementById("input");
        input.disabled = checkbox.checked;
    }

    function toggleInput2(el){
        var i = $('#input');
        $(el).is(':checked') ? i.prop('disabled', false) : i.prop('disabled', true);
    }
</script>
</body>
</html>
```

**Comment by alefab** [comment]
Not working with button

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="//cdn.metroui.org.ua/v4/css/metro-all.css?ver=@@b-version" rel="stylesheet">

    <title>% - Metro 4 :: Popular HTML, CSS and JS library</title>
</head>
<body class="m4-cloak">
<div class="container mt-20">
    <div class="mb-10">
        <input type="checkbox" data-role="checkbox" data-caption="Disable input" onclick="toggleInput(this)" id="checkbox">
        <button id="uploadButton" class="button success" style="width:100%;">Upload</button>
    </div>
</div>

<script src="//cdn.metroui.org.ua/v4/js/metro.js?ver=@@b-version"></script>
<script>
    function toggleInput(el){
        var input = document.getElementById("input");
        input.disabled = el.checked;
    }

    function toggleInput2(el){
        var i = $('#uploadButton');
        $(el).is(':checked') ? i.prop('disabled', false) : i.prop('disabled', true);
    }
</script>
</body>
</html>

**Comment by olton** [comment]
All works fine
https://codepen.io/olton/pen/gOOWMom

**Comment by olton** [comment]
add attr id to button and use $(id)
https://codepen.io/olton/pen/MWWmeqZ

**Comment by alefab** [comment]
Indeed, I must have mixed id and attibute then. Thanks.
