### ISSUE TITLE
Table : Sorting a column is losing the curent state of the element in the row

### ISSUE THREAD

**Issue by alefab** [olton/Metro-UI-CSS#1445]
I am using progress bar inside a table to show the current progression of each row.
But if one of the column is sorted using the header then the state of the progressbar is reset to is initial state.
I was expecting the progress bar to not be reset by the sort action.

**Comment by olton** [comment]
Table redraw all visible items. Use event onDrawCell to draw required progress bar

**Comment by olton** [comment]
https://codepen.io/olton/pen/rNNmxaB
