### ISSUE TITLE
Toast not centered

### ISSUE THREAD

**Issue by morrisjdev** [olton/Metro-UI-CSS#1446]
I realized that the toast is not centered.

It seems that the `magin-left: -(width / 2)` is not working, because the margin-left is always 0.
Would it make sense to add `transform: translateX(-50%);` instead?

![Unbenannt](https://user-images.githubusercontent.com/20016673/67483892-17086000-f667-11e9-883b-df5562cda2f5.PNG)

**Comment by olton** [comment]
Yes, I know, fixed in 4.3.3. Temporary you can add this hack:
```
.toast {
transform: translateX(-50%);
}
```

**Comment by morrisjdev** [comment]
Ok perfect. I already fixed it using the same code as you suggested above but thank you for the info.
