### ISSUE TITLE
MetroUI with Blazor

### ISSUE THREAD

**Issue by da-baranov** [olton/Metro-UI-CSS#1449]
Hi, have you experimented with MetroUI on Blazor (more precisely, server side Blazor)? 
Because of Blazor specific JavaScript processing I see a lot of side effects - eg. sidebar toggler and sidebar close button won't work as expected. Clicking on sidebar close button I see the following message: "Element not contain role sidebar! Please add attribute data-role="sidebar" to element #sb1", although I checked twice that HTML markup does contain div with such a data-role attribute.

**Comment by olton** [comment]
What is the Metro 4 version you use?

**Comment by da-baranov** [comment]
The latest one. And I've managed to resolve that issue by moving sidebar close button click event handler to a standalone .js file as follows:

$(document).ready(function () {
    $(document).on("click", "#sb1-close", function () {
        Metro.sidebar.close('#sb1');
        return false;
    });
});
