### ISSUE TITLE
dropdown/split button is little lower than info-button in the same row

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1451]
`<div class="row flex-justify-around bg-red p-1">`  
![drop-split-lower-than-info-same-row-p1](https://user-images.githubusercontent.com/1308706/67830205-bbc9e800-fb14-11e9-9d87-317c17b48e8b.png)

if remove `p-1` from the row, it will be more clear:  
![drop-split-lower-than-info-same-row](https://user-images.githubusercontent.com/1308706/67830293-0cd9dc00-fb15-11e9-8be6-7e667141edf5.png)

https://codepen.io/taurenshaman/pen/ExxwvwJ

Thank you very much!

**Comment by olton** [comment]
Thx, fixed in 4.3.3
