### ISSUE TITLE
Listview: data-on-node-dblclick is broken

### ISSUE THREAD

**Issue by smx-smx** [olton/Metro-UI-CSS#1453]
I observed the following issues in the Listview widget

Using `data-on-node-click`, the event handler gets called correctly
Using `data-on-node-dblclick`, nothing happens

Additionally, `data-on-node-click` prototype is not respected.
The documentation says `onNodeClick(node, listview)`. However, `listview` is undefined

```javascript
function nodeClicked(node, listview){
    console.log(node);
    console.log(listview); //undefined
```

Metro 4 - v4.3.2. Built at: 20/10/2019 17:53:59

Thanks in advance

**Comment by olton** [comment]
The second argument was removed. Now you can access to listview element with `this`

**Comment by somuelle-tmt** [comment]
This is not working for me in  v4.3.4.

```html
<ul data-role="listview" data-view="content" data-select-node="true" data-on-node-click="test1" data-on-node-dblclick="test2" style="display: table">
</ul>
```
`data-on-node-click` fires, `data-on-node-dblclick` does nothing

**Comment by olton** [comment]
Right for 4.3.7
Method click works fine: https://codepen.io/olton/pen/RwWXVyd
DoubleClick I will fix today.

**Comment by olton** [comment]
```
<ul data-role="listview" data-on-node-click="..." data-on-node-dblclick="...">
    ...
</ul>
```

**Comment by olton** [comment]
Thank you, fixed
