### ISSUE TITLE
Collapse: events not working

### ISSUE THREAD

**Issue by smx-smx** [olton/Metro-UI-CSS#1454]
Following events are not firing:
- data-on-drop
- data-on-up
- data-on-dropdown-create

It looks like none of the Collapse events are working

> Metro 4 - v4.3.2. Built at: 20/10/2019 17:53:59

**Comment by smx-smx** [comment]
May i ask if there has been a relevant change related to events?
Several DOM-defined events cited in the documentation are not working (see Listview, Collapse, and possibly others?)

**Comment by olton** [comment]
Collapse component has three events: `onExpand`, `onCollapse`, `onCollapseCreate`
https://metroui.org.ua/collapse.html#_dropdown_options

**Comment by smx-smx** [comment]
Please see this sample: https://jsfiddle.net/s31Lnpy7/
Collapse events defined as attributes do not trigger

**Comment by olton** [comment]
https://codepen.io/olton/pen/NWWwjLe

**Comment by smx-smx** [comment]
Ah the event names are different, so it's a documentation issue.
Thanks
