### ISSUE TITLE
TreeView Show Errors

### ISSUE THREAD

**Issue by paloky** [olton/Metro-UI-CSS#1455]
Hi.
I have problems with a TreeView component.
Sometimes, don't show correctly the tree, and disapears some of the the captions.

When I refhesh the page (with F5 for example), sometimes this solve the issue.

I review the HTML font with mouse right click "View source code of page", and it's all correct, but the visualitzation was wrong...
Attach a picture of it was happend...

![IMG-20191031-WA0000](https://user-images.githubusercontent.com/5292503/67937609-2ab74780-fbce-11e9-8a93-7d3fb69ace5e.jpg)

And this if the correct view:

![Captura](https://user-images.githubusercontent.com/5292503/67938013-f8f2b080-fbce-11e9-9cc2-df20fd3db572.PNG)

What may be going on?.

**Comment by olton** [comment]
Create your problem code on codepen.io.

**Comment by paloky** [comment]
It's imposible create the code on codepen.io, because the HTML is generated with php and mySQL.
The issue is random.  Sometimes happend and sometimes not.
I try with diferents browsers with the same result.

**Comment by olton** [comment]
Without seeing your html code, I cannot identify the problem.

**Comment by paloky** [comment]
I'll send you the code as soon as the error occurs again.
Thank's

**Comment by olton** [comment]
@paloky Ok, send code to sergey@pimenov.com.ua with subj `Metro 4 issue #1455`
