### ISSUE TITLE
Issue with nested Listviews

### ISSUE THREAD

**Issue by smx-smx** [olton/Metro-UI-CSS#1456]
See this sample: https://jsfiddle.net/yeL6n2dt/1/

I'm trying to define a listview as children of another listview.
Doing so however causes 2 issues
- duplicated elements in children listview (apparently doesn't happen if everything is wrapped in a collapsible)
- If the group is collapsed (clicking on the arrow next to the group), it cannot be expanded anymore

Is what i'm trying to do possible?
Thanks

**Comment by olton** [comment]
ListView was not designed to be used as a nested listview. Perhaps in future versions this will be done.

**Comment by smx-smx** [comment]
Update: it works for `data-view=content` if you also add `data-role-listview="true"`
But it doesn't seem to work if you want a different layout (say icons-medium) for the child list

**Comment by olton** [comment]
data-role-component_name = "true" is a service attribute that tells the witness module that this component has already been created and does not need to be created. It should not be used directly by anyone or anywhere else.
