### ISSUE TITLE
Баг окна WindowYoutube в шаблоне примеров Desktop

### ISSUE THREAD

**Issue by GjBrutello** [olton/Metro-UI-CSS#1459]
Здрасте, при открытии из меню Пуск окна WindowYoutube шаблона ./examples/desktop/desktop.html и затем последующих попыток отбросить это окно из стороны в сторону, особенно, вверх вниз, вверх вниз, происходит прилипание к указателю мыши данного окна.  Хотелось бы отметить, что именно при многократном отбрасывании, то есть когда удерживаешь и отпускаешь окно, в итоге помогает только двойной щелчок для раскратия окна во весь экран  с целью добраться до кнопки закрыть X либо обновление страницы. Тестировал на Firefox и Chrome последних версий на разных машинах.

**Comment by olton** [comment]
Please create issue in the docs repo.
