### ISSUE TITLE
metro4@4.3.3 fails to load as `import Metro from metro4` but 4.3.1 works

### ISSUE THREAD

**Issue by visitsb** [olton/Metro-UI-CSS#1460]
Can't say what could be the problem, but my `import` works _only_ on `4.3.1` but _not_ on `4.3.2` nor latest `4.3.3`. I recently upgraded my packages using `npm update` when I started to get this error.

Do you know why I might get this error on latest version of metro4?

`import Metro from 'metro4'`

**Environment**
`Vue` SPA frontend using `webpack` running on `nodejs@13.0.1`

**Behavior**
On `4.3.1` get `Metro` instance correctly when using `import Metro from 'metro4'`
On `4.3.3` get `{}` empty object when using `import Metro from 'metro4'`

**Workaround**
Use `4.3.1` until issue is resolved. 
Currently use `"metro4": "4.3.1"` instead of `"metro4": "^4.3.1"` in my `package.json`.

**Expected**
On latest `4.3.3` should be able to import without any errors. `4.3.2` has same problem.

**Comment by olton** [comment]
import "metro4"

**Comment by visitsb** [comment]
`import 'metro4'` works 👍, looks like `Metro` is a global variable. May be useful to put this in docs. Thanks!
