### ISSUE TITLE
Activity indicator not showing

### ISSUE THREAD

**Issue by fermart** [olton/Metro-UI-CSS#1461]
Hi!
I'm having problems to render the activity indicator, I updated the version to 4.3.3, but still not working, the activity is not showing, maybe a synchronicity problem?

Thanks in advance

var showProgress = function () {
    return Metro.activity.open({
        type: 'ring',
        overlayAlpha: 0.6
    });
};

var hideProgress = function (activity) {
    Metro.activity.close(activity);
};

          var activity = showProgress();
            hideProgress(activity);

**Comment by olton** [comment]
https://codepen.io/olton/pen/MWWXjWd

**Comment by fermart** [comment]
Thanks a lot is working fine!
