### ISSUE TITLE
Splitter: Cannot relase divider on IE11

### ISSUE THREAD

**Issue by atwupack** [olton/Metro-UI-CSS#1464]
The splitter control ( https://metroui.org.ua/splitter.html ) does not work correctly on IE11 (Windows 10). You can grab and move the divider but it is not possible to release it again. Releasing the mouse button does nothing and it keeps dragging the divider.
Everything seems to work fine in Edge and Firefox. But if I understand correctly, IE11 is also a fully supported platform and it should work there.

**Comment by olton** [comment]
Thx, fixed

**Comment by atwupack** [comment]
I just tested it with the latest version on the 4.3.4 branch and it works now. Thank you for the quick fix.

**Comment by tliu0c** [comment]
The splitter still has issue, if certain elements are selected before start dragging the gutter, the same issue happens and it cannot be released. For example, press ctrl+A before start dragging.

**Comment by sunishkumar** [comment]
Issue exists in Chromium 89

**Comment by olton** [comment]
@sunishkumar Metro version? Code example on codepen.io!
