### ISSUE TITLE
How to init Metro4 Keypad with dynamic input?

### ISSUE THREAD

**Issue by thinhpc86** [olton/Metro-UI-CSS#1465]
Hello,
Your Metro Keypad plugin is simple and really good to use, thanks for your time to make this.
But I'm in a case that after web page loaded, I dynamic create some input by jquery like this:

`$(".content").append('<input data-role="keypad" name="foo" type="text">');`

Then how to make keypad available for these new input box?
Thank you very much!

**Comment by olton** [comment]
https://codepen.io/olton/pen/Rwwvmgr

**Comment by thinhpc86** [comment]
Thank you for quick response, so the lib already support this. Maybe my side code has some lib conflict need to check.
