### ISSUE TITLE
data-role="list" and change color

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1466]
Hi Olton!

Can I change the color of the card box border (now bd-lightGray) and highlight this border when the mouse is over the card?

![SharedScreenshot](https://user-images.githubusercontent.com/37299746/69576394-79d57a00-0fcc-11ea-89a3-7a6359264a54.jpg)

Thank's!

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/952438076ad89b9e7703ae4b24641b2984db2b43/source/colors/colors-defs.less#L52

`bd-color_name-hover`

**Comment by TorakikiSan** [comment]
Thank's, but where i place that?

**Comment by olton** [comment]
Can I see your code?

**Comment by TorakikiSan** [comment]
I add the code in the previous message, I pressed "send" by mistake

**Comment by olton** [comment]
Add class to figure element

**Comment by TorakikiSan** [comment]
I change the FIGURE tag, but nothing seem changed!

`      <FIGURE class="bd-gray bd-red-hover border-size-3 text-center">
`
![SharedScreenshot](https://user-images.githubusercontent.com/37299746/69580620-33384d80-0fd5-11ea-854e-16030661a9fe.jpg)

**Comment by olton** [comment]
`<FIGURE class="border bd-gray bd-red-hover border-size-3 text-center">`

**Comment by TorakikiSan** [comment]
Great work!

I often have difficulty arranging the correct values in the "class" tag, so thank you very much!
