### ISSUE TITLE
Assigning value to role=input and role=select

### ISSUE THREAD

**Issue by ojosojo** [olton/Metro-UI-CSS#1468]
Hi.
Ok so I found out how to set and get a value to a **role=select** :
`$('#myselect').data('select').val(1);  // set`
`let myvar = $('#myselect').data('select').val();   // get`

Then when I wanted to assing a value to an  **role=input** I was expecting to do it like this :
`$('#myinput').data('input').val("Some value for the input");  // set`
`let myvar = $('#myinput').data('input').val();  // get`

But I am getting this error for **role=input** :
_VM5328:1 Uncaught TypeError: Cannot read property 'val' of undefined_

I can't find any information about this in the documentation, can someone please help me to propoerly get / set a value.  Thanks .

Here is the HTML code  : 

```
<input id="myinput" type="text" data-role="input" data-prepend="My Input : " />

        <select data-prepend="My Select : " data-role="select" id="myselect" >
            <option value="1">Valor 1</option>
            <option value="2">Valor 2</option>
            <option value="3">Valor 3</option>
        </select>
```

**IMPORTANT NOTE:   I am not using jQuery**

**Comment by olton** [comment]
https://metroui.org.ua/input.html#_input_methods, for input, you must use attribute value
https://codepen.io/olton/pen/PoorzWz

**Comment by ojosojo** [comment]
Thank you, it worked.  👍 👍   Have a great Day !!
