### ISSUE TITLE
Implementation of clear button on data-role="taginput" 

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1469]
If possible, the implementation of the clear button on data-role = "taginput" would be really useful.

If there are many elements (see image) to delete the field, without having to define a script associated with a button, you have to delete them one by one.

![SharedScreenshot](https://user-images.githubusercontent.com/37299746/69899193-3b8ce180-1363-11ea-8e25-c0e3e47a01bd.jpg)

Thank's!

**Comment by olton** [comment]
### 4.3.5
##### Metro 4
+ [x] Tag input: change `trigger` defining 
+ [x] Tag input: add `clear button` with attributes `clearButton`, `clsClearButton`, `clearButtonIcon`  
+ [x] Tag input: add attributes `clsComponent`, `clsInput`  
+ [x] Tag input: add event `onClear`

**Comment by olton** [comment]
![2019-12-03-14-45-20](https://user-images.githubusercontent.com/365108/70052247-8dd83780-15db-11ea-8608-fa7ead45750b.png)

**Comment by TorakikiSan** [comment]
Great work, as usual!

Thank's Olton!

**Comment by TorakikiSan** [comment]
Hi Olton!

If can be useful to you, the clear button seems off-center

![SharedScreenshot](https://user-images.githubusercontent.com/37299746/70137558-75752500-168e-11ea-8ba3-d9da43e49a5e.jpg)

Thank's!

**Comment by olton** [comment]
Maybe need to update CSS? 
![2019-12-04-15-23-48](https://user-images.githubusercontent.com/365108/70146148-4ff61480-16aa-11ea-91cf-ff682349aa03.png)

**Comment by TorakikiSan** [comment]
Forget to say, I use class="input-small" for field using 

```
 * Metro 4 Components Library v4.3.5  (https://metroui.org.ua)
 * Copyright 2012-2019 Sergey Pimenov
 * Built at 03/12/2019 14:42:42

Thank's!
```

**Comment by olton** [comment]
for small and large I will add styles tomorrow. Unfortunately, I feel bad about myself.

**Comment by TorakikiSan** [comment]
I'm very sorry.
First comes health; job comes later.

**Comment by olton** [comment]
I added the required styles for small and large sizes

**Comment by TorakikiSan** [comment]
Perfect!

Very Thank's
