### ISSUE TITLE
Metro UI - Datatables Visual Conflict

### ISSUE THREAD

**Issue by TomCorr** [olton/Metro-UI-CSS#1471]
Hi, I have been using datatables since metro 3, they were very good working together, now i have updated to metro 4 and since i need fixed table header and/or ScollY capacity (unfortunately not supported in Metro Tables yet). But when the datatable renders with these options,the whole table is misaligned and all the controls are all over the place.

![image](https://user-images.githubusercontent.com/57960665/70078010-8ad34c00-15c7-11ea-97ef-9222a15e573c.png)

If i remove Metro CSS file, datatables work perfectly, but as i use Metro in all my pages this becomes a problem.

I will add my JS Bin for reference. 
http://live.datatables.net/luyuqune/2/edit?html,css,js,console,output 

I hope there is a solution or workaround.

Thank you in advance.

**Comment by olton** [comment]
to support `datatables`, you must add additional css file from CDN, 
 `https://cdn.metroui.org.ua/v4/css/metro-third.css` or download this file from github

**Comment by TomCorr** [comment]
I already have that css in my bundle, i checked in JS Bin i sent you and my production code and still no difference.

**Comment by TomCorr** [comment]
DataTables helped me with the table wrapper part.
_
> The issue is caused by Metro making the DataTables container a flex box. That's good, but it looks like the scrolling aspect has been overlooked. Add the following:
_

`div.dataTables_scroll {
  flex-grow: 2;
}`

but the search, filter and info controls are still misaligned.

http://live.datatables.net/luyuqune/7/edit

![image](https://user-images.githubusercontent.com/57960665/70150750-1d2f2a80-1670-11ea-8a31-aec114f32498.png)

**Comment by olton** [comment]
add
```
.dataTables_wrapper {
    display: block;
}
```

**Comment by TomCorr** [comment]
Extraordinary!
Thank you Sergey!
