### ISSUE TITLE
Wizard events 4.3.4

### ISSUE THREAD

**Issue by rooks-1** [olton/Metro-UI-CSS#1472]
I've look at the new subscription to events however, there are some things I've noticed:

```
    <div data-role="wizard" id="wizard">
        <section><div class="page-content">Page 1</div></section>
        <section><div class="page-content">Page 2</div></section>
        <section><div class="page-content">Page 3</div></section>
        <section><div class="page-content">Page 4</div></section>
        <section><div class="page-content">Page 5</div></section>
    </div>
```
```

   <script>
        $("#wizard").on("page", function (index, page, wizard) {
            console.log(index);  //returns object
            console.log(page);   //returns undefined
            console.log(wizard); //returns undefined
        });
    </script>
```

Is this correct behavior or am I missing something?

The following events doesn't appear to work
-  **beforeprev**
-  **beforenext**

```
$("#wizard").on("beforeprev", function (index, page, wizard) { 
  //tried with before-prev as well
});
```

Many thanks

**Comment by olton** [comment]
For `onBeforePrev` and `onBeforeNext` you must use defining function with attributes `data-on-before-prev`, `data-on-before-next`

**Comment by rooks-1** [comment]
Can I request both onBeforePrev and onBeforeNext be able to subscribe to events programmatically without using data-*-before-* in HTML code.

I'm trying to update our Metro pre 4.3 code to the latest version using angular but stumbled into some issues.

Much appreciated.

**Comment by olton** [comment]
The purpose of these events is to allow or prohibit page navigation. In essence, these are pseudo-events that must necessarily return true or false. Therefore, you can’t subscribe to them, they can only be determined.
