### ISSUE TITLE
Accordion showing last frame content in error

### ISSUE THREAD

**Issue by CoveTechnologyAus** [olton/Metro-UI-CSS#1473]
Hi
I have noticed that if the frames and their associated content are dynamically created then the last frame shows the its content even if it is not active.

I have ensured that the last frame does not have an "active" class attached (in fact none of the frames do as I want them all the be collapsed on page load). The chevron also show as if the frame is collapsed yet the content is showing.

If I click the frame header twice (one to "activate" it and another time to collapse it), the content does in fact hide as expected, it is just on the initialization with dynamic content that the last frame is showing the content.

NOTE: All the other frames have their content collapsed on initial load as expected.

Any ideas on what I could do here? Is there someway to "refresh" an arbitrary frame by id so I can force it to hide the content after page load.

Thanks in advance.

**Comment by olton** [comment]
Create your code on codepen.io
