### ISSUE TITLE
data-role="list", the cards are still ordered

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1475]
Hi Olton!

See the example:

(https://codepen.io/TorakikiSan/pen/EeyWmp)

The query I execute returns the records ordered by year, but in the example in the link they are sorted by description (first line) as if the `data-sort-class` and `data-sort-dir` attributes were still automatically defined, while in the documentation these seem be optional.

Thank's!

**Comment by olton** [comment]
If You are not defined sort options, List will use item.textContent property of each element LI

**Comment by TorakikiSan** [comment]
And are they sorted by that value?
If yes, is it possible to have them not sorted?

Thank's!

**Comment by olton** [comment]
### 4.3.5
+ [x] List: add attribute `data-sort-initial` to sorts on create component

Set attribute to `false` to disable initial sorting

**Comment by TorakikiSan** [comment]
Hi Olton!

With `data-sort-initial="true"` all is ok! (first image)

![SharedScreenshot1](https://user-images.githubusercontent.com/37299746/70470656-cee4b600-1acb-11ea-8296-3f3da70dccaf.jpg)

With `data-sort-initial="false"` the LIST respect the original sort, but the page is stuck (second image)

![SharedScreenshot](https://user-images.githubusercontent.com/37299746/70470769-13705180-1acc-11ea-84dd-f2b142267ffc.jpg)

With

```
> Metro 4 - v4.3.5. Built at: 09/12/2019 11:27:42 metro.js:3958:16
> m4q - v1.0.4. Built at 24/11/2019 13:28:24

```

**Comment by olton** [comment]
fixed. Check it please

**Comment by TorakikiSan** [comment]
Perfect, works great!

Thank's Olton!
