### ISSUE TITLE
Calendar Picker dialog mode overlay error

### ISSUE THREAD

**Issue by rooks-1** [olton/Metro-UI-CSS#1478]
When Calendar Picker is set in dialog mode, if clicked on the overlay, it is removed however, the calendar remains.

Only when a date is picked the calendar is removed.

`<input type="text" data-role="calendarpicker"  data-dialog-mode="true">`

Tested using Metro 4.3.4 in Chrome

**Comment by olton** [comment]
fixed in 4.3.5 thx
