### ISSUE TITLE
Appbar Collapse not working

### ISSUE THREAD

**Issue by fugaku** [olton/Metro-UI-CSS#1479]
Hi,

I'm trying to use Metro 4.3.4 and also using the Nav-View and Appbar that I got from the Pandora template.

It seems the Collapse menu where you can click the Username and it will drop down another menu (Profile, Sign Out, etc) is not working.
Clicking the username does nothing. 
Is it perhaps something to do with Pandora still using Metro 4.2.x and with Metro 4.3.x it's different now?

I tried to replicate the issue at codepen.
https://codepen.io/fugaku/pen/WNbEeNx ?

**Comment by olton** [comment]
Thank you. I updated Pandora to using with latest (4.3.5) version of Metro 4. Also, Pandora now works correctly with Metro 4 (4.3.4)
