### ISSUE TITLE
Popover not hiding on click

### ISSUE THREAD

**Issue by gwatkins1957** [olton/Metro-UI-CSS#1480]
**Describe the bug**
When data-popover-hide="0" the popover is not hiding when clicked

**To Reproduce**
`<button class="button m-1" data-role="popover"
    data-popover-text="Click Me to close!"
    data-popover-position="top"
    data-popover-hide="0"
    data-close-button="false"
>
    Hover me
</button>`

**Expected behavior**
The popover should hide when clicked

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Metro Version  4.3.4

**Comment by olton** [comment]
You must enable close button

**Comment by gwatkins1957** [comment]
Thanks.

You might want to update the Guide for this component. It states……

Attribute data-popover-hide is responsible for closing popovers. If a value for this attribute more then zero, popovers auto-hiding after milliseconds defined in this attribute. If this value is zero, popover can be closed when user click on popover.

Greg Watkins
Digital Speech Systems
Work: 972-235-2999 ext 133
Cell: 214-455-4814

**Comment by gwatkins1957** [comment]
Thanks

**Comment by olton** [comment]
Thank you.
`TODO: Need update docs for closing popover`
