### ISSUE TITLE
Populate select options from json.

### ISSUE THREAD

**Issue by gwatkins1957** [olton/Metro-UI-CSS#1481]
I need to populate the options of a select element from json data when a function is called. It works if I don't set the attribute data-role ="select" but when that attribute is set no options are shown. What is the correct way to remove the current options and then add the desired options?

Here is my code to add the options
`
function getSites()
{
companyID = document.getElementById("companyID").value;
if (companyID)
{
	select = document.getElementById("siteID");
	addOption(select,"Select a site","");
	$.getJSON('get_sites.asp?Company_ID=' + companyID,function(data)
	{
		$.each(data.sites, function(i,data)
		{
			siteID = data.value;
			siteName = data.text;
			addOption(select,siteName,siteID);
		});
	});
}
}

function addOption(selectbox,text,value)
{

var optn = document.createElement("OPTION");
optn.text = text;
optn.value = value;
selectbox.options.add(optn);

}

`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Metro Version [ 4.3.4]

**Comment by olton** [comment]
https://metroui.org.ua/examples.html - Select in Runtime
https://github.com/olton/Metro4-Docs/tree/master/public_html/examples/ajax

**Comment by gwatkins1957** [comment]
Thanks and Happy New Year.

Greg Watkins
Digital Speech Systems
Work: 972-235-2999 ext 133
Cell: 214-455-4814
