### ISSUE TITLE
Using NPM install i am getting this error

### ISSUE THREAD

**Issue by raghunath004** [olton/Metro-UI-CSS#1482]
**Describe the bug**
metro.min.js:1 Uncaught SyntaxError: Unexpected token '<'

**To Reproduce**
class App extends Component {
	render() {
		return (
			<div>
				<div data-role='window' className={'p-2'}>
					This is a simple window
				</div>
			</div>
		);
	}
}

**Expected behavior**
it works fine with cdn link

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser  chrome
 - Metro Version  4.3.4

**Smartphone (please complete the following information):**
 - Metro Version [e.g. 4.3.3]

**Additional context**

**Comment by olton** [comment]
Check your import directive

**Comment by raghunath004** [comment]
> 
> 
> Check your import directive

i installed with npm (metro4-dist) directory. my path in <head> tag
 <link
			rel="stylesheet"
			href="../node_modules/metro4/build/css/metro-all.min.css"
		/>

and in <body> tag
<script src="../node_modules/metro4/build/js/metro.min.js"></script>

and i imported in app.js 
import '../node_modules/metro4/build/css/metro-all.min.css';

this is return code 
<div
						data-role='window'
						data-icon="<img src='images/location.png'/>"
						className={'p-2'}
					>
						Use image to create window icon.
					</div>

**Comment by olton** [comment]
You must use import for js module
