### ISSUE TITLE
Tiles control: When use tilegroup and not set fixsize, the behevour is not correct.

### ISSUE THREAD

**Issue by vincedan** [olton/Metro-UI-CSS#1483]
**Describe the bug**
for Tiles control, When use tilegroup and not set fixsize, the behevour is not correct.
**To Reproduce**
create tiles group without specifying the fixsize.

<pre><code class="html">
   &lt;div class="tiles-grid tiles-group" data-group-title="General"&gt;
  &lt;a href="https://github.com/olton/Metro-UI-CSS"
   data-role="tile" class="bg-indigo"&gt;
   &lt;span class="mif-github icon"&gt;&lt;/span&gt;
   &lt;span class="branding-bar"&gt;Github&lt;/span&gt;
   &lt;span class="badge-bottom"&gt;30&lt;/span&gt;
   &lt;/a&gt;
   &lt;div data-role="tile" class="bg-cyan"&gt;
   &lt;span class="mif-envelop icon"&gt;&lt;/span&gt;
   &lt;span class="branding-bar"&gt;Email&lt;/span&gt;
   &lt;span class="badge-bottom"&gt;10&lt;/span&gt;
   &lt;/div&gt;
   &lt;div data-role="tile" class="bg-orange" data-size="wide"&gt;
   &lt;span class="mif-chrome icon"&gt;&lt;/span&gt;
   &lt;span class="branding-bar"&gt;Chrome&lt;/span&gt;
   &lt;/div&gt;
   &lt;div data-role="tile" data-size="small"&gt;
   &lt;span class="mif-apple icon"&gt;&lt;/span&gt;
   &lt;/div&gt;
   &lt;div data-role="tile" data-size="small" class="bg-red"&gt;
   &lt;span class="mif-bell icon"&gt;&lt;/span&gt;
   &lt;/div&gt;
   &lt;div data-role="tile" data-size="small" class="bg-teal col-1 row-6"&gt;
   &lt;span class="mif-windows icon"&gt;&lt;/span&gt;
   &lt;/div&gt;
   &lt;div data-role="tile" data-size="small" class="bg-brown col-2 row-6"&gt;
   &lt;span class="mif-wind icon"&gt;&lt;/span&gt;
   &lt;/div&gt;
   &lt;div data-role="tile" class="bg-cyan"&gt;
   &lt;span class="mif-table icon"&gt;&lt;/span&gt;
   &lt;span class="branding-bar"&gt;Tables&lt;/span&gt;
   &lt;/div&gt;
   &lt;/div&gt;
   </code></pre>

**Expected behavior**
when not set fixsize, the tiles should display from left to right, if overflow, then put the rest tiles to the second row.

in IE11, it's good as expected. 
but in chrome and Edge, it is not correct.

 
**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome, Edge]
 - Metro Version [e.g. 4.3.5]

**Comment by olton** [comment]
create your code example on codepen.io

**Comment by vincedan** [comment]
[metrol tile sample](https://metroui.org.ua/examples/tiles/start.html), just remove class "size-1" or "size-2" in tiles-grid. it means no fix size for tilegroup. but it is fixed. for small tile just one tile, and for medium, two tiles a row.

**Comment by vincedan** [comment]
change witdh of tile-group from default setting :auto to 
`.tiles-group {
    width:100%;
}`
will solve the issue.
