### ISSUE TITLE
Window component on Drag move outside browser

### ISSUE THREAD

**Issue by paloky** [olton/Metro-UI-CSS#1485]
Hi.
I use the next simple code for a "window" component.

```
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
	<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css">	 
</head>
<body>
<div id="container">
	<div id="0001" class="p-2"
		data-role="window"
		data-title="win_title"
		data-resizable="true"
		data-draggable="true"
		data-width="300"
		data-height="200"
		data-top="50"
		data-left="50"
		data-shadow="true"
		data-btn-close="false"
		data-btn-min="false"
		data-btn-max="false">
</div>	
	<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>		
</body>
</html>
```

When I drag the "window", this it's move to upper of screen, outside of browser.
**This only occurs if I put the "window" component inside another DIV.** In this example, inside "container" DIV.
If I remove this DIV, works fine.

How can I put a "Window" inside a "DIV" container ??

**Comment by olton** [comment]
Check container height

**Comment by paloky** [comment]
Thank's a lot.
I change the container div with:
`<div id="container" style="height:100vh">`
Now works fine.
Thank Sergey.
