### ISSUE TITLE
Metro 4.3.5 NavView not working

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1487]
Hi Olton!

With the last Metro 4.3.5, the NavView component does not work, while, without changing anything in the HTML code, with the old version (JQuery 3.4.1 + Metro 4.2.48), it works correctly.

See the CodePen

https://codepen.io/TorakikiSan/pen/EeyWmp

The button that opens / closes the component in the upper left corner is not displayed.

Did I make mistakes in the code?

Thank's!

**Comment by olton** [comment]
1) Change `data-expanded` to `data-expand`
2) AppBar closes the pull button. Add class `z-model` to `navview-pane`

**Comment by TorakikiSan** [comment]
Perfect, works!

Thank's Olton!
