### ISSUE TITLE
data-role="select" not getting focus on tab click

### ISSUE THREAD

**Issue by ojosojo** [olton/Metro-UI-CSS#1488]
**Description:**
Can't focus on a data-role="select" to select an option.

**Steps:**
I can't use codepen or jsfiddle as they won't render correctly so where is a basic example :
```

 <input type="text" data-role="input" data-prepend="Marca mcía.:" id="mercancia">     
<select data-role="select" data-prepend="País" id="pais">
          <option value="CAN">CANADA</option>
          <option value="MEX">MEXICO</option>
          <option value="USA">ESTATUS UNIDOS</option>
        </select>
 <input type="text" data-role="input" data-prepend="Origen:" id="origen">     


```
**Expected behavior**:
When focused on input **mercancia** then pressing the TAB key I would expect that select **pais** would obtain focus insted input **origen** gains the focus.

**Desktop**
 - OS: macOS Catalina 
 - Browser : Chrome 
 - Metro Version : 4.3.5

**Additional context**
Im creating a form filling app

**Comment by olton** [comment]
I added focus state, but now I need to add select control from the keyboard.

**Comment by ojosojo** [comment]
> I added focus state, but now I need to add select control from the keyboard.

I appreciate your help. Thanks for considering my request.

**Comment by ojosojo** [comment]
Hi, any advance on this issue ?

**Comment by olton** [comment]
focus work in 4.3.6

**Comment by ojosojo** [comment]
Ok confirmed... awesome ! . Is it possible that : when focused the select it opens the list of options and use UP and DOWN keys to select an item ?

Thanks Mr. Sergey

**Comment by olton** [comment]
working on implementation
