### ISSUE TITLE
please add rtl features

### ISSUE THREAD

**Issue by MohammadReza1994** [olton/Metro-UI-CSS#1489]
Hello.
Your library does not fully support the rtl feature.
Please add this feature to make many developers happy in the world.
Because your library is not compatible with rtl, your library is almost unused in many countries, such as Iran, Saudi Arabia, and ... .
In the css files of this library, there is a file called metroui-rtl.css that is useless.
Please give some thought to right-to-left languages.

Thank You A Lot.

**Comment by olton** [comment]
Thank you for your interest in Metro 4. Please specify the components for which you want to add RTL support.

**Comment by MohammadReza1994** [comment]
Almost all components!
Everything left to right must be turned right to left.
This link is coreui admin template: [LINK](https://coreui.io/demo/3.0-rc.0/rtl/#main.html) that support rtl.
As you can see everything is right to left.
It is better to add a rtl class to the body tag whenever we want the right to be left، Then we can write programs that use both styles.

**Comment by olton** [comment]
you can add attribute `dir=rtl` to  most elements to enable rtl support

**Comment by olton** [comment]
Please specify specifically for which components rtl support should be added. One issue per component.
