### ISSUE TITLE
Problem with the "distances" between DIVs

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1490]
Hi Olton!

Example on
https://codepen.io/TorakikiSan/pen/EeyWmp

Every single row in the table is inside a DIV.
Not using classes of type m * or p * (margin or pad) why is there so much distance between one line and another instead of being all attached?

Of course, I use Metro last official version.

Thank's

**Comment by olton** [comment]
class `table ` has a margin, and class `cell-*` has a paddgin. Remove it.
```
.table, [class*=cell-] {
  margin: 0;
  padding: 0
}
```
