### ISSUE TITLE
Show "dialog" on FullScreen Browser mode

### ISSUE THREAD

**Issue by paloky** [olton/Metro-UI-CSS#1491]
Hi.
I have a "window" components that I show in a FullScreen mode on browser.
This "windows" have a custom button and in the push callback call a JS function, and show a "dialog" with the next code.
```
Metro.dialog.create({
		title: "Delete",
		content: content_str,
		clsDialog: "warning",
		actions: [
			{
				caption: "Yes",
				cls: "js-dialog-close alert",
				onclick: function()
				{
					//alert("You clicked Agree action");
				}
			},
			{
				caption: "No",
				cls: "js-dialog-close",
				onclick: function()
				{
					//alert("You clicked Disagree action");
				}
			}
		]
	});
```

This all works find, but only in normal screen mode.
When I put the browser in full Screen, the dialog don't apears. (Apears behind the fullScreen.  Apears when I close the fullscreen mode).

How can I configure the "dialog" to be displayed in FullScreen mode.

Thank's a lot.

**Comment by olton** [comment]
Please respect my time. If for some reason your code does not work or you think that it does not work correctly, you do not need to post a sheet of code here. Describe the problem in detail and post an example of your code on codepen.io

**Comment by paloky** [comment]
I'm so sorry Olton.
All respect for you and your time. (Perhaps a forum would be better for these types of questions.)
It may not be a Metro problem, but I'm new to HTML/JS and I'm a little lost in some things.

The Problem:
The "dialog" component is not displayed in full screen. It is hidden behind when you reset the screen size.
https://codepen.io/paloky/pen/QWwojGj

Thank you very much.

**Comment by olton** [comment]
The full-screen mode has a bigger z-index value than a dialog.
@zindex-modal:              1050; // Used in dialog
@zindex-fullscreen:         2147483647; // Used for full screen mode
