### ISSUE TITLE
Problem with table sorting in date format using data-format-mask

### ISSUE THREAD

**Issue by josejovi** [olton/Metro-UI-CSS#1492]
Hi, thank you for your outstanding work

I have a problem using the table sorting feature in date format. I want to use 'd-m-Y' for the date format, but the data-format-mask or data-formatMask doesn't work for me. while I can overcome this problem by replacing a few lines of code in the metro.js file as shown below

![Annotation 2020-01-30 213855](https://user-images.githubusercontent.com/38583603/73459952-420ef800-43aa-11ea-8fd3-3f2193eb16dc.png)

I was wondering if I was wrong in implementing the sorting feature or indeed there were a few bugs in this feature. thank you in advance for all your efforts in developing this great framework

**Comment by olton** [comment]
How are you define a table component?

**Comment by olton** [comment]
How are you define a table component? Show how your dates are displayed in the table.

**Comment by josejovi** [comment]
![new](https://user-images.githubusercontent.com/38583603/73461942-95367a00-43ad-11ea-8b2c-a45c9f42fcea.png)

I tried to change the value in data-format-mask, but still did not give any impact

**Comment by olton** [comment]
Thank you. I fix this in 4.3.6. You can get it and check from here https://github.com/olton/Metro-UI-CSS/tree/4.3.6

**Comment by josejovi** [comment]
Awesome !
Thank you so much
