### ISSUE TITLE
List search and sort doesn't appear to work

### ISSUE THREAD

**Issue by marajin** [olton/Metro-UI-CSS#1494]
I've recently been reworking a project to utilise the newest version of MetroUI4 (v4.3.5) compared against a version roughly 1 year old. So far it's being going great, excellent work on the continued development by the way. Unfortunately I can't for the life of me spot the reason causing this issue, but I simply cannot get my "List" component to search and sort. It functioned fine previously. 

It grabs the JSON external data and renders as expected, just fails to sort when the buttons are clicked and returns a blank list if anything is entered into the search box. Find attached an example JSON file (Data modified for data protection reasons) and the HTML snippet for the List.
[test.json.txt](https://github.com/olton/Metro-UI-CSS/files/4150161/test.json.txt)
[html snippet.txt](https://github.com/olton/Metro-UI-CSS/files/4150162/html.snippet.txt)

**Comment by marajin** [comment]
Just attaching a couple of screenshots that show default rendering vs the blank results when searching.
![MUI4 List Screenshot 1 - Renders correctly](https://user-images.githubusercontent.com/6208407/73690243-d5f10480-46c7-11ea-86a0-78b8c5e4d684.JPG)
![MUI4 List Screenshot 2 - Blank results on a search that should yield 2 matches](https://user-images.githubusercontent.com/6208407/73690244-d5f10480-46c7-11ea-8c32-50e67799d792.JPG)

**Comment by olton** [comment]
1) use `Metro.getPlugin(...)` to access to component API
```
function sortList(col, dir) {
    Metro.getPlugin('#students', 'list').sorting(col,dir,true);
}
```
2) add classes `student-surname`, `student-dob` into the appropriate divs
```
"template": "<a href='<%this.student_id%>/'><div class='icon-box bg-amber'><div class='cover bg-darkAmber fg-white'><img height=90px width=90px src='<%this.img_src%>' alt='Student Image'></div><div class='content p-2 **student-surname**'><div><%this.student_surname%>,<br><%this.student_forename%></div><div class='text-upper text-bold text-lead **student-dob**'><%this.student_dob%></div></div></div></a>"
```

**Comment by marajin** [comment]
Hi Olton,

Thanks for the quick response. I'll give it a shot in a short while. You may want to reflect the changes in the documentation too when you get chance. I did not see the examples under Lists utilise Metro.getPlugin() at all?

**Comment by olton** [comment]
https://metroui.org.ua/components-api.html

**Comment by marajin** [comment]
Sure, however https://metroui.org.ua/list.html contains an example that does not use Metro.getPlugin(). That's what threw me for a loop on this one.

Thanks again for your help. It's working perfectly now that's sorted :)

**Comment by chwahab** [comment]
Metro.getPlugin('#all-list','list')._createItemsFromHTML()
