### ISSUE TITLE
Tag input autocomplete

### ISSUE THREAD

**Issue by IvanVasquez** [olton/Metro-UI-CSS#1500]
Hi, I would like to have the autocomplete function working with a tag input, similar to this:
https://www.jqueryscript.net/demo/Tags-Input-Autocomplete/
![Autocomplete tagInput](https://user-images.githubusercontent.com/3309201/74347862-f88db800-4d6e-11ea-864e-5b1c1c44f267.png)
I know I could use a select, but I want a simple way for the user to add a value while being able to use the already stored values.
Thanks

**Comment by olton** [comment]
https://codepen.io/olton/pen/xxOvoLe?editors=1001
