### ISSUE TITLE
accordion menu

### ISSUE THREAD

**Issue by alri** [olton/Metro-UI-CSS#1502]
hello .
i can not use multi level sub menu in accordion menu in ui template or admin template  . Does this feature exist? Or I couldn't find it
thanks

**Comment by olton** [comment]
Component Navview not support multi-level submenu.

**Comment by alri** [comment]
Some programs are 3-step
package - sub package - curd action . for example blog - content - curd
and we can not use Metro ui in our project :(  im sooooooooooooooooooooooooo sad

**Comment by olton** [comment]
create example of your problem code on codepen.io

**Comment by alri** [comment]
like this :
[example](https://codepen.io/alri66/pen/zYGqLvG)

**Comment by olton** [comment]
You can use Accordion component.
Read the dev guide on https://metroui.org.ua
