### ISSUE TITLE
Do not implicitly set the Content-type for AJAX requests.

### ISSUE THREAD

**Issue by Aschratt** [olton/Metro-UI-CSS#1503]
Hi again,

currently, when posting an AJAX request, the `Content-type` header is implicitly set to `application/x-www-form-urlencoded` when it's not set to something else by overwriting it, for example by a script like:

```js
$.ajax({ method: 'POST', url: 'postForm/', headers: { 'Content-type': '...' });
```

Even if it might be rare, *not* setting the  `Content-type` for requests is valid and causes the server to guess it. An example is uploading files in ASP.NET Core (and possibly other server-frameworks), where specifying the content type actually prevents the uploaded files from `FormData` objects not to be correctly recognized (see [here](https://stackoverflow.com/a/39281156/1254352) and [here](https://stackoverflow.com/a/51944424/1254352)). The issue is, that the form content type must be set to `multipart/form-data`, which requires a `boundary` setting, that normally is appended by the browser, but MetroUI does not do this (and it does not need to). 

jQuery thus offers to explicitly disable the `Content-type` property by setting a `contentType` property to `false`:

```js
$.ajax({ type: 'POST', url: 'postForm/', contenType: false });
```

M4Q, however implicitly assumes `application/x-www-form-urlencoded`, if no other value is provided. I tried several options for the `headers` field, like `undefined`, `false`, etc., but all result in the header beeing added, but set to an invalid value, whereas there should be a possibility to explicitly not set the header.

```js
// Ex 1: Results in `Content-type: false`
$.ajax({
    type: 'POST',
    url: 'postForm/'
    headers: {
        'Content-type': false
    }
});

// Ex 2: Results in `Content-type: undefined`
$.ajax({
    type: 'POST',
    url: 'postForm/'
    headers: {
        'Content-type': undefined
    }
});

// Ex 3: Results in `Content-type: application/x-www-form-urlencoded`
$.ajax({
    type: 'POST',
    url: 'postForm/'
    headers: {
    }
});
```

Currently I have to create my own `XMLHttpRequest` to post forms without an `Content-type` header. I tried also tried different fixes for the M4Q Ajax API and got it to work with the expected behavior. Here is the  [original code](https://github.com/olton/Metro-UI-CSS/blob/master/source/m4q/m4q.js#L2015-L2025) responsible for building the header:

```js
if (p.headers) {
    $.each(p.headers, function (k, v) {
        xhr.setRequestHeader(k, v);
        headers.push(k);
    });
}
if (!isGet(method)) {
    if (headers.indexOf("Content-type") === -1) {
        xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    }
}
```

The simple solution for this (that works with the examples 1 and 2 above) is to simply check the header key before setting the request header:

```js
if (p.headers) {
    $.each(p.headers, function (k, v) {
        if (v !== undefined && v) {
            xhr.setRequestHeader(k, v);
        }
        headers.push(k);
    });
}
```

This also allows to explicitly remove other headers from the request, however I don't think that other headers require such behavior, since `Content-type` is the only one receiving special treatment. The other option thus is to implement a similar parameter like jQuery does and check it before adding the default header:

```js
if (!isGet(method)) {
    if (headers.indexOf("Content-type") === -1 && p.contentType !== false) {
        xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    }
}
```

Thanks again in advance. 🙂

**Comment by olton** [comment]
Please create an issue to M4Q repo.

**Comment by olton** [comment]
Thanks, Added to M4Q 1.0.6

**Comment by Aschratt** [comment]
Thank you for the quick fix! I just installed and tested with a fresh build and everything works like charm.

And sorry for posting in the wrong repository. Next time, I know better. 😃
