### ISSUE TITLE
Calendarpicker issue on Firefox with all locales (except en-US)

### ISSUE THREAD

**Issue by bauzlefou** [olton/Metro-UI-CSS#1506]
Hello,
First, sorry for my poor English ...

here is a simple html code : 

[calendarpicker.txt](https://github.com/olton/Metro-UI-CSS/files/4263724/calendarpicker.txt)

Works perfectly on first load, but if i refresh the page , i get this message : 

_Error creating component calendarpicker metro.js:4109:32
TypeError: h[o] is undefined_

Works fine with data-locale="en-US" only ... I tested with meta "metro4:locale", with METRO.locale and with element.attr("data-locale","fr-FR"), same issue.

Browser : Firefox 71.0.1 (lastest) - no plugin 
OS :   Windows 10

Works fine on Chrome ;)

Any ideas ? 

Thanks.

ps : try [calendarpicker](https://metroui.org.ua/calendarpicker.html) with Firefox , and look for the "picker value" section, make refresh (one or more) and see the result(s) 😃

**Comment by olton** [comment]
All work fine for your code example
![calendarpicker](https://user-images.githubusercontent.com/365108/75482093-cc984680-59ac-11ea-88e1-efee26ec65b3.gif)

**Comment by olton** [comment]
This is a problem with the Firefox cache. I will look for how to fix it. I don’t have a quick solution now.

**Comment by olton** [comment]
Add to input attribute `autocomplete="off"`. This solved the problem.

**Comment by bauzlefou** [comment]
You're Awesome !!!
I never use this attribute, so i have will never thought about it.

Thank You.

**Comment by olton** [comment]
Thanks for this bug report. In 4.3.6 I added attribute `data-value` to set init input value. This solved the problem for FF. You can use `value` or `data-value` in your project to set init value, but for FF, if you use value attribute, you must add `autocomplete="false"` to input.

**Comment by bauzlefou** [comment]
I was stuck on this bug for 2 days, moreover, at the beginning I did not test on Chrome ... I thought it was because of my code 
if I had known I would have posted faster !
Thanks again ;)
