### ISSUE TITLE
Select into dialog not show values

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1507]
Hi Olton!

Example here:

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

If I click the button, the dialog is show, but the SELECT field not open.

I can't directly insert the fields when I create the Metro.dialog, because the SELECT field is dynamically generated by a script in PHP and the script is in a separate file, so I thought to create the hidden DIV and to load the HTML content of this DIV inside the dialog, but unfortunately not it works.

Any hint?

Thank's

**Comment by olton** [comment]
Use `template` instead of `div` for dialog content. 
```
<template id="input">
...
</template>
```

**Comment by olton** [comment]
https://codepen.io/olton/pen/OJVgRWb

**Comment by TorakikiSan** [comment]
Works!

Thank's again
