### ISSUE TITLE
WhatsApp icon

### ISSUE THREAD

**Issue by cizordj** [olton/Metro-UI-CSS#1510]
**Is your feature request related to a problem? Please describe.**

I could not find any WhatsApp icon listed in the [docs](https://metroui.org.ua/icons.html)

**Describe the solution you'd like**
To have the WhatsApp icon available just like other social networks have.

**Describe alternatives you've considered**
Well, I searched on the internet for PNG icons but they don't fit well like a native Metro Icon

**Additional context**
The WhatsApp button shown below has some bugs, sometimes it opens the icon instead of a new chat, but I think it happens because I placed an image tag inside a link tag.

![Captura de tela_2020-03-10_16-50-56](https://user-images.githubusercontent.com/32869222/76354226-d432e600-62f0-11ea-825f-0e5dea7ba3b4.png)

**Comment by olton** [comment]
Added in 4.3.7

**Comment by cizordj** [comment]
Thank you so much
