### ISSUE TITLE
Pagination for data-role="table" 

### ISSUE THREAD

**Issue by ojosojo** [olton/Metro-UI-CSS#1511]
Hello.
Is it possible to extend to have a "Skip to page" ?

When having thousands of rows it is complicated to arrive to a middle point page .

Regards.

**Comment by olton** [comment]
In 4.3.7
+ [x] Table: add `skip to page` functionality
+ [x] Table: add attributes `data-show-skip`, `data-table-skip-title`, `data-skip-wrapper`, `data-cls-table-skip`, `data-cls-table-skip-input`, `data-cls-table-skip-button`
+ [x] Table: add event `data-on-skip`

Event `data-on-skip` receives two arguments: `skipTo` and `skipFrom`. All arguments received as an integer.
