### ISSUE TITLE
data-append little glitch

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1512]
Hi Olton!

A very small glitch with the data-append attribute and the class = "input-small".

See at:

https://codepen.io/TorakikiSan/pen/EeyWmp

If the INPUT is normal, this is displayed correctly (MAX field), while if the "input-small" class is used, this is not centered in the field, but is displayed as if the field was of normal size.

Thank you

**Comment by olton** [comment]
Hi! I am in a hospital (problem with heart), I can see problem in a week or two.

**Comment by arjarn** [comment]
Take care of yourself Olton, take time for come back healthy.

**Comment by TorakikiSan** [comment]
I am very sorry for your problem.
Think about your health, there is always time for the rest.
Good luck

**Comment by olton** [comment]
Fixed in 4.3.7

**Comment by TorakikiSan** [comment]
Glad to see you're back!
