### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by jeorlie** [olton/Metro-UI-CSS#1514]
**Documentation request**
Sir I've been searching in the web for an offline documentation for this framework but I cannot find it.
I am checking the online docs but it consumes my limited data allocation. Can you provide an offline documentation sir? 

Many thanks. More power to your projects

**Comment by cizordj** [comment]
Sounds interesting

**Comment by olton** [comment]
https://github.com/olton/Metro4-Docs
