### ISSUE TITLE
Splitter Events

### ISSUE THREAD

**Issue by gunslingor** [olton/Metro-UI-CSS#1516]
Is there a way to detect the splitter change event or can this be tied to the window resize event? I need to resize a canvas inside the splitter when the splitter moves but do not see how; what events get exposed?

**Comment by olton** [comment]
```
<div data-role="splitter" 
        data-on-resize-start="..." 
        data-on-resize-stop="..." 
        data-on-resize-split="..." 
>...</div>
```
Signature for `onResizeStart`
```
Utils.exec(o.onResizeStart, [start_pos, gutter[0], prev_block[0], next_block[0]], element[0]);
```
Signature for `onResizeStop`
```
Utils.exec(o.onResizeStop, [stop_pos, gutter[0], prev_block[0], next_block[0]], element[0]);
```
Signature for `onResizeSplit`
```
Utils.exec(o.onResizeSplit, [pos, gutter[0], prev_block[0], next_block[0]], element[0]);
```

**Comment by olton** [comment]
In 4.3.7
+ [x] Splitter: added event `onResizeWindow`. 

You can setup this event with prop `data-on-resize-window` or event `$(...).on('resizewindow', ...)`

**Comment by gunslingor** [comment]
Thanks so much! Really loving this framework, would love to see some cool charts!

**Comment by patrickelectric** [comment]
Hi @olton! Thank you for this great work. 

I'm trying to use this feature with both:
https://github.com/olton/Metro-UI-CSS/blob/build-builder-conf/test/metro/js/metro.min.js
https://github.com/olton/Metro-UI-CSS/blob/4.3.7/test/metro/js/metro.min.js

And I failed to get the event, my snippet: 
```
<div id= "main-div" data-role="splitter" class="h-100" data-on-resize-window="console.log('potatooooo1')">
   <div id="editor-div" data-on-resize-window="console.log('potatooooo2')"></div>
   <div id="qml-div" data-on-resize-window="console.log('potatooooo3')"></div>
</div>

// and with
$("#main-div").on("resizewindow", function(event) {
    console.log(event)
})
$("#editor-div").on("resizewindow", function(event) {
    console.log(event)
})
$("#qml-div").on("resizewindow", function(event) {
    console.log(event)
})
```

**Comment by olton** [comment]
All works fine with 4.3.7 https://codepen.io/olton/pen/wvKEwoV

**Comment by patrickelectric** [comment]
Thanks! It works perfectly!
