### ISSUE TITLE
Metro Menu Start group title vertically

### ISSUE THREAD

**Issue by kszere** [olton/Metro-UI-CSS#1517]
**Is your feature request related to a problem? Please describe.**
Now example Metro Start available only one group on vertically. In Windows can more that 1. 
https://metroui.org.ua/examples/tiles/start.html

**Additional context**
<img width="624" alt="Zrzut ekranu 2020-04-3 o 21 00 54" src="https://user-images.githubusercontent.com/7155051/78395759-5fe91b00-75ee-11ea-86f5-2b794088172e.png">

**Comment by olton** [comment]
This is just a demonstration. If you need to do something differently, you will have to do it yourself, using the presented features and your additional styles and js code
