### ISSUE TITLE
Metro.validator.validate issue?

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1518]
Hi Olton and welcome back.

I'm trying to create a page where I can insert the data (the small daily expenses) which I will then insert in a sqllite table but without using the FORM tag, just call ajax.

The page and the ajax script:

https://codepen.io/TorakikiSan/pen/EeyWmp

As you can see, for each field I also inserted the data-validate tag which I then go to check in the script when I press the SUBMIT button with the Metro.validator.validate function

Correctly, the script checks (and possibly displays the error) for the first two fields, Item and Quantity, while considering the following fields valid even if the data-validate would indicate an error (try to leave the fields empty for example).

Where am I wrong?

Thanks

**Comment by olton** [comment]
Hi!
You must change `date-validate` to `data-validate`

**Comment by TorakikiSan** [comment]
OMG, shame on me.... I checked, checked, checked and checked again but I just didn't see the stupid mistake.

One last question: in data-validate, what is the difference between "number" and "float"? In the Price field I had "required float" and whatever value I entered (I tried, for example, "5" "5.60" "5.") I always got an error.

Thanks

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/e4b9209bdc0b4e198954935e12152b47c9459008/source/components/validator/validator.js#L1

**Comment by olton** [comment]
Hi! I extend `Utils.isFloat` function for this issue

> I always got an error for "5" "5.60" "5."

Now, for `required float`:
5 - `false` no decimal point
5.60 - `true`
5. - `false` no numbers after decimal point
1.0 - `true`
.1 - `true`

**Comment by TorakikiSan** [comment]
Many thank's Olton.

It's perfect!
