### ISSUE TITLE
Data Table Dynamic Handling

### ISSUE THREAD

**Issue by MoonArrow** [olton/Metro-UI-CSS#1519]
Hi,
Not sure if it will be classified as a bug or a new feature request but I will try to describ as precisely my 'issue'. As a global description, I am using table or lists to display information and to enable users to manipulate them. I am intensively using Filtering and Sorting capabilities. My table configuration is something like that 
```
    <table class="table striped row-hover subcompact table-border mt-4" id="mytableid"
    data-role="table"
    data-rows="25"
    data-rows-steps="25, 50, 100"
    data-search-fields="title"
    data-show-rows-steps="true"
    data-show-search="true"
    data-filter="true"
    data-filters-operator="and"
    data-table-search-title="Recherche :"
    data-show-activity="true"
    data-info-wrapper=".my-info-wrapper"
    data-pagination-wrapper=".my-pagination-wrapper"
    data-search-wrapper=".my-search-wrapper"
    data-rows-wrapper=".my-rows-wrapper"
    data-on-data-loaded="filterStatusLoadData()"
>
```
It works like a charm except for one thing: when I edit the data. On each line, I have a button to launch a lightbox to edit some of the information displayed. I succesfully been able to change the data displayed with functions like :
```
 $('#mytableidtr').each(function() {
    filter_string = $(this).find("td").eq(6).text();
    td_id = $(this).find("td").eq(2).text();
    old_name = $(this).find("td").eq(3).text();
    line_number = $(this).find("td").eq(0).text();

    if (td_id == last_id) {
      alert('FOUND id : '+td_id + ' for item'+old_name + ' with filter : '+filter_string);
      new_string = filter_string.replace('status-tobekept', 'found')

      $(this).find("td").eq(6).text(new_string);
  ...
```
This code change the display but when I change the sort method or I use the filtering, the data goes back to the original value. I think that the table object is keeping the data in its own data structure and I only change the DOM structure and not the internal values.

I looked for a way to change the data itself and found nothing. My current workaround is to use a JSON source and to reload the whole table when change is detected which is a very costly operation as the changes are mainly done by Ajax calls for the moment so with no page reload.

Did I miss something on the API ? Can this be considered as a bug ? Or can it be considered as a feature to add to be able to manipulate the internal data?

Thanks in advance for your valuable feedback.

*

**Comment by olton** [comment]
Hi! To update real data, you must use `updateItem` method.
https://github.com/olton/Metro-UI-CSS/blob/master/source/components/table/table.js#L1581

**Comment by MoonArrow** [comment]
Hi,

just a quick follow up. Thanks for the pointer Olton. It works like a charm. For those who get the same kind of things to do. the updateItem combined with a call to draw() do the trick perfectly well. I change now dynamically the value on a called overlayed window and the table is refreshed with new values and redisplay without reloading the page even if the search/filter criteria for that particular row have changed.

M.
