### ISSUE TITLE
Scheduler component

### ISSUE THREAD

**Issue by hashitha** [olton/Metro-UI-CSS#1521]
It would be great to have a scheduler component like this 
https://dhtmlx.com/docs/products/dhtmlxScheduler/

Maybe it is possible to add verticle layout to streamer component and a week/month

**Comment by olton** [comment]
Sorry, but In the near future, I’m unlikely to write such a large component, especially now that the project has virtually no financial support and therefore I can not devote much time to Metro 4, including the development of large and complex components.
