### ISSUE TITLE
Input + append + input-small

### ISSUE THREAD

**Issue by Autoflow** [olton/Metro-UI-CSS#1522]
**Describe the bug**
Appended buttons/data does not resize to .input-small or .input-small or .input-large

**To Reproduce**
<input class="input-small" type="text" data-role="input" data-append=".00%">
<input class="input-small" type="text" data-role="input" data-custom-buttons="customButtons">

**Expected behavior**
Appended data or buttons should render smaller or larger according to additional classes

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser firefox
 - Metro Version current version online

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1512

**Comment by Autoflow** [comment]
Sorry for that Olton.
Please stay healthy and take care!

**Comment by olton** [comment]
Hi! Thank you for this report. I fix it now `input` and `select` for using `append`, `prepend`.
