### ISSUE TITLE
Add update method to Select control to refresh after adding new values / options

### ISSUE THREAD

**Issue by marinbale2377** [olton/Metro-UI-CSS#1523]
The ability to populate the Select after the document will allow to provide better performance to the initial rendering of the page, when the number of options is very large.

Currently I have a project where the Select control has 4000+ options. If I add all the options when the initial document is loaded, the Select option takes a couple of seconds to prepare. I have experience a similar problem in the past when using the Chosen Jquery plugin for the same task.

I found that a very good solution is to start with an empty Select (no options) and after the document is loaded, used a Javascript options to read a JSON array of values to populate the select.  

For example, in Chosen JQuery plugins this is accomplish by triggering the chosen.updated method, that indicates to the control that the structure has change and that it needs to update the rendering of the control.

function loadSelectValues(el, path) {
   let dropdown = $(el).chosen();
   const curl = window.location + '/' + path;

   $.getJSON(url, function(date) {
      $.each(data, function(key, entry) {
         dropdown.append('<option value=" = entry.value = '">' = entry.name + '</option>');
      });

     $dropdown.trigger("chosen:updated");
   });
 } 
});

Because this is not currently possible with the Select my only workaround is to try to use CSS stylesheets to try to mimic the look and feel of Metro4 to the Chosen plugin. Would be great to be able to do it with a single library.

**Comment by olton** [comment]
use method `data` from select API https://github.com/olton/Metro4-Docs/tree/master/public_html/examples/ajax
