### ISSUE TITLE
File browser drop mode bug

### ISSUE THREAD

**Issue by zettabyte920** [olton/Metro-UI-CSS#1524]
**Describe the bug**
whene i reset the form i found that file browser drop mode still say "3 file selected" !.

**To Reproduce**
codepen: https://codepen.io/hossem/pen/pojNOYd

**Expected behavior**
whene i reset my form my file browser drop mode should be reset.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Metro Version: 4.3.4

**Screenshots**
![Capture](https://user-images.githubusercontent.com/63545160/79948127-8d014e80-8473-11ea-9fef-b0c39f244270.JPG)

**Comment by olton** [comment]
This bug fixed. Update Metro to latest release 4.3.6

**Comment by zettabyte920** [comment]
@olton  sorry but still the same after i update to  4.3.6! check my pen https://codepen.io/hossem/pen/pojNOYd

**Comment by olton** [comment]
Thanks, fixed in 4.3.7
