### ISSUE TITLE
GRID system: no GAP between columns

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1525]
Hi Olton!

Example at

https://codepen.io/TorakikiSan/pen/EeyWmp

It's a simple visualization divided by month of my expenses (in the example the values are not real) divided by category (the different colors).

I read the page at

https://metroui.org.ua/grid.html#_grid_system

but, as seen in the example, my GRID does not have the GAP between the columns.

Where am I wrong?

Thanks

**Comment by olton** [comment]
Hi, I removed the gaps for cells. You must set your own specified gups for cells for your needs.

**Comment by olton** [comment]
In 4.3.10 I added new classes for grid, row, cells: `gap-*`, where `*` is one of `0, 8, 16, 24, 32, 40` in pixels

#### Sets gap for all cells in the grid
```
<div class="grid gap-16">
...
</div>
```

#### Sets gap for all cells in a row
```
<div class="row gap-16">
...
</div>
```

#### Sets gap for cells in a row
```
<div class="row">
    <div class="cell-md-4 border gap-16">...</div>
    <div class="cell-md-4 border gap-0">...</div>
    <div class="cell-md-4 border gap-16">...</div>
</div>
```

Also, you can **combine** gaps defining for the grid, row, and cells.

**Comment by TorakikiSan** [comment]
Thank You very much Olton!
