### ISSUE TITLE
Date Picker Selection

### ISSUE THREAD

**Issue by Rodolfo-XDR** [olton/Metro-UI-CSS#1526]
### **Bug Description**
I don't really know if its a bug or its made on purpose. When you try to select a date, it doesn't select it directly, you need to simulate a phone scroll, in order to select it.

### **To Reproduce**
![image](https://user-images.githubusercontent.com/49254245/80513042-16b58e00-8944-11ea-973b-cdd69abe44f4.png)
**E.g.: You can't select the other years directly**

### **Expected behavior**
When you click the year, it must be selected directly, no need to scroll.

### **Desktop:**
 - OS: Windows
 - Browser Chrome
 - Metro Version 4.3.5

**Comment by olton** [comment]
yes, currently this component not support input data directly
