### ISSUE TITLE
SELECT - Option with an Empty value not properly selected

### ISSUE THREAD

**Issue by CmPi** [olton/Metro-UI-CSS#1527]
**Describe the bug**
Select box does not work with an option having a content and an empty value.

**To Reproduce**
< select name="iUpdate" class=input-small data-role="select" data-filter="false">
< option selected value="">(all)</ option>
< option value="1">Option A</ option>
< option value="2">Option B</ option>
</ select>

https://sandbox.org.ua/cmp/code/Vbp8DUYQbR

**Expected behavior**
"(all)" should be displayed 

**Desktop (please complete the following information):**
 - Metro Version4

**Smartphone (please complete the following information):**
Independant

data-add-empty-value and data-empty-value does not solve the issue

**Comment by olton** [comment]
at this time, select required value for options. You can use, for example, -1 to setup option.

**Comment by olton** [comment]
in 4.3.7
Select: add using an empty value for `option`. To use the empty value set attribute `data-use-placeholder="false"`

**Comment by olton** [comment]
```
<select name="iUpdate" class=input-small data-role="select" data-filter="false" data-use-placeholder="false">
      <option value="" selected>All</option>
      <option value="1">Option A</option>
      <option value="2">Option B</option>
</select>
```
