### ISSUE TITLE
Select is taking ages to reder

### ISSUE THREAD

**Issue by sbuysse** [olton/Metro-UI-CSS#1534]
Hello!

I switched from old Metro 2 to Metro 4 and I am facing one issue with the select, it takes a lot of time to render.

If you have 2500 items, which is possible to use without problem with some autocomplete plugins, it takes 7s to render on a core i7.

As you can see in render, it does call a lot of functions. 
![select](https://user-images.githubusercontent.com/24626051/81875780-5a81d780-9581-11ea-8bee-05b5cc4f6a10.png)

I haven't figured out if there is a way of speeding it up, but nothing fancy in my code.

Thanks for your great work!

**Comment by olton** [comment]
You can use method `data()` from select api to load options with ajax. Example https://github.com/olton/Metro4-Docs/tree/master/public_html/examples/ajax

**Comment by olton** [comment]
Thx for this feedback. I found a problem and resolve it. Please check it for 4.3.7

**Comment by olton** [comment]
Performance test https://pimenov.com.ua/demo/select-performance/

**Comment by sbuysse** [comment]
Hello,

Thanks for the fix. I pulled 4.3.7 to test it out, it indeeds reduce the load from 7 to 4s, but it is still very slow as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/24626051/81911660-eae60980-95cd-11ea-807c-5000a1beaabf.png)

**Comment by sbuysse** [comment]
I checked out the demo/performance test:
https://pimenov.com.ua/demo/select-performance/

It loads in 1.4s on Firefox/Fedora. 

I can find alternatives to the select in our environment, but 1.4s to load 4000 lines is quite slow :-/

**Comment by olton** [comment]
![2020-05-14-11-37-56](https://user-images.githubusercontent.com/365108/81912555-65ffed80-95d7-11ea-90e7-cb50b7329c45.png)

**Comment by olton** [comment]
developer console enlarge time on 2-3 times

**Comment by sbuysse** [comment]
I have no console opened, and on this machine it is still a core i7, but with an intel GPU.
Opening the select is very slugish on this machine.

![image](https://user-images.githubusercontent.com/24626051/81912926-8cba2600-95cf-11ea-9fab-622f78127bd4.png)

**Comment by olton** [comment]
In any case, reducing the time from 2500 options in 7 seconds to 4000 options in 1 second is a significant increase in speed.

**Comment by sbuysse** [comment]
Sure :)
But we have more than one in some pages, thus some performance impact. I will search for other solutions, thanks for your help.

**Comment by olton** [comment]
You can also try using the data-select-deferred = "1" attribute.  This will start the creation of select in a separate thread.

**Comment by sbuysse** [comment]
Thanks for the hint. I inserted the tag but it doesn't seam to really help yet, I'll look into it further (and ultimately try another component for these select boxes).
