### ISSUE TITLE
Input with data-prepend issue: The editable area starts at the middle.

### ISSUE THREAD

**Issue by viktorcoronel07** [olton/Metro-UI-CSS#1535]
![input issue](https://user-images.githubusercontent.com/38776706/81908003-3367ec00-95fb-11ea-8054-941ded6f60f0.PNG)
Input with data-prepend issue: The editable area starts at the middle. Not us re why in the examples in the page is working as expected. But in my project, the editable part starts n the middle.

Here's my code snippet:
` <tr style="height:45px">
                        <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Home Address:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                    </tr>`

**Comment by olton** [comment]
All works fine https://codepen.io/olton/pen/GRpXJKY check your code.

**Comment by viktorcoronel07** [comment]
> All works fine https://codepen.io/olton/pen/GRpXJKY check your code.

Hello! Thanks for the response. I copy and pasted your sample code in my project and the same thing happens. I am using the latest version of metro4 on ASP.net MVC.

**Comment by olton** [comment]
Maybe you use `text-align: center`?

**Comment by viktorcoronel07** [comment]
> Maybe you use `text-align: center`?

i didn't use that. i copy and pasted what you wrote in codepen. still the same issue.

**Comment by viktorcoronel07** [comment]
> > Maybe you use `text-align: center`?
> 
> i didn't use that. i copy and pasted what you wrote in codepen. still the same issue.

kinda strange. i copy and pasted my whole block "accordion" in codepen and it works correctly. what could be possibility wrong in my setup? do you have any ideas?

**Comment by olton** [comment]
Show your result html

**Comment by viktorcoronel07** [comment]
Sorry, my browser keeps on crashing when I try to attach an image. Can you check my first post? I have there a screenshot.

**Comment by viktorcoronel07** [comment]
![sampleoutput](https://user-images.githubusercontent.com/38776706/81918933-bdb74c80-9609-11ea-8b7e-a8469b52fe4d.PNG)

**Comment by olton** [comment]
Show your result HTML code, not image

**Comment by viktorcoronel07** [comment]
Apologies if my code is messy. This is my first time in doing front-end development :)
`

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <meta charset="utf-8" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <title>CBBC-MIS</title>
  |  
  | <link href="/Content/css?v=dY4m39e2Xz1O9nbGAFVpJ52U0M0FW4j7KeJ87gnre9M1" rel="stylesheet"/>
  |  
  |  
  |  
  |  
  | <link rel="icon" href="/images/cbbclogo.jpg">
  |  
  |  
  | </head>
  | <body class="metro h-vh-100">
  | <div class="SystemMessageBox">
  | <div class="SystemNotification" id="SystemNotification" data-role="infobox">
  | <span class="button square closer va-middle"></span>
  | <div class="info-box-content">
  | <h3>Notification</h3>
  | <table width="100%">
  | <tr><td>&nbsp;</td></tr>
  | <tr>
  | <td><div id="SystemMessage"></div></td>
  | </tr>
  | <tr><td>&nbsp;</td></tr>
  | <tr><td>&nbsp;</td></tr>
  | <tr>
  | <td style="text-align:right"><button id="SystemMessageButton" class="button secondary," onclick="$('#SystemNotification').data('infobox').close()">OK</button></td>
  | </tr>
  | </table>
  | </div>
  | </div>
  | </div>
  | <aside class="sidebar pos-absolute z-2"
  | data-role="sidebar"
  | data-toggle="#sidebar-toggle-3"
  | id="sb3"
  | data-shift=".shifted-content">
  | <div class="sidebar-header" style="background-color: white;">
  | <div class="avatar">
  | <img data-role="gravatar"
  | data-email="app.cbbcmis@outlook.com"
  | data-default="https://cbbcmis.com/images/user-default.png" data-size="80">
  | </div>
  | <span class="title fg-black">Viktor Coronel CMS</span>
  | <span class="subtitle fg-black">CORONEL, VIKTOR</span>
  | </div>
  | <ul class="sidebar-menu" style="background-color: ghostwhite">
  | <li><a href="/Home/Index"><span class="mif-home icon"></span>Home</a></li>
  | <li><a><span class="mif-dashboard icon"></span>Dashboard</a></li>
  | <li><a><span class="mif-users icon"></span>Membership</a></li>
  | <li class="divider"></li>
  |  
  | <li><a href="/DataExplorer/Home/Index"><span class="mif-database icon"></span>Data Explorer</a></li>
  |  
  |  
  | <li><a href="/Financials/Home/Index"><span class="mif-money icon"></span>Financials</a></li>
  |  
  |  
  | <li class="divider"></li>
  |  
  | <li><a><span class="mif-tools icon"></span>Settings</a></li>
  |  
  |  
  | <li class="divider"></li>
  | <li><a href="/System/ReleaseNotes"><span class="mif-note icon"></span>Release Notes</a></li>
  | <li class="divider"></li>
  | <form action="/Account/LogOff" class="navbar-right" id="logoutForm" method="post"><input name="__RequestVerificationToken" type="hidden" value="69QRfNOZjkWMKADHlgXkNW104KMhOGNbRHr0V7lBYdO9iH7fhYlXaaD7r91EZWNee4EAS7Tky9iiK7Cqyad8l2ggwUhMPWyBpLdozp_HMGyVY0mxyi6FztTqSn3oFX6g9Akg3A2" />            <li><a href="javascript:sessionStorage.removeItem('accessToken');$('#logoutForm').submit();"><span class="mif-exit icon"></span>Log off</a></li>
  | </form>
  | </ul>
  | </aside>
  | <div class="shifted-content h-vh-100 p-ab" id="spacontainer">
  | <div class="app-bar pos-absolute bg-red z-1" data-role="appbar">
  | <button class="app-bar-item c-pointer" id="sidebar-toggle-3">
  | <span class="mif-menu fg-white"></span>
  | </button>
  | </div>
  |  
  | <div class="container-fluid border-none">
  | <div class="grid w-100" style="height:90vh !important">
  | <div class="row h-100">
  | <div class="cell">
  |  
  |  
  |  
  | <h2>MemberManagement</h2>
  | <table>
  | <tr style="height:45px"> <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" style="text-align:left" data-prepend="Home Address:" data-clear-button-icon="<span class='mif-cancel'></span>"></td> </tr>
  | </table>
  |  
  | <div data-role="accordion" data-one-frame="true" data-show-active="true">
  | <div class="frame active">
  | <div class="heading">Basic</div>
  | <div class="content">
  | <div style="overflow-x:auto;">
  | <table style="width:100%;margin:auto">
  | <tr style="height:45px"><td colspan="3">&nbsp;</td></tr>
  | <tr style="height:45px">
  | <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Last Name:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="First Name:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Middle Name:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | </tr>
  | <tr style="height:45px">
  | <td width="30%" style='padding:2px;vertical-align:middle;'>
  | <div id="salutationdropdowncontainer">
  | <select data-role='select' name='salutationdropdown' id='salutationdropdown' style='vertical-align:middle' data-filter='false' data-prepend='Year:' />
  | </div>
  | </td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'>
  | <div id="civilstatusdropdowncontainer">
  | <select data-role='select' name='civilstatusdropdown' id='civilstatusdropdown' style='vertical-align:middle' data-filter='false' data-prepend='Year:' />
  | </div>
  | </td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'>
  | <table style="width:100%;margin:auto">
  | <tr>
  | <td style='width:60px;padding:2px 0px 2px 0px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="DOB:" style="width:60px"></td>
  | <td style='padding:2px 0px 2px 0px;vertical-align:middle;'><input type="text" data-role="calendarpicker"></td>
  | </tr>
  | </table>
  | </td>
  | </tr>
  | <tr style="height:45px">
  | <td width="30%" style='padding:2px;vertical-align:middle;'>
  | <div id="genderdropdowncontainer">
  | <select data-role='select' name='genderdropdown' id='genderdropdown' style='vertical-align:middle' data-filter='false' data-prepend='Gender:' />
  | </div>
  | </td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'>&nbsp;</td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'>&nbsp;</td>
  | </tr>
  | <tr style="height:90%" />
  | </table>
  | </div>
  | </div>
  | </div>
  | <div class="frame">
  | <div class="heading">Contact</div>
  | <div class="content">
  | <div style="overflow-x:auto;">
  | <table style="width:100%;margin:auto">
  | <tr style="height:45px"><td /><td /><td /></tr>
  | <tr style="height:45px">
  | <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Home Address:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | </tr>
  | <tr style="height:45px">
  | <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Office Address" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | </tr>
  | <tr style="height:45px">
  | <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Mobile Phone:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Home Phone:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | <td width="5%">&nbsp;</td>
  | <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Office Phone:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
  | </tr>
  | <tr style="height:90%" />
  | </table>
  | </div>
  | </div>
  | </div>
  | <div class="frame">
  | <div class="heading">Membership</div>
  | <div class="content">
  | <div class="p-2">Bitter turkey can be made tasty by brushing with...</div>
  | </div>
  | </div>
  | </div>
  |  
  |  
  | </div>
  | </div>
  |  
  | </div>
  | </div>
  |  
  |  
  |  
  |  
  |  
  |  
  | </div>
  |  
  |  
  | <script src="/bundles/metro?v=w5S3u9auyrD4AtiaPGHZT3Z4BJymNN2ugadMvmeLXuU1"></script>
  |  
  | <script src="/bundles/CBBCMIS?v=Yd1USrMGsJv3H1RumrEc_MpWy1kKozW-FEf9vT2QhsA1"></script>
  |  
  |  
  | <script type="text/javascript">
  |  
  | $(document).ready(function () {
  | GetCivilStatuses("civilstatusdropdowncontainer", "civilstatusdropdown", false, '999');
  | GetSalutations("salutationdropdowncontainer", "salutationdropdown", false, '999');
  | GetGenders("genderdropdowncontainer", "genderdropdown", false, 'U');
  | SessionReset();
  | });
  |  
  | </script>
  |  
  |  
  | <script type="text/javascript">
  | $(document).ready(function () {
  |  
  | SessionReset();
  |  
  | });
  | </script>
  |  
  | </body>
  | </html>
  |  

`

**Comment by viktorcoronel07** [comment]
Apologies if my code is messy. This is my first time to do front-end development

`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CBBC-MIS</title>

    <link href="/Content/css?v=dY4m39e2Xz1O9nbGAFVpJ52U0M0FW4j7KeJ87gnre9M1" rel="stylesheet"/>




    <link rel="icon" href="/images/cbbclogo.jpg">


</head>
<body class="metro h-vh-100">
            <div class="SystemMessageBox">
                <div class="SystemNotification" id="SystemNotification" data-role="infobox">
                    <span class="button square closer va-middle"></span>
                    <div class="info-box-content">
                        <h3>Notification</h3>
                        <table width="100%">
                            <tr><td>&nbsp;</td></tr>
                            <tr>
                                <td><div id="SystemMessage"></div></td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                            <tr><td>&nbsp;</td></tr>
                            <tr>
                                <td style="text-align:right"><button id="SystemMessageButton" class="button secondary," onclick="$('#SystemNotification').data('infobox').close()">OK</button></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <aside class="sidebar pos-absolute z-2"
                   data-role="sidebar"
                   data-toggle="#sidebar-toggle-3"
                   id="sb3"
                   data-shift=".shifted-content">
                <div class="sidebar-header" style="background-color: white;">
                    <div class="avatar">
                        <img data-role="gravatar"
                             data-email="app.cbbcmis@outlook.com"
                             data-default="https://cbbcmis.com/images/user-default.png" data-size="80">
                    </div>
                    <span class="title fg-black">Viktor Coronel CMS</span>
                    <span class="subtitle fg-black">CORONEL, VIKTOR</span>
                </div>
                <ul class="sidebar-menu" style="background-color: ghostwhite">
                    <li><a href="/Home/Index"><span class="mif-home icon"></span>Home</a></li>
                    <li><a><span class="mif-dashboard icon"></span>Dashboard</a></li>
                    <li><a><span class="mif-users icon"></span>Membership</a></li>
                    <li class="divider"></li>                    

                            <li><a href="/DataExplorer/Home/Index"><span class="mif-database icon"></span>Data Explorer</a></li>


                            <li><a href="/Financials/Home/Index"><span class="mif-money icon"></span>Financials</a></li>


                    <li class="divider"></li>

                            <li><a><span class="mif-tools icon"></span>Settings</a></li>


                    <li class="divider"></li>
                    <li><a href="/System/ReleaseNotes"><span class="mif-note icon"></span>Release Notes</a></li>
                    <li class="divider"></li>
                    <form action="/Account/LogOff" class="navbar-right" id="logoutForm" method="post"><input name="__RequestVerificationToken" type="hidden" value="7tXtdrdc1pXX4xzoveTfqvJYG2b8Qm-ePnlHmi5kXT9zutHuG0db4eFOoS-oGzUT5_ncDSuKFN2-OdFOzE8znya7FRmB4DzKMo-sRXrqGLMFxdBBHWLE-HcYiWF022kLit98ng2" />            <li><a href="javascript:sessionStorage.removeItem('accessToken');$('#logoutForm').submit();"><span class="mif-exit icon"></span>Log off</a></li>
</form>
                </ul>
            </aside>
            <div class="shifted-content h-vh-100 p-ab" id="spacontainer">
                <div class="app-bar pos-absolute bg-red z-1" data-role="appbar">
                    <button class="app-bar-item c-pointer" id="sidebar-toggle-3">
                        <span class="mif-menu fg-white"></span>
                    </button>
                </div>

                <div class="container-fluid border-none">
                    <div class="grid w-100" style="height:90vh !important">
                        <div class="row h-100">
                            <div class="cell">
                                


<h2>MemberManagement</h2>
<table>
    <tr style="height:45px"> <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" style="text-align:left" data-prepend="Home Address:" data-clear-button-icon="<span class='mif-cancel'></span>"></td> </tr>
</table>

<div data-role="accordion" data-one-frame="true" data-show-active="true">
    <div class="frame active">
        <div class="heading">Basic</div>
        <div class="content">
            <div style="overflow-x:auto;">
                <table style="width:100%;margin:auto">
                    <tr style="height:45px"><td colspan="3">&nbsp;</td></tr>
                    <tr style="height:45px">
                        <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Last Name:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="First Name:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Middle Name:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                    </tr>
                    <tr style="height:45px">
                        <td width="30%" style='padding:2px;vertical-align:middle;'>
                            <div id="salutationdropdowncontainer">
                                <select data-role='select' name='salutationdropdown' id='salutationdropdown' style='vertical-align:middle' data-filter='false' data-prepend='Year:' />
                            </div>
                        </td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'>
                            <div id="civilstatusdropdowncontainer">
                                <select data-role='select' name='civilstatusdropdown' id='civilstatusdropdown' style='vertical-align:middle' data-filter='false' data-prepend='Year:' />
                            </div>
                        </td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'>
                            <table style="width:100%;margin:auto">
                                <tr>
                                    <td style='width:60px;padding:2px 0px 2px 0px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="DOB:" style="width:60px"></td>
                                    <td style='padding:2px 0px 2px 0px;vertical-align:middle;'><input type="text" data-role="calendarpicker"></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr style="height:45px">
                        <td width="30%" style='padding:2px;vertical-align:middle;'>
                            <div id="genderdropdowncontainer">
                                <select data-role='select' name='genderdropdown' id='genderdropdown' style='vertical-align:middle' data-filter='false' data-prepend='Gender:' />
                            </div>
                        </td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'>&nbsp;</td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'>&nbsp;</td>
                    </tr>
                    <tr style="height:90%" />
                </table>
            </div>
        </div>
    </div>
    <div class="frame">
        <div class="heading">Contact</div>
        <div class="content">
            <div style="overflow-x:auto;">
                <table style="width:100%;margin:auto">
                    <tr style="height:45px"><td /><td /><td /></tr>
                    <tr style="height:45px">
                        <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Home Address:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                    </tr>
                    <tr style="height:45px">
                        <td width="30%" colspan="5" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Office Address" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                    </tr>
                    <tr style="height:45px">
                        <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Mobile Phone:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Home Phone:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                        <td width="5%">&nbsp;</td>
                        <td width="30%" style='padding:2px;vertical-align:middle;'><input type="text" data-role="input" data-prepend="Office Phone:" data-clear-button-icon="<span class='mif-cancel'></span>"></td>
                    </tr>
                    <tr style="height:90%" />
                </table>
            </div>
        </div>
    </div>
    <div class="frame">
        <div class="heading">Membership</div>
        <div class="content">
            <div class="p-2">Bitter turkey can be made tasty by brushing with...</div>
        </div>
    </div>
</div>


                            </div>
                        </div>
                        
                    </div>
                </div>


                


                
            </div>


        <script src="/bundles/metro?v=w5S3u9auyrD4AtiaPGHZT3Z4BJymNN2ugadMvmeLXuU1"></script>

        <script src="/bundles/CBBCMIS?v=Yd1USrMGsJv3H1RumrEc_MpWy1kKozW-FEf9vT2QhsA1"></script>

        
    <script type="text/javascript">

        $(document).ready(function () {
            GetCivilStatuses("civilstatusdropdowncontainer", "civilstatusdropdown", false, '999');
            GetSalutations("salutationdropdowncontainer", "salutationdropdown", false, '999');
            GetGenders("genderdropdowncontainer", "genderdropdown", false, 'U');
            SessionReset();
        });

    </script>


    <script type="text/javascript">
        $(document).ready(function () {

            SessionReset();

        });
    </script>

</body>
</html>
`

**Comment by viktorcoronel07** [comment]
[CBBC-MIS.txt](https://github.com/olton/Metro-UI-CSS/files/4628213/CBBC-MIS.txt)

Apologies if my code is messy. Just been into front end development for 4 months only :)

Thanks for your support!

**Comment by viktorcoronel07** [comment]
> [CBBC-MIS.txt](https://github.com/olton/Metro-UI-CSS/files/4628213/CBBC-MIS.txt)
> 
> Apologies if my code is messy. Just been into front end development for 4 months only :)
> 
> I saved it in a file since when I post it here even using the "Insert Code" option, some parts are rendered.
> 
> Thanks for your support!

I really cannot understand this. I posted the whole code I gave you in your codepen and the inputs are working fine.

**Comment by olton** [comment]
All fine, check your styles in `<link href="./CBBC-MIS_files/css" rel="stylesheet">`
![2020-05-14-17-15-21](https://user-images.githubusercontent.com/365108/81945245-85fad580-9606-11ea-8637-7d008fd24578.png)
