### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by sbuysse** [olton/Metro-UI-CSS#1536]
Hello,

On page: https://metroui.org.ua/tabs.html

In block Target content, you specify the code to copy as:
```
<ul data-role="tabs" data-expand="sm">
```
as it should be
```
<ul data-role="tabs" data-expand-points="sm">
```
Took me some minutes to figure it out :)

Thanks.

**Comment by sbuysse** [comment]
< ul data-role="tabs" data-expand="sm" >
as it should be:
< ul data-role="tabs" data-expand-points ="sm"  >

**Comment by olton** [comment]
Please create an issue in the Docs repo : https://github.com/olton/Metro4-Docs
