### ISSUE TITLE
Create event of Treeview not working

### ISSUE THREAD

**Issue by atwupack** [olton/Metro-UI-CSS#1537]
**Describe the bug**
A Javascript function assigned to the attribute data-on-treeview-create of a treeview is not called.
Other create events like data-on-checkbox-create or data-on-textarea-create are working properly. Also other events on the Treeview like data-on-node-click are working.

**To Reproduce**
If needed I can provide an example but I would have to create it first.

**Expected behavior**
The Javascipt function should be called after the Treeview has been created.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 76, IE 11
 - Metro Version: 4.3.6

**Comment by olton** [comment]
```
<ul data-role="treeview" data-on-tree-view-create="treeReady">
...
</ul>
```
```
<script>
        function treeReady() {
            console.log("Tree is ready!");
        }
</script>
```

**Comment by olton** [comment]
https://codepen.io/olton/pen/VwvGLoN

**Comment by atwupack** [comment]
Thank you, that works. 
The documentation about the name of the attribute is not correct, then. As I have noticed some more differences between the documentation and the current implementation, I will create a PR for that.
