### ISSUE TITLE
Unable to interact with navview component

### ISSUE THREAD

**Issue by floppy69** [olton/Metro-UI-CSS#1538]
Hi, i want to interact with the component Navview to toogle the pane but whenever i use Metro.GetPlugin i got an undefined response

```
 $(".content-inner").on("click", function(){
            var navview = Metro.getPlugin("#nav", "navview-pane");
            if (navview.isOpen()) {
                navview.close();
            }
        });
```
even with 
```
Metro.getPlugin("#nav", "navview")
```

I use Metro 4.3.7 version

**Comment by olton** [comment]
methods open, close, toggle from navview API works when navview-pane is not visible according to media rules. I will add later (in 4.3.8 or 4.4.0) methods that will switch full and compacted modes.

**Comment by olton** [comment]
Added method `toggleMode()`. This method toggles mode between expanded and compact. 
```
var nv = Metro.getPlugin('el', 'navview');
nv.toggleMode();
```
