### ISSUE TITLE
Ability to choose what file format we can add in the file input component

### ISSUE THREAD

**Issue by floppy69** [olton/Metro-UI-CSS#1539]
The Ability to choose what file format we can add in the file input component can be more secure to add files to a server

**Comment by olton** [comment]
use the standard attribute `accept`:
Acceptable file types can be specified with the accept attribute, which takes a comma-separated list of allowed file extensions or MIME types. Some examples:

- accept="image/png" or accept=".png" — Accepts PNG files.
- accept="image/png, image/jpeg" or accept=".png, .jpg, .jpeg" — Accept PNG or JPEG files.
- accept="image/*" — Accept any file with an image/* MIME type. (Many mobile devices also let the user take a picture with the camera when this is used.)
- accept=".doc,.docx,.xml,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" — accept anything that smells like an MS Word document.
```
<form method="post" enctype="multipart/form-data">
  <div>
    <label for="profile_pic">Choose file to upload</label>
    <input data-role='file' type="file" id="profile_pic" name="profile_pic"
          accept=".jpg, .jpeg, .png">
  </div>
  <div>
    <button>Submit</button>
  </div>
</form>
```

**Comment by floppy69** [comment]
It worked thanks
