### ISSUE TITLE
data-validate="notequals=field" bug?

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1542]
Hi Olton!

Example code at

https://codepen.io/TorakikiSan/pen/EeyWmp

When the second entered value (MACHINE2) is checked, the program hangs on the "notequals", no error is generated.

After "notequals=" I tried both with the **ID** of the first field and with **name**, but in both cases it stuck.

Thanks

**Comment by olton** [comment]
this function works only inside a form:
```
if (['compare', 'equals', 'notequals'].indexOf(f) > -1) {
    a = input[0].form.elements[a].value;
}
```

**Comment by olton** [comment]
### 4.3.8
+ [x] Validator: fixed functions `compare`, `equals`, `notequals` to work not inside a form, issue #1542

**Comment by TorakikiSan** [comment]
Great! As usual!

Thank's!
