### ISSUE TITLE
Metro UI CSS and Asp.Net Core. Metro initialization doesn't work

### ISSUE THREAD

**Issue by FrancescoCarraro** [olton/Metro-UI-CSS#1546]
Hi,
I'm building up a Asp.Net core 3.1 project and I really would like to use metroui as css library.
I'm having troubles in using it:
I
[_Layout.zip](https://github.com/olton/Metro-UI-CSS/files/4677274/_Layout.zip)

 created a really basic navview by following your instructions but the dropdown button in menu doesn't work.
Following the issue as reported in cosole:
Uncaught TypeError: Cannot read property 'close' of undefined
    at HTMLUListElement.<anonymous> (metro.js:15472)
    at metro.js:1300
    at $.init.forEach (<anonymous>)
    at Function.$.each (metro.js:1299)
    at $.init.each (metro.js:1314)
    at HTMLDocument.<anonymous> (metro.js:15468)
    at HTMLDocument.func_event_click_5 (metro.js:1855)

Starting using metro I found that in order to make navview work, I have to add the following js instruction
Metro.makePlugin(".navview", "navview")
inside the document ready. It seems that automatic initialization doesn't work when used in asp pages while it works in a simple plain html page.

Any idea on how fix this strange behavior?

Attached is the _Layout page I'm trying to create with the navview

thanks in advance,

Francesco
[_Layout.zip](https://github.com/olton/Metro-UI-CSS/files/4677276/_Layout.zip)

**Comment by olton** [comment]
this code is not needed. To init compoennt you use data-role attribute OR makePlugin function
```
<script type="text/javascript">
        $(document).ready(function () {
            Metro.makePlugin(".navview", "navview");
            //Metro.makePlugin(".navview-menu", "dropdown");
        });
    </script>
```

**Comment by FrancescoCarraro** [comment]
Hi,
first of all thanks for the very quick answer.
I've just tried to remove js code, set <meta name="metro4:init" content="true"> at the beginning, the result is still menu not inited correctly. Please, look at the screenshot

![Annotazione 2020-05-25 165424](https://user-images.githubusercontent.com/21294511/82823747-6dad7500-9ea8-11ea-9b71-df8582297ea9.png)

**Comment by olton** [comment]
https://codepen.io/olton/pen/gOayxRE

**Comment by FrancescoCarraro** [comment]
Dear Olton...I really really want to thank you for your amazing work and for your help! Some minor issues were present and didn't let my page work. Now I'm on the right way....thanks again!

**Comment by FrancescoCarraro** [comment]
Hi,
hope you'll answer again even if I closed the "issue". I'm trying to adapt the layout for mobile. I'm trying to follow the "Pandora" example but due to html changes made by the metro library it's difficult to understand the starting html.  The main issue I'm experiencing is that the left-pane is not displayed in compact mode when mobile view is selected. The Pandora example works great but I'm not able to reproduce it. Can you help? Thanks in advance
