### ISSUE TITLE
Keypad backspace button not working at first time.

### ISSUE THREAD

**Issue by thinhpc86** [olton/Metro-UI-CSS#1547]
**Describe the bug**
The steps to see the bug:
1. Dynamic create a text box with keypad and assign a value.
2. Click on text box, the keypad show
3. Click backspace button ( with icon: ← )
4. Text box clear.

**To Reproduce**
https://codepen.io/thinhpc86/pen/OJyGaJj

**Expected behavior**
At step 4, the text box value need to remove last number only, not clear all text box.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - Browser chrome
 - Metro Version: v4.3.7

**Comment by olton** [comment]
Thank you, fixed!
