### ISSUE TITLE
set a value for SELECT not work

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1548]
Hi Olton!

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

I created a SELECT field with a series of values, without having selected a default.

By pressing the buttons I would like to set the SELECT field to the correct value, but it seems not to work, it seems that it lacks a kind of "refresh"

Where am I wrong?

**Comment by olton** [comment]
Metro.getPlugin("#MACHINE", 'select').val(tMACHINE);

**Comment by TorakikiSan** [comment]
This must be used only for SELECT field or also for others input types?

**Comment by olton** [comment]
method val present in aĺl input components
