### ISSUE TITLE
MetroUI css and mobile view

### ISSUE THREAD

**Issue by FrancescoCarraro** [olton/Metro-UI-CSS#1549]
Hi,
I'm trying to adapt the layout for mobile. I'm trying to follow the "Pandora" example but due to html changes made by the metro library it's difficult to understand the starting html. The main issue I'm experiencing is that the left-pane is not displayed in compact mode when mobile view is selected. The Pandora example works great but I'm not able to reproduce it. Can you help? Thanks in advance

Following the simple test HTML:
<html lang="en" class="metro-no-touch-device"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>M3S App | </title>
    <link rel="stylesheet" href="./Pandora - Admin template build with Metro 4_files/metro-all.css">

    <script src="./Pandora - Admin template build with Metro 4_files/jquery.js"></script>
    <script src="./Pandora - Admin template build with Metro 4_files/metro.js"></script>
<style></style><style data-styled="" data-styled-version="4.4.1"></style></head>
<body class="h-vh-100" style="opacity: 1">
<div data-role="navview" data-toggle="#paneToggle" data-expanded="xl" data-compact="lg" data-active-state="true" class="navview compact-lg expanded-xl" data-role-navview="true">
        <div class="navview-pane">
            
                <button class="pull-button m-0 bg-darkCyan-hover">
                    <span class="mif-menu fg-white"></span>
                </button>
        </div>
		
	<div class="navview-content d-flex flex-align-center flex-justify-center h-100">
        CIAO
    </div>
</div>

</body>
</html>

 - Metro Version [e.g. 4.3.7]
![compact_ko](https://user-images.githubusercontent.com/21294511/82937721-ee47a080-9f90-11ea-8a23-844b01f87109.png)
![large_ok](https://user-images.githubusercontent.com/21294511/82937726-ef78cd80-9f90-11ea-9ba5-9fb8c800559a.png)

**Comment by olton** [comment]
https://metroui.org.ua/navview.html#_navview_pane-display-modes

**Comment by FrancescoCarraro** [comment]
Dear Olton,
sorry for not having answered...replicating Pandora behavior is a very complex task and so far it is not clear to me how to replicate all functions. I already Known the page you suggested me but it is not sufficient. Pandora requires additional files (index.css and index.js) and I noticed that if you try to make it work on localhost the menu is not expanded/compressed. It seems there's a kind of check about url and comething else that is is not clear to me....still working on understanding how to make it work correctly...

**Comment by olton** [comment]
please read docs on https://metroui.org.ua

**Comment by FrancescoCarraro** [comment]
I'm doing it...any suggestion a little bit more specific?

**Comment by olton** [comment]
create example with your code on codepen.io

**Comment by FrancescoCarraro** [comment]
Maybe it's better sending you my test all in a zip file...
[pippo.zip](https://github.com/olton/Metro-UI-CSS/files/4687892/pippo.zip)

**Comment by FrancescoCarraro** [comment]
Olton,
I guess you can find interesting that in order to have semi-working page, after several attempts, I found that i need the metro.js and metro-all.css version used for the template. the version is 4.2.41
When I use the current version (4.3.7) nothing works

**Comment by olton** [comment]
media points are triggered automatically when the window is resized. For `navview-pane`, these points are indicated by the `data-expand`, `data-compact` attributes. For size less than defined as compact mode, pane hiding. To open hiding pane, you must call `navview` API method `open` or `close`.
To get API you must use the method `Metro.getPliugin(element, pluginName)`.

**Comment by FrancescoCarraro** [comment]
Olton,
the main issue, as I already said, is that the "navview" class in the navview div works only with the 4.2.41 version used in pandora template. when I try to use the latest one the hamburge menu and the left-side menu disappear....I want to try to have something similar to pandora style (which is want I really need) I have to use the old metro version, which does not contain Metro.makePlugin.

In any case, I am not able to have the perfect behavior of the example

**Comment by olton** [comment]
Get latest Pandora from GitHub (https://github.com/olton/Pandora). It works with 4.3.x

**Comment by olton** [comment]
Some properties (attribute names) have been changed. Access to IPA has also been changed. in 4.2.x, to get access to the API, you had to call $ (element) .data (pluginName)

**Comment by FrancescoCarraro** [comment]
I'm going to try the new template...I will let you as soon as possible...

**Comment by FrancescoCarraro** [comment]
AMAZING! It worked immediately! i really have no words to thank you!
