### ISSUE TITLE
How to "collapse" a data-role="collapse"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1550]
I still have difficulty (my fault) in understanding how to use Metro directly in scripts, or rather, how to "write" the correct syntax of a command.

In this case, I have difficulty expanding a "collapse" object via a button other than the one associated with the object.

So I wrote:

```
$(document).on("click", "[id^='ADDMACHINE_']", function(e) {
    e.preventDefault();

    tMACHINE="#DIVMCH_"+$(this).attr("data-machine");
    console.log(tMACHINE);

    Metro.getPlugin(tMACHINE, "collapse").expand();
  });

```
but it does not work.

I also tried replacing the statement with

`    $(tMACHINE).data("collapse").expand();
`
but even in this case nothing to do, it doesn't work.

can you help me?

Thanks

**Comment by olton** [comment]
https://codepen.io/olton/pen/mdeYBoV

**Comment by olton** [comment]
If you use `jQuery`, you must use `Metro.getPlugin`, otherwise you can use `$('...').data('pluginName')` syntaxis to get access to component API.

**Comment by olton** [comment]
Methods https://metroui.org.ua/collapse.html#_dropdown_options
