### ISSUE TITLE
Disabled Buttons in Ribbon should not hover and change to clicked style on click

### ISSUE THREAD

**Issue by jogibear9988** [olton/Metro-UI-CSS#1551]
It would be a better visualisation of the disabled state.

**Comment by olton** [comment]
I will fix it in 4.3.8

**Comment by jogibear9988** [comment]
I did like this:

    .ribbon-button[disabled] {
        background: transparent;
        border: none;
        opacity: 0.5;
    }

    .ribbon-icon-button[disabled] {
        background: transparent;
        border: none;
        opacity: 0.5;
    }

**Comment by olton** [comment]
fixed in 4.3.8. Use attribute `disabled` or class `disabled`
