### ISSUE TITLE
Remember state of tabs

### ISSUE THREAD

**Issue by justustheis** [olton/Metro-UI-CSS#1552]
Is there already any way to remember the state of [Tabs](https://metroui.org.ua/tabs.html)? 
I need a way to persist the state through reloads, so that after form posts the user "stays" at the right table :)

**Comment by ojosojo** [comment]
Save the tab item id using click event then  on document ready : 


 `
$('#tab_item_3').find('a')[0].click();  // if tab_item_3 is saved in localstorage then just trigger it
`


```


<ul  id="tab"   data-role="tabs"   data-tabs-type="group" data-expand="false"  data-expand-point="sm"
             data-cls-tabs="flex-justify-start">
            <li id="tab_item_1"><a href="#_target_1" >TAB 1</a></li>
            <li id="tab_item_2"><a href="#_target_2" >TAB 2</a></li>
            <li id="tab_item_3"><a href="#_target_3" >TAB 3</a></li>
</ul>
```

**Comment by olton** [comment]
1. Use `tabs` event `onTab` to store active tab into `Storage`
2. After reload, read a stored tab from Storage, and:
    2.1. Use class `active` for tab, when drawing HTML code of tabs
    2.2. Use `tabs` method `open(index)` to open a specified tab when tabs already created. The index must be defined from `1` to `tabs.length`

**Comment by justustheis** [comment]
Thank you!
