### ISSUE TITLE
calling focus() not work on material input

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1553]
**Describe the bug**
The `focus()` method doesn't work for material input: 
```
document.getElementById("minput").focus();
// OR
$("#minput").focus();
```

**To Reproduce**
https://codepen.io/taurenshaman/pen/oNbgjaQ

**Expected behavior**
Should set focus in JS code.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Opera 68, FireFox 76]
 - Metro Version v4.3.7

**Additional context**
n/a

**Comment by olton** [comment]
```
$(function(){
  document.getElementById("minput").focus();
})
```

**Comment by olton** [comment]
https://metroui.org.ua/configuring.html#_meta_options
Read about `metro4:init:mode`
