### ISSUE TITLE
Select specific node in Listview at runtime

### ISSUE THREAD

**Issue by Pitanium** [olton/Metro-UI-CSS#1554]
Hello,

I have been using the framework for some time now. Very good work!
I cant find any function, that can do this. I hope I haven't missed anything.

I use the (selectable) Listview control for a site with permission settings. I had the problem that I can't select certain nodes at runtime (i.e. select the node if the permission is already granted). 

I extendet the listview.js (source/components/listview/listview.js) with the following method behind line 403:

```javascript
selectSpecificOne: function(attributeName, attributeValue) {
        this.element.find('li[data-' + attributeName + '="' + attributeValue + '"]' + ' > .checkbox input').prop("checked", true);
        this.element.trigger('change');
   };
```
**Parameters:**
*attributeName:* The method searches the element for the given data attribute (i.e. data-id => 
                             lv.selectSpecificOne('id', '123);

*attributeValue:* The value for the data attribute.

If I have a set of ids to select, I can use this function to select them all: 

```javascript
var ids = '123,456,789';
var array = ids.split(',');

for (let i = 0; i < array.length; i++) {
    var lv = Metro.getPlugin('#lv', 'listview');
    lv.selectSpecificOne('id', array[i]);
}
```
The found elements get selected.

Perhaps it is possible to integrate this or a similar proposal.

**Comment by olton** [comment]
Hi Robin! Thanks for this purpose. I added method `selectByAttribute` in 4.3.8. You can test it from branch 4.3.8 or dev from cdn.  For using:
```
<div>
        <button class="button" onclick="selectSpecified()">Select specified</button>
        <button class="button" onclick="selectSpecified(false)">Deselect specified</button>
</div>


<ul data-role="list-view" id="list-view" data-selectable="true">
    <li id="l1">...</li>
    <li id="l2">...</li>
    <li id="l3">...</li>
    <li id="l4">...</li>
    <li id="l5">...</li>
</ul>
```
```
function selectSpecified(select){
        var val = ["l2", "l5", "l7", "l8"], attr = "id";
        var lv = Metro.getPlugin("#listview", "listview");
        $.each(val, function(){
            lv.selectByAttribute(attr, this, select);
        })
}
```

**Comment by Pitanium** [comment]
Hey Sergey,

thank you very much!
