### ISSUE TITLE
Required an Example to use metro validator functions without a form

### ISSUE THREAD

**Issue by satyajitbho** [olton/Metro-UI-CSS#1555]
Sir Olton,

I am learning jquery / javascript / metro4 / ajax. I want to get some data using ajax after validation without form.

Please give a simple example how to send data using .ajax after validating input field in metro4.

**Comment by olton** [comment]
https://codepen.io/olton/pen/ZEQGwdg?editors=1010

**Comment by satyajitbho** [comment]
> https://codepen.io/olton/pen/ZEQGwdg?editors=1010

Thank you very much sir, Now I will learn.
