### ISSUE TITLE
Submit data using ajax after metro validator

### ISSUE THREAD

**Issue by satyajitbho** [olton/Metro-UI-CSS#1556]
Sir Olton,

Please help me again to submit using ajax after validation,

https://codepen.io/satyajitbho/pen/eYJNqPM

Thank you for your help in advance.

**Comment by Pitanium** [comment]
Hello,

you can search in the metro documentation. There are a few samples, how you can transmit data with or without form. Keep in mind: you need and endpoint (i.e. webserver), which can compute the data (php, asp.net, ...). 

The samples can be found here: [https://metroui.org.ua/m4q-ajax.html](https://metroui.org.ua/m4q-ajax.html) 

I've created a codepen, to show an example. [https://codepen.io/pitanium/pen/GRopKZj](https://codepen.io/pitanium/pen/GRopKZj)

````javascript
var endpoint = "";
````
defines your endpoint, where the ajax request will be send. 

````javascript
var email = $('#email').val();
var name = $('#name').val();
````
get the value from the 2 input fields. I've added the id attribute to the <input>, to identify them. 

i hope the explanation is understandable. There are many videos where javascript and especially ajax is explained quite good. They teach you the basics with some easy samples.

**Comment by satyajitbho** [comment]
No sir,

I have tried but data submitting without validation.

**Comment by Pitanium** [comment]
I've updated the codepen. if i understood it correctly, each input field has to be checked individually.

**Comment by ojosojo** [comment]
`
HTML :
<form data-role="validator" id="myform"
      action="javascript:"
      data-on-submit="formisvalid_save();"
      data-on-error-form="return formerror(arguments);" >

JAVASCRIPT:

function formisvalid_save() { 
//Save your data using ajax or FormData
 }

function formerror(args)
{
console.log(args); // inspect the feedback
}

`

**Comment by satyajitbho** [comment]
> I've updated the codepen. if i understood it correctly, each input field has to be checked individually.

Thank you sir,
This is I am searching for. Thank you very much sir,

**Comment by satyajitbho** [comment]
> ```
> HTML :
> <form data-role="validator" id="myform"
>       action="javascript:"
>       data-on-submit="formisvalid_save();"
>       data-on-error-form="return formerror(arguments);" >
>             <input type="text"
>                 data-validate="required minlength=6"
>                 placeholder="Enter first name">
>             <span class="invalid_feedback">
>                 Input correct name with min length 6 symbols
>             </span>
> 
>   ...... 
> ```
> 
> ```
> 
> JAVASCRIPT:
> 
> function formisvalid_save() { 
> //Save your data using ajax or FormData
>  }
> 
> function formerror(args)
> {
> console.log(args); // inspect the feedback
> }
> ```

Ok Sir,

I shall use like your pattern also...

**Comment by olton** [comment]
```
<div class="container">
<div class="bg-white p-6 mx-auto border bd-default win-shadow">
  <h3>Submit data without form using Ajax</h3>
<div class="form-group">
  <label>Enter you email</label>
  <input name="email" type="text" data-validate="required email">
  <span class="invalid_feedback"> required</span> 
  <label>Enter you Name</label>
  <input name="name" type="text" data-validate="required">
  <span class="invalid_feedback"> required</span> 
  <hr>
  <button class="button">Validate</button>
</div>
</div>
</div>
```

```
$(function(){
	$("button").on("click",function(){
		var valida = Metro.validator;
		var email = $("input[name=email]");
                var name = $("input[name=name]");
		if(valida.validate(input)){
			alert("done");
                        return ;
		}
	       $("input").addClass("invalid");

              $.post(__your_url__, {
                    email: email,
                   name: name
              }).than(function(response){
                      ... success sending ...
              }, function(xhr){
                     ... ajax error
              })
	})
});
```
