### ISSUE TITLE
data-role="table"  USING  data-skip-wrapper  BUG

### ISSUE THREAD

**Issue by ojosojo** [olton/Metro-UI-CSS#1557]
When defining a data-skip-wrapper it does not function the click event to skip de page.

BUG ( defining  data-skip-wrapper  ) :
https://codepen.io/nafurset/pen/JjGYZeo

OSX 10.15.4 (19E287)
Chrome  81.0.4044.138 (Official Build) (64-bit)
Metro 4.3.7

In order to the button to work ... I must not define a data-skip-wrapper

**Comment by olton** [comment]
Thank, fixed
