### ISSUE TITLE
Prepend additional class for calendar picker

### ISSUE THREAD

**Issue by Marcel2508** [olton/Metro-UI-CSS#1558]
**Describe the bug**
The ``data-cls-prepend`` attribute is not working for inputs with ``data-role="calendarpicker"``

**To Reproduce**
https://codepen.io/Marcel2508/pen/OJMyKLq

**Expected behavior**
A custom class should be added to the prepended element.

**Screenshots**
See Codepen

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by olton** [comment]
Thanks, fixed in 4.3.8
