### ISSUE TITLE
NavView height and icon

### ISSUE THREAD

**Issue by jimbrew** [olton/Metro-UI-CSS#1559]
When using metro UI v4.3.2 I am adding in a navview however its height does not render to the full screen size.

Also when resizing the browser menu window the button is removed

![size issue](https://user-images.githubusercontent.com/35928790/84163440-68842480-aa69-11ea-89b9-fc527d4c6a63.png)

See my html as a text file
[nav-view.txt](https://github.com/olton/Metro-UI-CSS/files/4752898/nav-view.txt)

**Comment by olton** [comment]
update metro to latest version

**Comment by jimbrew** [comment]
Updated to the latest version but the issue still persists.

I added style='height : 100vh' to the <div data-role='navview'> which sorts out the height.

The menu hamburger button is still disappearing, this happens when the width is less than 768px

**Comment by olton** [comment]
create your code example on codepen.io

**Comment by olton** [comment]
Read about Navview pane here https://metroui.org.ua/navview.html#_navview_pane-display-modes

**Comment by jimbrew** [comment]
I have been using that as reference but looking at the site on my mobile then the problems appears to be with component.

The hamburger menu is not shown in most of the examples.

See attached image.

![Screenshot_20200609-183902~2](https://user-images.githubusercontent.com/35928790/84181307-a2acf080-aa80-11ea-8bd9-faff078876fe.png)

**Comment by olton** [comment]
Please READ DOCUMENTATION

![2020-06-09-20-47-10](https://user-images.githubusercontent.com/365108/84182023-6d110300-aa92-11ea-97be-c57773f96e1c.png)

**Comment by olton** [comment]
Also, you can see BIG EXAMPLE - https://metroui.org.ua/themes/pandora/
And the source for Pandora - https://github.com/olton/Pandora

**Comment by olton** [comment]
From Pandora example
```
<div data-role="navview" data-toggle="#paneToggle" data-expand="xl" data-compact="lg" data-active-state="true">...</div>
```

**Comment by olton** [comment]
In Pandora media points work as:
For display size from 1200px `pane` displayed in full size
For display size from 992px `pane` displayed in compact mode
For display size from 0 to 992 - `pane` is hidden, and can shows when user click on element with is `paneToggle`

**Comment by jimbrew** [comment]
Thanks for this

**Comment by olton** [comment]
Perhaps there are errors and inaccuracies in the documentation since the library is constantly evolving and changes are taking place in it. Unfortunately, there is not enough time for everything. If you notice an inaccuracy in the documentation or the component does not work as described in the dock, make an issue in the documentation repository (https://github.com/olton/Metro4-Docs). 

Thank you.
