### ISSUE TITLE
How to use datetime-local in metro4

### ISSUE THREAD

**Issue by satyajitbho** [olton/Metro-UI-CSS#1560]
Sir Olton,

I am trying to use datetime-local type in input element with metro4.

How can I use ? Or is there another option where can I pick date and time at a time.

Please help.

**Comment by olton** [comment]
the question is not clear

**Comment by satyajitbho** [comment]
Ok, Sorry Sir,

I want a text input for pick date and time both. Like the following -
`<input type="datetime-local" id="start_date" name="eventdate" value='12-06-2020 22:54:00' />`

instead of the following -
`<input type="text" id="start_date" name="eventdate" value='12-06-2020' data-role="calendarpicker" />`

How Can I use using metro4 for picking date and time both ?

**Comment by olton** [comment]
There is currently no special component in Metro 4 for selecting a date and time together.

**Comment by satyajitbho** [comment]
Ok sir
