### ISSUE TITLE
v4.3.7 - Error creating component calendarpicker - Firefox refresh with F5

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1561]
Hi Olton,

I hope you are well.
Testing a new program I found an issue I can reproduce only with Firefox (77.0.1 (64 bits))
On a page that use calendarpicker component if I reload the page with javascript or by hitting F5 the calendar picker fail to load.
"Error creating component calendarpicker"
"TypeError: aDays[nDay] is undefined"

Works well on others browsers

**Comment by Falconpage** [comment]
`<input name="date" type="text" id="date"  value="" size="12" maxlength="10" style="height: 35px; font-size: 0.9em;" data-role="calendarpicker" data-locale="fr-FR" data-header-format="%A %e %B" data-format="%d/%m/%Y"/>`

If I remove the data-format it works.

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1506

**Comment by Falconpage** [comment]
Thanks, adding `autocomplete="false"` fix the problem for me.
Great and quick support, thanks again.
