### ISSUE TITLE
Initialisation of table columns with Metro.makePlugin()

### ISSUE THREAD

**Issue by rod-farias** [olton/Metro-UI-CSS#1562]
I am building the dom of my website completely with javascript and the m4q utilities.
To activate the Metro 4 design components I am using the Metro.plugin () function, instead of html dataset.
However, I was unable to configure the columns of a Metro4 table in this way. It's possible?

var table1 = Metro.makePlugin("#table1", "table", {
    showPagination: false,
    columns.... //??
});

**Comment by olton** [comment]
https://metroui.org.ua/table.html#_table_columns
https://metroui.org.ua/table.html#_table_external_data
You must define columns: In `thead` or in `header` section of external json file

**Comment by olton** [comment]
Also, you can use attribute `data-head` (`head` for makePlugin)
```
var tableHeader = [
    {name: "option", title: "Option"},
    {name: "attribute", title: "Data-*", template: "<code>%VAL%</code>"},
    {name: "default", title: "Default", template: "<code>%VAL%</code>"},
    {name: "desc", title: "Description"}
];

Metro.makePlugin(element, "table", {
   ...
    head: tableHeader 
  ...
})
```

**Comment by rod-farias** [comment]
Perfect, thank you very much for your reply. I am really enjoying Metro4.
