### ISSUE TITLE
Meta viewport is deleted 

### ISSUE THREAD

**Issue by iProddev** [olton/Metro-UI-CSS#1563]
If i put this meta tag in the <head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

it is deleted at runtime from metro scripts
in this way, media breakpoints doesn't works right on mobile device

You can reproduce this apply a media breakpoint to a div in this way
<div class="d-none-fs d-block-md">
... content
</div>

You will see always the div if you try developer mode to a mobile screen.

**Comment by olton** [comment]
Metro does not remove the meta tag viewport, as it is required.  Something else removes it from you.

**Comment by iProddev** [comment]
I confirm sorry, was my mistake
