### ISSUE TITLE
setImmediate incompatibility with Electron

### ISSUE THREAD

**Issue by alaa-eddine** [olton/Metro-UI-CSS#1566]
Hi,

Metro uses setImmediate in several functions, and since it's not a standard function, there seems to be inconsistencies between environments.

Metro don't work on Electron v9 (didn't tested with older versions), and when debugging I noticed that the setImmediate callback is never called.

I saw that there is a polyfill in m4q but since electron have it already defined, the polyfill isn't used.

I used a quick fix just to make it running under electron by adding this 

```javascript
//checking electron env
if (typeof process != 'undefined' && process.versions && process.versions['electron']) {
    window.setImmediate = function (fn) {
        setTimeout(fn)
    }
}

``` 

I'm not sure if this is a bug, or is there some specific initialization I should use with electron.

**Comment by olton** [comment]
Metro 4 designed for web, and not tested for non browsers environment. Please create issue for m4q for adding this enhance.

**Comment by olton** [comment]
Thanks for the feedback, added support for process and web workers in 4.3.8
