### ISSUE TITLE
data-role="tabs", class for the selected tab

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1568]
Hi Olton!

How can I "highlight" the currently selected tab?

I have used data-cls-tabs-list-item but this applies to all tabs.

Thank's

**Comment by olton** [comment]
`clsTabsListItemActive` - `data-cls-tabs-list-item-active`

**Comment by TorakikiSan** [comment]
Sorry Olton, a little bug:

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

The active class don't reset when select an other tab.

**Comment by TorakikiSan** [comment]
Thank's!

**Comment by TorakikiSan** [comment]
Hi Olton!

Code:

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

seem the data-cls-tabs-list-item-active attribute is "broken" on 4.4.2
