### ISSUE TITLE
<select data-role="select" multiple> doesn't render like it should

### ISSUE THREAD

**Issue by markon1** [olton/Metro-UI-CSS#1572]
I'm using this component in my Vue project, this is my code:

```
<select data-role="select" multiple>
       <option v-for="tagOption in tagOptions" :key="tagOption.id" :value="tagOption.id">
                        {{ tagOption.name }}
       </option>
</select>
```

The problem is it renders like this:
https://prnt.sc/t3z3a1

instead of what it looks like here: https://metroui.org.ua/select.html#_select_multiple.

Other Metro components render fine, I include latest versions of `metro-all.min.css` and `metro.min.js`.

**Comment by olton** [comment]
I do not work with Vue, so I can’t answer, maybe someone from the community will help you.

**Comment by markon1** [comment]
@olton OK, I managed it to show up as intended (I missed calling `Metro.init();` in `mounted()` of my Vue app).
But how can I add an option dynamically, for example when it's returned from some API call?
I don't see an method for doing it in the docs.

**Comment by olton** [comment]
https://github.com/olton/Metro4-Docs/tree/master/public_html/examples/ajax
