### ISSUE TITLE
Cannot scroll with dragging on mobile browser when Tiles fill the page

### ISSUE THREAD

**Issue by ONLYA** [olton/Metro-UI-CSS#1573]
**Describe the bug**
Large tiles on the tile grid fill the screen on mobile (Safari and Edge on iPhone SE and iPad mini 2 in my case). When I scroll down by dragging the screen (P.S. the tile fills the screen so I can only drag the page on the tiles), the page turns to the tile's link that was at the beginning of dragging. It seems that the event of turning the page will be triggered by a single tap only.

Do not try this on Chrome Inspection tool as that cannot reproduce this. You should reproduce this bug on real mobile.

**To Reproduce**
Open this link in any **real** mobile device. Have tested on my devices. [https://codepen.io/onlya/full/ExPvXdy](https://codepen.io/onlya/full/ExPvXdy)

**Expected behavior**
For example, when you try to scroll down on iPhone browser, you must first tap the first or the second tile. Then the page will quickly be turned to the link of the tile where the starting point of your drag is.

**Screenshots**
N/A

**Desktop:**
 - iOS (I don't have android devices but I believe it will  be reproduced on those devices)
 - safari, Microsoft Edge
 - 4.3.4

**Smartphone:**
 - iPhone SE, iPad mini 2
 - iOS 13.5.1
 - Safari, Microsoft Edge
 - 4.3.4

**Additional context**
You can experience my problem by visiting [My website](https://www.300-300-300-300.space) with mobile devices. Try to scroll down, and you can find the pain.

**Comment by olton** [comment]
Unfortunately, I do not have real ios devices to check it.

**Comment by ONLYA** [comment]
Well, I have solved it now. With the combination of `touchmove` and `touchend` events, I can use a flag to indicate whether the user  is dragging or touching the tiles. See this adjusted pen link [https://codepen.io/onlya/pen/ExPvXdy](https://codepen.io/onlya/pen/ExPvXdy) to view my solution.

However, I suggest @olton to add tile href feature instead of `<a href="...">`. Or I may make a pull request to `tile.js`.

Additionally, tapping event seems not working in body filled with tiles.

Since this has been solved. I close this issue now.

**Comment by ojosojo** [comment]
This is how I solved this issue, it will let users scroll on touch screens : 

On the item of the menu :

` data-on-click="return menu.onclick(this);"  data-role="tile" `

The Javascript :
```
var menu =
{
    onclick : function(objeto)
    {
        if(Metro.utils.isTouchDevice())
        {
            if( $(objeto).containsClass('selected') === true )
            {
                window.location.href  =   $(objeto).data('href') ;
            }
            else
            {
                $('.menu .opcion').removeClass('selected'); // <- remove all selected class
                $(objeto).addClass('selected'); // <- add class to current item
            }
            return true;
        }
        else
        { // trigger the click event 
            $(objeto).addClass('selected');
            setTimeout(function(){
                window.location.href  =   $(objeto).data('href') ;
            },'100');
        }



    }
}

```
