### ISSUE TITLE
add options to autocomplete dynamically

### ISSUE THREAD

**Issue by markon1** [olton/Metro-UI-CSS#1576]
Is there a way to set `data-autocomplete` of autocomplete dynamically?
So for instance, I want to get autocomplete options from API each time user enters new character into input, I use onChange event to detect it, but I don't know how to add these new options to autocomplete, and I can't see a method for this in the docs?

**Comment by markon1** [comment]
Hi @olton , do you happen to know something about this, it would really help me.

**Comment by olton** [comment]
Added in 4.3.10. Use the input API method `setAutocompleteList` to change autocomplete sets.
```javascript
var comp = Metro.getPlugin(this, "input");
var newList = ... // <- string or array
comp.setAutocompleteList(newList);
```

**Comment by markon1** [comment]
Thanks @olton , but how can I download this version and use it in my project?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/4.3.10
