### ISSUE TITLE
Treeview Node Highlight

### ISSUE THREAD

**Issue by mike-zar** [olton/Metro-UI-CSS#1578]
It would be great to have the treeview node selected have a highlighted background, like in explorer :) 
a sweet addition would be able to select a tree node from code (and have it selected and highlighted)

**Comment by olton** [comment]
you can use the following additional styles to solve your problem.

```
.current::before {
  content: "";
  display: block;
  position: absolute;
  z-index: -1;
  background: lightcyan;
  height: 24px;
  top: 0;
  right: 0;
  bottom: 0;
}

.treeview > li > ul > li > ul > .current::before {
  left: -56px;
}

.treeview > li > ul > .current::before {
  left: -40px;
}

.treeview > .current::before {
  left: -24px;
}
```

Here is a link to a working example: https://codepen.io/olton/pen/WNrjeXg

In this example, I implemented 3 levels of nesting, if you need more, you can add them as an example, adding the right amount of additional ul li.

**Comment by mike-zar** [comment]
Thx a stax,, brilliant :)
