### ISSUE TITLE
Buttons on Carousel Slide

### ISSUE THREAD

**Issue by Rodolfo-XDR** [olton/Metro-UI-CSS#1581]
**Describe the bug**
Buttons do not work on carousel slide. 

**To Reproduce**
Create more than 1 slides, with buttons. You'll see that only the 1st Button will work, while the other slides wont't. However you can still press the 1st Slide Button.

**Expected behavior**
Slide content should be totally invisible when not showing, and should be able to press buttons on more than 1 slide.

**Screenshots**
![image](https://user-images.githubusercontent.com/49254245/86853020-5fdc3980-c07b-11ea-8426-0b5918aba621.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Metro Version Latest

**Comment by olton** [comment]
create your code examples on codepen.io

**Comment by Rodolfo-XDR** [comment]
I wasn't able to replicate in on stackblitz (since I use Metro4 in an Angular Project) however, I noticed what the problem is, when you set the carousel "data-effect='fade'" otherwise it works well.

**Comment by Rodolfo-XDR** [comment]
I already updated my issue, and also proposed a solution, hopefully you'll consider it @olton
