### ISSUE TITLE
Add feature to interact with data-role with M4Q Constructor

### ISSUE THREAD

**Issue by floppy69** [olton/Metro-UI-CSS#1587]
Hi, Sergey,

what do you think about use data-role to interact with MQ4 Constructor ?

I'm already using ID but it seems more simple if we can use data-role

regards, you're the best 🥇

**Comment by olton** [comment]
Please clarify your question.

**Comment by floppy69** [comment]
Hello Sergey,

you written about M4Q  constructor that you can interact with elements by their classes, id, names. Can M4Q be used to interact with data-role ?

ex :  `$( "!carrousel" )` or `$( "!taginput" )`

**Comment by olton** [comment]
Ok, please create issue for m4q project in m4q repository.

**Comment by olton** [comment]
Now, in 4.4.0 you can select elements by rolename:
```
var windows = $("@window"); // get all element with data-role="window"
var calendars =$("@calendar"); // get all element with data-role="calendar"
```
