### ISSUE TITLE
setting values for many Multi-select box

### ISSUE THREAD

**Issue by mrrafals** [olton/Metro-UI-CSS#1588]
Hello,

I am trying to set a value to all multi-select boxes each hosted inside a td element of a tr element of a table.

I found in the documentation how to set the value of one Multi-select box by ID:
var select = $(el).data('select');
select.val([1, 2, 3]);

but I am struggling to do the same for many of them. The way I am trying to accomplish this task is to select all of the select elements and than loop through them assigning values which were read from the database and are placed in hidden inputs.

When I do $(.className select) where className is assigned to each select element, the items of the resulting array have no "val" function. They have "value" but it does not work.

Would you be able to tell me how to do it , please?

Thanks,

Rafal

**Comment by olton** [comment]
$('tr select').each( function () {
    Metro.getPlugin(this, 'select').val(...) ;
} )

**Comment by mrrafals** [comment]
Much appreciated!
