### ISSUE TITLE
Calendar: onMonthChange() event not called when month if changed by clicking the outside area

### ISSUE THREAD

**Issue by Erdou** [olton/Metro-UI-CSS#1589]
**Describe the bug**
On the Calendar component, `onMonthChange()` event is called when user changes the months with explicetely selecting a month or by clicking right/left arrows on the both sides of the months. But if you click on the outside area, where you have **grayed dates** for previous/next months, it will also change month (which is correct) but without calling `onMonthChange()`.

**To Reproduce**
https://codepen.io/erdal-gunyar/pen/BajGooR

**Expected behavior**
`onMonthChange()` must be called even when the Calendar component automatically changes the month.

**Comment by olton** [comment]
Thx, fixed in 4.4.0
