### ISSUE TITLE
how to get window dailog changed height using onResize()

### ISSUE THREAD

**Issue by raghunath004** [olton/Metro-UI-CSS#1590]
**Describe the bug**
how to get window dailog changed height using onResize()

**Comment by olton** [comment]
Please clarify your question. Which component are you interested in window or dialog?

**Comment by raghunath004** [comment]
> 
> 
> Please clarify your question. Which component are you interested in `window` or `dialog`?

Window sir

**Comment by raghunath004** [comment]
i want to create window with header footer and canvas sir.  while resize the window height i want only resize the canvas sir.
is it any possible to set maximum height of window sir?

**Comment by raghunath004** [comment]
sir ribbon menu height, can i fix the height is it posible sir? 
thankyou for replying me sir

**Comment by olton** [comment]
```
<div data-role="window" data-on-resize="onResize">
    This is a window content
</div>

<script>
    function onResize(size) {
        console.log(size); // size is a object with width and height values
    }
</script>
```

**Comment by raghunath004** [comment]
thank you sir.
can i set max height to window sir because it is resizing outside drag area also

**Comment by olton** [comment]
> can i set max height to window sir because it is resizing outside drag area also
You must change attribute `data-height` (int value)

**Comment by olton** [comment]
new in 4.4.0
+ [x] Window: add API methods `pos(top, left)`, `top(v)`, `left(v)`, `width(v)`, `height(v)`, issue #1590
+ [x] Metro.window: add methods `pos(top, left)`, `top(v)`, `left(v)`, `width(v)`, `height(v)`

**Comment by blueandblue** [comment]
Hi Olton,
it is possible to know the position, size of a window (x, y or top, left) to save the state in a database.
When the window reopens, put it back in the position chosen by the user.
Thank you

**Comment by olton** [comment]
```
var pos = Metro.getPlugin("#win1", "window").win.pos();
console.log(pos);
```

**Comment by blueandblue** [comment]
in your example "Desktop" there is the function:
*************************
function createWindow(){
//    var index = Metro.utils.random(0, 3); //  NOT WORK
    var index = 123;
    var w = Desktop.createWindow({
        resizeable: true,
        id: "finestra",
        draggable: true,
        width: 300,
        top: 30,
        icon: "<span class='mif-"+w_icons[index]+"'></span>",
        title: w_titles[index],
        content: "<div class='p-2'>This is desktop demo created with Metro 4 Components Library</div>"
    });

    setTimeout(function(){
        w.setContent("New window content");
    }, 3000);
}
***************************
how can i know and save the position (x, y) and window size?
Thank you

**Comment by olton** [comment]
> // var index = Metro.utils.random(0, 3); // NOT WORK
need change to (already fixed in ...don't remember when)
```
var index = $.random(0, 3);
```
**For position** - store returned value from `Desktop.createWindow(...)` to global variable - this is a HTMLElement as m4q object with role window, and use it in
```
var pos = Metro.getPlugin(your_global_war, "window").win.pos();
console.log(pos);
```

**Comment by blueandblue** [comment]
good morning, in the meantime, thanks for the answers.
Could you help me by giving me a small example.
Thank you
