### ISSUE TITLE
Double-Slider: Right-hand button moves when grabbing the left-hand hint

### ISSUE THREAD

**Issue by bgxie** [olton/Metro-UI-CSS#1591]
Can be observed with the Hint Position or Hint Value example at https://metroui.org.ua/double-slider.html 

- Both slider buttons work as expected when selecting the button and moving it.
- Clicking the right hint and moving it also moves the right button

Issue: Clicking the left hint highlights the left button but 
- when moving it right, first he right button+hint get moved towards the left button and then the right button gets moved
- when moving it left: nothing happens

**Comment by olton** [comment]
Thx, fixed in 4.4.0

**Comment by Djang0** [comment]
Hello, I experience the same issue with 4.5.1. ... Would you mind to reopen?
thanks in advance
