### ISSUE TITLE
Call forms validator manually

### ISSUE THREAD

**Issue by patrickelectric** [olton/Metro-UI-CSS#1593]
**Is your feature request related to a problem? Please describe.**
I'm using vue with metroui, and after the html is rendered, the validator is not runing when vue populates the controls.

**Describe the solution you'd like**
I would like to call the form validation manually

**Describe alternatives you've considered**
No idea.

**Additional context**
My form:
`<form id="network-form" data-role="validator" action="javascript:" data-interactive-check="true">`

I did try to call `document.getElementById("network-form").submit();` but it appears that it does not trigger validator

**Comment by olton** [comment]
You can use API method `Metro.validattor.validate(...)` to validate fields manually.
```
var inputs = $("you_form_id [data-validate]");
var result = {
    val: 0,
    log: []
};
$.each(inputs, function(){
    Metro.validattor.validate(this, result);
})
if (result.val === 0) {
    // success
} else {
   // form has errors, see result.log
}
```
