### ISSUE TITLE
Table column width not working

### ISSUE THREAD

**Issue by RayenMh** [olton/Metro-UI-CSS#1594]
this is my table html code

`<table id="tfstable" class="table striped table-border mt-4 w-100" data-role="table" data-rows="-1"
                   data-show-rows-steps="false" data-show-pagination="false" data-horizontal-scroll="true" >
                <thead>
                <tr>
                    <th class="sortable-column sort-desc" data-format="number">CS #</th>
                    <th >Author</th>
                    <th data-size="100">Comment</th>
                    <th data-format="date" data-format-mask="%y-%m-%d">Date</th>
                    <th data-format="date" data-format-mask="%H:%M">Time</th>
                    <th>Files</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>`

and i need to set all my Comment columns width to 100px but with no luck. is there any work around.

i try with css also with no luck.
table tbody tr td:nth-child(2){
            width: 100px !important;
        }
        table thead tr th:nth-child(2){
            width: 100px !important;
        }

**Comment by olton** [comment]
https://codepen.io/olton/pen/NWxQqva
