### ISSUE TITLE
For dropdown element, is there a way to click on the dropped down element and not disappear?

### ISSUE THREAD

**Issue by projeffboy** [olton/Metro-UI-CSS#1596]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
I tried using your [dropdown component](https://metroui.org.ua/dropdown.html) today, and I like it except that I don't want it to go up when I press the element with the `data-role="dropdown"`. 

Basically, I don't want the red box below to disappear when I click on it (only "Drop block" can make it disappear/reappear):
![Annotation 2020-08-10 212634](https://user-images.githubusercontent.com/20577302/89787529-3027c200-db50-11ea-931f-318461460626.png)

**Describe alternatives you've considered**
I tried modifying `$('#filters').data('no-close')` but it seems to be read-only.
I then tried `event.preventDefault` and `return false` when using the event handler `onUp`.
Maybe I have to tinker with `$('#filters').data('dropdown')`?

I'm quite new to your framework, so if I'm using it incorrectly please let me know. Thanks for the framework!

**Comment by olton** [comment]
Use `collapse` component

**Comment by projeffboy** [comment]
Ugh, I didn't think outside the box. Thank you.
