### ISSUE TITLE
contentEditable="true" on table's <td> node

### ISSUE THREAD

**Issue by n-mam** [olton/Metro-UI-CSS#1598]
Hello

I am rendering table rows on the server side using below logic but the resulting view does not seem to have the contenteditable attribute set. However from within the inspector when I manually edit the td's html node with this attribute then the on click edit box shows fine. Could you please advise on what could be causing this issue ?

```
  for (let i = 0; i < rows.length; i++)
  {
    h += `<tr>`

    for (let j = 0; j < keys.length; j++)
    {
      h += `<td contentEditable="true">${rows[i][keys[j]]}</td>`;
    }

    h += `</tr>`
  }
```

![image](https://user-images.githubusercontent.com/17683324/89980583-ce6e7180-dc8f-11ea-8e2f-3e0373e2514b.png)

**Comment by olton** [comment]
You must use the attribute `data-on-draw-cell` to set `td` element attributes. 

In the example below, I render a progress bar inside a table cell. 
https://codepen.io/olton/pen/rNNmxaB?editors=1010

In your case, you need to set the desired attribute on the cell
```
td.attr("contentEditable", true)
```

**Comment by n-mam** [comment]
sure thanks.. this worked:

```
  let td = $('#id-camera-right-table td');
  $.each(td, function(){
    $(this).attr("contenteditable", true);
  });
```

**Comment by olton** [comment]
When moving from page to page, the table component completely redraws the `td` elements that are inside the `tbody`. Therefore, you need to use the onDrawCell event.
