### ISSUE TITLE
Website Front Page

### ISSUE THREAD

**Issue by chicagocomputerclasses** [olton/Metro-UI-CSS#1599]
This is unrelated, but your website front page doesn't seem to be properly loading anymore. Like logo and stuff like that.

**Comment by olton** [comment]
All work fine for me, please show screenshot

**Comment by olton** [comment]
![Screenshot_2020-08-12-09-28-55-543_com android chrome](https://user-images.githubusercontent.com/365108/89982440-66fbf600-dc7e-11ea-9069-db037bfaf161.jpg)
