### ISSUE TITLE
Some Select Box Event Handlers Don't Work

### ISSUE THREAD

**Issue by projeffboy** [olton/Metro-UI-CSS#1600]
**Describe the bug**
On v4.3.2, the `onDown` event handler for select boxes doesn't work. `onChange` and `onUp` work.

On v4.3.4, all three handlers don't work.

**To Reproduce**
~~https://codepen.io/projeffboy/pen/OJNNLaw~~ [not a valid link anymore]

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Metro Version: 4.3.2

**Comment by olton** [comment]
update to latest version 4.3.10 from master or 4.4.0 develop

**Comment by projeffboy** [comment]
I tried the exact same thing for v4.3.10, but `onDown` still doesn't work. Here's the new codepen: https://codepen.io/projeffboy/pen/ZEWWKqz

**Comment by olton** [comment]
You must use the attribute `data-on-drop` or event 'drop'
```
$("#select1").on("drop", function () {
    console.log("drop down");
});
```

**Comment by projeffboy** [comment]
Okay, thanks.
