### ISSUE TITLE
Start menu destroy a new item each time

### ISSUE THREAD

**Issue by nash68** [olton/Metro-UI-CSS#1601]
**Describe the bug**
Hi, when using the "start menu" , there is a bug that remove each time an item in the list.

**To Reproduce**
You can try on the demo : https://metroui.org.ua/examples/desktop/desktop.html 
First time you click on the start menu, there is 4 option menu : Youtube, New, Custom, Modal.
Click 3 times on the "windows" icon, there is only 2 option menu left...

**Expected behavior**
Menu list should be always the same.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version 84.0.4147.125 (Build officiel) (64 bits)
 - Metro Version Metro 4 - v4.4.0. Built at: 27/07/2020 13:10:53
m4q - v1.0.7. Built at 25/07/2020 18:43:54

**Additional context**
It seems that with Edge Version 84.0.522.59 (Version officielle) (64 bits) the behaviour is ok.

**Comment by olton** [comment]
Tnx, Remove class `h-100` from an element with class `start-menu-inner`.

**Comment by nash68** [comment]
Works fine now !
Thanks.
