### ISSUE TITLE
Problem with using table in Metro4

### ISSUE THREAD

**Issue by Olena-Alena** [olton/Metro-UI-CSS#1603]
[html.txt](https://github.com/olton/Metro-UI-CSS/files/5098568/html.txt)
[ts.txt](https://github.com/olton/Metro-UI-CSS/files/5098559/ts.txt)

Hello.
I have a problem using a table in Metro4 (Angular 10).
The data that should be displayed in the table is shown only if I set it when defining the variable.
If the variable is assigned a value from the Get-Request to webApi, the table is empty. Although in the console I can see, that the data is received.
Could you tell me what I'm doing wrong. Thank you in advance.

**Comment by Rodolfo-XDR** [comment]
Don't show the table until your invitedUsers.length is greater than 0. Then you'll see that your table will be populated. 
@Olena-Alena
