### ISSUE TITLE
Carousel Fade Effect Bug

### ISSUE THREAD

**Issue by Rodolfo-XDR** [olton/Metro-UI-CSS#1605]
**Describe the bug**
I previously posted an issue on this, but was closed. I even made comments on it, to see if you guys could re open the issue. I thought that carousel component wasn't working correctly when using buttons on slides. Buttons would overlap each other when using carousel. Carousel does work correctly, the bug reproduces as following:

**To Reproduce**
Set Carousel with Fade Effect and place different buttons on different slides. You'll see the bug immediately. 

**Expected behavior**
Buttons should not overlap and should be able to click.

**Screenshots**
![image](https://user-images.githubusercontent.com/49254245/90808379-87165f80-e2e5-11ea-93b7-5433d42ac300.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Metro Version (Metro4 Version Official Page)

**Additional context**
I proposed a solution on the closed thread: 
_If addding "display: none" to the slides that are not shown, maybe that will solve the fade effect issue_

**Comment by olton** [comment]
Thank you, fixed in 4.4.0
