### ISSUE TITLE
"Select at least on checkbox" and validation

### ISSUE THREAD

**Issue by mariusin** [olton/Metro-UI-CSS#1607]
Hey!

Thanks for a wonderful UI library. How can I validate group of checkboxes to check if at least one checkbox is selected with metro validation?

Thanks!

**Comment by Rodolfo-XDR** [comment]
I don't think the actual framework handles that, although you can easily check that with jQuery

https://stackoverflow.com/questions/2204250/check-if-checkbox-is-checked-with-jquery

**Comment by olton** [comment]
Validator can't contain a function to validate this rule, but you can use js to check it:
```
$(function(){
  $("button").on("click", function(){
    var result = $("input[type=checkbox]").is(":checked");
    if (result) {
      alert('One of the checkboxes is checked');
    } else {
      alert('Please check one of the checkboxes!');
    }
  })
})
```
https://codepen.io/olton/pen/jOqyJLz?editors=1010
