### ISSUE TITLE
Clear button on select is not working anymore

### ISSUE THREAD

**Issue by Merenia** [olton/Metro-UI-CSS#1610]
The clear button on select is not working anymore in version 4.3.10.
If I changed to a previous version (ex : 4.3.4), it works.

Code is the same in both version.

**Comment by olton** [comment]
show your code on codepen.io

**Comment by Merenia** [comment]
Hope it helps :

https://codepen.io/Merenia/pen/mdPmwyN

**Comment by olton** [comment]
Thank you, fixed in 4.4.0
