### ISSUE TITLE
table component pagination issue

### ISSUE THREAD

**Issue by n-mam** [olton/Metro-UI-CSS#1611]
Hello,

I am facing an issue with table pagination where the second page is not accessible for a 7 items table (5 per page). The link for the second page is shown only once I cycle from 5 items per page to 10 items per page. I have uploaded a video for this here: https://youtu.be/pQy_1nNXG3g

Could you please advise on what could be causing this issue. The table td's are being rendered on the server. I dont seem to be doing anything else extraordinary.

Neelabh

**Comment by olton** [comment]
show your table code

**Comment by n-mam** [comment]
you could check it live here  http://52.66.251.154:8080/   user test, pwd: test 
from the side nav click the video cam button. This will navigate to the cameras anchor which shows the problematic table with 6 items

relevant server rendering code reproduced below:

     <table
       id=${id + '-table'}
       class="table row-hover text-left striped table-border"
       data-rows="5"
       data-role="table"
       data-check="true"
       data-rows-steps="5, 10"
       data-static-view="true"
       data-show-activity="false"
       data-cls-search="cell-md-8"
       data-cls-rows-count="cell-md-4" 
       data-cls-table-top="row flex-nowrap"
       data-on-check-click="${'On' + handler + 'TableNodeClick()'}"
       data-pagination-wrapper=".my-pagination-wrapper">

      <thead>
       ${renderTH(columnNames)}
      </thead>
      <tbody>
        ${renderTD(rows, columnNames)}
      </tbody>
     </table>

![image](https://user-images.githubusercontent.com/17683324/91431695-5a7ebc80-e87e-11ea-9eab-cf5c77b88a9f.png)

**Comment by olton** [comment]
remove the `data-role` attribute from table and show your rendered `tbody`

**Comment by olton** [comment]
https://codepen.io/olton/pen/JjXNJMz?editors=1000
All works fine, check your data in tbody

**Comment by n-mam** [comment]
rendered tbody after removing data-role="table"

![image](https://user-images.githubusercontent.com/17683324/91438757-82275200-e889-11ea-87a6-b9ac43a892a3.png)

![image](https://user-images.githubusercontent.com/17683324/91438797-9408f500-e889-11ea-8de4-e06bf8162d8c.png)

original with data-role="table"

![image](https://user-images.githubusercontent.com/17683324/91438918-c155a300-e889-11ea-9c17-72c21240f781.png)

**Comment by olton** [comment]
Please in text form, I do not have time to decipher your images and/or translate them into text!

**Comment by n-mam** [comment]
rendered tbody after removing data-role="table"
```
<tbody>
   <tr>
      <td>2</td>
      <td>Webcam-0</td>
      <td>0</td>
      <td>face</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
   <tr>
      <td>3</td>
      <td>Webcam-1</td>
      <td>1</td>
      <td>face</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
   <tr>
      <td>4</td>
      <td>Tapo IP Cam</td>
      <td>
         <div style="white-space: nowrap;overflow:hidden;text-overflow:ellipsis;width: 100px;">rtsp://neelabh.mam:welcome123@10.0.0.1:554/stream2</div>
      </td>
      <td>person</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
   <tr>
      <td>5</td>
      <td>TV(file)</td>
      <td>f:\tv2.mp4</td>
      <td>person</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
   <tr>
      <td>8</td>
      <td>Highway Live</td>
      <td>
         <div style="white-space: nowrap;overflow:hidden;text-overflow:ellipsis;width: 100px;">rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa</div>
      </td>
      <td>car</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
   <tr>
      <td>9</td>
      <td>overpass</td>
      <td>
         <div style="white-space: nowrap;overflow:hidden;text-overflow:ellipsis;width: 100px;">f:\overpass.mp4</div>
      </td>
      <td>person</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
   <tr>
      <td>10</td>
      <td>junk</td>
      <td>junk</td>
      <td>person</td>
      <td>CSRT</td>
      <td>1</td>
      <td>2</td>
      <td>100</td>
   </tr>
</tbody>
```

**Comment by olton** [comment]
activate table after render (thead, tbody) is complete.
1) remove data-role
2) after render complete call $("#Your_table_id").table();

**Comment by olton** [comment]
https://codepen.io/olton/pen/xxVdXbg

**Comment by olton** [comment]
your component is activated before the table data is formed

**Comment by n-mam** [comment]
Thanks, it is fixed now. As suggested, removed data-role="table" and activated the table using $("#Your_table_id").table(); from inside windowonload cbk. With this, pagination works as expected.
