### ISSUE TITLE
Select Component and Array of emails

### ISSUE THREAD

**Issue by Picard1971** [olton/Metro-UI-CSS#1613]
Hi,
if I try to assign an array of emails that contain a dot (like 'aaa.bbb@ccc.com') to a "Select" Component I get this error:
"Cannot read property 'bbb@ccc' of undefined".

There is an error in the function Utils.isObject() that you use at line 23544.
I changed the line
       if (Utils.isObject(val) {
with
      if (!!val && val.constructor === Object) {
and now it works

**Comment by olton** [comment]
show your component code

**Comment by Picard1971** [comment]
HTML: <select id="email_links"   data-role="select"   data-filter="false"   data-cls-select="mr-2 drop-shadow"   data-cls-selected-item="bg-green fg-white"   data-cls-selected-item-remover="bg-red fg-white" multiple></select> JS:Metro.getPlugin("#email_links", "select").data(msg.data); Value:msg.data = [“aaa.bbb@ccc.com”, ”ddd.eee@ccc.com”, ”fff.ggg@ccc.com”]  Da: Serhii PimenovInviato: lunedì 31 agosto 2020 22:40A: olton/Metro-UI-CSSCc: Picard1971; AuthorOggetto: Re: [olton/Metro-UI-CSS] Select Component and Array of emails (#1613) show your component code—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by olton** [comment]
You must use object with key=>value pairs
