### ISSUE TITLE
elements not evaluated after vue update

### ISSUE THREAD

**Issue by patrickelectric** [olton/Metro-UI-CSS#1614]
**Describe the bug**
New elements are not evaluated by metro

**To Reproduce**
```
<li data-icon="<span class='mif-library'></span>" data-caption="Hearbeat"></li>
<li v-for="key in keys" data-icon="<span class='mif-library'></span>" data-caption="Hearbeat"></li>
```
The second element is updated by vue
**Expected behavior**
That all elements get updated

**Screenshots**
The first one is the correct rendered DOM by metroui, the second is one is vue subproduct 
![image](https://user-images.githubusercontent.com/1215497/91927060-083f0080-ecaf-11ea-9ae6-eb88ed146d41.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Metro Version: 4.3.10

**Additional context**
I did try to call metro.init() for each tick but it did not work, any tips ?

**Comment by olton** [comment]
https://metroui.org.ua/vuejs.html

**Comment by olton** [comment]
if component already initiated, you must add node in full mode, with children elements: icon and caption.

**Comment by olton** [comment]
Unfortunately, at the moment Metro 4 is not tested for Vue, and does not take into account the features of this framework.

**Comment by patrickelectric** [comment]
Hi @olton thank you for your reply, I'm using metro ui documentation for vue, will try to create a minimal example just to have it documented here.

**Comment by olton** [comment]
https://codepen.io/olton/pen/dyMeYxp

**Comment by patrickelectric** [comment]
Hi @olton, yes it works when the values are predefined, but I'm getting the values from a websocket, as you can see in my screenshot the elements are all not rendered by metro. I'm calling vue update manually after I receive my data from websocket.

**Comment by olton** [comment]
Please create example on codepen.io

**Comment by patrickelectric** [comment]
Hi @olton, I'll asap, just need to finish some things first.

**Comment by olton** [comment]
use next code:
```
<li v-for="key in keys">
    <span class="icon"><span class="mif-library"></span></span>
    <span class="caption">Hearbeat</span>
</li>
```

**Comment by patrickelectric** [comment]
Minimal test that replicates my issue: https://codepen.io/pen/?template=JjXZMWd


> use next code:
> 
> ```
> <li v-for="key in keys">
>     <span class="icon"><span class="mif-library"></span></span>
>     <span class="caption">Hearbeat</span>
> </li>
> ```

With this it work, but with `<li v-for="key in keys" data-icon="<span class='mif-library'></span>" data-caption="Hearbeat"></li>` nops

**Comment by olton** [comment]
parsing of attributes occurs at the moment of creating a component, in the future you need to use either api methods to add / remove nodes, or use the full form of a node.
