### ISSUE TITLE
SELECT: option with own attr don't work

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1616]
Hi Olton!

Example at:

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

I have associated two attributes (data-year and data-status) to each OPTION of a SELECT.

How can I get the attribute values of the selected OPTION?

I tried with

```
// Try sintax 1
console.log($("#MACHINE option:selected").attr("data-year"));

```
and

```
// Try sintax 2
console.log($("option:selected", this).attr("data-year"));

```
but neither works!

Thank's!

**Comment by olton** [comment]
m4q not support syntax `option:selected` for queries this is specified for jQuery. use `option:checked`

**Comment by TorakikiSan** [comment]
Perfect!
