### ISSUE TITLE
Some table API, how is using be better?

### ISSUE THREAD

**Issue by ncxn** [olton/Metro-UI-CSS#1617]
Hello everyone, 

With Table component:  I use API to load /add new / update / delete row

here: https://codepen.io/ncxn/pen/poyrVyd

1) Is there a better way?
2) how to get [index] of selected items, ex: table.getselectedItems().index() => [0,1,3...]? 

--------------------
thanks, 
ncxn,

**Comment by olton** [comment]
> how to get index
In the component `table`  for indexes uses values from the field, defined with attribute `data-check-col-index`  (default 0). This is an integer value, the number field in the dataset begins from zero. To get keys for selected items use the API method `getStoredKeys()`. This method return array of key values.
```
var keys = Metro.getPlugin("table", "table").getStoredKeys();
```
