### ISSUE TITLE
Problem with event for button in the table

### ISSUE THREAD

**Issue by Olena-Alena** [olton/Metro-UI-CSS#1618]
Hello all,
unfortunately I have the problem with button in the the table. My function for "click " does not run on the real click. But if comment the part of code : data-role="table", then it works

Thanks
[admin-user-html.txt](https://github.com/olton/Metro-UI-CSS/files/5175943/admin-user-html.txt)
[admin-user-ts.txt](https://github.com/olton/Metro-UI-CSS/files/5175944/admin-user-ts.txt)

**Comment by olton** [comment]
use leave event:
```
$("table_selector").on("click", "button_selector", function (e){...})
```

**Comment by Olena-Alena** [comment]
I'm new in angular and don't understand the answer.
Where exactly should I write this. 
And it seems it is not typescript.

**Comment by olton** [comment]
You must use delegate events. Add event handler for click to table element, and delegate it to buttons in cells. 

About event delegation https://javascript.info/event-delegation#:~:text=Capturing%20and%20bubbling%20allow%20us,handler%20on%20their%20common%20ancestor.
