### ISSUE TITLE
$.remove  element input and select

### ISSUE THREAD

**Issue by ojosojo** [olton/Metro-UI-CSS#1619]
Hi. When trying to do a **$.remove( selector )** it does not remove form elements input and select.

**To Reproduce**
https://codepen.io/nafurset/pen/QWNOoWJ

**Expected behavior**
I expected that the rendered object would be removed from DOM 

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.6
 - Chrome 84.0.4147.125
 - Metro Version  4.3.9

**Additional context**
I have also tried to uso **Metro.destroyPlugin**  and **Metro.destroyPluginAll**  with no success.

Regards.

**Comment by olton** [comment]
most of the components have a complex structure, so it is not enough to remove the base element, its wrapper will remain. Example, To remove select you must call api method `destroy`, this method removes all event handlers and return base element. Then you must wrapper and remove it:
```
var sel = Metro.getPlugin(el, "select");
var el = sel.destroy();
var wrapper = $(el). closest (".select");
wrapper.remove();
```

**Comment by ojosojo** [comment]
Perfecto, yes I added a <div> wrapper around the element then just removed it.

Thanks !
