### ISSUE TITLE
Validator - validating radio button error when name is array with index

### ISSUE THREAD

**Issue by nlared** [olton/Metro-UI-CSS#1620]
Bug
Document.querySelectorAll: 'input[name=data[lider_sexo]]:checked' is not a valid selector

**To Reproduce**
<label for="data_p1_sexo">Sexo<br></label><input type="radio" name="data[p1_sexo]" id="data_p1_sexo_0" value="Masculino" data-role="radio" data-caption="Masculino" /><input type="radio" name="data[p1_sexo]" id="data_p1_sexo_1" value="Femenino" data-role="radio" data-caption="Femenino" />

**Expected behavior**
fix the use of name tag with array

 - OS: all
 - Browser all
 - Metro Version  4.3.10

**Comment by olton** [comment]
querySelectorAll is DOM JS function, not a Metro 4 routine.

**Comment by nlared** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/source/components/validator/validator.js 
Line 212
var radio_selector = 'input[name=' + input.attr('name') + ']:checked';

input.attr('name') need to be escaped

**Comment by nlared** [comment]
https://codepen.io/enrique-flores-rodr-guez/pen/PoNejzz

**Comment by olton** [comment]
ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".")

https://www.w3.org/TR/html4/types.html#type-cdata

**Comment by nlared** [comment]
yes  NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".")

 but 
**CDATA** is a sequence of characters from the document character set and may include character entities. User agents should interpret attribute values as follows:

    Replace character entities with characters,
    Ignore line feeds,
    Replace each carriage return or tab with a single space.
when you use [ on inputs the backend interpret these like arrays, the line that you describe is about the begin of the name
<input name="begin"> input normal
<input name="begin[]"> input array dynamic
<input name="begin[1]"> input array width key
<input name="begin[1][subkey]"> input array width key
<input name="[]begin">this is invalid  this about begin whit letters etc etc

when you use especial chars the browsers send entities for these and asp y php decode when are [] convert to arrays

**Comment by olton** [comment]
Metro use for queries `document.querySelectorAll`, and this method throw exception. If you present working example for your case where it works, I'm add it to Validator in Metro 4. Thx

**Comment by olton** [comment]
Thank you, Fixed in 4.4.0

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/4.4.0/source/components/validator/validator.js#L214
