### ISSUE TITLE
Event calender

### ISSUE THREAD

**Issue by gakyuz** [olton/Metro-UI-CSS#1621]
In the month calender component, Is there a way display one or more events in a day ?
 If not is there a plan to add.

**Comment by olton** [comment]
there is no such functionality in the current version, but in the future it will most likely be implemented.

**Comment by olton** [comment]
In 4.4.3 I added the attribute `data-events` - to display events inside days. Showing only counts events for the specified day.

Example: https://codepen.io/olton/pen/MWeNvxy?editors=1010

**Comment by olton** [comment]
![2020-11-23-17-22-30](https://user-images.githubusercontent.com/365108/99980079-81cb2400-2db0-11eb-9d45-a7ef9a30f54f.png)
