### ISSUE TITLE
Destroy plugin not working

### ISSUE THREAD

**Issue by waretec** [olton/Metro-UI-CSS#1622]
**Describe the bug**
Destroying a plugin throws script error
**To Reproduce**
https://jsfiddle.net/dfh7uwe8/1/

**Expected behavior**
I thought I can destroy a plugin, add some html and create it again. Am i wrong? I want to achieve some kind of a reinit functionality...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome 85
 - Metro Version: 4.3.10

**Comment by olton** [comment]
About destroy method - https://github.com/olton/Metro-UI-CSS/issues/1619#issuecomment-687549987

To add, delete, or update data in the table component, you must use TABLE COMPONENT API METHODS: setItems, setData, loadData, addItem, addItems, updateItem, deleteItem, deleteItemByName, ... You can read about methods in docs or get details in sources - https://github.com/olton/Metro-UI-CSS/blob/master/source/components/table/table.js#L1581

**Comment by waretec** [comment]
About the method: I did it exactly like you suggested in your comment. But the .destroy() function throws an exception.
I'd need the destroy function in several usecases for different components, but the function always throws an error

**Comment by olton** [comment]
please describe your case where you use destroy method

**Comment by waretec** [comment]
For example: cascading select components. 
After selecting the first option in the first component remove/add options in the second select component. 
Since I didn't find any API method to manipulate the options, I tried to destroy the plugin, removed the unnecessary options and made it a plugin again. 

Should plugin.destroy() be used at anytime?

**Comment by olton** [comment]
https://github.com/olton/Metro4-Docs/tree/master/public_html/examples/ajax

**Comment by olton** [comment]
use method data from select api https://github.com/olton/Metro-UI-CSS/blob/master/source/components/select/select.js#L543

**Comment by waretec** [comment]
Thx, I really appreciate the help!
