### ISSUE TITLE
Shadow-DOM support

### ISSUE THREAD

**Issue by rafalsk** [olton/Metro-UI-CSS#1623]
First of all thank you for the wonderful library. We've been having trouble using Ribbon within Shadow-DOM. Tried loading Metro's JavaScript?CSS from within it and externally from light-dom, to no avail. Maybe it's the same case as with Bootstrap who simply for now does not support and there's no easy way around it? 

The effect is that the Metro's elements remain raw and 'not-rendered'

**Comment by olton** [comment]
Please, create an example with your problem on codepen.io

**Comment by rafalsk** [comment]
Olton, please, here's a sample:
[https://codepen.io/rafalsk/pen/KKzREaX](url)

**Comment by olton** [comment]
https://codepen.io/olton/pen/bGpMyJE?editors=1010

**Comment by olton** [comment]
But this is not a good way, because you will download CSS for each shadow.
