### ISSUE TITLE
data-label missing on data-role="calendarpicker"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1627]
Hi Olton!

data-label is a **great feature** but is missing with "calendarpicker" type fields. Is there a possibility that it will also be included in these?

Thank's!

**Comment by olton** [comment]
Added to 4.4.0
+ [x] Calendar picker: add attribute `data-label`. If this attribute defined, `label` element for input will be created automatically.
+ [x] Time picker: add attribute `data-label`. If this attribute defined, `label` element for input will be created automatically.
+ [x] Date picker: add attribute `data-label`. If this attribute defined, `label` element for input will be created automatically.

**Comment by TorakikiSan** [comment]
Awesome!
