### ISSUE TITLE
Problem with data-role="file"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1631]
Hi Olton, I have a little problem with drop-role = "file"

Example

https://codepen.io/TorakikiSan/pen/EeyWmp

Any type of file I pass to it with "drag & drop" the border turns green but always writes "0 file (s)" and if I click on it with the mouse, the window for choosing the file does not open.

I took the code in the component documentation as an example at https://metroui.org.ua/file.html and here the field works perfectly.

Any hint?

Thank's

**Comment by olton** [comment]
add attribute `type="file"` to input
