### ISSUE TITLE
Countdown Component

### ISSUE THREAD

**Issue by Dexilez** [olton/Metro-UI-CSS#1632]
Hello,

I was testing countdown component and i found out that some values are printing wrong.

Example:

Date is **9/19/2020 6:57pm** right now.
My code is: 
`<span data-role="countdown" data-date="11/19/2020 00:00:00" id="countdownItems" class="countdownItems">`
Output is:
![resim](https://user-images.githubusercontent.com/70412161/93671260-2e83df00-faaa-11ea-81cf-78e8aa799b34.png)
It should be
60 Days
05 Hours
01 Mins
06 Secs

If i change my code to:
`<span data-role="countdown" data-date="11/20/2020 00:00:00" id="countdownItems" class="countdownItems">`
Output is:
![resim](https://user-images.githubusercontent.com/70412161/93671302-7efb3c80-faaa-11ea-816f-2c4ac3d26662.png)

and this is correct.

I want to learn if i do anything wrong in my code but i don't think so. Is that a bug? I am looking forward for your answer.

Thanks.
Regards.

**Comment by olton** [comment]
use date format `mm/dd/yyyy`

**Comment by Dexilez** [comment]
> 
> 
> use date format `mm/dd/yyyy`

I am already using it like that or did i get you wrong? @olton 
`data-date="11/20/2020"`
isn't it mm/dd/yyyy?

**Comment by Dexilez** [comment]
one more example

This is correct:
![resim](https://user-images.githubusercontent.com/70412161/93671590-e9ad7780-faac-11ea-9350-d80443ec936b.png)

This is wrong:
![resim](https://user-images.githubusercontent.com/70412161/93671600-f762fd00-faac-11ea-9923-ea7e3fe5ce62.png)
it should be 10 hours. but 0 and 1 changes places.

**Comment by olton** [comment]
Thank you. It's strange. This bug appears for any month on the 19th :0

**Comment by Dexilez** [comment]
> 
> 
> Thank you. It's strange. This bug appears for any month on the 19th :0

not 19th of the month actually.
Something strange is happening when 0 comes near any number. whether it is days, hours, minutes or seconds.

```
10
20
30
40
50
...
```

These are appears as:

```
01
02
03
04
05
... 
```

and so on

**Comment by olton** [comment]
Thanks, bug confirmed in a draw function.

**Comment by olton** [comment]
Fixed in 4.4.0, Please check it...

**Comment by Dexilez** [comment]
Done! Thanks @olton
