### ISSUE TITLE
No way to disable datepicker element

### ISSUE THREAD

**Issue by EastSideAngus** [olton/Metro-UI-CSS#1633]
How does one set a datepicker element as readonly either on initialization or later through a JS call? 

I've tried attributes like **disabled** and **readonly** on the input element with data-role being datepicker, but they don't work.

I've tried using the data- prefix, but that doesn't seem to do the trick.
 
I would expect there is some way to disable an input element of type datepicker. Is that the case or no?

Thank You

**Comment by olton** [comment]
Fixed in 4.4.0
+ [x] Date picker: added methods `enable()`, `disable())`, `toggleState()`, added observing for prop `disabled`, issue #1633

**Comment by olton** [comment]
to disable `datepicker` use property disabled for input element:
```html
<input data-role="date-picker" disabled data-label="Select date" id="p3">

<button class="button" onclick="$('#p3').prop('disabled', false)">Enable picker</button>
<button class="button" onclick="$('#p3').prop('disabled', true)">Disable picker</button>
```

**Comment by olton** [comment]
Thank you for this request.
