### ISSUE TITLE
<select> not able to change background color dynamically (using java script)

### ISSUE THREAD

**Issue by raghunath004** [olton/Metro-UI-CSS#1634]
dear sir,

'select' component not able to change background color dynamically (using java script) data-role='select'
if i am not using data-role='select' its working fine but not able to use data-append or data-prepend in this case

**Comment by olton** [comment]
https://codepen.io/olton/pen/jOqJaKv

**Comment by raghunath004** [comment]
sir i am facing problem in react js (not using react metro)

**Comment by olton** [comment]
https://github.com/olton/Metro4-React
