### ISSUE TITLE
onClick on tiles is triggered twice

### ISSUE THREAD

**Issue by ngirot** [olton/Metro-UI-CSS#1636]
**Describe the bug**
I mixed metro-ui with react, and i tried to add an onClick event on a tile.
The issue is that the onclick event is triggered twice.

**To Reproduce**
https://codepen.io/ngirot/pen/JjXVGER

There is two item, triggered the same increment function
- one is triggered once (the one on the button)
- the second is triggered twice (the one on the tile)

**Expected behavior**
The onClick event should be triggered once.

**Desktop (please complete the following information):**
 - OS: Linux Fedora 
 - Browser Firefox 81.0
 - Metro Version 4.3.2

**Comment by olton** [comment]
use attribute `data-on-click`. https://codepen.io/olton/pen/xxVegJK

**Comment by ngirot** [comment]
The bug comes from the mix between metro & React, if you remove React, yeah, it works...
So, maybe I didn't understand your answer, but if I use 'data-on-click' on my codepen, it doesn't increment the counter at all.

**Comment by olton** [comment]
Fixed in 4.4.1
+ [x] Tile: fixed double firing click event. Component internal event `onClick` renamed to `onTileClick` (attribute `data-on-click` => `data-on-tile-click`)

**Comment by olton** [comment]
https://codepen.io/olton/pen/rNebmpG?editors=1011

**Comment by ngirot** [comment]
The 4.4.1 version fixed my issue. Thank you very much for your fix and responsiveness.
