### ISSUE TITLE
window in react 

### ISSUE THREAD

**Issue by raghunath004** [olton/Metro-UI-CSS#1637]
how to pass functions for html attributes sir (please check data-on-resize)

its not working like this

`export const DrawWindow = (props) => {
    const handle = useFullScreenHandle()
    function resized(size) {
        console.log(size)
    }
    return (
        <div
            className='m-0 p-0 bg-red'
            data-role='window'
            data-resizable='true'
            data-height='480'
            data-width='480'
            data-place='top-left'
            data-title="Draw Panel"
            data-icon="<span class='mif-apps'></span>"
            data-shadow="false"
            data-btn-close="true"
            data-btn-min="false"
            data-btn-max="false"
            data-on-resize='resized'
        >
            <div className={'w-100 h-100'}>
                <FullScreen handle={handle}>
                    <div className={'d-flex flex-row'}>
                        <DrawSideMenu handle={handle}/>
                        <div className={'d-flex w-100'}>
                            <Canvas2d/>
                            <DrawInputPanel/>
                        </div>
                    </div>
                </FullScreen>
            </div>
        </div>
    );
};`

**Comment by olton** [comment]
Please respect my time, format your code and create examples in codepen.io

**Comment by olton** [comment]
This is a question you should ask the React developers.
