### ISSUE TITLE
Destroy and Add options to a data-role="select"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1638]
Hi Olton!

II tried with the usual methods I know to "destroy" an input field with data-role = "select" and then to add options, then make it "dynamic" through an ajax call

I usually used this syntax

```
  $("#DISPSWITCH")
    .empty()
    .append("<OPTION value=''></OPTION>")
    .append("<OPTION value='0' class='fg-orange'>NEW DIPSWITCH</OPTION>")
    .val("");

```
but it does not work.

What am I doing wrong?

Thank's

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1622#issuecomment-690026268

**Comment by olton** [comment]
Currently, the destroy method does not destroy components, it only cancels the attached event handlers and returns the base element. This is done so that the library can be used in conjunction with such frameworks as react, vue, ... To replace option, use the API data method of the select component.

**Comment by TorakikiSan** [comment]
The .data () method does not seem to support a multirecord Json file, with two fields, key and description, for example like this:

```
[
  {"machine": "mrdo", "description": "Mr Do!"},
  {"machine": "xevious", "description": "Xevious"}
]
```

There is a work-around?

**Comment by olton** [comment]
Currently, you must use a plain object with pairs `key => value`:
```
var options = {
    key1: value1
    ...
    keyN: valueN
}
```

**Comment by TorakikiSan** [comment]
Example at

https://codepen.io/TorakikiSan/pen/EeyWmp

How can I do to view the OPTIONS in the desired order? In the example, NEW DIPSWITCH and Empty Option are swapped positions.

Thank's!

**Comment by olton** [comment]
The component does not sort elements in your object. The component gets options already sorted, You can check it with `console.log(tVALUE);`
```javascript
$(document).ready(function() {

  $(document).on("click", "#SET-DATA", function(e) {
    e.preventDefault();

    var tDIPSWITCH=Metro.getPlugin("#DIPSWITCH", "select");
    var tVALUE={"&nbsp;" : "&nbsp;",
                "0": "NEW DIPSWITCH",
                "T": "Time",
                "L": "Lives",
                "H": "Health",
                "C": "Coins"
               }
    console.log(tVALUE);
    tDIPSWITCH.data(tVALUE);
    tDIPSWITCH.val("");

   });

 });
```
