### ISSUE TITLE
Table cell color.  How to?

### ISSUE THREAD

**Issue by paloky** [olton/Metro-UI-CSS#1641]
Hi Olton.
I try to put a color on a specific cell into table. like    https://metroui.org.ua/tables.html   ( "Colored Table" section ).

I try to use a  [ class="info" ]  and   [data-cls ="bg-green"]  but this don't work when I use  [ data-role="table" ]

How can I change a specific cell colors using  [data-role="table" ] ??

Here a CodePen Sample
https://codepen.io/paloky/pen/BazaLYK

Thank a lot.

**Comment by olton** [comment]
Classes who defined in attributes `data-cls-head-cell` and `data-cls-body-cell`, applied to all cells in a table. To apply classes to a specified cell, you must use event `data-on-draw-cell`.

Example using event `onDrawCell`
https://codepen.io/olton/pen/rNNmxaB
