### ISSUE TITLE
Select option text manipulation after selected

### ISSUE THREAD

**Issue by akayueh** [olton/Metro-UI-CSS#1642]
Hi

I am trying to work out how to do this... here are my structure:

```
<optgroup label="Microsoft">
<option value="microsoft-usa">USA</option>
<option value="microsoft-usa-alabama">Alabama<option>
<option value="microsoft-usa-alaska">Alaska<option>
</optgroup>

<optgroup label="Apple">
<option value="apple-usa">USA</option>
<option value="apple-usa-alabama">Alabama<option>
<option value="apple-usa-alaska">Alaska<option>
</optgroup>
```

As you can see both "Microsoft" and "Apple" share the same geo-locations in their list, but when say I selected the "USA" for both of outgroup, the selected item simply says "USA", and there is no way to identify which company it belongs too.

Is there a way for me to manipulate the option label or display text after an item been selected, so it somehow displays something like "Microsoft - USA" and "Apple - USA"?  I think "**data-on-item-select**" event only trigger after the item been moved?

**Comment by akayueh** [comment]
I am also throw in another suggestion, that when a cascading option been presented, there can be an option to remove all the sub-level options.

For example, if someone selects the country USA, all the States under USA should be removed as the top tier already cover the selection...

**Comment by olton** [comment]
In 4.4.1. I'm added
Select: added attributes `data-show-group-name="true|false"` (default - **false**), `data-short-tag="true|false"` (default - **true**)

Example: https://codepen.io/olton/pen/oNLLENZ

**Comment by olton** [comment]
> I am also throw in another suggestion, that when a cascading option been presented, there can be an option to remove all the sub-level options.
> 
> For example, if someone selects the country USA, all the States under USA should be removed as the top tier already cover the selection...

Work with cascading values is not planned in the near future.

**Comment by akayueh** [comment]
Hi @olton

Here is a quick sample of the function I described, maybe you can consider it.  It is not the best code, just something quick and simple to illustrate.

https://codepen.io/akayueh/pen/rNLdeYE
