### ISSUE TITLE
Options added to <select> after an event functions not showing

### ISSUE THREAD

**Issue by petrjahoda** [olton/Metro-UI-CSS#1644]
**Describe the bug**
I created a simple selection in html:
`<select data-role="select" data-prepend="<span class='mif-lines'></span>" id="operation-select">
            </select>`

In javascript I added a function, after a button is clicked, this function add option to this select, for example:
`var option = document.createElement("option");
    option.text = "TEST";
    option.value = "TEST";
    operationSelect.append(option);`

After a button is clicked, I can see that <option> is added to dom, but not shown in the browser.
When i remove `data-role="select"` from html select element, it shows, see screenshots

**Screenshots**
<img width="1085" alt="Screenshot 2020-10-15 at 11 31 29" src="https://user-images.githubusercontent.com/45359845/96105248-1bfa9b00-0eda-11eb-8729-f9cc19bda76f.png">
<img width="1099" alt="Screenshot 2020-10-15 at 11 30 37" src="https://user-images.githubusercontent.com/45359845/96105278-2321a900-0eda-11eb-9976-b41008668186.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari and chrome tested
 - Metro Version 4.4.0

**Comment by olton** [comment]
to change select options, you must use api method `data()`. Please read closed issues for this future. I have already answered this question many times.
