### ISSUE TITLE
Color gradient

### ISSUE THREAD

**Issue by rod-farias** [olton/Metro-UI-CSS#1645]
This is just a feature suggestion for Metro4, it is not due to any issues.

Maybe you could include a color gradient facilitator. I'm not sure how to do it, maybe something like this:

`<div data-role='gradient' data-from='red' data-to='lightRed' data-direction='vertical' />`
`<div data-role='gradient' data-color='red' data-mode='analog' />`
`<div data-role='gradient' data-color='red' data-to='darken' />`
`<div data-role='panel' data-bg-style='gradient' />`

Thank you Olson for your work, Metro4 is really easy, stylish and complete.

**Comment by olton** [comment]
new in 4.4.1, added component `gradient-box`

Example: https://codepen.io/olton/pen/GRqZXvv

**Comment by rod-farias** [comment]
Wow! That was fast.
Thank you very much!!!

**Comment by olton** [comment]
Hi! In 4.4.2 gradient-box attributes will change, but all options will be described in docs after release.
