### ISSUE TITLE
progress: can't set data-cls-bar as darkgray

### ISSUE THREAD

**Issue by patrickelectric** [olton/Metro-UI-CSS#1646]
**Describe the bug**
Can't set data-cls-bar color darkgray

**To Reproduce**
https://codepen.io/patrickelectric/pen/ExyKYgX

**Expected behavior**
data-cls-bar should be darkgray

**Screenshots**
![image](https://user-images.githubusercontent.com/1215497/96195272-b5e63600-0f22-11eb-9f78-43589c3444c6.png)

**Comment by rod-farias** [comment]
I think css is case-sensitive. You may try with **bg-darkGray**.
