### ISSUE TITLE
data-role="carousel"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1647]
Hi Olton!

A little help/hint!

Regardless of the video resolution (ex. 1680x1050 or 1920x1080 or 3840x2160), I would like to display various images (old arcade screen shoots) in the center of the screen with the object data-role="carousel". All screen shoots have a fixed width (640px) and variable height. I use

```
<DIV data-role = "carousel"
      data-auto-start = "true"
      data-controls-on-mouse = "true"
      data-cls-controls = "fg-white"
      data-bullet-style = "square"
      data-period = "3000"
      data-duration = "1000"
    >
    <DIV class = "slide" data-cover = "/snaps/bankp-640px.png"> </DIV>
    <DIV class = "slide" data-cover = "/snaps/mrdo-640px.png"> </DIV>
    <DIV class = "slide" data-cover = "/snaps/pacman-640px.png"> </DIV>
    <DIV class = "slide" data-cover = "/snaps/rodland-640px.png"> </DIV>
    <DIV class = "slide" data-cover = "/snaps/xevious-640px.png"> </DIV>
</DIV>

```
but the image is displayed full screen.

Is there a way to center in X and Y without resizing them?

Thank you!

**Comment by olton** [comment]
You can set a fixed width for the carousel via the data-width = "640" attribute.

**Comment by TorakikiSan** [comment]
```
<DIV data-role="carousel"
     data-auto-start="true"
     data-controls-on-mouse="true"
     data-cls-controls="fg-white"
     data-bullet-style="square"
     data-period="3000"
     data-duration="1000"
     data-width="640px"
   >

```
This are 2 sample images (same width, different height)

![rodland-640px](https://user-images.githubusercontent.com/37299746/96255328-04451480-0fb7-11eb-93de-8ff6f4d27a73.png)

![xevious-640px](https://user-images.githubusercontent.com/37299746/96256579-33f51c00-0fb9-11eb-93fb-344761b39ce8.png)

but nothing is changed!

**Comment by olton** [comment]
640 without px

**Comment by TorakikiSan** [comment]
Sorry for the "px", but I tried both with and without and nothing has changed.

**Comment by olton** [comment]
Fixed in 4.4.1
+ [x] Carousel: fixed usage attribute `data-width`, now this attribute applied to `max-width` css property for carousel

**Comment by olton** [comment]
In the current version, slides fill the entire carousel according to its width and the rule for height. You can set the width for the carousel (already fixed). or put the image inside the slide.

**Comment by olton** [comment]
I'm added in 4.4.1 new component `ImageBox` - https://codepen.io/olton/pen/GRqZBVN

**Comment by TorakikiSan** [comment]
Thank you very much!
