### ISSUE TITLE
Splitter stucks in resize mode

### ISSUE THREAD

**Issue by Kasper1985** [olton/Metro-UI-CSS#1649]
**Describe the bug**
By starting resizing of panels in splitter through drag of splitter comes a mouse unavailable mode (cossed circle) and aftre this the splitter stucks in resizing mode. One can't move a mouse without moving the splitter.

**Expected behavior**
After mouse up event, the resizing mode should be off

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Metro Version [e.g. 4.3.4]

**Comment by olton** [comment]
This issue is closed in older versions.
