### ISSUE TITLE
class="button cycle", icon layout shift to left ???

### ISSUE THREAD

**Issue by one0410** [olton/Metro-UI-CSS#1650]
**Describe the bug**
When upgrade from 4.4.0 to 4.4.1, layout of cycle button will change to left,
Pls see the following scrrenshot

**To Reproduce**
N/A

**Expected behavior**
icon should be center layout

**Screenshots**
![image](https://user-images.githubusercontent.com/11656628/96551233-8baac480-12e4-11eb-9094-4602fef9ce8f.png)

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1648
