### ISSUE TITLE
select is undefined

### ISSUE THREAD

**Issue by ocea1979** [olton/Metro-UI-CSS#1651]
Why get select is undefined ??
`<select id="ddlCaja01" runat="server" name="ddlCaja01" 
                            data-role="select" data-add-empty-value="true" data-clear-button="true"
                            data-on-item-select="onItemSelect"
                            style="width:100px"  />
`

`function onItemSelect(el) {        
        var select = $(el).data('select');
        console.log(select.val());
    } `

**Comment by olton** [comment]
https://metroui.org.ua/components-api.html

**Comment by ocea1979** [comment]
![imagen](https://user-images.githubusercontent.com/73247610/96761730-d38e2200-139e-11eb-88fb-0bb49b4ee7e4.png)
 
select is undefined

usign your example [https://github.com/olton/Metro4-Docs/blob/master/public_html/examples/ajax/select.html](url)

tks for your time

**Comment by olton** [comment]
And..? Example work fine https://metroui.org.ua/examples/ajax/select.html without errors
