### ISSUE TITLE
SELECT: data-show-group-name minor display bug

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1652]
Hi Olton!

Code at

https://codepen.io/TorakikiSan/pen/EeyWmp

If I select an item from the Categories field, it's correctly displayed with the group name after the item.

If instead I set the value via javascript, only the value is displayed, not the group name.

Thank's!

**Comment by olton** [comment]
Thx. fixed in 4.4.2

**Comment by TorakikiSan** [comment]
Thank's to You!
