### ISSUE TITLE
Hint for Dialog on Submit

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1653]
Hi Olton!

Code at

https://codepen.io/TorakikiSan/pen/EeyWmp

I would like the Dialog to be displayed in case the three parameters are all empty.

If I answer YES the search continues, with NO the search stops.

But it does not work, the Dialog is displayed for a while, it does not wait for the response and the JS code continues normally.

Where did I go wrong?

Thank you!

**Comment by rod-farias** [comment]
MetroUI components are wrappers that decorate form controls.
The documentation tells how to access the value of the control from the component.

You are getting like this:
`var tTYPE = $("#TYPE").val(); //NOT WORK`

...but you should do it like this:
`var metro4Select = $("#TYPE").data('select');`
`var tTYPE = metro4Select.val();  //OK`

**Comment by olton** [comment]
https://codepen.io/olton/pen/oNLBgJK?editors=1011

**Comment by TorakikiSan** [comment]
Thank's to both!

**Comment by TorakikiSan** [comment]
Olton, one final clarification / explanation.

I always use <BUTTON and stop, while in your example there is the attribute type="button".

With the attribute ypur JS script works, while without it it does not. Why this behavior?

**Comment by olton** [comment]
without attribute type=button input work as submit, but in this example, we need manual form submitting.

**Comment by TorakikiSan** [comment]
Many thank's for explanation
