### ISSUE TITLE
Windows - Where is my error?

### ISSUE THREAD

**Issue by Manyletoulousain** [olton/Metro-UI-CSS#1655]
**Describe the bug**
           I would like to create a window hidden at the begining. and show it later

**To Reproduce**
         in my index.php

       <div 
 			id="my" 
 			data-role="window" 
 			class="no-visible"
 			data-place="center"
 			data-width="500"
 			data-height="600"
 			>
                This is a simple window
       </div>

**Expected behavior**
      class="no-visible": has no effect. the window is visible.

Where is my error?? any idea?
thank you

**Comment by olton** [comment]
use attribute `data-hidden="true"`, and api method `show ()` when you need open window

**Comment by Manyletoulousain** [comment]
Thank you
