### ISSUE TITLE
onDown function for select

### ISSUE THREAD

**Issue by akayueh** [olton/Metro-UI-CSS#1657]
The "onDown" function doesn't seem to be firing up when I click on the select droplist, or am I misunderstand its usage?

https://codepen.io/akayueh/pen/rNLdeYE

Google Chrome, Version 86.0.4240.183 (Official Build) (64-bit), Windows 10 Pro

**Comment by akayueh** [comment]
Found another thread in here with the same issue, and the correct attribute for the function is now "data-on-drop", not "data-on-down"

**Comment by akayueh** [comment]
![image](https://user-images.githubusercontent.com/3982857/98183112-8e9beb00-1f5b-11eb-9c3c-bc80b3a68e3a.png)

The document still shows "data-on-down"

https://metroui.org.ua/select.html

**Comment by olton** [comment]
fixed, thanks
