### ISSUE TITLE
How to change buttons propierties of "Timepicker"?

### ISSUE THREAD

**Issue by paloky** [olton/Metro-UI-CSS#1659]
It is possible change the propierties of "Buttons" of the "Timepicker" ??
Basically the colors.

In the documentation, it just mentions:
"data-cls-picker, data-cls-part, data-cls-hours, data-cls-minutes, data-cls-seconds"

Can it be modified using the "data-cls-part" perhaps?

![imagen](https://user-images.githubusercontent.com/5292503/98344942-42f94800-2014-11eb-9eea-f6fb1dd8c986.png)

Thanks  a lot.
Best regards.

**Comment by olton** [comment]
```css
.my-picker .action-block .button{
   ...styles for button...
}

.my-picker .action-block .button-ok{
   ...styles for ok button...
}

.my-picker .action-block .button-cancel{
   ...styles for cancel button...
}
```
and
```html
<input data-role="time-picker" data-cls-picker="my-picker">
```

**Comment by olton** [comment]
in 4.4.2 I added attributes to `timepicker`.
+ [x] Timepicker: added attributes `data-cls-button`, `data-cls-ok-button`, `data-cls-cancel-button` to modify picker buttons style.
