### ISSUE TITLE
navview menu item inccorrect height

### ISSUE THREAD

**Issue by bekatd** [olton/Metro-UI-CSS#1661]
Two problems with Navigation View menu version 4.4.2

Problem with height:
![image](https://user-images.githubusercontent.com/6948919/98514927-b05ee000-2283-11eb-8705-d810da861e4f.png)

I guess it is related to the `line-height` set to `48px` instead of `40px` for `a` tags in the menu.
![image](https://user-images.githubusercontent.com/6948919/98515632-c5883e80-2284-11eb-9b7f-9f0a547761bb.png)

Problem with on `hover`
![image](https://user-images.githubusercontent.com/6948919/98514997-ce2c4500-2283-11eb-9aa8-5a729d26c260.png)

this issue gets fixed after removing border and adjusting height
![image](https://user-images.githubusercontent.com/6948919/98515724-ea7cb180-2284-11eb-89e5-b89061365169.png)

Would be great to remove border from menu items, its redundant imo

So, fix is just to set the `height` and `line-height` of `.navview .navview-menu li a` to `40px` and remove the border at all.

**Comment by bekatd** [comment]
Thanks for a quick response, but border also needs to be removed from menu items or considered in height of menu element to resolve second issue

**Comment by olton** [comment]
The issue with hover already fixed

**Comment by bekatd** [comment]
Thanks for quick fixes and such a great job :)
