### ISSUE TITLE
Material Tabs Marker: wrong position

### ISSUE THREAD

**Issue by bekatd** [olton/Metro-UI-CSS#1662]
Metro version: 4.4.2

Sometimes material tabs marker gets wrong position

![image](https://user-images.githubusercontent.com/6948919/98518336-ae4b5000-2288-11eb-87ef-0263e942b814.png)

Suggestion: Maybe better to make `tab-marker` just `border-bottom` of `li` and for animation use different approach

**Comment by bekatd** [comment]
Guess this is css timing related, when animation is being interrupted somehow, since JS position calculations are correct. For example when changing tabs fast enough.

![image](https://user-images.githubusercontent.com/6948919/98522797-8bbc3580-228e-11eb-9fdf-9fd5fc687548.png)

**Comment by olton** [comment]
Please create your code example on codepen.io

**Comment by bekatd** [comment]
[Here it is](https://codepen.io/bekatd/pen/oNLaeEB). To reproduce issue, please switch tabs couple of times and sometimes marker position at wrong place

**Comment by olton** [comment]
All work for me
![navview-tabs-material](https://user-images.githubusercontent.com/365108/98529474-53b0f480-2286-11eb-9d32-3fec11e45b39.gif)

**Comment by olton** [comment]
> And btw, navview active class also does not change when clicking on the navview menu items

Add attribute `data-active-state="true"`

**Comment by bekatd** [comment]
> 
> 
> > And btw, navview active class also does not change when clicking on the navview menu items
> 
> Add attribute `data-active-state="true"`

thanks.

I am not able to reproduce issue with chrome. Only firefox has issue with tabs

**Comment by olton** [comment]
> I am not able to reproduce issue with chrome. Only firefox has issue with tabs

![navview-tabs-material-ff](https://user-images.githubusercontent.com/365108/98530993-5b719880-2288-11eb-94e7-13c02c4fdf86.gif)

**Comment by bekatd** [comment]
Not at PC right now. But will record issue as soon as I get back

**Comment by olton** [comment]
> Not at PC right now. But will record issue as soon as I get back

I cannot solve the problem if I cannot reproduce it

**Comment by bekatd** [comment]
Here is video [screen capture](https://streamable.com/ai9i1w)
