### ISSUE TITLE
The scroll bar of the Metro4 website navigation menu disappeared.

### ISSUE THREAD

**Issue by rod-farias** [olton/Metro-UI-CSS#1663]
There is no vertical scroll bar in the left navigation pane of the Components section in the website. Therefore, you cannot scroll down to the bottom of the list on non-touch devices. I checked it in Firefox and Chrome.

![Selección_004](https://user-images.githubusercontent.com/57115850/98547997-bd75d200-2277-11eb-80fc-7b0627aea0a0.png)

**Comment by olton** [comment]
Use the mouse wheel to scroll the menu. If you use docs site as template for self site, you can add attribute `data-menu-scrollbar="true"` to show scroll bar.

**Comment by rod-farias** [comment]
Of course I always scroll through the pages with the mouse wheel, but suddenly this stopped working in your navigation panel, and I thought it was a Metro bug.

Now I remember and you are right, there has never been a scroll bar there.

Apparently it is an Ubuntu issue, because it occurs in both Chrome and Firefox. When I roll the wheel down it does nothing. When I move it up, the panel shifts about an inch and "bounces."

Thanks Olton for your reply and excuse me for using your time. I will continue to investigate.

**Comment by rod-farias** [comment]
My problem has nothing to do with Metro, it also happens in other places and in the Thunderbird mail client.
