### ISSUE TITLE
Navigation View Menu data-actives-tate applies on non-menu items

### ISSUE THREAD

**Issue by bekatd** [olton/Metro-UI-CSS#1664]
Navigation View Menu `data-active-state` applies `active` class on non-menu items on click, like: `item-separator`.

Would be great if we had an option to differentiate menu-items from non-menu items, for example with `menu-item` class on an items we want to be considered as menu items

![image](https://user-images.githubusercontent.com/6948919/98550424-87efd980-22b5-11eb-8d10-904fccf916a3.png)

**Comment by olton** [comment]
create example on codepen.io

**Comment by olton** [comment]
Almost all components are designed as they were described in the Microsoft Developer Guide. And they work as defined there. Therefore, the library is called Metro UI CSS, I do not plan to introduce any non-standard behavior yet.

**Comment by olton** [comment]
you can use class `.item-header` for non-menu item

**Comment by bekatd** [comment]
Unfortunately even `item-header` is being treated as menu item. Actually any `li` inside `navview-menu` is treated as menu item including separators and header items
