### ISSUE TITLE
Should Mega container work in app-bar-container?

### ISSUE THREAD

**Issue by taurenshaman** [olton/Metro-UI-CSS#1665]
**Describe the bug**
[Mega container for h-menu](https://metroui.org.ua/menu.html#_h_menu_mega)  
Mega container didn't works in app-bar-container.

**To Reproduce**
https://codepen.io/taurenshaman/pen/gOMBVMR

**Expected behavior**
Maybe Mega container should works in app-bar-container?

**Screenshots**
![image](https://user-images.githubusercontent.com/1308706/98636852-93e5a500-2362-11eb-8a79-67179c046507.png)

![image](https://user-images.githubusercontent.com/1308706/98636886-9fd16700-2362-11eb-9afa-b7af4d53f9ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Opera, Edge]
 - Metro Version 4.4.0

Thanks for your time!

**Comment by olton** [comment]
use app-bar-menu
