### ISSUE TITLE
data-cls-tabs-list-item-active is "broken"?

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1666]
Hi Olton!

Code at

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

The attribute

`data-cls-tabs-list-item-active`

seem to be "broken"

Thank's

**Comment by bekatd** [comment]
Its working as supposed. you have messed with styling in your codepen.

Look at corrected result

![image](https://user-images.githubusercontent.com/6948919/98671319-81249d80-236d-11eb-8df4-99cccbcd543e.png)

**Comment by bekatd** [comment]
Oh, now I see what OP meant.

This happens due to the class order precedence in CSS file.

Higher order precedence class overcomes lower order precedence class, that's all.

**Comment by olton** [comment]
https://codepen.io/olton/pen/VwjVvBZ?editors=1111
