### ISSUE TITLE
navview data-on-menu-item-click no longer works as supposed

### ISSUE THREAD

**Issue by bekatd** [olton/Metro-UI-CSS#1667]
Starting from Metro UI CSS v4.4.0 `data-on-menu-item-click` is not working as supposed.

When click on menu items, `this` references `navview` node itself not the actual menu item clicked

[codepen of v4.3.10](https://codepen.io/bekatd/pen/XWKyWOy)

[codepen of v4.4.0 and greater](https://codepen.io/bekatd/pen/NWrEPRY)

**Comment by olton** [comment]
use `data-on-menu-item-click="onmenuitemclick"`

**Comment by olton** [comment]
https://metroui.org.ua/events.html

**Comment by bekatd** [comment]
Great. Thanks olton
