### ISSUE TITLE
Add Overlay close to info-box

### ISSUE THREAD

**Issue by EastSideAngus** [olton/Metro-UI-CSS#1668]
I noticed that there is no equivalent data option for the info-box window to close on click of the overlay, as you have for the dialog window.

Could you please add the following to the info-box: **overlayClickClose | data-overlay-click-close | false | Close dialog when user click on overlay**

**Comment by olton** [comment]
in 4.4.3
+ [x] InfoBox: added attribute `data-overlay-click-close=true|false`, default `false`
