### ISSUE TITLE
Material tabs tab-marker missing if tabs were hidden initially.

### ISSUE THREAD

**Issue by bekatd** [olton/Metro-UI-CSS#1669]
Material tabs `tab-marker` missing if tabs were hidden initially.

example: [codepen](https://codepen.io/bekatd/pen/oNLaeEB)

**Comment by olton** [comment]
For hidden elements (display: none) you cannot get a position and offset data, so what you specified happens. This is not a library bug, this is a HTML + JS feature. Just avoid such cases.
