### ISSUE TITLE
Treeview with checkbox - How to identify selected items?

### ISSUE THREAD

**Issue by akayueh** [olton/Metro-UI-CSS#1670]
Hi Serhi

There doesn't seem to be a way of identifying what's been selected in a treeview with checkbox in the DOM.
Before Check:

![image](https://user-images.githubusercontent.com/3982857/98871997-f0af9f80-24c9-11eb-8119-c1396273f9f6.png)

![image](https://user-images.githubusercontent.com/3982857/98872038-07ee8d00-24ca-11eb-8ef0-6eed42ad12c6.png)

After Check:

![image](https://user-images.githubusercontent.com/3982857/98872072-1341b880-24ca-11eb-8aca-94d81c49e041.png)

![image](https://user-images.githubusercontent.com/3982857/98872105-1f2d7a80-24ca-11eb-8643-2f8223d903b9.png)

Am I miss reading something or there is a javascript to call to get the selected items? 

Steven

**Comment by olton** [comment]
Get checked checkboxes from a treeview:
```html
<ul data-role="treeview" id="tv1">
            <li>
                <input type="checkbox" data-role="checkbox" data-caption="Play video" title="">
                <ul>
                    <li><input type="checkbox" data-role="checkbox" data-caption="AVI" title=""></li>
                    <li><input type="checkbox" data-role="checkbox" data-caption="MPEG" title=""></li>
                    <li><input checked type="checkbox" data-role="checkbox" data-caption="VIDX" title=""></li>
                    <li><input type="checkbox" data-role="checkbox" data-caption="MP4" title=""></li>
                    <li><input checked type="checkbox" data-role="checkbox" data-caption="XVID" title=""></li>
                </ul>
            </li>
            <li><input type="checkbox" data-role="checkbox" data-caption="Play audio" title=""></li>
            <li>
                <input type="checkbox" data-role="checkbox" data-caption="Subtitles" title="">
                <ul>
                    <li><input type="checkbox" data-role="checkbox" data-caption="English" title=""></li>
                    <li><input checked type="checkbox" data-role="checkbox" data-caption="Ukrainian" title=""></li>
                    <li><input type="checkbox" data-role="checkbox" data-caption="Dutch" title=""></li>
                </ul>
            </li>
        </ul>
```
```javascript
var elements = $("#tv1").find("input[type=checkbox]").filter(function(el){
   return el.checked;
});

console.log(elements);
```

**Comment by akayueh** [comment]
Thanks, but it seems o be returning the whole lot rather than those been checked.

**Comment by olton** [comment]
Using the filter function filtering elements by check state.

**Comment by olton** [comment]
https://codepen.io/olton/pen/BazvRPM?editors=1011

**Comment by akayueh** [comment]
Thanks, it is working in codepen but for some reason when I used the same code in my c# razor page, the "el.checked" seem to be failing.  it will find 0 check item and return everything when finding unchecked.

I can see the attribute is correctly marked:

![image](https://user-images.githubusercontent.com/3982857/99601038-b35f8a80-2a52-11eb-8f6e-37cfda55531f.png)

For Belconnen:

![image](https://user-images.githubusercontent.com/3982857/99601150-f3bf0880-2a52-11eb-876e-eb84a96dc673.png)

For Woden:

![image](https://user-images.githubusercontent.com/3982857/99601197-06d1d880-2a53-11eb-8555-d09f58ad1c72.png)

I ill do some more testing

**Comment by olton** [comment]
show your code

**Comment by akayueh** [comment]
`<body>
<div class="container">
    <div class="treearea">
        <ul data-role="treeview" id="tv1">

            @foreach (var company in Model.Companies)
            {
                if (Model.Complexes.Any(complex => complex.CompanyId == company.CompanyId))
                {
                    <li>
                        @{
                            var optVal = "company_" + company.CompanyId;
                            var optTitle = optVal;
                            var optText = company.CompanyName;
                        }
                        <input type="checkbox" data-role="checkbox" data-caption="@optText" title="" value="@optVal">

                        @foreach (var country in Model.Countries)
                        {
                            if (Model.Complexes.Any(complex => complex.CompanyId == company.CompanyId &&
                                                               complex.CountryId == country.CountryId))
                            {
                                <ul>

                                    @{
                                        optVal = "company_" + company.CompanyId + "-country_" + country.CountryId;
                                        optTitle = optVal;
                                        optText = country.CountryName;
                                    }

                                    <li>
                                        <input type="checkbox" data-role="checkbox" data-caption="@optText" title="" value="@optVal">


                                        @foreach (var state in Model.States)
                                        {
                                            if (Model.Complexes.Any(complex => complex.CompanyId == company.CompanyId &&
                                                                               complex.CountryId == country.CountryId &&
                                                                               complex.StateId == state.StateId))
                                            {
                                                <ul>
                                                    @{
                                                        optVal = "company_" + company.CompanyId + "-country_" + country.CountryId + "-state_" + state.StateId;
                                                        optTitle = optVal;
                                                        optText = state.StateName;
                                                    }

                                                    <li>
                                                        <input type="checkbox" data-role="checkbox" data-caption="@optText" title="" value="@optVal">


                                                        @foreach (var complex in Model.Complexes)
                                                        {
                                                            if (complex.CompanyId == company.CompanyId &&
                                                                complex.CountryId == country.CountryId &&
                                                                complex.StateId == state.StateId)
                                                            {
                                                                <ul>
                                                                    @{
                                                                        optVal = "company_" + company.CompanyId + "-country_" + country.CountryId + "-state_" + state.StateId + "-complex_" + complex.ComplexId;
                                                                        optTitle = optVal;
                                                                        optText = complex.ComplexName;
                                                                    }
                                                                    <li>
                                                                        <input type="checkbox" data-role="checkbox" data-caption="@optText" title="" value="@optVal">
                                                                    </li>
                                                                </ul>
                                                            }
                                                        }
                                                    </li>
                                                </ul>
                                            }
                                        }
                                    </li>
                                </ul>
                            }
                        }

                    </li>
                }
            }

        </ul>
    </div>


    <div class="mb-4 mt-4">
        <button class="button" onclick="getChecks(1)">Get checked</button>
        <button class="button" onclick="getChecks(0)">Get unchecked</button>
    </div>

    <div>

        <form method="post">
            <div class="form-group" style="visibility: hidden">
                <input id="InputTextBox" asp-for="SelectedComplexGroupMapping" class="form-control" value="abcd"/>
            </div>

            <div class="row">
                <div class="cell">
                    <input type="submit" id="submitbutton" value="Create" class="btn btn-primary"/>
                </div>
            </div>
        </form>
    </div>

</div>
`

**Comment by akayueh** [comment]
This does not work:

`            var elements = $("#tv1")
                .find("input[type=checkbox]")
                .filter(function(el) {
                    return !$(el).parent().parent().hasClass('tree-node') &&
                        !Metro.utils.bool($(el).attr('data-indeterminate')) &&
                        (m ? el.checked : !el.checked);
                });`

But this does:

  var elements = $("#tv1")
                .find("input[type=checkbox]");

            elements.each(function() {
                var status = (this.checked ? $(this).val() : "");
                var id = $(this).attr("id");
                console.log(id + " : " + status);
            });

**Comment by olton** [comment]
Are you using jQuery?

**Comment by akayueh** [comment]
> Are you using jQuery?

yes 

on _Layout.cshtml under shared

```
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
```

on my razor page:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/metro/4.4.1/js/metro.min.js"></script>`

**Comment by olton** [comment]
`filter()` in **m4q** and `filter()` in **jquery** work **differently**. So https://codepen.io/olton/pen/ExyzZQP?editors=1011

**Comment by olton** [comment]
You must redefine $ on m4q in your function or use m4q directly.

**Comment by olton** [comment]
https://metroui.org.ua/m4q-population.html

**Comment by olton** [comment]
Optimized function with m4q:
```javascript
function getChecks(m) {
  var $ = m4q;
  var elements = $("#tv1")
    .find("[type=checkbox]")
    .filter(function (el) {
      return !$(el).closest('li').hasClass('tree-node') && (m ? el.checked : !el.checked);
    });
  console.log(elements.length);
}
```

**Comment by akayueh** [comment]
thanks, I will do some test
