### ISSUE TITLE
Add localization for table component

### ISSUE THREAD

**Issue by Merenia** [olton/Metro-UI-CSS#1671]
Currently, the table component does not support localizations. It is necessary to modify the labels in the js file and it's not practical in case of update.
In general, all labels should be localizable.

ex. : 
`itemsSteps: "all, 10,25,50,100",
        itemsAllTitle: "Show all",
        listItemsCountTitle: "Show entries:",
        listSearchTitle: "Search:",
        listInfoTitle: "Showing $1 to $2 of $3 entries",
        paginationPrevTitle: "Prev",
        paginationNextTitle: "Next"`

`tableRowsCountTitle: "Show entries:",
        tableSearchTitle: "Search:",
        tableInfoTitle: "Showing $1 to $2 of $3 entries",
        paginationPrevTitle: "Prev",
        paginationNextTitle: "Next",
        allRecordsTitle: "All",
        inspectorTitle: "Inspector",
        tableSkipTitle: "Go to page",`

**Comment by olton** [comment]
In 4.4.3 to i18n files added section table:
```
"table": {
    "rowsCount": "Show entries:",
    "search": "Search:",
    "info": "Showing $1 to $2 of $3 entries",
    "prev": "Prev",
    "next": "Next",
    "all": "All",
    "inspector": "Inspector",
    "skip": "Goto page",
    "empty": "Nothing to show"
}
```
Now translation added for `uk-UA`, `ru-RU`. For others used the English version. Wait for PR from the community to change localizations for other locales.

**Comment by olton** [comment]
The old attributes work if you define these.
