### ISSUE TITLE
stepper  event onStepClick not work

### ISSUE THREAD

**Issue by vaasal** [olton/Metro-UI-CSS#1672]
In metro v4 it seem that the click event is not triggered:

<div data-role="stepper" data-steps="5" id="stepper"  data-click-step="true" data-on-step-click="alert('HELLO')"></div>

Any idea?
thank you!

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS-3

**Comment by vaasal** [comment]
Sorry for my mistake but is V4 not V3 metro version

**Comment by olton** [comment]
https://codepen.io/olton/pen/BazMWWL?editors=1011
