### ISSUE TITLE
Proposed changes to fix Dialog in the documentation

### ISSUE THREAD

**Issue by golgor** [olton/Metro-UI-CSS#1673]
**Describe the bug**
Some minor errors in the example for a Dialog in the documentation.

**To Reproduce**
Just copy-paste the example under "Predefined method"

**Expected behavior**
Expects the code to work basically by copy-paste.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows (WSL)
 - Browser Chrome
 - Metro Version 4.3.3

**Additional context**
* In the example you are missing a reference to dialog-class you create just above. Adding "id='demoDialog1' fixes this problem.
* By default, buttons become submit-buttons which creates a problem with possible redirects or refreshes if you have a form on the page. Adding "type='button'" solves this issue.

Proposed code:
```
<div class="dialog" data-role="dialog" id="demoDialog1">
    <div class="dialog-title">Use Windows location service?</div>
    <div class="dialog-content">
        Bassus abactors ducunt ad triticum.
        A fraternal form of manifestation is the bliss.
    </div>
    <div class="dialog-actions">
        <button class="button js-dialog-close">Disagree</button>
        <button class="button primary js-dialog-close">Agree</button>
    </div>
</div>
<button type="button" class="button primary"
    onclick="Metro.dialog.open('#demoDialog1')">Open dialog</button>
```

**Comment by olton** [comment]
Please create an issue in the special docs repo https://github.com/olton/Metro4-Docs. Thank you.
