### ISSUE TITLE
Keypad show wrong value after dynamic change value by jquery

### ISSUE THREAD

**Issue by thinhpc86** [olton/Metro-UI-CSS#1674]
**Describe the bug**
Let's say we have a Form with many input text boxes include an input with keypad plugin set.
Step 1: Using keypad to input any number. For example: 123
Step 2. In some situation of the form process, we use Jquery to set value for that keypad input to: 1000
`$("#exampleID").val(1000);`
Step 3. Using keypad, click backspace key (←) 
It not do anything, the value still 1000 and throw an error in console log:

![Screen Shot 2020-11-18 at 15 35 47](https://user-images.githubusercontent.com/57983918/99494101-c1aa9980-29b3-11eb-91b1-071da0aedbe5.png)
![Screen Shot 2020-11-18 at 15 36 41](https://user-images.githubusercontent.com/57983918/99494164-e3a41c00-29b3-11eb-9e5c-aa381bb5d413.png)

**Expected behavior**
I expect the value will be: 100

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]
 - Metro Version [e.g. 4.4.2]
(But I believe this happen at all Os or browser of Desktop or Smartphone

**Comment by olton** [comment]
create pen with your code on codepen.io

**Comment by olton** [comment]
to set value for keypad, use 
```
Metro.getPlugin(element, 'keypad').val(...);
```

**Comment by olton** [comment]
Method `val()` from jquery not triggered event change, so to set value from outside, you must use the component method `val`.

In 4.4.3 I fixed value type mismatch? when the user clicks on the symbol delete button.
