### ISSUE TITLE
Select  - clear button not displayed correctly in "input-small" mode

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1675]
Hi Olton!

Code at:

https://codepen.io/TorakikiSan/pen/EeyWmp

The small glitch is related to the data-clear-button = "true" attribute, the cross is only partially displayed.

**Comment by olton** [comment]
Sorry.  Unfortunately my computer is broken and at the moment the work on the library is suspended.  If the community helps me with the purchase of a new computer, then the work will continue as quickly as possible.  Unfortunately, I myself now have financial problems due to illness.

**Comment by olton** [comment]
clear button fixed
