### ISSUE TITLE
TimePicker data-minutes-step="15" always selects 0 minutes

### ISSUE THREAD

**Issue by dugi007** [olton/Metro-UI-CSS#1676]
Hi,

i'm not sure if this feature is fully developed because it is not documented, but if it is there is a bug! 😄 

Besides not selecting correct value, it seems scroll doesnt center.

![image](https://user-images.githubusercontent.com/74769392/99791072-5da7e280-2b25-11eb-8233-df2db1a3bd93.png)

Vedran

**Comment by olton** [comment]
At the moment I am left without a computer, so it will be difficult for me to help. Details on https://www.facebook.com/metrouicss

**Comment by olton** [comment]
What is your browser?

**Comment by dugi007** [comment]
Hi Olton,

tnx for getting back at me! I tested in Edge, FF and Chrome.. After some more testing, it seems that returns initial value (not only 0), and **sometimes** i can switch value only to 0 if it set for example to 15 and thats it..

Vedran

**Comment by dugi007** [comment]
Here's code pen if it helps:

https://codepen.io/dugi007/pen/VwjJZYg

**Comment by olton** [comment]
Thank you, fixed in 4.4.3, check it.

**Comment by dugi007** [comment]
Tnx! Works like a charm!
