### ISSUE TITLE
NuGet package installation version

### ISSUE THREAD

**Issue by CD4443** [olton/Metro-UI-CSS#1684]
After installation of package via Package Manager Console via
-> Install-Package Metro4 -Version 4.4.2 (Same Behaviour via Project->right Click->Manage NuGet Packages)
Visual Studio installs always Version 4.2.41 to Solution Packages Folder and Project.

I am using:
Visual Studio  2019 V 16.8.2
Asp.net Core 5.0 Webb Project

**Comment by olton** [comment]
Ask Nuget Developers.

**Comment by olton** [comment]
https://www.nuget.org/packages/Metro4/
All ok, if I download a package from it, the contained version of Metro4 is 4.4.2

**Comment by CD4443** [comment]
But if i view metro,js in browser while debuging I see 

 

/*

* Metro 4 Components Library v4.2.41  (https://metroui.org.ua)

* Copyright 2019 Sergey Pimenov

* Licensed under MIT

*/ ….

 

Von: Serhii Pimenov <notifications@github.com> 
Gesendet: Dienstag, 24. November 2020 11:40
An: olton/Metro-UI-CSS <Metro-UI-CSS@noreply.github.com>
Cc: CD4443 <g.brust@chips-at-work.de>; Author <author@noreply.github.com>
Betreff: Re: [olton/Metro-UI-CSS] NuGet package installation version (#1684)

 

https://www.nuget.org/packages/Metro4/
All ok, if I download a package from it, the contained version of Metro4 is 4.4.2

**Comment by olton** [comment]
This is a screen from the package, downloaded directly from neget.org. Contact NuGet support.

![2020-11-24-13-14-57](https://user-images.githubusercontent.com/365108/100087237-1a1be400-2e57-11eb-9aa4-d7947c8631c3.png)
