### ISSUE TITLE
Conflict with str.search() javascript function

### ISSUE THREAD

**Issue by Federico-Luna** [olton/Metro-UI-CSS#1685]
Hello.

First of all congratulate them for this great job.

I work with Asp.Net Core 3.1 (Razor Pages) and I have a piece of code that gives an error when I load metro.min.js.

If I comment the line that loads metro.min.js or put my piece of code before loading metro.min.js there is no error.

The error is as follows:
(index):352 Uncaught SyntaxError: Invalid regular expression:
/
`

        function () {
            var a = this.concat();
            for (var i = 0; i < a.length; ++i) {
                for (var j = i + 1; j < a.length; ++j) {
                    if (a[i] === a[j])
                        a.splice(j--, 1);
                }
            }
            return a;
        }
`
/: Nothing to repeat
    at String.search (<anonymous>)
    at (index):352

My piece of code is in _Layout.cshtml and is as follows:

`

    <script src="~/_content/Comunes/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="~/_content/Comunes/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/_content/Comunes/lib/metro/js/metro.js"></script>

    <script src="~/_content/Comunes/lib/jsGrid/jsgrid.min.js"></script>
    <script src="~/_content/Comunes/lib/jsGrid/i18n/jsgrid-es.js"></script>

    <script src="~/_content/Comunes/lib/spectrum-colorpicker/spectrum.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/_content/comunes/js/funciones.js" asp-append-version="true"></script>
    <script src="~/_content/comunes/js/ventana.js" asp-append-version="true"></script>

    <script>
        cultureInfo = '@System.Globalization.CultureInfo.CurrentCulture';
        phFecha = '@System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern';
        phFecha = phFecha.toLowerCase(); // (phFecha = d/mm/yyyy)

        let sFecha = phFecha.split("/");
        for (var i in sFecha) {
            if ("md".search(sFecha[i])) {
                if (sFecha[i].length == 1) {
                    sFecha[i] = sFecha[i].repeat(2);
                }
            }
        }
        phFecha = sFecha[0] + "/" + sFecha[1] + "/" + sFecha[2];
    </script>

`

**Comment by olton** [comment]
Show your browser dev console screenshot

**Comment by olton** [comment]
Metro doesn't use `String.search()`

**Comment by olton** [comment]
Why did you decide that the problem was in Metro and not in your code?

**Comment by Federico-Luna** [comment]
Thanks for your quick response.

Browser dev console screenshot:
![VS2019-2020-11-27-16-01-34](https://user-images.githubusercontent.com/46276855/100462162-222f8a00-30ca-11eb-8c14-6daa0e824e85.png)

Why did you decide that the problem was in Metro and not in your code?

As I mentioned in my first post, when I load metro.js the error occurs and if I comment the line that loads metro.js the error does not occur.

In the same way, if I put my code before loading metro.js there is no error and if I put it after metro.js the error occurs.

The code is simple:
![VS2019-2020-11-27-16-08-15](https://user-images.githubusercontent.com/46276855/100462678-e6e18b00-30ca-11eb-96a1-eedd1492ac3d.png)

**Comment by olton** [comment]
You have written in the console that there is an error in the index

**Comment by Federico-Luna** [comment]
I have searched for a.splice (j--, 1); in metro.js and here is the piece of code that generates the error:
I don't know why the conflict can occur.

![VS2019-2020-11-27-16-17-07](https://user-images.githubusercontent.com/46276855/100463714-8e12f200-30cc-11eb-9eba-84991601f8ae.png)

**Comment by Federico-Luna** [comment]
The weird thing is that if I put my code before loading metro.js the error does not occur.

**Comment by Federico-Luna** [comment]
If I remove this piece of code that uses search function, the error doesn't occur either:

            if ("md".search(sFecha[i])) {
                if (sFecha[i].length == 1) {
                    sFecha[i] = sFecha[i].repeat(2);
                }
            }

That's why I say that it may be a conflict with the search function, but I don't know how.

**Comment by Federico-Luna** [comment]
I don't know javascript in depth, but there seems to be a conflict with the definition of Array.protptype.unique.

I just changed the code that uses search to another that uses includes, and I get an error that includes is not a function. I remove the line that loads metro.js and there is no longer an error.

The new code is this:

        for (var i in sFecha) {
            if (sFecha[i].includes("m") || sFecha[i].includes("d")) {
                if (sFecha[i].length == 1) {
                    sFecha[i] = sFecha[i].repeat(2);
                }
            }
        }

**Comment by olton** [comment]
If you define an argument for the function `String.search([regexp])`, this argument must be a valid regular expression.

**Comment by olton** [comment]
The error occurred in `if ("md".search(sFecha[i])) {`. Variable `sFecha[i]` doesn't contains a valid regullar expression. It has nothing to do with the Metro 4.

**Comment by Federico-Luna** [comment]
I have no define any regex. Is an array.

Here is a simple html in codepen:

https://codepen.io/FedericoLuna/pen/xxExeLK

Just comment out the line that metro.js loads and it will work.

**Comment by Federico-Luna** [comment]
It is a simple iteration of an array.

**Comment by olton** [comment]
If you define an argument for the function String.search([regexp]), this argument must be a **valid regular expression**.

**Comment by olton** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search

**Comment by Federico-Luna** [comment]
https://www.w3schools.com/jsref/jsref_search.asp

If change code and replace search function with includes, for example, if metro.js is loads get this error error: 
index.html:18 Uncaught TypeError: sFecha[i].includes is not a function
    at index.html:18
Includes is a function.

Here is a codepen with includes function:

https://codepen.io/FedericoLuna/pen/WNGNWma

Just comment metro.js loads and it will be work fine.

**Comment by olton** [comment]
```
        for (var i in sFecha) {
            if (i.includes('m') || i.includes('d')) {
                if (sFecha[i].length == 1) {
                    sFecha[i] = sFecha[i].repeat(2);
                }
            }
        }
```

**Comment by Federico-Luna** [comment]
Another test, I have commented out the code block in metro.js and the error no longer occurs.
![VS2019-2020-11-27-18-26-12](https://user-images.githubusercontent.com/46276855/100473295-4bf2ac00-30de-11eb-8f99-d5e37a9b91f1.png)

**Comment by olton** [comment]
Please read about loop `for` in javascript

**Comment by Federico-Luna** [comment]
OK. thank you very much. It remains for the experience.

As I said before, I do not know javascript in depth, but, why when I comment the block of code in metro.js the functions do work correctly?

Thank you again.

**Comment by olton** [comment]
> why when I comment the block of code in metro.js the functions do work correctly?

I don't know, but I know that the Metro4 code you commented out is completely working.

**Comment by Federico-Luna** [comment]
OK. Thank you very much again.

**Comment by olton** [comment]
If the error occurred in Metro, the compiler would say about it - `Error in metro.min.js` or `Error in metro.js` if you use a not minimized version.

**Comment by Federico-Luna** [comment]
Thank you.

And, again, great work with this library.

I don't even know 10% of the javascript that you know.

Just 7 months ago I started web programming, after 30 years programming windows forms.

**Comment by olton** [comment]
I wish you success in learning javascript!

**Comment by Federico-Luna** [comment]
I just read about the for...in loop and MDN says that it should not be used with arrays. I already changed it to for (var i = 0; i < length; i ++) and now everything work fine.

Thank you again and congratulations for your work.

**Comment by olton** [comment]
Also, for an array you can use `Array.forEach()` function:
```
<script>
    cultureInfo = '@System.Globalization.CultureInfo.CurrentCulture';
    phFecha = '@System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern';
    phFecha = phFecha.toLowerCase(); // (phFecha = d/mm/yyyy)

    let sFecha = phFecha.split("/");
    sFecha.forEach(function(element){
          if (element.length === 1) {
          ...
          }
    })
    phFecha = sFecha[0] + "/" + sFecha[1] + "/" + sFecha[2];
</script>
```

**Comment by Federico-Luna** [comment]
OK. thanks for your help, i will also try foreach.

**Comment by Federico-Luna** [comment]
You've been very kind.
