### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [olton/Metro-UI-CSS#1687]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by olton** [comment]
Metro 4 hasn't any dependencies. Therefore, I don't see the need to discuss something. If you think otherwise, write, I will consider. Thank you.

**Comment by pwntester** [comment]
This is a vulnerability in Metro's code, not on any dependency

**Comment by olton** [comment]
Some kind of incomprehensible discussion. If you want me to make some changes to the code, write what and what is the problem.

**Comment by pwntester** [comment]
We prefer to disclose security vulnerability details in a private issue so they are not made public before a patch is ready

**Comment by olton** [comment]
You can write me directly to the address serhii@pimenov.com.ua

**Comment by olton** [comment]
Thank you for your report. I confirm this problem and will fix it in the near time.

**Comment by olton** [comment]
Thank you for your report. I confirm this problem and will fix it in the near time.

**Comment by pwntester** [comment]
Thanks for the quick turnaround. Please let us know if you plan to open a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and request a CVE Id to help users know about the necessity to update to the latest version.
