### ISSUE TITLE
Make window div stay on top (z index) when dragging and afterwards

### ISSUE THREAD

**Issue by ajh123** [olton/Metro-UI-CSS#1689]
As the title says how do i make a window do what the title says?
So far i tried but the zIndex dose not stay afterwards
```
	<script type="text/javascript">

		function setWindowTop(position, el) {
			els = document.querySelectorAll('[data-role="window"]');
			els.forEach(function(elem){ 
				if (elem != el) {
					elem.style.zIndex = -999999;
				}
			})
			el.style.zIndex = 999999;
		}
	</script>


	<div data-role="window"
		 data-resizable="true"
		 data-draggable="true"
		 data-drag-area="body"
		 data-on-drag-start="setWindowTop"
		 onclick="setWindowTop(0, this)" 
		 style="position:relative;" 
		 data-title="Hello!"
		>
	    <div class="window-content p-2">
	        Window content
	    </div>
	</div>
```
I also tired to set the `data-on-drag-stop` attribute to `setWindowTop`. However when the mouse is released the zIndex goes back to normal order.
Also in my actual project i have more complicated windows

**Comment by olton** [comment]
You must use parent div with class `.window` to set `z-index`

**Comment by ajh123** [comment]
didn't work with z-index of 0, the second still overlaps the first when dragging finshes

**Comment by ajh123** [comment]
Also my code works when i'm dragging the window, but afterwards the zIndex goes to noraml

**Comment by ajh123** [comment]
@olton  Look at this fiddle https://jsfiddle.net/samuelh2005/2aL9hfd1/1/

**Comment by olton** [comment]
You must set z-index to the parent div with class .window

**Comment by ajh123** [comment]
But how do i do that dynamically (with the `setWindowTop`function )

**Comment by ajh123** [comment]
In the function i'm finding all the windows setting zIndex to -999999 and the window thats wanted on top to 999999

**Comment by ajh123** [comment]
And `els = document.querySelectorAll('[data-role="window"]');` is used to find all the windows

**Comment by olton** [comment]
Thank you. Fixed in 4.4.3 Example: https://codepen.io/olton/pen/RwGWQJg?editors=1011

**Comment by ajh123** [comment]
It works on the codepen, but cant seem to get it to work on my one, The zindex is set while dragging then unset afterwards

**Comment by ajh123** [comment]
And I downloaded the libraries from the download zip button from the website today

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/4.4.3

**Comment by ajh123** [comment]
Thank you, it works now!
