### ISSUE TITLE
data-sortable in thead not worked

### ISSUE THREAD

**Issue by yamin1313** [olton/Metro-UI-CSS#1697]
hi,
i make a table with static header and dynamic data from json. i create header in html with data-sortable="true" but sorting not worked for me.
in your example data-sortable not worked too: 
https://metroui.org.ua/table.html#_table_data
please check it and make help for me to have a sortable header in html.

thanks

**Comment by olton** [comment]
create example with your code on codepen.io

**Comment by yamin1313** [comment]
here:
https://codepen.io/yamin1313/pen/BaLdmZq

**Comment by olton** [comment]
Currently, you can add to th class `sortable-column` instead of `data-sortable`. I will see why the data-sortable definition does not work.

**Comment by olton** [comment]
Thank you, fixed in 4.4.3
