### ISSUE TITLE
'Metro' is not defined in Vue 3.0.x

### ISSUE THREAD

**Issue by JaceDigital** [olton/Metro-UI-CSS#1700]
I believe I had seen that as of Metro 4.3.3 that Metro should be a global variable after installing via npm and importing into the Vue "App" component.

I have now installed 4.4.3 via npm into my new project and performed the following in App.vue:
```
import 'metro4'
...
export default {
  name: 'App',
  components: {
    HelloWorld
  },
  mounted:() => {
     Metro.init();
   }
}
```
but am receiving *'Metro' is not defined* error.

If I perform the following in App.vue:
```
import Metro from  'metro4'
...
export default {
  name: 'App',
  components: {
    HelloWorld
  },
  mounted:() => {
     Metro.init();
   }
}
```
I do not receive an error message about Metro not being defined but I cannot access any of the Metro functions from any other Vue components. e.g. `Metro.toast.create("Toast message", null, 5000);` in the HelloWorld component will throw the *'Metro' is not defined* error.

Should 'Metro' not be global after `npm install` and `import 'metro4'` with Metro 4.4.3?

**Comment by olton** [comment]
Check your bundler for including Metro4 into the result bundl.
