### ISSUE TITLE
input select all on focus

### ISSUE THREAD

**Issue by Manyletoulousain** [olton/Metro-UI-CSS#1701]
**Describe the bug**
I would like to to select an input and select all the contend with jquery.

If I remove the line 
                   <script src="/Metro-UI-CSS-master/build_v4.3.6/js/metro.js"></script>
   it is working
If I keep 
                  <script src="/Metro-UI-CSS-master/build_v4.3.6/js/metro.js"></script>
   the third input become a dropdown

=> how, when we use metro, to select an input and select all the contend? Is there another way?
Thank you

**To Reproduce**
  
![image](https://user-images.githubusercontent.com/66750276/103483882-96a4c980-4dea-11eb-8af9-16e2ae5e32b1.png)

<link rel="stylesheet" href="/Metro-UI-CSS-master/build_v4.3.6/css/metro-all.css">

  <script src="/js/jquery-3.5.0.js"></script>

  <script src="/Metro-UI-CSS-master/build_v4.3.6/js/metro.js"></script>

  <input type="text" id="one" >

  <input type="text" id="two" >

  <input type="text" id="target" >

  <input type="text" id="three" >

$(document).ready(function()
{
	$("#one").on("keydown", function(event)
	{
		var key = event.keyCode;
		if (key == 9) 
		{
			event.preventDefault();
			$("#target").select()
		}
	});
});

**Expected behavior**
I enter any text in all input
I select the first input
I press "TAB"
the content of the third input shall be all selected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome and firefox
 - Metro Version 4.3.6

**Comment by olton** [comment]
create pen with your code on codepen.io

**Comment by Manyletoulousain** [comment]
without metro js added
https://codepen.io/Manouletoulousain/pen/JjRLZXW
when you press tab on the first input, the third on will be focus and all its content (if any) will be selected

if you add metro.js; that ficture does not work anymore. the ".slelect()" trigger a metro piece of code which create localy a dropdown, in codepen.io a check box

Hope the link is working
Thank you

**Comment by olton** [comment]
Metro contains a component `select`. If you use jquery, Metro added function `select` to `jQuery.fn.prototype` for `select` component init. Use method `focus` isntead of `select`.

**Comment by Manyletoulousain** [comment]
Thank you for you quick answer.
The focus fonction give the focus to the input
the select function give the focus and select all the content.

So those two functions are not equivalent.
I whish to select all the content. Is there a solution when we use metro?

________________________________
De : Serhii Pimenov <notifications@github.com>
Envoyé : dimanche 3 janvier 2021 22:10
À : olton/Metro-UI-CSS <Metro-UI-CSS@noreply.github.com>
Cc : Manyletoulousain <emmanuel_soler@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [olton/Metro-UI-CSS] input select all on focus (#1701)


Metro contains a component select. If you use jquery, Metro added function select to jQuery.fn.prototype for select component init. Use method focus isntead of select.

**Comment by olton** [comment]
Use standard HTMLElement methods:
```javascript
$("#one").on("keydown", function(event) {
    var key = event.keyCode;
    var target = document.querySelector("#target");

    if (key == 9) {
        event.preventDefault();
        target.focus();
	target.select();
    }
});
```

**Comment by Manyletoulousain** [comment]
Thank you, it is workling exactly as I need!

All the best
Emmanuel

________________________________
De : Serhii Pimenov <notifications@github.com>
Envoyé : lundi 4 janvier 2021 20:53
À : olton/Metro-UI-CSS <Metro-UI-CSS@noreply.github.com>
Cc : Manyletoulousain <emmanuel_soler@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [olton/Metro-UI-CSS] input select all on focus (#1701)


Use standard HTMLElement methods:

$("#one").on("keydown", function(event) {
    var key = event.keyCode;
    var target = document.querySelector("#target");

    if (key == 9) {
        event.preventDefault();
        target.focus();
        target.select();
    }
});

**Comment by olton** [comment]
Also, you can disable delegation Metro functions into `jQuery.fn`. To disable injection you must use init meta tag:
```
<meta name="metro4:jquery" content="false">
```
This definition disable injection Metro 4 functions into jQuery.fn, and now, you can use jquery method $(...).select() as was expected.
