### ISSUE TITLE
Table hover event

### ISSUE THREAD

**Issue by gakyuz** [olton/Metro-UI-CSS#1702]
Table component is very powerfull and life saver. 
Is there an event fired in hover (cell-hover and row-hover). I could not find it.

If there is not, it will be very helpfull to find which row and column and data of the howered item.
Thanks again for your excellent work.
Gokalp AKYUZ

**Comment by olton** [comment]
```html
<table data-role="table" id="t1">...</table>
```
```javascript
$("#t1").on("mouseenter", "tr", function(){
    // this === tr
})

$("#t1").on("mouseenter", "td", function(){
    // this === td
})

```
