### ISSUE TITLE
a button icon and text not centered in 4.4.3

### ISSUE THREAD

**Issue by TommyCorr** [olton/Metro-UI-CSS#1703]
Hello, I recently updated metro to 4.4.3, and all "a" links have the icon and text stuck to the top of the a button (all browsers).
Is it a bug??
--------------------------
![image](https://user-images.githubusercontent.com/6476657/103917489-47ed7d00-50d3-11eb-930a-2430940a2f5f.png)
--------------------------
https://codepen.io/tommycorr/pen/zYKaMQR

**Comment by olton** [comment]
```
<a class="button bg-black fg-white" href="#"> 
    <span class="mif-eye"></span>
    <span>View</span>
</a>
```

**Comment by TommyCorr** [comment]
Thank you Olton!
