### ISSUE TITLE
The request adapts a media response to the base-table

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#1704]
![image](https://user-images.githubusercontent.com/22745515/103928182-6ea0c780-5156-11eb-8f96-a8e91e9f39f9.png)
The deformation is too serious,
![image](https://user-images.githubusercontent.com/22745515/103928690-2b932400-5157-11eb-9b42-7397fe190d13.png)

**Comment by olton** [comment]
You can enable horizontal scrolling for the table (required data-role='table'). Additional styles for the table in the near feature I don't plan.
