### ISSUE TITLE
Option texts of an select box within an inline form are not completely visible, if previously a shorter option was chosen

### ISSUE THREAD

**Issue by netfaresi** [olton/Metro-UI-CSS#1705]
**Describe the bug**
I am not sure whether this is a real bug or a default behavior, which is changeable by configuration.
The option texts of a select box within an **inline form** are not shown in full length, if previously a shorter option was chosen.

**To Reproduce**
https://codepen.io/netfaresi/pen/poEGWpE

**Expected behavior**
When opening a select box list, which is placed in an inline form,  all options should be readable to the user and not be cut at the current length of the selectbox width.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox/Chrome
 - Metro Version 4.3.2 and earlier.

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 9
 - Browser Chrome
 - Metro Version 4.3.2

**Comment by olton** [comment]
If you need a full-sized select dropbox, add the next style:
```
.inline-form .drop-container {
  width: auto!important
}
```

**Comment by netfaresi** [comment]
**Thank you for your support!**

**FYI**
The same problem exists in higher versions too, such as in 4.4.1.  The solution above did not work in that version.
I tried following and it worked in 4.4.1 and the latest version:

.inline-form .drop-container { 
     width: max-content;
`}`

**Comment by olton** [comment]
In 4.5.0 I added attributes `data-drop-full-size=true|false` (default: false), `data-drop-width=int_value` to set drop container width
```
<select data-role="select" data-drop-full-size="true"
...
</select>
```

**Comment by netfaresi** [comment]
You are great! Thank you!
