### ISSUE TITLE
Slect with more than 10k Data

### ISSUE THREAD

**Issue by WGCNet** [olton/Metro-UI-CSS#1706]
hey, 

Do the SELECT have a "data-src" attribute?

We have the problem that we have more than 15000 Options (User-Data).

**Comment by olton** [comment]
You can use the method `data()` from select API to load your dataset. For example: https://github.com/olton/Metro4-Examples/blob/master/src/ajax/select.html#L46

**Comment by Tallerik** [comment]
Which format/structure needs the JSON file to have?

**Comment by olton** [comment]
https://github.com/olton/Metro4-Examples/tree/master/src/ajax/data

**Comment by Tallerik** [comment]
Thank you
