### ISSUE TITLE
class="badge" issue

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1707]
Hi Olton.

A little glitch about the class="badge". Example at

https://codepen.io/TorakikiSan/pen/EeyWmp

With 4.4.2 final

![4 4 2](https://user-images.githubusercontent.com/37299746/105022657-4bc1bd80-5a4a-11eb-86b8-dfaf937a25ec.jpg)

With 4.4.3 final

![4 4 3](https://user-images.githubusercontent.com/37299746/105022714-5e3bf700-5a4a-11eb-865a-c0aab97e6d02.jpg)

the badge over the button is cropped.

Thank's!

**Comment by olton** [comment]
add for table `data-cell-wrapper="false"`
