### ISSUE TITLE
Clicking dropdown-toggle element closes other dropdown menus out of the context

### ISSUE THREAD

**Issue by netfaresi** [olton/Metro-UI-CSS#1708]
**Describe the bug**
If you click an element with class dropdown-toggle, other dropdown menus, which are not related to clicked element, will be closed.

**To Reproduce**
This behavior can be reproduced on the Pandora Admin page. 

1. Open the Mailbox submenu on the navigation menu and click Inbox. 
2. Then click the down icon besides the checkbox icon above the mails table, which opens a dropdown menu.
3. Look at the navigation menu on the left side. The submenu for Mailbox is collapsed.

**Expected behavior**
Click on a dropdown-toggle element should close only related submenus if at all. In this example the submenu for Mailbox should NOT  be closed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox, IE11, MS Edge
 - Metro Version 4.4.3

**Comment by olton** [comment]
create issue in the pandora repo

**Comment by netfaresi** [comment]
Thank you for your feedback.
I was not really sure and thought that it might be a bug in the core.
