### ISSUE TITLE
Tables filtering using an more words

### ISSUE THREAD

**Issue by vaasal** [olton/Metro-UI-CSS#1711]
Hi. There is a way to use filter table for more words, without writing as many function as words you have?

I tryalso this with concat, but doesnt work.

function myFilter(row, heads){
        var is_active_index = 0;
        heads.forEach(function(el, i){
            if (el.name === "name") {
                is_active_index = i;
            }
        });
        var c1 =  row[is_active_index].contains("Jak");
       var c2 =  row[is_active_index].contains("Simon");
      var c3 = [].concat(c1, c3);
             return c3;

    }

The code return all the record.

Thank you

**Comment by olton** [comment]
create pen on codepen.io with your code

**Comment by vaasal** [comment]
Thank you. My code is just a test. Just wan't to know if is possible to filter with more words without write many function.
Thank you.

**Comment by olton** [comment]
filter function must return a bool value

**Comment by olton** [comment]
https://codepen.io/olton/pen/JjRgKNW?editors=1010

**Comment by vaasal** [comment]
Thank you very much.
