### ISSUE TITLE
set Content Dialog not centered

### ISSUE THREAD

**Issue by TommyCorr** [olton/Metro-UI-CSS#1712]
When I open a Dialog with setContent(), it loads onto the **bottom** of the screen. 
When i minimize and maximize the browser or change browser window width or height, the dialog **centers** properly.

![Dialog 1](https://user-images.githubusercontent.com/6476657/105884630-c69c5280-5fcd-11eb-99be-776dc1e27ea3.png)
![Dialog 2](https://user-images.githubusercontent.com/6476657/105884633-c734e900-5fcd-11eb-8123-beb72236c664.png)

Is there a way to redraw or refresh dialog position before opening? or is there a solution??

Thank you

**Comment by olton** [comment]
Please, create an example on codepen.io

**Comment by TommyCorr** [comment]
https://codepen.io/tommycorr/pen/bGwXYrz

Open the dialog, and then resize your browser window.

**Comment by olton** [comment]
All ok for me

**Comment by olton** [comment]
You can use `setPosition()` API method to repositioning

**Comment by olton** [comment]
What version of Metro 4 you are use? Maybe you use not the latest version, and this version contains any bugs.

**Comment by TommyCorr** [comment]
I'm using 4.4.3.

Do i use setPosition() before or after Metro.dialog.open('#dialog');?? and by default will it locate the dialog at the center??

**Comment by olton** [comment]
Yiu can call setPosition after setContent. Also setPosition executing automatically when window is resized.

**Comment by TommyCorr** [comment]
I added dialog.setPosition() after setContent and before open in the codepen i attached here, and no results.

**Comment by olton** [comment]
Check your browser console for errors

**Comment by TommyCorr** [comment]
No errors :(

**Comment by TommyCorr** [comment]
![image](https://user-images.githubusercontent.com/6476657/105917641-3fb09f80-5ff8-11eb-9554-cf0bcfcb219f.png)

**Comment by olton** [comment]
Ok, I understand your problem. Maybe this is a bug in the dialog positioning procedure. I will study this question. Thank you for your feedback.

**Comment by TommyCorr** [comment]
Thank you Olton, I'll be on the lookout

**Comment by olton** [comment]
Try this
```
    function OpenDialog() {
        var dialog = Metro.getPlugin('#IdDialog', 'dialog');
        dialog.setTitle('My Dialog Title');
        dialog.setContent(...);
        setTimeout(function(){
            dialog.open();
        }, 100);
    }

```

**Comment by TommyCorr** [comment]
That did the trick, thank you Olton!

**Comment by olton** [comment]
Since the content for the dialog contains Metro **components**, which are built after adding them to the DOM, it takes some time to calculate the height correctly. For static content, you don't need to use setTimeout.

**Comment by TommyCorr** [comment]
Noted, thank you for your support
