### ISSUE TITLE
Is posible to add a row to a table, the row must be empty and have colspan = to all the fields

### ISSUE THREAD

**Issue by elpepefontana** [olton/Metro-UI-CSS#1718]
Hi.
I need to add a row/cell to a Metro UI table, that is empty = no content, i will add the content with javascript later, and with a colspan of all the columns, to add content all across the table?
See this image, i want to add a row/cell like the second one on the image, and later fill the content by javascript.
<img width="1084" alt="Captura de Pantalla 2021-02-05 a la(s) 12 32 15" src="https://user-images.githubusercontent.com/2715358/107053969-42588500-67ae-11eb-8b5b-4ea35e07a052.png">

**Comment by elpepefontana** [comment]
The row must be added between others rows.
Click on the top row, add the row just below the one you clicked (i'll add a button to do this, on each row).
Can it be done?
Thanks in advance.
José.

**Comment by olton** [comment]
You can use event `data-on-append-row` and append an additional row after inserted row. https://codepen.io/olton/pen/gOLXxbY?editors=1010
