### ISSUE TITLE
Checkbox indeterminate state

### ISSUE THREAD

**Issue by henriquewerlang** [olton/Metro-UI-CSS#1720]
In the https://metroui.org.ua/checkbox.html you have an example of the check box with the indeterminate state. The problem is that when you click the checkbox with this attribute, nothing happens.

By programming JS you call the toggle() function, the checkbox is cleared and marked as expected.

 - OS: Windows 10
 - Browser Chrome
 - Metro Version 4.4

**Comment by olton** [comment]
The indeterminate state can't be changing with a click on the input. You must change an attribute `data-indeterminate` value.
https://codepen.io/olton/pen/KKNgJqR
