### ISSUE TITLE
Table TR tags getting stripped

### ISSUE THREAD

**Issue by stpaulsmilaca** [olton/Metro-UI-CSS#1721]
**Describe the bug**
Either my browser has some nasty cache, or `<tr>` tags are stripped of anything I put in them.  I'm trying to create a double-click event so users can open a Metro Window by double-clicking on a table row.  But both the "ondblclick=" is stripped away, and if I try to add an id element to the tag (and run a jquery ondblclick function) the id tag disappears.

Is this actually happening?  And if so, does it need to?  And if so, is there a work-around?  Trying to create a membership page with a list of members, and the person who double-clicks on a member row can see the member's profile in a Metro.Window.  Sounds like it'd be cool.

**Comment by gakyuz** [comment]
I put them in a span tag and put the ondblclick  event  on this spna it worked.

Instead

               <td onclick=”f_test();”>test</td>

I use 

<td><span onclick=”f_test();”>test</span></td>

 

It worked in my case

**Comment by olton** [comment]
Table component rewrites `tr`, `td` tags. To create a clickable element inside a table,  you must use live binding for the click event on the table and delegate it to the required element:
```
$(table).on('dblclick', 'tr', function(e){
    ...
})
```

**Comment by stpaulsmilaca** [comment]
Thank you!  I will try both of these options and see which works the best in my context.  Also, one more question about tables.  What is the best jquery plugin or other framework to use with MetroUI's tables to bring in additional features such as printing, exporting to excel, or advanced features?  I'm quite comfortable with DataTables, but is it the one to use?

**Comment by olton** [comment]
You can export data from Metro table to CSV with built in method

**Comment by stpaulsmilaca** [comment]
I'm aware but there's other features I'm considering such as PDF exports, direct printing, emailing, and a few other things that Metro table, by itself, does not offer (yet).  BTW, I've totally abandoned Bootstrap for MetroUI!  I am really liking it.
