### ISSUE TITLE
data-role="switch" idea

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1723]
Hi Olton!

What do you think of the possibility of being able to define instead of the classic on/off switch, a switch made with icons or images?

For example:

```
<input id="FLAG" name="flag" type="checkbox"
       data-role="switch"
       data-icon-check="mif-lock fg-red"
       data-icon-uncheck="mif-unlock fg-green" checked />

```
A red closed lock would appear in the field space and clicking on it would be replaced by a green open lock.

Thank's!

**Comment by olton** [comment]
Added in 4.5.0
https://codepen.io/olton/pen/dyOZZbV?editors=1100

**Comment by olton** [comment]
If it doesn't show like this, clear your browser cache.
![2021-02-23-19-08-17](https://user-images.githubusercontent.com/365108/108880164-aed6df00-760a-11eb-8b98-53503626bbe7.png)

**Comment by TorakikiSan** [comment]
Awesome! Thank's!
