### ISSUE TITLE
Delay in Hint 

### ISSUE THREAD

**Issue by vahidbabaveisi** [olton/Metro-UI-CSS#1724]
I have a question regarding "Hints". I confronted with a problem. "When I hover the button, hints are showing instantly, but I want to show it with a desirable delay because it confuses the users". I have no opportunity to send the original code, but I saw the example in "https://metroui.org.ua/hints.html"; however, It didn't help me.

**Comment by olton** [comment]
In 4.5.0
Hint: added attribute `hintDeffered` if value of this > 0, a hint will display with delay.
```
<button class="button"
    data-role="hint"
    data-hint-text="This is a hinted button"
    data-hint-deferred=1000
>
    Hover me
</button>
```

**Comment by vahidbabaveisi** [comment]
Thanks, nut I can not find Metro 4.5.0, where is  the sources?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/4.5.0

**Comment by vahidbabaveisi** [comment]
Thanks for your consideration, but there is a problem. when users hover button A and move mouse to B, then the hint for A is shown after desired interval while mouse is on B.

**Comment by olton** [comment]
> Thanks for your consideration, but there is a problem. when users hover button A and move mouse to B, then the hint for A is shown after desired interval while mouse is on B.

fixed

**Comment by vahidbabaveisi** [comment]
Hi
Thanks, lets try it.

**Comment by vahidbabaveisi** [comment]
It works well. Thanks for your determination.
