### ISSUE TITLE
Window will not open

### ISSUE THREAD

**Issue by stpaulsmilaca** [olton/Metro-UI-CSS#1726]
Not sure if this is a bug or something I'm doing wrong.

Trying to create a "window" (what I used to call a modal in bootstrap??) that opens when I click a button.  I created the Window div as follows:
```
               <div id="editWindow" data-role="window" data-shadow="true" data-draggable="true" data-width="800" data-height="375" data-drag-area="window-area" data-title="Individual Editor" data-resizable="true" data-place="top-center" data-hidden="true">
                    <div class="window-caption">
                         <span class="icon mif-pencil"></span>
                         <span class="title">Individual Editor</span>
                         <div class="buttons">
                              <span class="btn-min"></span>
                              <span class="btn-max"></span>
                              <span class="btn-close"></span>
                         </div>
                    </div>
                    <div class="window-content p-2" id="indiveditor_window">
                         This content is dynamically created
                    </div>
               </div>
```
I've then created a button with an onclick event:

`<button onclick="Metro.window.show('#editWindow')" class="button success square mini outline" data-role="popover" data-popover-text="Edit Profile" data-popover-position="auto" data-hide-on-leave="true"><span class="mif-pencil"></span></button>`

However, I always get the following error in the console: "metro.js:6719 window #editWindow not found!"

Essentially what I want to do is create a window that appears and populates with member data and fields that the user can edit and save.  But I need to get the window to open, and this is where I'm seemingly missing something.

I'm using Metro 4.4.3.  Thanks!

**Comment by olton** [comment]
use codepen.io for your code

**Comment by stpaulsmilaca** [comment]
Here you go:
[codepen](https://codepen.io/petrakid/pen/QWGpPPW)

**Comment by olton** [comment]
```
<div id="editWindow" data-role="window" data-draggable="true" data-width="800" data-height="375"
     data-title="Individual Editor" data-resizable="true" data-place="top-center" data-hidden="true">
        This content is dynamically filled from Db
</div>

<button onclick="Metro.window.show('#editWindow')" class="button success" data-role="popover"
        data-popover-text="Edit Profile" data-popover-position="auto" data-hide-on-leave="true"><span
        class="mif-pencil"></span> Edit
</button>
```
