### ISSUE TITLE
Issue with dates and calendar picker

### ISSUE THREAD

**Issue by stpaulsmilaca** [olton/Metro-UI-CSS#1727]
As you can see in the example, the VALUE for the date is 1975/07/18, which is the correct value (pulled from DB).  But, as the example shows, the input field which is populated from that value shows a different date, specifically a day before, 1975-07-17.

Reading through the issues others have had concerning this, I've added the meta tag metro4:locale to the head and set it to en-US, i've added the php function date_default_timezone_set to "America/Chicago", I've added the data-locale attribute to the input, setting it to en-US, but still the date does not appear correctly.  It IS correct in the database.

I use Microsoft Edge for my browser, if that helps, and my PC is properly set to Central Time (CST).
![IMAGE 3](https://user-images.githubusercontent.com/78992884/108845454-11949000-75a3-11eb-988f-2f988e619b35.png)
![IMAGE 2](https://user-images.githubusercontent.com/78992884/108845456-11949000-75a3-11eb-9f84-bd60b89eaf97.png)
![IMAGE 1](https://user-images.githubusercontent.com/78992884/108845457-11949000-75a3-11eb-93cf-0334ca80597c.png)

**Comment by olton** [comment]
use addribute `data-input-format="YYYY-MM-DD"`
