### ISSUE TITLE
Crazy for a "collapse"

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1728]
Hi Olton!

Help, I'm going crazy with a "collapse"! See the example:

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

If I activate the checkbox, the "collapse" should close and the button that opens / closes it should be disabled, but the JS returns error on the "collapse" component.

Where is the problem?

Thank's

**Comment by olton** [comment]
Check your code. element with id `DIV-MACHINE` hasn't role `collapse`

**Comment by olton** [comment]
https://codepen.io/olton/pen/OJbzXma?editors=1010

**Comment by TorakikiSan** [comment]
OMG!

Another (my) stupid error!

Thank's!
