### ISSUE TITLE
Multi language support in table component

### ISSUE THREAD

**Issue by yamin1313** [olton/Metro-UI-CSS#1734]
Hello dear Mr. Pimenov

In metroui 4 "table",
when the table has no data, this text is displayed: "Nothing to show"
we ask you to, please add the multilanguage support for this element.

Thank you for your support

![table](https://user-images.githubusercontent.com/76277853/109942153-25e63480-7ce9-11eb-9a0a-1fefa0361206.png)

**Comment by TorakikiSan** [comment]
The attribute already exists

data-empty-table-title="text"

where you can put the text that will be displayed in the case of an empty table.

**Comment by olton** [comment]
use attribute `data-locale`

**Comment by yamin1313** [comment]
thank you sir
