### ISSUE TITLE
data-role="tabs" access to a specific tab

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1739]
Hi Olton!

I have this code (ex. https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111)

```
<UL data-role="tabs" data-expand="true" data-cls-tabs-list-item="text-bold fg-crimson" data-cls-tabs-list-item-active="fg-orange">
   <LI><A href="#MACHINE">Machine</A></LI>
   <LI><A href="#CLONES">Clones</A></LI>
   <LI><A href="#ROMS">Roms</A></LI>
   <LI><A href="#HISTORY">History</A></LI>
   <LI><A href="#INFO">Info</A></LI>
</UL>
```

How can I display, for example, the #HISTORY tab first without having to place it in the first position?

And the two attribute

data-cls-tabs-list-item="text-bold fg-crimson"
data-cls-tabs-list-item-active="fg-orange"

are correct?

I ask because, for example, if I replace fg-crimson with fg-steel the colors in the TABS are no longer recognized. Bug?

**Comment by olton** [comment]
This has to do with how the browser handles the order in which the styles are displayed. Styles of the same level take precedence in the definition - the later defined style is displayed. All color styles defined in one level. The color `fg-steel` is determined later, therefore takes precedence. For cases like yours, it's best to use your own color definitions.
```
.default-item {
  color: #647687;
}

.active-item {
  color: #fa6800!important;  
}
```

and in HTML
```
<UL data-role="tabs" data-expand="true" data-cls-tabs-list-item="text-bold bg-grayWhite-hover default-item" data-cls-tabs-list-item-active="active-item">
   <LI><A href="#MACHINE">Machine</A></LI>
      <LI><A href="#CLONES">Clones</A></LI>
      <LI><A href="#ROMS">Roms</A></LI>
      <LI><A href="#HISTORY">History</A></LI>
         <LI><A href="#INFO">Info</A></LI>
   </UL>
```

**Comment by TorakikiSan** [comment]
Thank's You.

To display a particular TAB first, what can I do? Exists an attribute like data-tab-active?

**Comment by olton** [comment]
> Thank's You.
> 
> To display a particular TAB first, what can I do? Exists an attribute like data-tab-active?

add class `active` to required tab (li)

**Comment by TorakikiSan** [comment]
Thank's!
