### ISSUE TITLE
Changing "Navigation View" Width

### ISSUE THREAD

**Issue by yamin1313** [olton/Metro-UI-CSS#1740]
Hi Mr. Pimenov
How can I change "Navigation View" width?

https://metroui.org.ua/navview.html

**Comment by olton** [comment]
hi, you must override specific styles

**Comment by olton** [comment]
You can't change compact width (48 px) this value uses as constant in js code of navview

**Comment by yamin1313** [comment]
thanks, but this solution can be used when we want to use original source of metroui4
but in this case that we are using the build of metroui4 (only metro-all.js & metro-all.css files), what is the solution?

**Comment by olton** [comment]
> thanks, but this solution can be used when we want to use original source of metroui4
> but in this case that we are using the build of metroui4 (only metro-all.js & metro-all.css files), what is the solution?

Override styles in an additional CSS file. Check out [Pandora](https://github.com/olton/Pandora) example, I override navview there.

**Comment by yamin1313** [comment]
fixed!
thank you

**Comment by one0410** [comment]
Excuse me! I didn't see naview overriding in https://github.com/olton/Pandora/tree/master/source/css
Could you please tell me where the overriding is ?
Thank you for the help.

**Comment by olton** [comment]
https://github.com/olton/Pandora/blob/master/source/css/index.less#L5
