### ISSUE TITLE
onSend Chat bug ?

### ISSUE THREAD

**Issue by virjeej** [olton/Metro-UI-CSS#1743]
Hi, I just started to work with metro and especially with the chat component.
I tried to use the onSend event but I can't manage to make it work on my project.
It seems like the onSend event doesn't respond to the click on the "send" button.

Here's a codepen that illustrates the problem : https://codepen.io/VirgileSP/pen/QWdLQyZ
When I click on the "send" button, nothing pops up in the console, and alert is not shown.

I'm working on widows 10, I tried this codepen on Firefox & Chrome, and i'm using the lastest version (4.4.3).
Is there actually a bug? Or am I doing something wrong?

Thanks.

**Comment by olton** [comment]
Your code work 
![2021-03-22-17-00-47](https://user-images.githubusercontent.com/365108/112010664-30e5f500-8b30-11eb-97c0-9c09a107b1dc.png)

**Comment by virjeej** [comment]
Alright, I thought it was fired regardless of the content of the input. Thanks.
