### ISSUE TITLE
data-role="calendarpicker" bug

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1744]
Hi Olton!

Code at:

https://codepen.io/TorakikiSan/pen/EeyWmp?editors=1111

If I set the date via JS (on click button in this example) and then I click the open calendar button, the calendar is always show the current day, not the day I set.

Thank's!

**Comment by olton** [comment]
Hi

First-off - you must use component method `val()`
```
Metro.getPlugin("#LAST_UPDATE", 'calendar-picker').val("01/02/2021");
```

In 4.4.3 this method have a bug, I fixed it in 4.5.0. Example (for 4.5.0) https://codepen.io/olton/pen/zYNveZa

**Comment by TorakikiSan** [comment]
Thank You for the answer.

When I set the field with an empty value, like

`Metro.getPlugin("#LAST_UPDATE", "calendar-picker").val("");`

I get this error

```
Metro 4 - v4.5.0. Built at: 02/03/2021 09:13:59 metro.js:7377:25
m4q - v1.0.10. Built at 08/01/2021 14:20:31

Uncaught (in promise) Error: Invalid date
    from metro.js:727
    val metro.js:12907
.
.
.
metro.js:727:22
```

Thank's

**Comment by TorakikiSan** [comment]
Sorry again, did you consider the possibility of being able to enter the date directly?

Thank's

**Comment by olton** [comment]
> Sorry again, did you consider the possibility of being able to enter the date directly?
> 
> Thank's

Haven't considered adding such a feature yet. At the moment, most of the time is spent making money for basic needs. A lot of funds take away the medicines that I need to take every day. The time on Metro 4 is now much shorter than usual because of this.

**Comment by olton** [comment]
to clear input, use 
```
$(selector).val('')
```

**Comment by TorakikiSan** [comment]
I am very sad to know that you still have health problems. Hope you can find all the help you need soon.

**Comment by olton** [comment]
in 4.5.0
+ [x] CalendarPicker: added API method `clear()`
+ [x] CalendarPicker: fixed API method `val()`, if you set argument as empty string `val("")`, you clear calendar picker value

**Comment by TorakikiSan** [comment]
Thank you very much for the wonderful work you have been doing
