### ISSUE TITLE
$.get - incorrect url built

### ISSUE THREAD

**Issue by CmPi** [olton/Metro-UI-CSS#1745]
**Describe the bug**

$.get(url, data, options) works fine whith data if url does not contain "?"
but if called with an url like _toto.php?a=0_ and _data= { b: 0 }_ the called url is  _toto.php?a=0?b=0_

**Expected behavior**
check if "?" is present in the url and add data with "&" instead of "?"

**Comment by olton** [comment]
Thank you

**Comment by olton** [comment]
Fixed in 4.5.0

**Comment by CmPi** [comment]
> Fixed in 4.5.0

Many thanks
