### ISSUE TITLE
Padding issue 

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1746]
Hi Olton,

I'm updating from 4.3.7 to latest release 4.4.3.
Padding stops working on cell div when I've got grid with no-gap.

Exemple : https://codepen.io/Falconpage/pen/YzNWxqp

**Comment by olton** [comment]
put div into cell and apply padding to it, no-gap cancelled paddings for the cells

**Comment by Falconpage** [comment]
Thanks
