### ISSUE TITLE
Problem with dot in JSON data for <select>

### ISSUE THREAD

**Issue by Pitanium** [olton/Metro-UI-CSS#1755]
Hi olton,

i have a problem with the `<select>` component. I try to retrieve data from a .NET Core WebAPI. This is the response JSON object from the WebAPI.

```
{
    "Vendor 1",
    "Vendor.2",
    "Vendor 3 GmbH",
    "Vendor 4 GmbH & Co. KG"
}
```

In the jquery success: method i do the following: 

```
success: function(successResponse) {
    var select = Metro.getPlugin('#select', 'select');
    select.data(successResponse));
}
```

Here is the point. The index 1 of the array fails with error: "metro.js:6139 Uncaught TypeError: Cannot read property '2' of undefined"

It seems the data([]) method try to access the 2 as property of the "Vendor.2" array index. Is there a other way to add the `<option>` to the `<select>`? 

Thank you very much for the help.

**Comment by olton** [comment]
Hi!
You must use a qualified JSON object:
```json
{
  "1": "Item 1",
  "2": "Item 2",
  "3": "Item 3",
  "Item group": {
    "1_1": "Item 1_1",
    "2_2": "Item 2_2",
    "3_3": "Item 3_3"
  }
}
```

https://github.com/olton/Metro4-Examples/tree/master/src/ajax

**Comment by Pitanium** [comment]
Hi olton, 

thank you. I've changed the output string from the WebAPI. Now i get the following: 

```
{
	"K001": "Vendor1",#
	"K002": "Vendor.2",
	"K003": "Vendor 3 GmbH",
	"K004": "Vendor 4 GmbH & Co. KG"
}
```
```
success: function(successResponse) {
    var select = Metro.getPlugin('#select', 'select');
    select.data(JSON.parse(successResponse)));
}
```

But Metro.js, line 6664 still fails with: 

`Uncaught TypeError: Cannot read property '2' of undefined`

Again at the Vendor.2 index. Do you have another idea? The error should by reproducable. 

Thank you very much.

**Comment by olton** [comment]
Delete `#` after first item

**Comment by Pitanium** [comment]
Oh, Sorry. This was a copy-paste failure. The # is not in the successResponse of the API

**Comment by Pitanium** [comment]
Here is a examble on Codepen: https://codepen.io/pitanium/pen/OJWOVrP

**Comment by marciotisouza** [comment]
Hello everyone !

When I pass the elements for assembly of the select and indicate the element to be selected, that doesn't happen!

tArray = {
	"K001": "Vendor1",
	"K002": "Vendor.2",
	"K003": "Vendor 3 GmbH",
	"K004": "Vendor 4 GmbH & Co. KG"
}
    var select = Metro.getPlugin('#select', 'select');
    select.data(tArray,'K002');

**Comment by olton** [comment]
> Hello everyone !
> 
> When I pass the elements for assembly of the select and indicate the element to be selected, that doesn't happen!
> 
> tArray = {
> "K001": "Vendor1",
> "K002": "Vendor.2",
> "K003": "Vendor 3 GmbH",
> "K004": "Vendor 4 GmbH & Co. KG"
> }
> var select = Metro.getPlugin('#select', 'select');
> select.data(tArray,'K002');

Thank you, fixed

**Comment by marciotisouza** [comment]
I took a look at version 4.5, I did the test here and needed to remove the + sign on the line: if (_selected.indexOf(key2) > -1). See if that's right

**Comment by olton** [comment]
> I took a look at version 4.5, I did the test here and needed to remove the + sign on the line: if (_selected.indexOf(key2) > -1). See if that's right

Already fixed
