### ISSUE TITLE
Input not clickable if use data-role="touch" in body

### ISSUE THREAD

**Issue by JoaquinDecima** [olton/Metro-UI-CSS#1757]
**Describe the bug**
The inputs cannot be selected. When clicking, no cursor appears to write if use data-role="touch"

**To Reproduce**
https://codepen.io/PatoJAD/pen/bGgYZMq

**Expected behavior**
By selecting the input box you should be able to type, see the type cursor

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browsers: chrome, firefox, vivaldi, qtwebbrowser
 - Metro Version: 4.3.2 and V4

**Smartphone (please complete the following information):**
 - Devices: Samsun j6 and samsung A6
 - OS: Android 9
 - Browsers: stock browser, chrome and Firefox
 - Metro Version 4.3.2 and V4

**Additional context**
If I remove 
```html 
<body data-role="touch">
```
don't have a problem

**Comment by olton** [comment]
Add attribute `data-excluded-elements`
```html
<body data-role="touch" data-excluded-elements=".input">
...
</body>
```

**Comment by olton** [comment]
For a lot of elements, use comma separated-value.
