### ISSUE TITLE
Charms not work

### ISSUE THREAD

**Issue by lvlirko** [olton/Metro-UI-CSS#1758]
Have the same problem.
Since the Sanbox is not accessible from you I have set up a new one.
https://jsfiddle.net/p1romg9k/7/

There it also does not work.
> Cannot read property 'toggle' of undefined
> "Element not contain role charms! Please add attribute data-role="charms" to element #default"

What exactly am I missing?

_Originally posted by @lvlirko in https://github.com/olton/Metro-UI-CSS/issues/1291#issuecomment-817155881_

**Comment by lvlirko** [comment]
Ok, did some tests.

When "data-role-charms="true" is specified - it does not work. 
> But this is what you used on your website for example: https://metroui.org.ua/charms.html (Sourcecode)

Another problem - charms only works with the dollar sign $('#default', 'charms').toggle() when charms is already open.

And .. Metro.getPlugin('#default', 'charms').toggle() always works.

After all, I did it now as a workaround that I call a function via onclick in which I pass the ID as a parameter.
In which then via Metro.getPlugin('#default', 'charms').toggle() the charm element is set on and off.

**Comment by olton** [comment]
The attribute `data-role-charms="true"` is used internally, created automatically, and should not be added manually

**Comment by olton** [comment]
To get access to component API use must use `Metro.getPlugin(element, componentName)` https://metroui.org.ua/components-api.html

**Comment by olton** [comment]
The documentation may lag behind the code. I have only two hands and I spend most of my time on work, not on the Metro.

**Comment by olton** [comment]
To create `charm`:
```html
<id="charm1" div data-role="charms" data-position="right">
    ...charm content here...
</div>
```
To open charm:
1) Use component API (access to API with method `Metro.getPlugin(...)`)
```javascript
var charm = Metro.getPlugin("#charm1", "charm");
charm.toggle(); // open, close
```
2) Use global object `Metro.charms` with methods `open()`, `close()`, `toggle()`, `closeAll()`, `opacity()`
```javascript
Metro.charms.open("#charm1");
```
