### ISSUE TITLE
.select() conflicts with copying data to clipboard

### ISSUE THREAD

**Issue by peltenburg** [olton/Metro-UI-CSS#1759]
I want to copy the content of an input field (with: data-role="input") to the clipboard. Simply using something like this:

    $(this).focus();
    $(this).select();
    document.execCommand('copy');

However, the .select() command generates a empty dropdown selectbox.
I assume this is because the select function overrides the original function. 
But maybe I'm just doing something wrong...

Metro 4 - v4.4.3. Built at: 27/12/2020 15:34:21
m4q - v1.0.10. Built at 08/12/2020 00:01:48

**Comment by olton** [comment]
The original function for selecting text in input is 
```
HTMLElement.select()
```
You are use $(element).select()

**Comment by peltenburg** [comment]
Thanks!
