### ISSUE TITLE
js native for in loop adding (shuffle,clone,unique,contains)

### ISSUE THREAD

**Issue by jeorlie** [olton/Metro-UI-CSS#1760]
** Weird behaviour **

I wrote a simple for loop to read my array I found out that my loop gives an incorrect value or behavior. The length of the array is only 3 yet when I use the for loop it becomes 7. Checking the log (console.dir(i)) I found this 4 weird values 

0, 1, 2, shuffle, clone, unique,  contains

The above is the result when I run this script

```
for(i in headers) {
 console.dir(i)
}
```

running the script above and produces the result below.
```
0
1
2
shuffle
clone
unique
contains
```

**Expected behavior**
The expected result is only 3 since the lenght of the object/array is only 3 yet I get 7 when I tried for loop.

**Screenshots**
![image](https://user-images.githubusercontent.com/7919418/115145592-f155ee80-a084-11eb-928d-5491b29f09bc.png)

**Desktop (please complete the following information):**
 - OS: (Ubuntu Mate 20.4)
 - Browser (Opera latest)
 - Metro Version (4)

**Additional context**
Please note that using jquery alone produce correct result but using metro.js (v4) produces some extra values.
I am noob and I am learning your metroui project sir. I hop you can help me. Is this a bug or not?

Please note that this error only occurs when I combine jquery and metro ui. I need jquery serialize, serializeArray so I am using your metroui along with jquery js.

**Comment by jeorlie** [comment]
Update: The weird behavior in for loop also shows even if I am using metro.js alone. 
This code below
```
var car = ['ford', 'kia', 'toyota'];

    for(i in car){
      console.dir(i);
    } 
```

produces same weird behavior and the output is below

![image](https://user-images.githubusercontent.com/7919418/115146636-e94c7d80-a089-11eb-9b82-44d6b575fdd0.png)

how can I fix this? in the mean time I am using $.each to loop however I wanted to use the for loop (natively).

**Comment by olton** [comment]
> Update: The weird behavior in for loop also shows even if I am using metro.js alone.
> This code below
> 
> ```
> var car = ['ford', 'kia', 'toyota'];
> 
>     for(i in car){
>       console.dir(i);
>     } 
> ```
> 
> produces same weird behavior and the output is below
> 
> ![image](https://user-images.githubusercontent.com/7919418/115146636-e94c7d80-a089-11eb-9b82-44d6b575fdd0.png)
> 
> how can I fix this? in the mean time I am using $.each to loop however I wanted to use the for loop (natively).

```
for (let i of car){
     console.log(i)
}
```

**Comment by olton** [comment]
Please, respect my time, use an issue tracker for the bug reports for Metro4 only.

**Comment by jeorlie** [comment]
> Please, respect my time, use an issue tracker for the bug reports for Metro4 only.

I am sorry for taking your time sir.
The repo link in https://metroui.org.ua/ was pointed here. I thought this is the repo. The link in the website is this https://github.com/olton/Metro-UI-CSS  so I just opened an issue. I apologized.

I wrote a codepen to save you some time reproducing the weird behavior that I experienced.
https://codepen.io/cloudwhen/pen/KKaxzMW

be well.

**Comment by olton** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration

**Comment by olton** [comment]
Your problem is the problem of using javascript language. This does not apply in any way to the use of Metro4.

**Comment by olton** [comment]
I added additional routines to Array type for quick solving certain problems. shuffle, clone, unique, contains is an additional method. You can see these when using the loop `for...in`.

**Comment by olton** [comment]
To access Array elements you must use loop `for...of`
