### ISSUE TITLE
Switch Text Status not updateable.

### ISSUE THREAD

**Issue by darbid** [olton/Metro-UI-CSS#1761]
**Describe the bug**
I am using the [Switch Text Status](https://metroui.org.ua/switch.html).

my HTML is simply

`<input type="checkbox" checked data-role="switch" data-on="on" data-off="off">`

I want to change the on and off - for example to ein and aus in German.

I have tried;

` element.setAttribute('data-on', 'ein');
  element.setAttribute('data-off', 'aus');`

This does not update the checkbox status text.

**To Reproduce**
just call element.setAttribute('data-on', 'ein'); on any element.

**Expected behavior**
The Text Status changes.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser firefox
 - Metro Version Metro 4 - v4.4.3. Built at: 27/12/2020 15:34:21 / m4q - v1.0.10. Built at 08/12/2020 00:01:48

**Additional context**
I tried sending a coffee to your[ paypal email address on this page ](https://metroui.org.ua/support.html) (also just sent you an email) Paypal sent the money to DNService. Is that correct?

**Comment by olton** [comment]
For PayPal all correct. Thank you.
For labels: you must define on/off text in component definition with attributes data-on, data-off.

**Comment by darbid** [comment]
Great the Paypal worked.

Are we talking about the same thing? I am talking about the Status Text within the element. In the picture the "ON" text.

![image](https://user-images.githubusercontent.com/3191525/115211685-18053b00-a100-11eb-9048-2d9af861f0d2.png)

I am able to set it with `<input type="checkbox" checked data-role="switch" data-on="on" data-off="off">` note both data-on and data-off.

My issue is changing these 2 values. I thought `element.setAttribute('data-on', 'ein'); element.setAttribute('data-off', 'aus');` would do it.

**Comment by olton** [comment]
```
<input type="checkbox" data-role="switch" data-on="ein" data-off="aus" data-material="true">
<input type="checkbox" data-role="switch" data-on="ein" data-off="aus" checked data-material="true">
```

https://codepen.io/olton/pen/oNbOZzr

**Comment by darbid** [comment]
I am at that point too. But what if my page supports multiple languages?

Once my document is ready I loop though all the elements and set the innerHTML to a certain language.  I would like to do the same for data-on  data-off?

**Comment by olton** [comment]
I added it to TODO for 4.5.0

**Comment by darbid** [comment]
Ok. Sounds good.  I suppose making them updateable would be the best.

Maybe because they are either on/off or positive/negative that they could also form part of your https://metroui.org.ua/i18n.html as well.  However that would be alot of work in supporting all the languages.

**Comment by olton** [comment]
I will add support for Metro4 i18n subsystem

**Comment by darbid** [comment]
Is it possible that [Select Components](https://metroui.org.ua/select.html) also do not update their text as well?

As I explained above I am using javascript to set option text based on language setting after the document has loaded;

`<select id="languageselect" data-role="select">
          <option value="language_default">Default</option>
          <option value="language_en">English</option>
          <option value="language_de">German</option>
        </select>`

I have tried using;

```
el.innerHTML = "";
el.textContent = "";
el.innerText = "";
```

**Comment by olton** [comment]
> Is it possible that [Select Components](https://metroui.org.ua/select.html) also do not update their text as well?
> 
> As I explained above I am using javascript to set option text based on language setting after the document has loaded;
> 
> ```
> <select id="languageselect" data-role="select">
>           <option value="language_default">Default</option>
>           <option value="language_en">English</option>
>           <option value="language_de">German</option>
>         </select>
> ```
> 
> I have tried using;
> 
> ```
> el.innerHTML = "newvalue";
> el.textContent = "newvalue";
> el.innerText = "newvalue";
> ```

https://github.com/olton/Metro4-Examples/tree/master/src/ajax

**Comment by olton** [comment]
Please do not mix questions in the same thread for different components. And if it's not a bug, use the discussions!

**Comment by olton** [comment]
in 4.5.0 I added:
+ [x] Switch: To show on-off label you must set attribute `data-show-on-off='true'` and use attributes: `data-on`, `data-text-on`, `data-off`, `data-text-off` or `i18n` configs with attribute `data-locale`
+ [x] Switch: added `i18n` support with props `locale.switch.on`, `locale.switch.off`
+ [x] Switch: added changing on-off text in runtime with API method `i18n(locale_name)`

**Comment by olton** [comment]
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="../metro/css/metro-all.css?ver=@@b-version" rel="stylesheet">

    <title>Test Switch - Metro 4 :: Popular HTML, CSS and JS library</title>

</head>
<body class="m4-cloak">
<div class="container">
    <h1>Switch test page</h1>

    <div class="mb-10">
        <button class="button">en-US</button>
        <button class="button">uk-UA</button>
        <button class="button">ru-RU</button>
    </div>
    <div>
        <input type="checkbox" data-role="switch" data-on="on" data-off="off">
        <input type="checkbox" data-role="switch" data-text-on="yes" data-text-off="no">
        <input type="checkbox" data-role="switch" checked data-locale="uk-UA">
        <input type="checkbox" data-role="switch" id="switch1">
    </div>
</div>

<script>
    window.metroSwitchSetup = {
        showOnOff: true
    }
</script>
<script src="../metro/js/metro.js?ver=@@b-version"></script>
<script>
    $("button").on("click", function(){
        Metro.getPlugin("#switch1", "switch").i18n($(this).text())
    })
</script>
</body>
</html>
```
