### ISSUE TITLE
Table Component with static table not show all rows

### ISSUE THREAD

**Issue by slouchy** [olton/Metro-UI-CSS#1764]
**Describe the bug**
I have total 1000 rows static table, but there only show 448 rows in my website (show 268 rows in fiddle).
And last page miss some row data, the table display incomplete.

**To Reproduce**
https://jsfiddle.net/slouchy/eh8Lt2nq/1/

**Expected behavior**

**Screenshots**
![image](https://i.imgur.com/kkkdUFu.jpg)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Chrome 89
 - Metro Version: 4.2.48

**Additional context**

In other online editor, there is no question

eq: codepen
https://codepen.io/slouchy592/pen/ExZdKRR

**Comment by olton** [comment]
Update Metro to the latest version. All work fine https://codepen.io/olton/pen/zYNmBpQ
