### ISSUE TITLE
Calendar Picker - wrong initial date

### ISSUE THREAD

**Issue by MenesesEvandro** [olton/Metro-UI-CSS#1767]
**Describe the bug**
The default value should be '2021-04-26' but right after the calendar picker initialization it changes to '2021-04-25'.

**To Reproduce**
```
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css">
<script src="https://cdn.metroui.org.ua/v4.3.2/js/metro.min.js"></script>
<input type="text" data-role="calendarpicker" data-locale="pt-BR" data-format="%d/%m/%Y" value="2021-04-26">
```

**Comment by olton** [comment]
check please with latest release version

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/README.md#lts
