### ISSUE TITLE
Calendarpicker show day less that date value assigned

### ISSUE THREAD

**Issue by nicocan** [olton/Metro-UI-CSS#1769]
I assign value to one day but calnedarpicker show day less

![image](https://user-images.githubusercontent.com/1160511/116708676-903bee00-a995-11eb-82f3-bf1782f2ee19.png)

Also, console shows warning:
The specified value "1951/08/27" does not conform to the required format, "yyyy-MM-dd".

I do not specify format or input format.
Only window.METRO_LOCALE are used.

**Comment by olton** [comment]
create pen on codepen.io with your problem code

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/CONTRIBUTING.md#issues-guidelines
