### ISSUE TITLE
Drag Items gets buggy

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1771]
**Description**
Role "Drag Items" gets buggy when you have a list with sub-items and you try to move those sub-items.

**To Reproduce**
Simply use the example on documentation, just add another sub-list in one of the items.

**Expected behavior**
Being able to drag sub-items without a problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/14809454/117335449-c7604280-ae60-11eb-87c2-efe9a80fd97e.png)
![DragItems2](https://user-images.githubusercontent.com/14809454/117335477-d0511400-ae60-11eb-99ee-53df8dd05278.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Metro Version 4.4.3

**Comment by olton** [comment]
use codepen to create example
