### ISSUE TITLE
ListView items appended on runtime not being properly rendered

### ISSUE THREAD

**Issue by rafaellehmkuhl** [olton/Metro-UI-CSS#1773]
First of all, thank you @olton for the awesome library!

**Describe the bug**
ListView used with Vue is initially rendered correctly, but new entries are not.

The data I'm trying to render is a array of objects.
The objects that are on the initial array are correctly rendered by Metro (it creates the necessary divs and spans inside the list-item (`<li>`). The ones that are appended after are correctly rendered by Vue (the show up on the  list (`<ul>`) but are not parsed by Metro (it doesn't create the divs and spans inside it).

I feel like I'm maybe missing something on how to tell Metro to update the elements on the screen. I was using grids before without problem, but with ListViews things are not working.

**To Reproduce**
https://codepen.io/rafaellehmkuhl/pen/PopwKRO?editors=1010

This minimum codepen is correctly reproducing the "bug", by appending new elements on an interval. You can see them showing up on the list, but not being properly handled by Metro.

**Expected behavior**
I was expecting that each new item appended to this array of objects would be correctly rendered by Metro.

**Screenshots**
![image](https://user-images.githubusercontent.com/6551040/117459334-a9a6e200-af21-11eb-808e-8820e72df5ff.png)

**Comment by rafaellehmkuhl** [comment]
Found [this issue](https://github.com/olton/Metro-UI-CSS/issues/1614) with the same problem.

As I understood, it's not a bug, but the fact that the library was developed with static pages in mind.

@olton do you see it as a possibility for the future of the library to be able to update the static items generation?

For the meantime, this was my manual implementation for the list-items to replicate the Metro parsing behaviour:

```html
<ul data-role="listview" data-view="table" data-select-node="true" data-structure='{"signal": true, "frequency": true}'>
  <li v-for="(network, key) in networks" :data-signal="network.signal" class="node" :key="key">
    <label class="checkbox transition-on">
      <input type="checkbox" data-role="checkbox" data-style="1" data-role-checkbox="true" class="">
      <span class="check"></span>
      <span class="caption"></span>
    </label>
    <span class="icon">
      <span class="mif-folder fg-orange"></span>
    </span>
    <div class="data">
      <div class="caption">{{ network.ssid }}</div>
    </div>
    <div class="node-data item-data-signal">{{ network.signal }}</div>
    <div class="node-data item-data-frequency">{{ network.frequency }}</div>
  </li>
</ul>
```

You can check it working here:
https://codepen.io/rafaellehmkuhl/pen/zYZxWZW?editors=1010

**Comment by olton** [comment]
> First of all, thank you @olton for the awesome library!
> 
> **Describe the bug**
> ListView used with Vue is initially rendered correctly, but new entries are not.
> 
> The data I'm trying to render is a array of objects.
> The objects that are on the initial array are correctly rendered by Metro (it creates the necessary divs and spans inside the list-item (`<li>`). The ones that are appended after are correctly rendered by Vue (the show up on the list (`<ul>`) but are not parsed by Metro (it doesn't create the divs and spans inside it).
> 
> I feel like I'm maybe missing something on how to tell Metro to update the elements on the screen. I was using grids before without problem, but with ListViews things are not working.
> 
> **To Reproduce**
> https://codepen.io/rafaellehmkuhl/pen/PopwKRO?editors=1010
> 
> This minimum codepen is correctly reproducing the "bug", by appending new elements on an interval. You can see them showing up on the list, but not being properly handled by Metro.
> 
> **Expected behavior**
> I was expecting that each new item appended to this array of objects would be correctly rendered by Metro.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/6551040/117459334-a9a6e200-af21-11eb-808e-8820e72df5ff.png)

This is not a bug, you must use API methods to add leaves to the list view. Currently, Metro has not supported dynamically intersection with frameworks such as Vue.
