### ISSUE TITLE
Bug: Popover not resizing to short texts

### ISSUE THREAD

**Issue by rafaellehmkuhl** [olton/Metro-UI-CSS#1774]
Popover too big (not resizing) when using with texts shorter than 20 characters:
![image](https://user-images.githubusercontent.com/6551040/117673700-634fbe00-b181-11eb-9ccf-80e9b83f2b50.png)

**Expected behavior**
Expected the popover to resize to short texts, as it does for long ones.

**Screenshots**

**Comment by olton** [comment]
add this style:
```
.popover {
    min-width: 0!important;
}
```
