### ISSUE TITLE
dynamically created tag input on Metro Dialog is not accessible via component API

### ISSUE THREAD

**Issue by n-mam** [olton/Metro-UI-CSS#1776]
Please see [this codepen](https://codepen.io/n-mam/pen/vYxLGqW)

I have a metro.dialog which creates the tag input element. The getTags in the above codepen function fails in all 3 callbacks (i.e. when executed directly inline from the callbacks).. The order is onShow first then comes onOpen and then finally onDialogCreate.. I was hoping that It should have at-least executed successfully from onDialogCreate because it seems to be the last callback.. but no it fails there as well.. It is only when I execute it after a timeout of 3 secs (from inside onDialogCreate) that it succeeds.. is there a better way do do this ? Either that or if you could point me to a (new) callback where the elements are guaranteed to have been created, then that should also be fine..

**Comment by olton** [comment]
Your 3 callbacks `onShow`, `onOpen`, `onDialogCreate` executing before a `input-tag` will create. 
In your case: first, the `dialog` is created and shown, then when the `input` is mounted in the **DOM**, a handler is called that will start the creation of the `input-tag`. You should access to component or after a time interval, or in the dialog actions. Also, you can use an event `data-on-tag-input-create` defined for input.

**Comment by n-mam** [comment]
Just for clarity.. when we say this:

`Also, you can use an event data-on-tag-input-create defined for input.`

are we suggesting that I should be able to access the component API in this event callback ? because Metro.getPlugin fails inside the  data-on-tag-input-create callback as well.. I am fine with accessing it via a setTimeout function.. just wanted to make sure that accessing the dynamically created component after a time interval is the only way to do it safely.
