### ISSUE TITLE
Sidebar Toggle Off When Clicking outside

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1777]
**Is your feature request related to a problem? Please describe.**
Not an issue but kinda annoying to have buttons on both page and sidebar to toggle OFF, Toggling ON is ok, but would be better to have an option to toggle OFF sidebar by clicking outside of it.

**Describe the solution you'd like**
data-toggle-outside= true|false
If true you can click anywhere on your web (Not sidebar) to close sidebar, if false then clicking outside will not make any effect, you have to set a button inside sidebar or have an accesable button on web to toggle it

**Comment by olton** [comment]
Added in 4.5.0 with attribute `data-close-outside`
