### ISSUE TITLE
Select all in table under pagination 

### ISSUE THREAD

**Issue by akayueh** [olton/Metro-UI-CSS#1778]
When a table its been paginated, when using "the select all" select box, instead of selecting the items on the current page, it selects all items through all the pages.

https://codepen.io/akayueh/pen/MWpeZRm

Am I missing some flag in the setting?

**Comment by olton** [comment]
This is not a bug, this behavior I added as logically correct when you select CHECK ALL. I will add new behavior for the case if need select/deselect in the current slice.

**Comment by olton** [comment]
Done, you can check it in 4.5.0

**Comment by akayueh** [comment]
Thanks.  is there a URL path to 4.5?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/4.5.0

**Comment by akayueh** [comment]
thanks.
