### ISSUE TITLE
Touch and swipe in carousel

### ISSUE THREAD

**Issue by gakyuz** [olton/Metro-UI-CSS#1779]
Is there a way enable touch and swipe in carousel component. I could not find in documantation. If not, it will be helpfull if it is enabled with a parameter.

**Comment by olton** [comment]
https://codepen.io/olton/pen/YzzEZyo

**Comment by gakyuz** [comment]
Thanks it worked as charm (as usual).I know that you are working alone, and know that in my experince how boring is, but, you should put this feature on the documentation page.

Gökalp AKYÜZ

 
 
  22:18’’21e’ 21 May 2021 Cum tarihinde, Serhii ***@***.***> şunu yazdı:   


https://codepen.io/olton/pen/YzzEZyo
