### ISSUE TITLE
table return all elements with getSelectedItems  .. even when i select only one 

### ISSUE THREAD

**Issue by Mohammed-abdelawal** [olton/Metro-UI-CSS#1786]
**Describe the bug**
the bug happen to me when i start use table inside master view .. when i get selected items inside master data-on-before-page it return all items and when i go back to the table page i found all items get selected

**Screenshots**
![Screenshot from 2021-06-12 18-24-33](https://user-images.githubusercontent.com/25667065/121782924-4d804f00-cbac-11eb-9947-ecc85b7da812.png)
then 
![Screenshot from 2021-06-12 18-24-44](https://user-images.githubusercontent.com/25667065/121782919-4b1df500-cbac-11eb-8ffd-706f3e815ba8.png)

 - OS: Ubuntu
 - Browser Firefox
 - Metro Version 4.4.3

**Comment by Mohammed-abdelawal** [comment]
and i notice that master has problem when i slide next and prev some times (2:5 times) it don't respond any more .. that's happen even in the examples on the documents website

**Comment by olton** [comment]
Please check it in 4.5.0

**Comment by olton** [comment]
> and i notice that master has problem when i slide next and prev some times (2:5 times) it don't respond any more .. that's happen even in the examples on the documents website

I have no such problems. Create your problem code on codepen.io

**Comment by Mohammed-abdelawal** [comment]
the same problem with 4.5
and another one when i press select all and error in the screenshot below
![Screenshot from 2021-06-12 19-36-11](https://user-images.githubusercontent.com/25667065/121791711-14b49a00-cbed-11eb-8f6c-f13450215808.png)

[https://drive.google.com/file/d/1gA7-ZaG1y7-4CsOt1T1CX7QVTsh8HTL_/view?usp=sharing](video with problem on site)

**Comment by olton** [comment]
Master bug confirmed, please create seprate issue

**Comment by olton** [comment]
> and i notice that master has problem when i slide next and prev some times (2:5 times) it don't respond any more .. that's happen even in the examples on the documents website

https://github.com/olton/Metro-UI-CSS/issues/1787

**Comment by olton** [comment]
Create an example with your code (for getting selected data) on codepen.io
