### ISSUE TITLE
Close App-bar on item click

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1788]
**Is your feature request related to a problem? Please describe.**
Not a problem, when app-bar is minimized not fully shown, when you click on an item it doesn't closes automatically.

**Describe the solution you'd like**
It would be nice to have an option that app-bar (when minimized) when you click on an item it closes automatically.

![Metro4AppBar](https://user-images.githubusercontent.com/14809454/123148362-c477dc00-d425-11eb-9b58-95d5ce0a305c.gif)

**Comment by olton** [comment]
You must handle this yourself using the `close()` method from the `app-bar` component `API`. Something like:
```javascript
$(element).on("click", function(){
    var appBar = Metro.getPlugin('element_selector', 'appbar')
    appBar.close()
})
```
