### ISSUE TITLE
Problem in windows desktop demo page ( https://metroui.org.ua/examples/desktop/desktop.html)

### ISSUE THREAD

**Issue by 432ena** [olton/Metro-UI-CSS#1789]
In the examples page of the metroui.org.ua, there is a very interesting example, which demonsrate an windows desktop (https://metroui.org.ua/examples/desktop/desktop.html).
So, 
There is a problem in this windows desktop demo page https://metroui.org.ua/examples/desktop/desktop.html
Steps to occur:
1. Open the "youtube" window 
2. Drag the opened window (from the title bar of the window) to the bottom so the cursor is UNDER the bar of the window
3. leave the button of the mouse, to stop dragging (when as I said the cursor is under the window bar with the title "youtube video")
4. Then the problem occurs: the window follows the cursor and you can not stop the dragging behavour with any way.
Could you please correct this problem or could you tell me how to correct it?
PS. I thing that this demo would be closer to windows reality, if it left the user to move the window beyond the "desktop" area (like the windows desktop). But ok, it is my opinion.

Thanks a lot for the answer and for the metroui which is one of my favorite frameworks!!

**Comment by olton** [comment]
Use discussion for repo https://github.com/olton/Metro4-Examples
