### ISSUE TITLE
CSS .text-ellipsis by number of lines

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1790]
Current .text-ellipsis uses: `white-space: nowrap` which assures there'll be only 1 line.

Implementing:
**.text-ellipsis-_[lines-number]_**

Replacing:

`white-space: nowrap`

by:

```
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: [number of lines];
```

**Comment by olton** [comment]
I do not use specific prefixed selectors in Metro 4
