### ISSUE TITLE
Components Tab bug

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1793]
**Describe the bug**
If you create many tabs it doesn't stay on parents dimensions, it just expands indefinitely.

**To Reproduce**
Just create multiple tabs, (Like alot)

**Expected behavior**
expand-point should activate automatically if too many tabs are created

**Screenshots**
![image](https://user-images.githubusercontent.com/14809454/125825610-116334a1-8f3e-4012-8f8a-c508035a3f61.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Metro Version v4.4.3

**Comment by olton** [comment]
use codepen.io to create example

**Comment by olton** [comment]
This is not a bug. Currently, you must control the count of tabs in the visible region.
