### ISSUE TITLE
Material Tabs Component Anchor Bug?

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1794]
**Describe the bug**
When a tab is active and you click it, it redirects you to "/#tab"  happens similarly on MetroUI Docs

**To Reproduce**
Just double click on an active Material Tab

**Expected behavior**
In normal tabs,When a tab is active and you click it, nothing happens which is good I think that should happen as well on material Tabs

**Screenshots**
Try it on MetroDocs

**Additional Context**
~~It works as it should if anchor tags are disabled, no redirection :)~~

CSS on anchor `pointer-events: none`

**Comment by olton** [comment]
use codepen.io to create example

**Comment by RodolfoXDR** [comment]
This "bug" is really easy to fix through CSS, so I don't really mind a lot on this but here it is, I'll leave you a Tab & Material Tab Comparison

**Comment by olton** [comment]
Thanks, fixed in 4.5.0
