### ISSUE TITLE
Material Tabs Bug

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1795]
**Describe the bug**
If you have many tabs, you can easily slide onto hidden tabs to the right however you cannot go back to see previous tabs unless the name it's pretty long.

**To Reproduce**
Have tabs with small names, go all the way to the right, you can't go back

**Expected behavior**
Be able to return

**Screenshots**
First Example of Material Tabs on MetroDocs 

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Metro Version [4.3.4]

**Comment by olton** [comment]
use codepen.io to create example

**Comment by RodolfoXDR** [comment]
![CantGoBack](https://user-images.githubusercontent.com/14809454/125973346-a8e69e76-a73e-4759-8daf-784bea053024.gif)

Right now I can't do the codepen snippet, but I leave you here an example of what I mean, I can't go back

**Comment by olton** [comment]
Hold the left button and move mouse

**Comment by RodolfoXDR** [comment]
I already tried that, look at this gif:
![Tab Bug](https://user-images.githubusercontent.com/14809454/127552773-8a927bc5-e810-4871-8391-f6a538b77343.gif)

**Comment by olton** [comment]
added mouse wheel support for scrolling tabs, thanks for feedback
