### ISSUE TITLE
checkbox/switch toggleState() doesn't work

### ISSUE THREAD

**Issue by FrancescoCarraro** [olton/Metro-UI-CSS#1799]
when using input type="checkbox" and data-role="checkbox" or data-role="switch" the toggleState() method doesn't work, while the other 2 available ones (enable, disable) work.

**Expected behavior**
checkbox/switch change its state after toggleState() has been called

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, edge]
 - Metro Version [e.g. 4.3.6]

**Comment by olton** [comment]
create example on codepen.io

**Comment by olton** [comment]
Your code has an error. You wrtite:
```
var elem = Metro.getPlugin('#myswitch');
```
but you must
```
var elem = Metro.getPlugin('#myswitch', 'switch');
```

**Comment by FrancescoCarraro** [comment]
Hi,
thanks for your reply.
Sorry for the issue in code. Anyway even when fixed, the code doesn’t work. In my production code I spent several minutes trying to understand, but no way. The test code has been  written in a hurry 😊

I also would like to warn you about an error in documentation.
Look at Switch - Metro 4 :: Popular HTML, CSS and JS library (metroui.org.ua)<https://metroui.org.ua/switch.html>
In ‘methods’ section the following example is available:
var checkbox = Metro.getPlugin(el,'checkbox');
I guess this is a typo….

Anyway thanks for your amazing work. I really love it…

Frankie

Da: Serhii Pimenov ***@***.***>
Inviato: giovedì 22 luglio 2021 08:09
A: olton/Metro-UI-CSS ***@***.***>
Cc: Francesco ***@***.***>; Author ***@***.***>
Oggetto: Re: [olton/Metro-UI-CSS] checkbox/switch toggleState() doesn't work (#1799)


Your code has an error. You wrtite:

var elem = Metro.getPlugin('#myswitch');

but you must

var elem = Metro.getPlugin('#myswitch', 'switch');

**Comment by olton** [comment]
thanks, fixed

**Comment by olton** [comment]
https://codepen.io/olton/pen/PomJeJm

**Comment by FrancescoCarraro** [comment]
Thank you very much!

Frankie

Da: Serhii ***@***.***>
Inviato: giovedì 22 luglio 2021 13:53
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [olton/Metro-UI-CSS] checkbox/switch toggleState() doesn't work (#1799)


https://codepen.io/olton/pen/PomJeJm<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodepen.io%2Folton%2Fpen%2FPomJeJm&data=04%7C01%7C%7C4461f4e95f974be3a10b08d94d07407a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637625515802417590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l6KIhZdHWodj7W30j8AzfjvHqjB4t66hE%2FuAjOKbX2k%3D&reserved=0>
