### ISSUE TITLE
data-on-clear-click on input doesn't work

### ISSUE THREAD

**Issue by FrancescoCarraro** [olton/Metro-UI-CSS#1800]
**Describe the bug**
I tried to define the callback for data-on-clear-click event, in input type="text" but is is not called

**Expected behavior**
callback should be called

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, edge]
 - Metro Version [e.g. 4.3.6]

**Comment by olton** [comment]
create example on codepen.io

**Comment by FrancescoCarraro** [comment]
Sorry,
it works. A mistake of mine

Frankie

Da: Serhii Pimenov ***@***.***>
Inviato: mercoledì 21 luglio 2021 16:17
A: olton/Metro-UI-CSS ***@***.***>
Cc: Francesco ***@***.***>; Author ***@***.***>
Oggetto: Re: [olton/Metro-UI-CSS] data-on-clear-click on input doesn't work (#1800)


create example on codepen.io

-
