### ISSUE TITLE
Clear button on Select doesn't fire onChange event

### ISSUE THREAD

**Issue by Lynx-Boreal** [olton/Metro-UI-CSS#1802]
Hello

On a **Select** component with `multiple` option and `data-clear-button` enabled, if one or more values are selected, clicking on the Clear button doesn't fire the `onChange` event. 

**To Reproduce**

    <select data-role="select" multiple data-clear-button="true" data-on-change="console.log('on-change fired')">
       <option value="1">Option 1</option>
       <option value="2">Option 2</option>
       <option value="3">Option 3</option>
    </select>
1. Select one or more options : the console reports the `onChange` event at each new selection (this is an expected behavior)
2. Clear the selection using the Clear button : the console does not report the `onChange` event

**Expected behavior**
Clicking on the Clear button should fire the `onChange `event, as the selection goes from one or several values to none.

**Desktop:**
 - OS: tested on Windows10 and Ubuntu 20.04.2
 - Browser : Chrome, Firefox
 - Metro Version : 4.3.2

**Comment by olton** [comment]
Thanks, fixed
