### ISSUE TITLE
$.post returning JSON problem

### ISSUE THREAD

**Issue by TorakikiSan** [olton/Metro-UI-CSS#1810]
Hi Olton!

Sorry, but i can't use codepen for this problem.

I use Firefox (last version 90.0.2), PHP (last version, 7.4.21) e Metro for ajax call. This is the script

```
  var tSelect=Metro.getPlugin("#MY_GROUP", "select");
  tSelect.data([]);

  $.post("/ajax.common.php", {
     query: "GROUP",
     machine: "mrdo"
    }).then(
       function(response) {
         console.log(response);
         var tOptions=JSON.parse(response);
         console.log(tOptions);

         tSelect.data(tOptions);
         tSelect.val("0");
       },
      function(xhr){
        console.log(xhr.status, xhr.statusText);
     });
```

If success return an array JSON with my favorite groups like

`{"0":"NEW GROUP","7082":"Mr DO! clone"}`

and if found no data

`{"0":"NEW GROUP"}`

This JS works fine with

```
Metro 4 - v4.5.0. Built at: 04/07/2021 21:11:56 metro.js:7385:25
m4q - v1.1.0. Built at 05/05/2021 22:47:56
```

while with official 4.5.0

```
Metro 4 - v4.5.0. Built at: 01/08/2021 18:39:05 metro.js:7385:25
m4q - v1.1.0. Built at 05/05/2021 22:47:56

```
if found no data, fail; seem don't recognize the "0" as index and no elements was added to select field!

If i put "-1" instead "0", this work, but i can't use this (-1 in my page mean other)

I hope that what I have written is enough to make you understand the problem and find the solution.

Thank's!

**Comment by olton** [comment]
https://codepen.io/olton/pen/QWvVJOv
This example demonstrated applying options from your "found no data" object `{"0":"NEW GROUP"}`. All works fine, check your ajax response data for troubles.

**Comment by TorakikiSan** [comment]
Thank you. I will investigate my problem
