### ISSUE TITLE
Can i use a descendant selector on metro ui?

### ISSUE THREAD

**Issue by elpepefontana** [olton/Metro-UI-CSS#1811]
Can i use a descendant selector in metro ui??? like this $('#ancestor #descendant') or like this Metro.getPlugin('#ancestor #descendant').
I have many forms on the same page, with ids 'form_0', 'form_1', 'form_2', etc.
This forms have all the same inputs, so i have an input 'street' on each of these forms, as well as a 'number' input, etc.
With Jquery i can use a descendant selector, is there a way to use them on metro  ui? will it work if i have jquery loaded to?
I want to do this:
`
.....

let select = Metro.getPlugin('#form_' + id_form + ' #' + id_input, 'select');

select.data(selectData);

.....
`
This is to automatically load all the options on the page combos.
Another way to do this?
Is using the Metro object posible when $ is owned by jquery?

is there a way to populate metro 4 combos with jquery???

**Comment by olton** [comment]
You can use descendant selector in metro
