### ISSUE TITLE
How to clickable table row and return the object data?

### ISSUE THREAD

**Issue by tomeroto** [olton/Metro-UI-CSS#1823]
How to clickable table row and return the object data?
And how to add some button on table cell?

**Comment by olton** [comment]
I already answered a similar question, look in the closed issues

**Comment by tomeroto** [comment]
can you give a link?

**Comment by olton** [comment]
Example - How to draw components and elements in table cell https://codepen.io/olton/pen/mdRwqBB

**Comment by olton** [comment]
To create a clickable row you must use live event binding/delegation
```
$(table).on("click", "tr", function(event){
    ...
})
```

**Comment by tomeroto** [comment]
thank you for the example.
