### ISSUE TITLE
Calendar Picker Component Bug

### ISSUE THREAD

**Issue by RodolfoXDR** [olton/Metro-UI-CSS#1824]
**Describe the bug**
When selecting a date it chooses 2 dates.

**To Reproduce**
https://codepen.io/RodolfoXDR/pen/YzQGzYX

**Expected behavior**
Work as on documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/14809454/132064118-8313717f-2302-4fb5-9ad7-d619de1617f7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Metro Version 4.5.0

**Comment by olton** [comment]
![2021-09-04-09-00-54](https://user-images.githubusercontent.com/365108/132084519-d73eab17-cfb4-45af-8de6-c78955393256.png)
All works fine for me

**Comment by RodolfoXDR** [comment]
Hmmm, it is pretty odd.

On the codepen I still see this bug, what do you think it could be?

**Comment by olton** [comment]
Can you record a short video of the problem?

**Comment by RodolfoXDR** [comment]
![Metrroui bug](https://user-images.githubusercontent.com/14809454/132228269-80a2f61a-cbaf-44bd-a2c0-c298feaa9443.gif)

**Comment by RodolfoXDR** [comment]
I already erased cache thinking it could be that, I also tested it on Microsoft Edge and same thing happens, I reset my PC and it keeps bugging.

And it is pretty strange cuz, on metroui docs, it does work well

**Comment by RodolfoXDR** [comment]
Update: I tested it on my iPhone and it is also bugged

**Comment by olton** [comment]
show your browser console

**Comment by RodolfoXDR** [comment]
![Metrroui bug3](https://user-images.githubusercontent.com/14809454/132243741-cb419e80-3af2-4f9c-bf23-1367ca73e44b.gif)

**Comment by olton** [comment]
Do you have a Metro connected twice?

**Comment by RodolfoXDR** [comment]
What do you mean connected twice? Like on codepen I haven't changed anything (https://codepen.io/RodolfoXDR/pen/YzQGzYX)

**Comment by olton** [comment]
In your console, I see connected metro.js and metro.min.js

**Comment by RodolfoXDR** [comment]
![image](https://user-images.githubusercontent.com/14809454/132246222-ff983a02-6fae-4ada-912c-bd1784a7acba.png)

**Comment by olton** [comment]
![2021-09-06-19-48-21](https://user-images.githubusercontent.com/365108/132246452-ade7621e-117b-40a3-ad22-e1443b93e38d.png)

**Comment by RodolfoXDR** [comment]
Yeah, I see what you mean, but how is that possible if I'm only using the external JS metro.min file

**Comment by RodolfoXDR** [comment]
And for example on MetroUI Docs I don't know if its correct but when selecting a Date it is marked as "Today"

![image](https://user-images.githubusercontent.com/14809454/132249806-e716442c-d443-4bb2-8f6c-9e156986dda4.png)

**Comment by olton** [comment]
![2021-09-06-20-45-57](https://user-images.githubusercontent.com/365108/132250127-ef8365cd-11b7-4ec1-9a53-0a2685954e73.png)

**Comment by olton** [comment]
I don't know where you get it :0

**Comment by olton** [comment]
The Docs uses an old version of Metro 4 (4.4.3) In this version `calendar-picker` works as you see. For selected date executes internal method `setToday(selected_date)`

**Comment by RodolfoXDR** [comment]
![image](https://user-images.githubusercontent.com/14809454/132250553-1625bea5-95aa-4728-9b4c-b208b7a6f8ee.png)

Look, I tested it on my iPhone and same thing happens, really I don't know what's happening X'D
