### ISSUE TITLE
How can i remove metro ui table row using table component api?

### ISSUE THREAD

**Issue by Jakirhosen** [olton/Metro-UI-CSS#1825]

**Comment by olton** [comment]
You can use methods `deleteItem(fieldIndex, value)` or `deleteItemByName(fieldName, value)`
```
var table = Metro.getPlugin(element, "table");
table.deleteItemByName("id", 123).draw();
```

**Comment by Jakirhosen** [comment]
Thanks. But i want to remove only one specific row when click delete button.

**Comment by olton** [comment]
use field with unique values

**Comment by Jakirhosen** [comment]
Ok, Thanks.
