### ISSUE TITLE
Table pagination is not compatible with ajax 

### ISSUE THREAD

**Issue by vahidbabaveisi** [olton/Metro-UI-CSS#1833]
Hello,

I am using Metro UI table component. I am happy with it, but when i using pagination, I become sad:

1) I want to load not all the data, but just selected page.
2) I  want to load each page by ajax, is that available or not.
3) Is pagination available when I load just one page data. I need this feature.

Thanks.

**Comment by olton** [comment]
Please use codepen.io to create example with your problem

**Comment by vahidbabaveisi** [comment]
my question is general.

**Comment by vahidbabaveisi** [comment]
I also uploaded my code. 
suppose I have a json that table is loaded from it. when data is large, table loads slowly. I want to load just the first page, but I should see pagination to navigate between pages. When I press page 2 then the rest of the data should be read from json on page 2. ofcourse accodring to Show entries number.
 How is this?
thanks
[https://codepen.io/vahidbabaveisi/pen/bGBQvEZ](url)

**Comment by olton** [comment]
Currently, partially loads not implemented. You can load full dataset only. Maybe in the next version I will add this feature.
