### ISSUE TITLE
Have conflict with CSS framework bulma, sticky invalid

### ISSUE THREAD

**Issue by benben233** [olton/Metro-UI-CSS#1844]
When using both [bulma](https://github.com/jgthms/bulma) and Metro-UI-CSS, the style of position:sticky becomes invalid.

Sample Code, the button can not stick on.
```
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css"> 
</head>
<body  style="height: 2000px;">
    <button style="position: sticky; top: 20px;"> test </button>
</body>
```
Also conflict with a minority framework [nicepage](https://nicepage.com/)

**Comment by olton** [comment]
Your question is not clear!

**Comment by benben233** [comment]
> Your question is not clear!

Why sticky becomes invalid?

**Comment by olton** [comment]
Create an example on codepen.io with your issue.

**Comment by benben233** [comment]
https://codepen.io/benben233/pen/bGoEZLW
Only if you delete one stylesheet link, the button becomes sticky

> Create an example on codepen.io with your issue.

**Comment by olton** [comment]
add style
```
body {
  overflow-x: none;
}
```
