### ISSUE TITLE
Metro 4 is not imported in project when using es6

### ISSUE THREAD

**Issue by vahidbabaveisi** [olton/Metro-UI-CSS#1880]
Hello,

I am working on a project that uses Metro UI framework. When I want to import the library it does not work. CSS is ok. I put an example in Codepen using CDN, but I can not put the node_modules folder to show the original problem. When I call table command, it does not recognize table but it recognize metro in console. I have to use await import structure due to using self-executive function. Also, I use import 'metro4' in my project, but the problems exists there again.

https://codepen.io/vahidbabaveisi/pen/WNJRReJ

**Comment by olton** [comment]
Hi! Use metro from cdn

чт, 15 сент. 2022 г. в 16:15, vahidbabaveisi ***@***.***>:

**Comment by vahidbabaveisi** [comment]
As I showed in Codepen, it does not work from CDN

**Comment by vahidbabaveisi** [comment]
any ideas...

**Comment by olton** [comment]
https://codesandbox.io/p/sandbox/metro4-vite-start-vljhzy?file=%2Fsrc%2Fmain.ts%3A1%2C1
