### ISSUE TITLE
Date picker data-day="false" errors

### ISSUE THREAD

**Issue by 66Noah2018** [olton/Metro-UI-CSS#1909]
Hi, 

I'm running into the following error when selecting a new month and or year from the date picker when the day is disabled: 
![image](https://github.com/olton/Metro-UI-CSS/assets/49675916/45fb8310-baf6-468b-9694-7e7f2f9ef8b2)
I'm running into the issue in my own appliction (v4.5.1, fixed version) as well as on the MetroUI website (https://metroui.org.ua/datepicker.html#_datepicker_parts) whenever one of the fields (i.e., year, month, or date) is disabled. 'Min & max years' and 'change locale at runtime' seem to be broken as well (FYI).

Is there anything I can do locally, can I downgrade to a version where the date/time pickers still work, or do I have to wait for a new version of MetroUI to be released?

**Comment by olton** [comment]
please create an example with your code on codepen.io

**Comment by 66Noah2018** [comment]
found the issue, turns out that I was using a setter somewhere in my code that apparently crashed the component. Did not expect that to be the cause

**Comment by 66Noah2018** [comment]
nvm... same issue, different result. I made a codepen: https://codepen.io/renskelotte48/pen/zYMyQGL?editors=1111#
I cannot upload screenshots there, so here's a screenshot of the copied error: 
![image](https://github.com/olton/Metro-UI-CSS/assets/49675916/e2f8e020-7dfd-4c5e-8eae-b1b33ec7daa6)

**Comment by olton** [comment]
fixed in 4.5.2, please check it

**Comment by olton** [comment]
You can access to 4.5.2 on 

https://cdn.metroui.org.ua/v4-dev/css/metro-all.min.css
https://cdn.metroui.org.ua/v4-dev/js/metro.min.js

**Comment by 66Noah2018** [comment]
Awesome! Thanks!
