### ISSUE TITLE
Static Calendar

### ISSUE THREAD

**Issue by festing** [olton/Metro-UI-CSS#1921]
How do I crreate the calendar so days are NOT selectable?  
I can preset days but if user happens to click on any day, the preset "blue check box" clears.

I simply want a static calendar with any options to select days.

**Comment by festing** [comment]
Any updates on this?  Regarding this a few other items.

- IF I happen to click a date, the preset dates disappear.  There should be some setting so that they remain regardless of what user clicks.
- I cannot CENTER the calendar in a div, frame, panel, etc...

**Comment by olton** [comment]
To center calendar use flex-model

**Comment by olton** [comment]
In the `dev (5.1.0)` branch I added to the calendar two additional options:
- `static` - user can't change calendar and can't change selection
- `readonly` - user can change month, and year but can't change selected

**Comment by festing** [comment]
Sadly... center does NOT work if in Panel.  When I add to panel div:   "data-cls-content=" fg-black d-flex flex-justify-center" the panel will not close, it's perpetually open.  I need it centered and closable.  UGH. LMK

Adding class to <div  data-role="calendar" does not work

**Comment by olton** [comment]
https://codepen.io/olton/pen/PoveOaz

**Comment by festing** [comment]
FANTASTIC!  Thank you!
