### ISSUE TITLE
Calendar OFF by 1 day

### ISSUE THREAD

**Issue by festing** [olton/Metro-UI-CSS#1922]
Calendar dates:  6/4-24 - 6/8/24
<div data-role="calendar" data-buttons="today" data-picker-mode="false" data-show="2024/06/04" data-preset="2024/06/04,2024/06/05,2024/06/06,2024/06/07,2024/06/08" data-role-calendar="true" class="calendar">

I have tried changing various date formats- NOTHING works.  Calendar is always 1 day shifted.

![cal off](https://github.com/olton/Metro-UI-CSS/assets/20490535/21985c2d-be79-41bd-a596-c932af243290)

**Comment by festing** [comment]
Some further research... the actual problem is the 1st day of the month is off by 1.
Example from above-  JUNE 1 is SATURDAY- NOT SUNDAY!!!!!  Calendar is currently unusable.  How to fix????

**Comment by olton** [comment]
What is your timezone?

**Comment by olton** [comment]
![image](https://github.com/olton/Metro-UI-CSS/assets/365108/66801702-1f5d-4075-9d94-805ce7343657)

**Comment by olton** [comment]
Use the latest version: dev branch, or 4.5.12-rc11 if you use from npm

**Comment by festing** [comment]
I'm using CDN.  I'm in US Central on a development PC.  All indications are my pc is set correctly
What/where would I look to find what system function is effecting this calendar generation

**Comment by festing** [comment]
Also, i'm uploading to a test server (offsite).  SAME issue exists on that system as well, so I'm unconvinced it's MY pc.  Something in coding I suspect.

**Comment by olton** [comment]
> I'm using CDN. I'm in US Central on a development PC. All indications are my pc is set correctly What/where would I look to find what system function is effecting this calendar generation

<link rel="stylesheet" href="https://cdn.metroui.org.ua/dev/metro.css">
<script src="https://cdn.metroui.org.ua/dev/metro.js"></script>

**Comment by festing** [comment]
UGH... When I add the dev links, the calendar works but all the ICONS are gone....

**Comment by olton** [comment]
```
<link rel="stylesheet" href="https://cdn.metroui.org.ua/dev/icons.css">
```
