### ISSUE TITLE
$(this) exists in m4q?

### ISSUE THREAD

**Issue by festing** [olton/Metro-UI-CSS#1926]
jQuery has $(this).  It enables me to control/grab/manipulate any object the mouse clicks on.
I cannot seem to find any documentation this exists within the framework.  Further when I try to implement, nothing happens.
Does metro have a "$(this)" function???

Please explain how I can click on an object and grab it's ID without knowing what it is.
thanks

**Comment by olton** [comment]
`this` must be a htmlelement

**Comment by festing** [comment]
got it... So why doesn't this grab the id of the list item???

**Comment by festing** [comment]
Got it! Thanks.
