### ISSUE TITLE
Calendar Picker stopped working

### ISSUE THREAD

**Issue by latinorooster** [olton/Metro-UI-CSS#1935]
**Describe the bug**
The calendar picker cannot be interacted with, i.e. cannot change the date. It was working upto a few days ago.

**To Reproduce**
Issue also occurs on https://metroui.org.ua/calendarpicker.html

**Screenshots**
Here is the error:
![image](https://github.com/olton/Metro-UI-CSS/assets/17992311/a6570fe8-371f-4372-8762-e6d524128532)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Metro Version: 4.5.12

**Comment by olton** [comment]
Thank you, fixed
