### ISSUE TITLE
V5.0.4 on Metro CDN breaks UI

### ISSUE THREAD

**Issue by alexAdtronics** [olton/Metro-UI-CSS#1936]
**Describe the bug**
Metro UI version v5.0.4 on the Metro CDN breaks some of the ui that works fine on v5.0.3.
Such as the app-bar brand no-hover not working, app-bar icon not display normally, and body padding top.

**To Reproduce**
For app-bar brand no-hover
```html
<a class="brand no-hover c-default pos-absolute put-left">
    <p class="text-leader text-medium fg-white">New project</p>
</a>
```

For app-bar icon
```html
<div class="row pos-absolute put-right">
    <a class="app-bar-item c-pointer" href='{{ logout }}'>
        <span class="mif-exit mif-2x icon fg-white"></span>
    </a>
</div>
```

For body
body's padding top was set to padding-top: 52px !important with p-ab (should be fixed by 5.0.6?)

**Expected behavior**
For app-bar brand no-hover
no hover effect and just display the text

For app-bar icon
display icon without a 'button' around it

For body
no padding on top

**Screenshots**
v5.0.4
![image](https://github.com/olton/Metro-UI-CSS/assets/149552010/936df406-0c6d-4c5b-a27e-12a0e25df6ae)

Expected (from v5.0.3)
![image](https://github.com/olton/Metro-UI-CSS/assets/149552010/7e90be43-63cc-4ca5-a108-544d7114f36d)

**Additional context**
Is there any way to choose library version from the CDN?

**Comment by olton** [comment]
Thank you for your feedback. I am currently actively modifying components to support CSS variables. There may be various problems before version 5.1.0.

You can choose the version from CDN for example 
```
https://cdn.metroui.org.ua/5.0.3/metro.css
https://cdn.metroui.org.ua/5.0.3/icons.css
https://cdn.metroui.org.ua/5.0.3/metro.js
```

**Comment by olton** [comment]
In version 5.0.4+: to change appbar color
https://codepen.io/olton/pen/BaeydvP?editors=1101

**Comment by olton** [comment]
Variables for each component will be written in its less file at the beginning.
For example: https://github.com/olton/Metro-UI-CSS/blob/dev/source/components/accordion/accordion.less#L4-L12

**Comment by olton** [comment]
`no-hover` - deprecated, use `app-bar-item-static`

**Comment by alexAdtronics** [comment]
> In version 5.0.4+: to change appbar color https://codepen.io/olton/pen/BaeydvP?editors=1101

But in this example, "M.A.M.E." changes color when hover, unless the bg-*-hover was set to be the same color as the bg color.

**Comment by alexAdtronics** [comment]
> In version 5.0.4+: to change appbar color https://codepen.io/olton/pen/BaeydvP?editors=1101

So in 5.0.4, the no-hover will not disable changing color when hover?

**Comment by alexAdtronics** [comment]
As the default icon changes from version 5.0.4, it is possible set the icon to custom icon in select's dropdown menu?

**Comment by olton** [comment]
> As the default icon changes from version 5.0.4, it is possible set the icon to custom icon in select's dropdown menu?

It is not entirely clear what we are talking about

**Comment by alexAdtronics** [comment]
> > As the default icon changes from version 5.0.4, it is possible set the icon to custom icon in select's dropdown menu?
> 
> It is not entirely clear what we are talking about

For example, the input-clear-button from select's dropdown menu, it used to be "<span class='default-icon-cross'></span>" (before v5.0.3?), from v5.0.4, it is a '❌', is it possible to change it to other custom icons?

![image](https://github.com/olton/Metro-UI-CSS/assets/149552010/83fc854d-c9eb-463a-bc34-d91abb88fe20)
