### ISSUE TITLE
some metro5  incompatibilities 

### ISSUE THREAD

**Issue by nlared** [olton/Metro-UI-CSS#1942]
some jquery incompatibilities with metro5 the last version that 

$.widget is not a function

$.fn.dataTable.pipeline

Metro 4 Working
https://nf5.nlared.com/tmp/datatablemetro4.php

Metro 5 issues
https://nf5.nlared.com/tmp/datatablemetro5.php

i have to use those links because use ajax create linked to session that codepen.io can't access

**Comment by olton** [comment]
1. Metro 5 not compatible with Metro4
2. The development of Metro 5 has been suspended indefinitely.

**Comment by nlared** [comment]
The problem is not between metro4 vs metro5
is about
metro5 and jquery
with $.fn

Metro 4 Working

https://nf5.nlared.com/tmp/datatablemetro4.php 
Metro 4 - v4.5.12
m4q - v1.1.0. Built at 05/05/2021 22:47:56

Metro 5 issues
https://nf5.nlared.com/tmp/datatablemetro5.php
METRO UI  v5.0.5  13.05.2024, 10:26:53 
M4Q  v2.1.1  12.05.2024, 14:54:16 
Hooks  v0.3.0  08.05.2024, 12:58:44 
HtmlJS  v0.8.0  08.05.2024, 13:24:07 
Animation  v0.3.0  08.05.2024, 13:35:42 
Farbe  v1.0.0  12.05.2024, 20:30:46 
Datetime Library  v3.0.4  08.05.2024, 14:05:56 
String  v0.5.0  08.05.2024, 14:20:26

**Comment by olton** [comment]
Metro UI is not responsible for the operation of third-party components.  Ask the DataTable developer a question.
