### ISSUE TITLE
Form validation "required number" not working

### ISSUE THREAD

**Issue by ct12goa** [olton/Metro-UI-CSS#1950]
**Describe the bug**
In the form the input validation **data-validate="required number"** is not working as expected.

**To Reproduce**
I checked even the example code given at https://docs.metroui.org.ua/validator.html. 

    <div class="form-group">
        <label>Input age</label>
        <input type="text" data-validate="required number" name="age">
         <span class="invalid_feedback">Please give only numbers</span> 
    </div>

**Expected behavior**
It should accept numbers, and "invalid_feedback" should invoke only when input is not a number. But, it invokes it for every input, even when we input a valid number.

**Screenshots**
![image](https://github.com/user-attachments/assets/ec8a8e9b-907c-4226-90ec-6396d589f0f8)

**Desktop (please complete the following information):**
 - Metro Version [e.g. 4.3.4]

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS:  Windows 10
 - Chrome
 - Metro Version : "https://cdn.metroui.org.ua/current/metro.css"

**Additional context**
None

**Comment by olton** [comment]
Please check it in latest version

**Comment by ct12goa** [comment]
How to check in latest version? I am using the CDN using this link https://cdn.metroui.org.ua/current/metro.css
Is this not the latest?

**Comment by olton** [comment]
Thank you. This is a bug in `Guardian` library. Now fixed in `dev`, tomorrow I merge this fix into master.

**Comment by olton** [comment]
fixed in master
