### ISSUE TITLE
Question about checkboxes

### ISSUE THREAD

**Issue by orichalcum** [olton/Metro-UI-CSS#288]
When I try to use the checkbox, the check mark that's supposed to appear doesn't do so. It looks like this instead:

![im](https://f.cloud.github.com/assets/4515304/673158/517642b0-d8ab-11e2-8870-353fa61d37ab.jpg)

I understand I need to add a link to the UTF-8 font to be able to get it to appear, would someone help me with how to do so please? Thanks again

**Comment by Gurucharan** [comment]
how checkbox data caption needs to capitalize the first letter.
