### ISSUE TITLE
ListView links do not work

### ISSUE THREAD

**Issue by afripino** [olton/Metro-UI-CSS#374]
I am not able to successfully link to another page with the ListView component. The URL is set correctly with the href tag, but no action is taken when a list item is clicked.

**Comment by Mike-Honey** [comment]
I've been stumped by this same issue also - the behaviour seems counterintuitive to me. 

FWIW I tried kerwitz's code but it was throwing HTTP errors.  Then I tried Olton's code - while debugging it threw: "JavaScript runtime error: 'list' is undefined", but it does seem to work...

**Comment by kerwitz** [comment]
Mike, `list is undefined` because @olton called the argument `_list` not `list`. But still: the argument does not contain the anchor but its parent - so my version should work.
What kind of errors did you get?

**Comment by Mike-Honey** [comment]
I haven't been able to repro those HTTP errors - I guess something else was happening on my side.

Now with kerwitz's code I'm getting the "out-of-the-box" behaviour - the clicked entry just becomes "active" without following the URL.  

Maybe I've built my DOM "wrong", but my list is an anchor, e.g. 

`<div class="group-content"><a class="list" href="google.com"><div class="list-content"><span class="list-title">Google</span></div></a></div>`

**Comment by aghict** [comment]
Hello,
I can not fix this problem please give more information about this solving this problem.
