### ISSUE TITLE
DatePicker on date-selected not working

### ISSUE THREAD

**Issue by EricBabin** [olton/Metro-UI-CSS#466]
Hi

I'm trying to capture the event when the date gets changed and I'm not sure how to do it. With the old .95a version I could use the date-selected event but I can't seem to get it to work with version 2.0.27. Here is my html and script.

	<div>
		<div id="dtpStartsOn" class="input-control text span3" data-role="datepicker" data-date="2014-01-01" data-effect="slide" data-format="yyyy-mm-dd" >
			<input id="txtDate" type="text"  />
			<button class="btn-date" type="button"></button>
		</div>
	</div>

	<script type="text/javascript">

		$(document).ready(function () {
			$('#dtpStartsOn').on('date-selected', function (el, dateString, dateMoment) {
				alert('date-selected');
			});
		});

	</script>

**Comment by ahmadkarim** [comment]
i tried it like you said it but it didnt work. I am trying to do exactly as what is done in the event binding example of metro UI. But no matter what i try it doesn't work i have tried this:
```
<div class="input-control text" data-role="datepicker" data-on-select="alert(d +'\n'+ d0)">
                            <input type="text">
                            <button class="button"><span class="mif-calendar"></span></button>
                        </div>
```

it dint work and i have tried this too:
```
$("#datepicker").datepicker({selected: function(dateString, dateObject) {
 alert('date-selected');
}});
```
