### ISSUE TITLE
No thing happened when setting value to zero on progress bar.

### ISSUE THREAD

**Issue by xiongchen2012** [olton/Metro-UI-CSS#485]
Progress bar was created with following code
    <div class="progress-bar"
    data-role="progress-bar"
    data-value="75"
    data-color="bg-pink"></div>

but when I change the value of the progress bar with javascript.

var pb = $("#componennt_id").progressbar();
pb.progressbar('value', 0);

No thing happend.

**Comment by thecopy** [comment]
Having the same problem,

        var finish = function () {
            dom.progressbar("value", 100);

            setTimeout(function () {
                dom.progressbar("value", 0);
            }, 1000);
        }

Sets it to 100, it also sets it to 0 after 1s in code-behind but the DOM is not updated
