### ISSUE TITLE
[Version 2.0.28] Examples are broken when viewing with Google Chrome

### ISSUE THREAD

**Issue by ehan1990** [olton/Metro-UI-CSS#496]
Many of the examples under the "docs" directory are broken when using Google Chrome. Some of the broken files include accordion.html, datepicker.html, fluent-menu.html, and more. In general, drop down boxes and tab controls are not working.

Tested with Ubuntu 12.04 with Google Chrome 32.0.1700.107. and Win7 with Google Chrome 33.0.1750.117.

Works fine with Firefox. 

Using metro ui css version 2.0.28

**Comment by parthi2929** [comment]
Can you please elaborate on how to fix this issue? Do we have to modify any file? If yes, can you kindly share the file?
