### ISSUE TITLE
data-hint dead when adding the attribute with jquery

### ISSUE THREAD

**Issue by tekamolo** [olton/Metro-UI-CSS#528]
After loading the page and pulling an ajax call which is adding a data hint. the attribute data-hint="foo message" doest not work.

**Comment by atcrawford** [comment]
For anyone that might run into this issue in the future. You just need to call this method after the DOM has been updated with the AJAX call: `$('[data-hint]').hint();`

I found that by looking at the metro-initiator.js file, located here: https://github.com/olton/Metro-UI-CSS/blob/master/js/metro-initiator.js

**Comment by olton** [comment]
Set global var METRO_AUTO_REINIT to true
