### ISSUE TITLE
Tiles not responsive

### ISSUE THREAD

**Issue by ninja-yan** [olton/Metro-UI-CSS#529]
Window resize, tiles with double to quadro goes beyond the container (span6)

![1](https://cloud.githubusercontent.com/assets/2074501/2563522/80e024a2-b880-11e3-9317-9601055be264.png)

![2](https://cloud.githubusercontent.com/assets/2074501/2563533/c4bbf14c-b880-11e3-858d-c9fb05e9aeba.png)

**Comment by wawneeds** [comment]
Any news on this ?

**Comment by navinkumarkg** [comment]
Cakn somebody revert back

**Comment by olton** [comment]
To foum please

**Comment by olton** [comment]
To foum please in topic Metro UI CSS 2x
