### ISSUE TITLE
Dynamically adding items in the list, it does not create the click event.

### ISSUE THREAD

**Issue by pedroisaac** [olton/Metro-UI-CSS#534]
Dynamically adding items in the list, it does not create the click event.

<code>
 element.find('.list').on('click', function(e){
                element.find('.list').removeClass('active');
                $(this).toggleClass('active');
                that.options.onListClick($(this));
                e.preventDefault();
});
</code>

**Comment by chwahab** [comment]
Metro.getPlugin('#all-list','list')._createItemsFromHTML()
