### ISSUE TITLE
Sample on how to use the streamer

### ISSUE THREAD

**Issue by SummerRijndael** [olton/Metro-UI-CSS#551]
hello sir could you please teach me on how am I going to use the streamer thanks

**Comment by prototypeSean** [comment]
+1 !!! it's a really awesome feature, i'm trying to rewrite it to base on weekly timeline or calender-like,  but still stock in figure out the structure...

**Comment by onlyongunz** [comment]
@olton wait, why did you close this? is this really still a prototype?

**Comment by onlyongunz** [comment]
@olton wait, no comment? really, mate?

**Comment by olton** [comment]
example of real usage
http://2017.iforum.ua/schedule/

**Comment by onlyongunz** [comment]
Can you a little bit, give us some documentation on how to use it, and why adding so much `event-*` to padd it?
