### ISSUE TITLE
Cannot use input file in dialog box

### ISSUE THREAD

**Issue by daniVerz** [olton/Metro-UI-CSS#558]
Hi,
I'm using dialog boxes with other types of input and have no problems, but I can't make a dialog work with an input type="file". The input box appears with missing borders and the open file icon fires the form submit. Am I missing something?
Any ideias?

    self.Upload = function () {
        $.Dialog({
            overlay: true,
            shadow: true,
            flat: true,
            draggable: true,
            icon: '<i class="icon-book"></i>',
            title: 'Novo arquivo',
            content: '',
            padding: 30,
            content:
                 '<form action="/StudentModule/Upload" enctype="multipart/form-data" class="user-input"> ' +
                    '<h3>Prova</h3> ' +
                    '<div class="input-control file"> ' +
                        '<input name="ExamFile" type="file" /> ' +
                        '<button class="btn-file"></button> ' +
                    '</div> ' +
                    '<button class="primary">Gravar</button> ' +
                    '<input name="StudentsModuleID" type="hidden" value="' + self.StudentsModuleID + '" /> ' +
                 '</form>'
        });
    }

Thanks,
Daniel

**Comment by LensHunnel** [comment]
Hi!
I have the same issue. Any ideas ?
