### ISSUE TITLE
error javascript runtime error object doesn ' t support property .tablecontrol

### ISSUE THREAD

**Issue by yooth** [olton/Metro-UI-CSS#560]
Hi friends,

I try to apply metro-UI-Css in visual studio2010.
I 've download from nuget  to vs 2010 and use nav bar . It ' s error   
javascript runtime error object doesn ' t support property .tablecontrol

happen on page load 

When I ignore this error ,nav bar can show on my page but it 's can not show dropdown menu when I click navy bar 

Please tell me for solve this problem.

**Comment by Mike-Honey** [comment]
I'm stumped by this too - did you ever find a resolution?

**Comment by Mike-Honey** [comment]
I've since found that if I remove the asp:ScriptManager section from the Site.Master generated by VS, the dropdown menu starts working. My hunch is there was some clash with Bootstrap or similar? 

I still get that runtime error for .tablecontrol ... it would be nice to sort that out.
