### ISSUE TITLE
Cannot get Metro UI navigation bar dropdown to work

### ISSUE THREAD

**Issue by vkurpad** [olton/Metro-UI-CSS#574]
I'm having trouble getting the navigation bar to work. I'm using Jquery ver 2.1.1. I've validated that jquery is working (added a little alert for window load). The navigation bar itself is rendering, but the dropdown just does not work. I'm using Visual Studio and installed the package via nuget.

JS Files included:
metro.min.js
jquery-2.1.1.js

CSS Files:
metro-bootstrap.css
metro-bootstrap-responsive.css

Please help.

**Comment by gopala-krishna** [comment]
Everything is working fine for me when all my webpages are in the root folder. when I moved one of my webpage to a sub folder dropdown-toggle, Accordin is not working...please help.

**Comment by geekgopala** [comment]
Everything is working fine when all my webpages are in the root folder. when I moved one of my webpage to a sub-folder many things are not working like
1) Dropdown-toggle on the top header
2) Accordin frame content

**Comment by mativer** [comment]
No idea to resolve the problem ? I still can't use the dropdown (i'm using the last version of Ruby on Rails, and all other components are up-to-date).

**Comment by SunDi3yansyah** [comment]
make sure the <init> all the components you have input into the <head>

provide the code you use?

**Comment by aureo91** [comment]
To solve this problem, I remplace 
	    
	    <script src="js/load-metro.js"></script>
By 
	    
	    <script src="js/metro.min.js"></script>
and now it works fine.
Thanks to Sergey for this great job !

**Comment by AVONnadozie** [comment]
I do have this issue of drop-down menu not working too, but only when I move a file out of the root folder. I've tried different ideas but none has worked so far. I always end up putting the file back into the root folder (against the initial project design).
My head tag has the same format as that in docs/examples.html

**Comment by ngugijmn** [comment]
This works for me using Javascript
--------------------------------------------------------
<ul class="dropdown-menu open" data-role="dropdown" id="menu" style="visibility:hidden;">
            <li class="menu-title">This is a title</li>
            <li class="menu-item"><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li class="menu-title">This is another title</li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="disabled"><a href="#">Disabled link</a></li>
            <li class="divider"></li>
            <li class="checked"><a href="#">Checked link</a></li>
            <li class="unchecked"><a href="#">Unchecked link</a></li>
            </ul>   
--------------------------------------------

Javascript
-------------------------------------------------------------
function toggle_visibility()
{
	    var e = document.getElementById("menu");
    if (e.style.visibility == 'hidden')
    {
		e.style.visibility = 'visible'; 
    }  else 
    {
		e.style.visibility = 'hidden';
    }	
}

**Comment by thilinapiy** [comment]
add this : <script src="js/metro/metro-dropdown.js"></script>

**Comment by DeanisRusmaniar** [comment]
@thilinapiy doens't works!

**Comment by Fngatia** [comment]
I done same as:
aureo91 who commented on Feb 28

thus:
To solve this problem, I replace

src="js/load-metro.js

WITH


src="js/metro.min.js
and now it works fine.
Thanks to Sergey for this great job !

Thanks so much..

**Comment by AVONnadozie** [comment]
Yes, I confirmed it as well, the suggestion by aureo91 does work but I hope the js/load-metro.js script removal does not affect the functionality of the library.

**Comment by fngatia** [comment]
Remember  olton commented on Dec 5, 2014 and said <quote>metro.min.js includes all js metro components...</quote>
Its Versa. This is the main library.

**Comment by AVONnadozie** [comment]
Ok. Actually, a look into js/load-metro.js shows that the script actually inserts js/metro.min.js to the head tag if the document's host name does not contain ".dev" or "modernui". In essence, the bug comes from line 5 of load-metro.js file which appends metro.min.js to head tag assuming the js directory is in the root directory i.e. "js/metro.min.js" instead of something like "path-to-js-directory/js/metro.min.js"
