### ISSUE TITLE
Implement Metro UI in MVC4 project

### ISSUE THREAD

**Issue by DilnuwanW** [olton/Metro-UI-CSS#643]
I'm new to MVC4. I have created few html pages with metro UI CSS. now i want to integrate them with my MVC4 project Please give me full tutorial how to intergrate them with my project.

**Comment by mbedded** [comment]
On http://metroui.org.ua there is a small demo, what you have to do.

<html>
    <head>
        <link rel="stylesheet" href="css/metro-bootstrap.css">
        <script src="js/jquery/jquery.min.js"></script>
        <script src="js/jquery/jquery.widget.min.js"></script>
        <script src="js/metro/metro.min.js"></script>
    </head>
    <body class="metro">
        ... markup page ...
    </body>
</html>

If you implement all the scripts and css you can use it within your MVC4 structure.
My advice: Try to understand the structure of your MVC4-Project first, and then import these scripts.
To use it, you have to update your _Layout.cshtml-file. It is the foundation of a MVC4-Project.

I assume that u mean ASP.Net MVC4 as you said "MVC4". If you understand the structure of a MVC-Project you can import/use every framework. It's not very different rom HTML-Websites.
