### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by vriera** [olton/Metro-UI-CSS#659]
More than 300 opened issues, a bunch of pull requests, latest commit older than one month...

Has this project been abandoned?

**Comment by ShubhamBadal** [comment]
@vriera ya i also wonder the same.
this is a good project, but last major release was over a year ago :(
i proposed some new ideas a few months back but i am not sure whats the current status of this project. check it here https://github.com/olton/Metro-UI-CSS/issues/559

**Comment by olton** [comment]
Dear friends! I live in Ukraine. You probably know what the situation, including economic. I now have to exert a lot of effort to provide for the family. Work on the framework is only very slowly, because most of the time I'm busy at the earnings. Sorry.

**Comment by billyhawaii** [comment]
God bless you. Olton .
