### ISSUE TITLE
How to use metro-ui-css for Single Page Applications built with AngularJS? (or backbone)

### ISSUE THREAD

**Issue by ShubhamBadal** [olton/Metro-UI-CSS#673]
The CSS works fine always.
but the jquery code (metro.min.js or all other metro js) does not work in the ng-view (partials)

Is there a AngularJS version of metro-ui-css?
if not, what changes are necessary to make metro jquery effects work with angular? what is the best solution?

**Comment by hmalipula** [comment]
The latest version of metro ui css has built-in support for RequireJS and Angular js. Please see this: http://metroui.org.ua/
