### ISSUE TITLE
TypeError: 'append' called on an object that does not implement interface FormData

### ISSUE THREAD

**Issue by dkova** [olton/Metro-UI-CSS#696]
Good day. I have an issue. I created a Dialog and paste into it form with a file upload. But it is not working and Firebug shows error:
    `TypeError: 'append' called on an object that does not implement interface FormData`

My JS code:

``` javascript
        function regnf()
        {
            var data = new FormData($('#s2')[0]);
            $.ajax(
            {
                url : "/include/proc/register.php",
                type: "POST",
                data : data,
                success:function(response)
                {
      window.location.reload;
            }});
        };
```

Please help me.

**Comment by juanu96** [comment]
add to ajax:({ 
        processData: false,
        contentType: false,
},
)
