### ISSUE TITLE
Metro Tiles animations fails after dynamic content load

### ISSUE THREAD

**Issue by dvinodeluru** [olton/Metro-UI-CSS#703]
Hi, 

Please provide a fix for this issue. I am having in need of these features. 
1. On mouse-hover on a tile a description should show by animating slides-up
2. When content populate dynamically, the animation doesn't works (&lt;div class="tile double bg-orange event_list live" data-role="live-tile" data-effect="slideUp"&gt; )
3.Specifi tiles must size to half for smaller screen resolution like 360x640

Please provide the inputs for this thanks in advance for your help

**Comment by kremen-karl** [comment]
Why this issue is closed without any answers?
