### ISSUE TITLE
Things are not working when webpages moved to sub-folder from root folder

### ISSUE THREAD

**Issue by geekgopala** [olton/Metro-UI-CSS#705]
Everything is working fine when all my webpages are in the root folder. when I moved one of my webpage to a sub-folder many things are not working like:
 1) Dropdown-toggle on the header
 2) Accordin frame content

Test Case:

1) Create a folder named "Test" in docs folder
2) Move Accordion.html to this folder
3) Edit  "<a href="Test/accordion.html">Accordion</a>"  in header.html
4) append the javascript files path, css files path, header.html with ../
5) Run - Try header dropdowns on headers and see accordion's data

**Comment by bruno4eva** [comment]
Re_Link all the js files especially the jquery.js am sure this might work.

--- Original Message ---

**Comment by olton** [comment]
use metro.min.js (contains all plugins) or check path in metro-loader.js

**Comment by geekgopala** [comment]
@olton  
Including metro.min.js works. shall I have to include this file in every sub-folder I create? why? 
any alternative solution?
How to modify path in metro-loader.js say for "test" subfolder? shall I have to include this file also in every subfolder? (things are working fine without this file as of now)
@bruno4eva 
Could you please help me how we can re-link a js file say for subfolder "test"?

**Comment by olton** [comment]
metro.min.js you need to include 1 times

**Comment by olton** [comment]
and please read this http://metroui.org.ua/requirements.html
