### ISSUE TITLE
iconFont.css missing from metro/docs/css/

### ISSUE THREAD

**Issue by tmey2016** [olton/Metro-UI-CSS#710]
http://metroui.org.ua/requirements.html

Indicates that iconFont.css should be in css/ folder. The url's in iconFont.css seem to agree. However, in the master branch (and sandbox), iconFont.css is not there, it is only in docs/css/ but the .htaccess in docs/ prevent it from working because it changes the protocol and domain name. If you agree, please copy iconFont.css into css/

Thank you.

**Comment by Mike-Honey** [comment]
I also noticed this file was missing from a VS project where I had installed Metro UI using nugget.  Perhaps it is for the same reason?
