### ISSUE TITLE
Can not scroll and enter text within dialog on mobile browser

### ISSUE THREAD

**Issue by koolpitt** [olton/Metro-UI-CSS#715]
Hello,

Please I can not have the dialog to scroll content on mobile, also textbox within the dialog can hardly be selected to input text but everything works perfectly on desktop.

Has anyone had the issue, please I need help.

Thanks in advance.

**Comment by SunDi3yansyah** [comment]
see the code you use?

**Comment by bruno4eva** [comment]
thats true. it only works perfectly on chrome.any help?

--- Original Message ---
