### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by gekobe** [olton/Metro-UI-CSS#716]
hi, 

I can't get to set up the countown like this:

05:00

only with minutes and seconds, starting from five minutes and stopping at 00:00.

could somebody help me?

Thanks.

**Comment by gekobe** [comment]
I'm trying with this:

    <div class="countdown" data-role="countdown" data-blink="false" style="font-size: 40px;">
          <span class="countMinutes">
                     <span class="digit-wrapper">                        
                                <span class="digit bg-dark fg-white" style="top: 0px; opacity: 1;">0
                                </span>                    
                       </span>                    
                     <span class="digit-wrapper">                        
                                 <span class="digit bg-dark fg-white" style="top: 0px; opacity: 1;">5
                                 </span>                    
                      </span>
           </span>
           <span class="divider fg-dark">
           </span>
          <span class="countSeconds">
                      <span class="digit-wrapper">                        
                                  <span class="digit bg-dark fg-white" style="top: 0px; opacity: 1;">0
                                  </span>                    
                       </span>                    
                       <span class="digit-wrapper">                        
                                  <span class="digit bg-dark fg-white" style="top: 0px; opacity: 1;">0
                                  </span>                    
                        </span>
             </span>
</div>

And I get this:
![1](https://cloud.githubusercontent.com/assets/10811480/6019314/63b82fc4-ab9f-11e4-9875-fa2a35c6c1dc.jpg)

**Comment by JohnArcher** [comment]
Did you try to set the time like this: 

```<div class="countdown" data-role="countdown" data-stoptimer="2013-07-05 12:00"></div>```

(see http://metroui.org.ua/times.html)

**Comment by gekobe** [comment]
yes, but I haven't a finish date. I only want a 5 minutes countdown since the user enter in this page.

Thank you.

**Comment by JohnArcher** [comment]
Depending on your site and which technologies you use you could calculate the finish date with PHP or JS, depending on the time the user visits your page the first time.

**Comment by gekobe** [comment]
I will try this option, but why I get so many digits? I only want minutes and seconds.

**Comment by olton** [comment]
v3 countdown demo http://metroui.org.ua/v3/countdown.html

**Comment by gekobe** [comment]
thank you!
Date: Sat, 14 Mar 2015 04:07:43 -0700
