### ISSUE TITLE
Form dropdown-menu

### ISSUE THREAD

**Issue by alexandresoliveira** [olton/Metro-UI-CSS#722]
Hi, everyone!

It's possible a form in dropdown menu like this ...

![screenshot from 2015-02-11 22 06 00](https://cloud.githubusercontent.com/assets/3682611/6159273/63210800-b23a-11e4-90d4-ce00f494ae93.png)

I don't want redirect for a new partial template only for this.

Thanks.

**Comment by bruno4eva** [comment]
Hi Alexandre Oliveira,

to achieve this very login you are looking for use css to customize the <ul class=”dropdown”>.

Give is a width and a height to fit you design.

Example

<li>
     <a href="#" class="dropdown-toggle">General CSS</a>
           <ul class="dropdown-menu" data-role="dropdown" style=’’width:250px,height:350px; background-color:#999; ‘’>
                <li>

                  <form>

                     //form details

                  </form>

                </li>
             </ul>
 </li>

**Comment by alexandresoliveira** [comment]
Thank bruno4eva for your help, but it does not work because, when you click my input, my component closes.
