### ISSUE TITLE
Metro UI CSS 3.0

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#734]
Countdown to version 3 started. See metroui.org.ua

**Comment by olton** [comment]
v3 Menu demo  http://metroui.org.ua/v3/menu.html

**Comment by olton** [comment]
v3 Grid demo http://metroui.org.ua/v3/grid.html

**Comment by olton** [comment]
v3 Buttons demo http://metroui.org.ua/v3/buttons.html

**Comment by bruno4eva** [comment]
hi sergey, for the v3 i suggest heights and widths of div elements should be included in the .css rather than part of the jquery plugins for easy adjustment of styles. thank you.

--- Original Message ---

**Comment by olton** [comment]
@bruno4eva what plugin is it?

**Comment by wgebczyk** [comment]
Hi,

Great that you plan to refresh control suite.

For me most important drawback is lack of support scenario where you dynamically load HTML parts from templates. The controls are initialized on page load and you have to hack current implementation to cover such scenario.

**Comment by olton** [comment]
@wgebczyk dynamically load and init HTML parts now default in 3.x

**Comment by Mike-Honey** [comment]
@olton  those demos look very nice - I'm keen to try it.

**Comment by olton** [comment]
http://metroui.org.ua/v3/inputs.html

**Comment by wgebczyk** [comment]
@olton how it detects attaching to DOM?

**Comment by olton** [comment]
DOM periodically checked for changes

**Comment by olton** [comment]
@wgebczyk 

```javascript
    $.Metro.initWidgets();

    if (METRO_AUTO_REINIT) {
        if (!canObserveMutation) {
            var originalDOM = $('body').html(),
                actualDOM;

            setInterval(function () {
                actualDOM = $('body').html();

                if (originalDOM !== actualDOM) {
                    originalDOM = actualDOM;

                    $.Metro.initWidgets();
                }
            }, 100);
        } else {
            var observer, observerOptions, observerCallback;
            observerOptions = {
                  'childList': true
                , 'subtree': true
            };
            observerCallback = function(mutations){
                mutations.map(function(record){
                    if (record.addedNodes) {
                        for(var i = 0, l = record.addedNodes.length; i < l; i++) {
                            var obj = $(record.addedNodes[i]);
                            if (obj.find('[data-role]').length) {
                                $.each(obj.find('[data-role]'), function(){
                                    var $this = $(this), func = $this.data('role');
                                    $.fn[func].call($this);
                                });
                            }
                        }
                    }
                });
            };
            observer = new MutationObserver(observerCallback);
            observer.observe(document.body, observerOptions);
        }
    }
```

**Comment by wgebczyk** [comment]
great! seems that it will be transparent regardless of js framework. thanks! :)

**Comment by olton** [comment]
v3 inputs full demo http://metroui.org.ua/v3/inputs.html

**Comment by bruno4eva** [comment]
Am impressed by what am seeing. Metro V3 looks very promising.@olton keep it up. 56hrs more...#wink

--- Original Message ---

**Comment by olton** [comment]
@bruno4eva 56 days more... :)

**Comment by olton** [comment]
v3 progressBar demo http://metroui.org.ua/v3/progressbar.html

**Comment by olton** [comment]
v3 table demo http://metroui.org.ua/v3/tables.html

**Comment by olton** [comment]
v3 windows demo http://metroui.org.ua/v3/windows.html

**Comment by olton** [comment]
v3 typography demo http://metroui.org.ua/v3/typography.html

**Comment by olton** [comment]
v3 images partial demo http://metroui.org.ua/v3/images.html

**Comment by olton** [comment]
v3 images partial demo http://metroui.org.ua/v3/images.html (upd added fitImage plugin demo)

**Comment by olton** [comment]
v3 calendar demo http://metroui.org.ua/v3/calendar.html

**Comment by olton** [comment]
v3 datepicker demo http://metroui.org.ua/v3/datepicker.html

**Comment by olton** [comment]
v3 stepper demo http://metroui.org.ua/v3/stepper.html

**Comment by bruno4eva** [comment]
@olton if you agree with me, tiles dont look nice on moble portal view. I stand to be corrected. If the titles are allowed to resize  to fit full screen i ll like it.

--- Original Message ---

**Comment by olton** [comment]
The main new feature in version 3 is: a declarative approach to the definition and initialization of components, and the framework itself monitors components, pressure via ajax. When a declarative definition of all component parameters are set via data - attributes, including methods and events of the component. This approach allows to further separate html and javascript code. Now that would determine which component do not need to know javascript :).

**Comment by olton** [comment]
v3 countdown demo http://metroui.org.ua/v3/countdown.html

**Comment by olton** [comment]
v3 wizard2 prototype demo http://metroui.org.ua/v3/wizard2.html (this wizard as Azure)

**Comment by olton** [comment]
v3 sidebar demo http://metroui.org.ua/v3/sidebar.html

**Comment by olton** [comment]
v3 tabControl demo http://metroui.org.ua/v3/tabcontrol.html

**Comment by olton** [comment]
v3 accordion demo http://metroui.org.ua/v3/accordion.html

**Comment by olton** [comment]
Fully updated treeview. New future, new render. More on http://metroui.org.ua/v3/treeview.html

**Comment by Nikandros** [comment]
excellent!

**Comment by olton** [comment]
v3 TreeView updated for indeterminate state, please test it http://metroui.org.ua/v3/treeview.html

**Comment by bruno4eva** [comment]
It works fine on wp8 IE10 and wpUcBrowser

Sent from my Windows Phone
________________________________

**Comment by olton** [comment]
need to check the correctness of the status indeterminate when placed and removed a check on the leafs

**Comment by Mike-Honey** [comment]
I tried it on a windows 8.1 machine, using ie11, chrome 41 and opera 28.  The expand, collapse and checking all worked well.  But I did notice that for the Checkbox & Radio tree and the Indeterminate tree, when you click the text of any entry, it becomes bold, but the checkbox or button is not affected.  I would expect that the checkbox or button associated with the text gets set/unset?  Otherwise I guess don't set the text to bold.

**Comment by olton** [comment]
@Mike-Honey  this is a diferent objects with own events and methods

**Comment by olton** [comment]
@Mike-Honey you can associate manualy over event "click"
```javascript
            <script>
                function tree_add_leaf_example_click(leaf, node, pnode, tree){
                    var checkbox = leaf.siblings('.input-control');
                    checkbox.click();
                }
            </script>
```

**Comment by Mike-Honey** [comment]
Ok - great.  Thanks for explaining.

**Comment by olton** [comment]
v3 will be moved to the repository on bitbucket

**Comment by olton** [comment]
Templates: http://metroui.org.ua/v3/templates/start-screen.html

**Comment by olton** [comment]
minor update for start screen demo ;)

**Comment by olton** [comment]
minor update for start screen demo: added handler for search button

**Comment by olton** [comment]
minor update for start screen demo: added handler for settings button

**Comment by olton** [comment]
Explorer style listview http://metroui.org.ua/v3/listview.html

**Comment by olton** [comment]
Reset notify system http://metroui.org.ua/v3/notify.html

**Comment by bruno4eva** [comment]
@olton . Notify displays well on IE 10. Its also cool in mobile view.

Sent from my Windows Phone
________________________________

**Comment by olton** [comment]
if You want to get early access to version 3 (alpha) give me your email

**Comment by bruno4eva** [comment]
Bruno4eva@live.com
________________________________

**Comment by olton** [comment]
Check email

**Comment by bruno4eva** [comment]
Thanks @Olton. I have been able to download it now.

**Comment by olton** [comment]
completely rebuilt the font icons http://metroui.org.ua/v3/font.html

**Comment by asdw741111** [comment]
chizongyang@aliyun.com 

thanks



姓名：池宗洋
邮箱：chizongyang@aliyun.com
 
From: Sergey Pimenov
Date: 2015-04-10 20:48
To: olton/Metro-UI-CSS
Subject: Re: [Metro-UI-CSS] Metro UI CSS 3.0 (#734)
if You want to get early access to version 3 (alpha) give me your email

**Comment by olton** [comment]
if You want to get early access to version 3 (alpha) give me your email and confirm my skills on linkedIn

**Comment by olton** [comment]
v3 Preloaders http://metroui.org.ua/v3/preloaders.html

**Comment by bruno4eva** [comment]
Does it start automatically? How do you end the loader then.

**Comment by olton** [comment]
```
$("preloader").hide()
```

**Comment by olton** [comment]
@bruno4eva preloader is not a control. This visualization element
