### ISSUE TITLE
Hint issue

### ISSUE THREAD

**Issue by didix16** [olton/Metro-UI-CSS#738]
Hi again... I'm experimenting a new issue. This time are with hints. I'm refreshing the data-hint value with javascript but when I show again the hint it has the same value not the new...

Any ideas to solve it?

Thanks in advance.

**Comment by didix16** [comment]
Well I tried to solve it. It works now as spected by doing this: I've manually edit metro.min.js and in _destroy method of widget hint I wrote:
```javascript
var a=this.element;a.removeData("hint");
```
Then, before I call the "refresh" data-hint  method, I check if data-hint attribute exists and if exists, call the destroy method.
```javascript
if($("#elem").attr("data-hint"))
		$("elem").hint("destroy");
```
If anyone has better solution please let me know.

Thanks!

**Comment by olton** [comment]
thanks

**Comment by didix16** [comment]
You are welcome :+1:
