### ISSUE TITLE
Suggestions to Metro UI CSS v3

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#739]
Dear friends! If You have suggestions for version 3, please write them here. I will try their best to satisfy.

**Comment by AnnieGitUrGun** [comment]
Hi there!

Love what you're doing. I have one suggestion. I forked a copy of your project and added themes for the dialogs. I guess it's not 100% in the Metro style but I've found it useful for the project I'm currently working on. Below is what the dialog.js now looks like.

```javascript
(function($) {
    if (METRO_DIALOG == undefined) {
        //var METRO_DIALOG = false;
    }

    $.Dialog = function(params) {
        if(!$.Dialog.opened) {
            $.Dialog.opened = true;
        } else {
            return METRO_DIALOG;
        }

        $.Dialog.settings = params;

        params = $.extend({
            icon: false,
            title: '',
            content: '',
            flat: false,
            theme: '',
            shadow: false,
            overlay: false,
            width: 'auto',
            height: 'auto',
            position: 'default',
            paddingTop: false,
            paddingLeft: false,
            paddingRight: false,
            paddingBottom: false,
            overlayClickClose: true,
            sysButtons: {
                btnClose: false,
                btnOK: false,
                btnCancel: false
            },
            onShow: function(_dialog){},
            sysBtnCloseClick: function(event){},
            sysBtnMinClick: function(event){},
            sysBtnMaxClick: function(event){},
            sysBtnCancelClick: function(event){
                $.Dialog.close();
            },
            sysBtnOKClick: function(event){}
        }, params);

        var _overlay, _window, _caption, _content, _footer;

        _overlay = $("<div/>").addClass("metro window-overlay");

        if (params.overlay) {
            _overlay.css({
                backgroundColor: 'rgba(0,0,0,.7)'
            });
        }

        _window = $("<div/>").addClass("window");
        if (params.flat) _window.addClass("flat");
        if (params.theme == 'default') _window.addClass("default");
        if (params.theme == 'lime') _window.addClass("lime");
        if (params.theme == 'red') _window.addClass("red");
        if (params.theme == 'blue') _window.addClass("blue");
        if (params.theme == 'orange') _window.addClass("orange");
        if (params.shadow) _window.addClass("shadow").css('overflow', 'hidden');
        _caption = $("<div/>").addClass("caption");
        _content = $("<div/>").addClass("content");
        _content.css({
            paddingTop: params.paddingTop,
            paddingLeft: params.paddingLeft,
            paddingRight: params.paddingRight,
            paddingBottom: params.paddingBottom
        });
        _footer = $("<div/>").addClass('footer').addClass('button-set');
        if (params.sysButtons) {
            if (params.sysButtons.btnClose) {
                $("<button/>").addClass("btn-close").on('click', function(e){
                    e.preventDefault();
                    e.stopPropagation();
                    $.Dialog.close();
                    params.sysBtnCloseClick(e);
                }).appendTo(_caption);
            }
            if (params.sysButtons.btnMax) {
                $("<button/>").addClass("btn-max").on('click', function(e){
                    e.preventDefault();
                    e.stopPropagation();
                    params.sysBtnMaxClick(e);
                }).appendTo(_caption);
            }
            if (params.sysButtons.btnMin) {
                $("<button/>").addClass("btn-min").on('click', function(e){
                    e.preventDefault();
                    e.stopPropagation();
                    params.sysBtnMinClick(e);
                }).appendTo(_caption);
            }
            if (params.sysButtons.btnOK) {
                $("<button>OK</button>").addClass("btn-ok").on('click', function(e){
                    e.preventDefault();
                    e.stopPropagation();
                    params.sysBtnOKClick(e);
                }).appendTo(_footer);
            }
            if (params.sysButtons.btnCancel) {
                $("<button>Cancel</button>").addClass("btn-cancel").on('click', function(e){
                    e.preventDefault();
                    e.stopPropagation();
                    params.sysBtnCancelClick(e);
                }).appendTo(_footer);
            }
        }

        if (params.icon) $(params.icon).addClass("icon").appendTo(_caption);
        $("<div/>").addClass("title").html(params.title).appendTo(_caption);

        _content.html(params.content);

        _caption.appendTo(_window);
        _content.appendTo(_window);
        _footer.appendTo(_window); 
        _window.appendTo(_overlay);

        if (params.width != 'auto') _window.css('min-width', params.width);
        if (params.height != 'auto') _window.css('min-height', params.height);

        _overlay.hide().appendTo('body').fadeIn('fast');

        METRO_DIALOG = _window;

        _window
            .css("position", "fixed")
            .css("z-index", parseInt(_overlay.css('z-index'))+1)
            .css("top", ($(window).height() - METRO_DIALOG.outerHeight()) / 2 )
            .css("left", ($(window).width() - _window.outerWidth()) / 2)
        ;

        addTouchEvents(_window[0]);

        if(params.draggable) {
            _caption.on("mousedown", function(e) {
                $.Dialog.drag = true;
                _caption.css('cursor', 'move');

                var z_idx = _window.css('z-index'),
                    drg_h = _window.outerHeight(),
                    drg_w = _window.outerWidth(),
                    pos_y = _window.offset().top + drg_h - e.pageY,
                    pos_x = _window.offset().left + drg_w - e.pageX;

                _window.css('z-index', 99999).parents().on("mousemove", function(e) {
                    var t = (e.pageY > 0)?(e.pageY + pos_y - drg_h):(0);
                    var l = (e.pageX > 0)?(e.pageX + pos_x - drg_w):(0);

                    if ($.Dialog.drag) {
                        if(t >= 0 && t <= window.innerHeight - _window.outerHeight()) {
                            _window.offset({top: t});
                        }
                        if(l >= 0 && l <= window.innerWidth - _window.outerWidth()) {
                            _window.offset({left: l});
                        }
                    }
                });
                e.preventDefault();
            }).on("mouseup", function() {
                _window.removeClass('draggable');
                $.Dialog.drag = false;
                _caption.css('cursor', 'default');
            });
        }

        _window.on('click', function(e){
            e.stopPropagation();
        });

        if (params.overlayClickClose) {
            _overlay.on('click', function(e){
                e.preventDefault();
                $.Dialog.close();
            });
        }

        params.onShow(METRO_DIALOG);

        $.Dialog.autoResize();
        // Prevent the body from scrolling while the dialog is open.
        $('html, body').css('overflow', 'hidden');
        return METRO_DIALOG;
    }

    $.Dialog.content = function(newContent) {
        if(!$.Dialog.opened || METRO_DIALOG == undefined) {
            return false;
        }

        if(newContent) {
            METRO_DIALOG.children(".content").html(newContent);
            $.Dialog.autoResize();
            return true;
        } else {
            return METRO_DIALOG.children(".content").html();
        }
    }

    $.Dialog.title = function(newTitle) {
        if(!$.Dialog.opened || METRO_DIALOG == undefined) {
            return false;
        }

        var _title = METRO_DIALOG.children('.caption').children('.title');

        if(newTitle) {
            _title.html(newTitle);
        } else {
            _title.html();
        }

        return true;
    }

    $.Dialog.autoResize = function(){
        if(!$.Dialog.opened || METRO_DIALOG == undefined) {
            return false;
        }

        var _content = METRO_DIALOG.children(".content");

        var top = ($(window).height() - METRO_DIALOG.outerHeight()) / 2;
        var left = ($(window).width() - METRO_DIALOG.outerWidth()) / 2;

        METRO_DIALOG.css({
            width: _content.outerWidth(),
            height: _content.outerHeight(),
            top: top,
            left: left
        });

        return true;
    }

    $.Dialog.close = function() {
        if(!$.Dialog.opened || METRO_DIALOG == undefined) {
            return false;
        }

        $.Dialog.opened = false;
        var _overlay = METRO_DIALOG.parent(".window-overlay");
        _overlay.fadeOut(function(){
            $(this).remove();
        });
        // Allow the body to scroll again
        $('html, body').css('overflow', 'auto');
        return false;
    }
})(jQuery);
```

**Comment by mtycholaz** [comment]
Integration with WinJS?

**Comment by olton** [comment]
@mtycholaz NO

**Comment by 0xbaadf00d** [comment]
Hi,

what about :
  - More color theme for the bottom menu bar
  - Compatibility with AngularJS or EmberJS

**Comment by duytq** [comment]
Hi.
Can you make loader for Metro-UI? That is displayed when user's waiting some task .
Thanks.

**Comment by enr00ted** [comment]
Less use of the "!Important" as I have to do black magic to change some styles :)

**Comment by olton** [comment]
@enr00ted http://metroui.org.ua/v3/sliders.html (min[max]Value example)

**Comment by enr00ted** [comment]
- Be able to set the calendar to choose only years, or only months or the way it works right now. So it becomes a 3 in 1 picker (year, month or day). I imagine it like a 3-depth widget, and you start by selecting year, then month, then day but be able to limit the depth.

Can't wait for the v3, just in time for my academic project :)

**Comment by bruno4eva** [comment]
@olton. Please can you add a php sample script on how to retreive form values of input fields when the slider and switches are used?

--- Original Message ---

**Comment by olton** [comment]
@bruno4eva http://metroui.org.ua/v3/sliders.html (Example: Put slider value to input)

**Comment by olton** [comment]
@bruno4eva switch eq checkbox :)

**Comment by aminsaghi** [comment]
RTL support please...

**Comment by ShubhamBadal** [comment]
I believe this present version can be improved a lot by adding more new features and functionality. These are my ideas which can be considered for next releases and most are derived from windows metro design -


integrated off-canvas metro-styled sidepanel
bottom panel (on-hover or on-click) (can be used as footer or nav pane)
charms bar on-hover (as in windows 8)
top-panel (like in outlook mail)


tiles stack vertically first instead of horizontal (better for mobile/tab screens)
drag and drop for tiles (save positions using cookies or local storage)
customize bg and tile color (save using cookies or local storage)
an 'All apps' screen (an extension of start screen, like in windows 8)
keyboard selector for tiles (like in win 8 start screen)
enable right click for tiles and start screen


background/theme/color changer (like in win 8 start screen)
continuously varying background color (as seen when setting up windows 8 first time)


smoother scroll in startscreen (tiles page)
parallex scroll in startscreen
scroll on right edge hover like in windows 8 start screen
ajax loader to load more tiles on scroll

if you like some of my ideas let me know because i think i can help more. thank you very much. you are doing great work, keep it up!

**Comment by devo5teee** [comment]
RTL support

**Comment by enr00ted** [comment]
@olton What will happen with the actual elements from version 2, like the navigation-bar ? Will it be a plug'n'play transition or I will have to redo things, or do them differently ? :)

We also need more icons, font icons, or a way of creating them. I normally use http://www.flaticon.com/ for images but I prefer font-icons. I am not sure about the licencing though.

**Comment by olton** [comment]
@enr00ted trying to do so would be most compatible

**Comment by olton** [comment]
@enr00ted icons you can use any, it might be your own set

**Comment by enr00ted** [comment]
I'm only a student not a very experienced developer, so bear with me. I have one question that might turn into another suggestion, regarding the defined grid system. For example, I want to add a navigation-bar at the top and a sidebar. If I just define them with the syntax they will correctly overlap because both start from the upper left corner and take 100% of the width/height (and maybe they have different indexes ?). I imagine being able to build a ui like a puzzle, or a matrix grid.

Overlap!

![captura 104](https://cloud.githubusercontent.com/assets/3756926/6951330/c602a270-d8ba-11e4-920a-8dfe520910c9.png)

Matrix grid system (in my head).
- Red as the topbar
- Yellow as the sidebar
- Every cell width is the total width/number of colums defined
- Every cell height is the total height/number of rows defined

![captura 105](https://cloud.githubusercontent.com/assets/3756926/6950327/6b30a5e0-d8ba-11e4-87cd-a7f78004bbb8.png)

If this makes no sense, then I appologize :)

**Comment by if1live** [comment]
## CSS class name with prefix
### Use metro-ui-css with other css library
For example, pure-css use prefix. 
http://purecss.io/buttons/
```
<button class="pure-button pure-button-disabled">...
```

Thus mixing pure-css and bootstrap is possible.
http://purecss.io/extend/

### Safe
current metro-ui-css use short css classname.
```
<button class="button info">Button</button>
<button class="button link">Button</button>
```
info, link, success, ... is too simple. It may conflict with other library or user's stylesheet.
Adding prefix is a method to avoid css conflict.

**Comment by enr00ted** [comment]
Make tiles unclickable, so that one can add buttons, and other interaction elements inside.

**Comment by olton** [comment]
@enr00ted If you do not see icons from other fonts, you incorrectly connect the font

**Comment by olton** [comment]
@if1live Metro UI CSS since version 3 is no longer positioned as an additional style, so additional namespaces will not be

**Comment by enr00ted** [comment]
@olton I don't think so, might be, i'm not sure, but the icons work fine outside the tiles.

![captura 109](https://cloud.githubusercontent.com/assets/3756926/7004053/c67d697a-dc65-11e4-98b3-77f6c383e434.png)

```
<div class="tile-group two">
	<div class="tile-group-title text-bold text-shadow fg-white">PASSWORD 
		<i class="fa fa-music"></i>
	</div>
	<div class="tile double triple-vertical bg-taupe opacity">
		<div class="tile-content">
			<div class="margin20">
				<label class="fg-white text-shadow">Current password</label>
				<div class="input-control text block shadow" data-role="input-control">
					<input type="text">
					<button class="btn-clear" tabindex="-1" type="button"></button>
				</div>
				<label class="fg-white text-shadow">New password</label>
				<div class="input-control text block shadow" data-role="input-control">
					<input type="text">
					<button class="btn-clear" tabindex="-1" type="button"></button>
				</div>
				<label class="fg-white text-shadow">Repeat new password</label>
				<div class="input-control text block shadow" data-role="input-control">
					<input type="text">
					<button class="btn-clear" tabindex="-1" type="button"></button>
				</div>
				<br>
				<button class="block">CHANGE</button>
				<i class="fa fa-music"></i>
			</div>
		</div>
	</div>
</div>
```

```
/* Rewrite fonts path for fonts-awsome.min.css */
@font-face{
  font-family:'FontAwesome';
  src: 
      url('/Touristique/fonts/fontawesome-webfont.eot?v=4.3.0');
  src: 
      url('/Touristique/fonts/fontawesome-webfont.eot?#iefix&v=4.3.0') 
      format('embedded-opentype'), 
      url('/Touristique/fonts/fontawesome-webfont.woff2?v=4.3.0') 
      format('woff2'), 
      url('/Touristique/fonts/fontawesome-webfont.woff?v=4.3.0') 
      format('woff'), 
      url('/Touristique/fonts/fontawesome-webfont.ttf?v=4.3.0') 
      format('truetype'), 
      url('/Touristique/fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular') 
      format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by enr00ted** [comment]
8) This arrow type of drop-down, drop-up, would be very cool.
![captura 110](https://cloud.githubusercontent.com/assets/3756926/7010225/d76ee99a-dc9f-11e4-91e9-96213c88b0e3.png) 
Also it seems you can't add shadows right now, it looks kind of bad. Now it merges with the naigation bar, and you can't really tell wich is what. I would prefer someting that gives the impression of floating, similar to the image.
![captura 111](https://cloud.githubusercontent.com/assets/3756926/7010338/9d776860-dca0-11e4-82ff-fb036635e32e.png)

PS: If I'm spamming too much, please let me know :)

**Comment by olton** [comment]
@enr00ted arrow this is google style, not windows metro, shadow maybe I will reconsider

**Comment by ShubhamBadal** [comment]
We can s=have something like in bing - metro style dropdown with tiles. very useful for modern navigation problems.

![screenshot 38](https://cloud.githubusercontent.com/assets/6375378/7021740/b5483b16-dd42-11e4-89d8-826dfd7eec13.png)

**Comment by ShubhamBadal** [comment]
Also i think we should add ability to center a span.
center tags don't work for tiles and span in this framework.
we can have certain classed like . centered to move any element to center of screen like in gumby framework.

check this : http://gumbyframework.com/docs/grid/#!/centered-columns

right now, its very difficult to use <center> tags with metro ui css especially in tiles and span classes.

**Comment by ShubhamBadal** [comment]
also we can add some cool animations to tiles and spans

example:
http://sarasoueidan.com/demos/windows8-animations/

**Comment by ShubhamBadal** [comment]
we should also work on metro styled off-canvas and smart navigation panels.
we can either include these plugins directly in this metro ui css or write our own code for something like this.

live demo:
http://demo.siterepo.com/metropanel/metropanel-left.php?mpid=metrotabs
http://demo.sonhlab.com/biz/js-plugins/openpanel/demo.php
http://demo.sonhlab.com/biz/js-plugins/metrotab/metrotab-v2.html
http://demo.sonhlab.com/biz/js-plugins/metrobox/metrobox.php

more here:
http://www.webdesigntunes.com/coding/metro-style-navigation-menus/

**Comment by olton** [comment]
@ShubhamBadal https://msdn.microsoft.com/en-us/library/windows/apps/hh465424.aspx

**Comment by ShubhamBadal** [comment]
yes, that is a good guide to metro design. we should always follow that. I just shared some elements (features) that are missing (and should be added) to make metro-ui-css for modern metro styled web apps. :)

**Comment by olton** [comment]
@ShubhamBadal and I'm very grateful for the resources provided

**Comment by olton** [comment]
@ShubhamBadal tiles animation in v3 http://metroui.org.ua/v3/tiles.html

**Comment by enr00ted** [comment]
Very cool animations :)

**Comment by ShubhamBadal** [comment]
@olton very good sir, but please do not remove anything that is there in existing version because all tile animations and elements that are in v2 are also very good! :)

**Comment by olton** [comment]
@ShubhamBadal no one was going to remove them

**Comment by enr00ted** [comment]
Regarding the arrow and non-metro drop-down/up, I think it's not that hard to acheive. I used a notice widget and hided the drop-down holder. However the arrow position and the placement need "a little bit of fiddling :)

![captura 112](https://cloud.githubusercontent.com/assets/3756926/7030140/bfc15120-dd62-11e4-9884-ff7229c503a2.png)

**Comment by bruno4eva** [comment]
@Gabriel, I think the class " .metro.notice.marker-on-top" has same effects. That small triangle sitting on the rectangle 😁.

Sent from my Windows Phone
________________________________

**Comment by enr00ted** [comment]
@bruno4eva Yes, that's what I used :grin:

**Comment by olton** [comment]
@enr00ted I will add a simple implementation of a drop-down block with arrow tomorrow or the day after, so stay tuned 3rd

**Comment by enr00ted** [comment]
@olton One question with these drop-downs, wich I did not understand from the docs in v2: Can I specify in wich direction does it take space/opens or is it automatic ? This might also be usefull, what do you think ?

![sense titol](https://cloud.githubusercontent.com/assets/3756926/7030893/311bf2a8-dd68-11e4-87f7-89fee705d9a2.png)

**Comment by olton** [comment]
@enr00ted http://metroui.org.ua/buttons.html#_dropdown-btn

**Comment by enr00ted** [comment]
@olton Ok :smile:

**Comment by aminubakori** [comment]
@olton Great work you have done in V3. The changes are impressive i cant wait for it to be released. By the way can you please check the tiles page? It seems like they dont scroll in mobile view. Thanks

**Comment by Mike-Honey** [comment]
@olton I'm also very interested to try v3 - it looks great! 

Could you please consider adding larger screen sizes (e.g. in metro-bootstrap-responsive.css). 1920x is quite common this days, but that css only scales up to 1200x, leaving a lot of whitespace on either side.

Thanks!

**Comment by ShubhamBadal** [comment]
@olton okay, i am very excited :)
@Mike-Honey  i too agree :+1:

**Comment by renielcanlas** [comment]
@olton sir, Is there any chance that MetroUI will have new widget for Rich Text Editors? By the way, I checked the Version3 and when you start the progress bar test then click on the start button again, see what will happen.

**Comment by olton** [comment]
@renielcanlas may be

**Comment by renielcanlas** [comment]
i think this should be very helpful. how about direct implementation of validation. 
for example
<input data-transform="form-control" type="text" data-validate="true" data-required="true" data-minlength="5" data-maxlength="25">

then automatically validated on loosing focus then after that, if validation is failed, validation input classes will be automatically applied to that control

**Comment by renielcanlas** [comment]
@olton can you please add a captcha widget?

**Comment by olton** [comment]
all to forum please http://forum.metroui.org.ua

**Comment by enr00ted** [comment]
Oh ! a forum, nice :). So we move discussion/requestes there ?

**Comment by olton** [comment]
yes yes yes

**Comment by olton** [comment]
@ShubhamBadal http://metroui.org.ua/v3/appbar.html example #2

**Comment by andrusenko-m** [comment]
How can add the arrow into input select?

![clip2net_160908174919](https://cloud.githubusercontent.com/assets/21101925/18354000/b8179f50-75ec-11e6-8006-f3e6b21ba4dc.png)
