### ISSUE TITLE
Slider don't release grab

### ISSUE THREAD

**Issue by 0xbaadf00d** [olton/Metro-UI-CSS#745]
Hi,

I think they have an issue on the slider (Tested on the last stable version of Chrome); when you grab a cursor slider and release the grab with the mouse cursor outside of the slider (cursor must be outside , it's important to reproduce issue), the slider stay grabbed until we click again on the slider.

Page to test issue: http://metroui.org.ua/v3/sliders.html

**Comment by olton** [comment]
thanks, fixed
