### ISSUE TITLE
How can i disable Past Dates from DatePicker

### ISSUE THREAD

**Issue by zahedkamal87** [olton/Metro-UI-CSS#747]
Hi, I've been trying to disable old dates from DatePicker. But its not working. Here is the codes i tried ---
   $("#datepicker1").datepicker({
        format: "yyyy-mm-dd",
        effect: "fade",
        minDate: new Date()
    });

If i replace "minDate" by "date" it selects current date automatically. Some one please help me..

Thanks

**Comment by olton** [comment]
At no datepicker minDate properties

**Comment by zahedkamal87** [comment]
I didnt understand what you meant. So, no way to disable old dates like here - http://www.redbus.in/

**Comment by olton** [comment]
while there is no such functionality

**Comment by zahedkamal87** [comment]
Found a code on jqueryui from here - http://jqueryui.com/datepicker/#min-max

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Datepicker - Restrict date range</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script>
  $(function() {
    $( "#datepicker" ).datepicker({ minDate: -20, maxDate: "+1M +10D" });
  });
  </script>
</head>
<body>
 
<p>Date: <input type="text" id="datepicker"></p>
 
</body>
</html>



As you used JqueryUI, why its not working on ur script?

**Comment by olton** [comment]
I'm not use jqueryui
04 Апр 2015 г. 15:46 пользователь "zahedkamal87" <notifications@github.com>
написал:

**Comment by zahedkamal87** [comment]
i see! okay.. Thanks.. But it would be great if you add the functionality on datepicker! But your UI is great anyway!

**Comment by olton** [comment]
http://metroui.org.ua/v3/calendar.html Example: Min Date

**Comment by zahedkamal87** [comment]
that min-date function was already there!!!!! or you added it newly!?
whatever is it.. Thanks a lot :)

**Comment by zahedkamal87** [comment]
that min-date function was already there!!!!! or you added it newly!?
whatever is it.. Thanks a lot :)

**Comment by zahedkamal87** [comment]
that min-date function was already there!!!!! or you added it newly!?
whatever is it.. Thanks a lot :)

**Comment by olton** [comment]
@zahedkamal87 future in v3
