### ISSUE TITLE
Uncaught TypeError: Cannot read property 'initAll' of undefined

### ISSUE THREAD

**Issue by udhaya2kmrv** [olton/Metro-UI-CSS#750]
When i run my metro ui page initAll Error come... Anything error while my js/css loading?

**Comment by olton** [comment]
http://metroui.org.ua/requirements.html

**Comment by udhaya2kmrv** [comment]
Thanks for your quick comments...:) I will check with my code...:) Sorry for my late responce....:(

**Comment by udhaya2kmrv** [comment]
I have load a page Inside a Main DOM using ajax/dataload that time i got initAll problem.. May i renitialize again for that page?

**Comment by olton** [comment]
after load you must  reinit components manualy or set global variable METRO_AUTOREINIT to true

**Comment by udhaya2kmrv** [comment]
I tried its not working. Can you show some example it will help us our best practise.

**Comment by olton** [comment]
your source code please

**Comment by udhaya2kmrv** [comment]
Initial File Loading:


     <link href="../asset/css/metro-bootstrap.css" rel="stylesheet">
    <link href="..asset/css/metro-bootstrap-responsive.css" rel="stylesheet">
    <link href="../asset/css/iconFont.css" rel="stylesheet">
    <link href="../asset/css/docs.css" rel="stylesheet">
    <link href="../asset/prettify/prettify.css" rel="stylesheet">

<script src="../asset/js/jq/jquery.min.js"></script>
    <script src='../asset/js/jq/jquery.cookie.min.js'></script>
    <script src="../asset/js/jq/jquery.widget.min.js"></script>
    <script src="../asset/js/jq/jquery.mousewheel.js"></script>
    <script src="../asset/prettify/prettify.js"></script>
    
    <script src="../asset/js/load-metro.js"></script>


After Ajax Call i initialized once again.
<script src="../asset/js/jq/jquery.min.js"></script>
    <script src='../asset/js/jq/jquery.cookie.min.js'></script>
    <script src="../asset/js/jq/jquery.widget.min.js"></script>
    <script src="../asset/js/jq/jquery.mousewheel.js"></script>
    <script src="../asset/prettify/prettify.js"></script>
    
    <script src="../asset/js/load-metro.js"></script>

**Comment by olton** [comment]
use metro.min.js, not load-metro

**Comment by udhaya2kmrv** [comment]
Thanks for your comments. I found exact error. I initialized JQuery both Parent DOM and Chile DOM(Which one i loaded using AJAX) thats a problem. I Removed Jquery in chile dom now its working fine your amazing Metro UI:) Thanks for giving us great Metro UI... Its a great Job:)
