### ISSUE TITLE
How to set set from/to date fixed in datepicker?

### ISSUE THREAD

**Issue by udhaya2kmrv** [olton/Metro-UI-CSS#755]
I am using datepicker to pick a date. But i couldnot set a default date from/to? so we can choose any date period.

**Comment by olton** [comment]
put to forum please

**Comment by udhaya2kmrv** [comment]
How to disable datepicker in particular input field?

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/752
