### ISSUE TITLE
Navigation: Sidebar Menu custom close

### ISSUE THREAD

**Issue by abhiabhi15** [olton/Metro-UI-CSS#759]
Hi,

I was wondering if there is a way to make the sidebar menu to be toggled based on click after selecting an item from the menu.

Eg: If I want to select an item from a dropdown and I want the selected item to stay selected, until I click on another item. This is a common requirement if selected item has some action and the user want to know which item click has caused the action or want to stay in the same sub-menu.

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/756
