### ISSUE TITLE
How can using the Validate function to compare two form fields on the same content?

### ISSUE THREAD

**Issue by HTMH** [olton/Metro-UI-CSS#813]
How can using the Validate function to compare two form fields on the same content?

**Comment by olton** [comment]
out of the box - this is not possible

**Comment by HTMH** [comment]
could not add metro.js my java of the function?

**Comment by olton** [comment]
custom functions currently are not supported.

**Comment by olton** [comment]
You can add function to validator.js and rebuild metro.js

**Comment by HTMH** [comment]
I would do if I can program :(

**Comment by olton** [comment]
Metro 4, Validator, added compare function https://metroui.org.ua/v4/validator.html#_validator_funcs
