### ISSUE TITLE
jQuery Time Picker Add-on

### ISSUE THREAD

**Issue by GManNAtl** [olton/Metro-UI-CSS#814]
Thanks in advance for any assistance.

I am assuming there is a conflict with using this add-on with Metro? Can anyone confirm if they have gotten this to work properly with Metro? If there is a conflict and it can't be used can you suggest an integrated date/time picker that is known to work.

https://github.com/trentrichardson/jQuery-Timepicker-Addon

I have used this in dozens of projects using other CSS Frameworks with no issue. In Metro it simply never displays the calendar. No JS errors at all. 

As stated I have used it enough and have checked (many many times) the order of loading the jQUI, CSS, etc. and everything matches what I've done in the past. I've tried a couple different versions of jQ and the jQUI as well with the same results.

**Comment by olton** [comment]
link to your page
