### ISSUE TITLE
Calendar and Schedule like windows 10

### ISSUE THREAD

**Issue by icefaces** [olton/Metro-UI-CSS#816]
The metro ui is really fantastic however is there a possibility to develop some components like date picker and schedule looks like the windows 10?

Thanks

**Comment by taschultz** [comment]
To add onto this feature request, the Windows 10 mobile calendar week view would be an awesome feature as well! 

Thanks!

Animated GIF: [http://assets.windowsphone.com/302498a8-fadb-40ba-bd50-bead8eaae5e6/calendar-open-item_InvariantCulture_Default.gif](url)

![calendar-open-item_invariantculture_default](https://cloud.githubusercontent.com/assets/12669524/17117988/b0cd5826-528c-11e6-9f1f-7e80299a8cb1.gif)
