### ISSUE TITLE
Pullmenu will not close after click

### ISSUE THREAD

**Issue by Ontanio** [olton/Metro-UI-CSS#818]
Hello,
I have a problem with the pullmenu (app-bar-pullmenu) that will appear after resizing the browser window. It won't close when I click outside the menu or even when i click on a list item. 
This is especially troublesome for single-page application, when the website navigation will not be reloaded. I am currently testing Metro-UI with Angular 2 and as far as i can tell there is no proper way for me to close the pullmenu without pressing the pullbutton (app-bar-pullbutton) again. This however is not intuitive.

In my opinion the pullmenu should close, when i click outside the menu (like other dropdown elements) and after clicking an list item.

You can see this behavior in the admin-template ([here](https://metroui.org.ua/templates/admin-sidebar-appbar.html)) or on the main project page ([here](https://metroui.org.ua/)) when resizing the browser

**Comment by olton** [comment]
all ok for me

**Comment by Ontanio** [comment]
Does your app-bar-menu close when you click outside of it? For me it does not. And it will not close after clicking a list item (on the project page it will because the hole website is reloaded which is not the case in a single-page application like angular)

**Comment by hrvylein** [comment]
I'd like to bring this topic up again. I recently converted my server rendered app with MetroUI to SPA with vue2. Everything adapted smooth (except modals stealing 'this') and the responsove appbar.

Is there a fix available to let the dropdown close after click?

**Comment by hrvylein** [comment]
I fixed it here https://github.com/hrvylein/Metro-UI-CSS/commit/de45eb1e59ccbf1310228ead587472cdea624a95

Maybe this will be fixed in MetroUI4 from the beginning :)

**Comment by olton** [comment]
Thanks, merged to develop branch. Will be added to master when starting Metro 4. (Metro 3 will be closed)
