### ISSUE TITLE
DatePicker INCORRECT

### ISSUE THREAD

**Issue by jedifan** [olton/Metro-UI-CSS#828]
```
<div class="input-control text" data-role="datepicker" data-preset="07/30/2016" data-format="mm/dd/yyyy"  data-min-date="2016-07-17">
   <span class="mif-calendar prepend-icon"></span>
   <input type="text" name="gigDate" placeholder="Gig date..." class="gigDate">
</div>
```

Prepopulated field value presented to user:  07/29/2016
Calendar HTML popup highlight:  7/30/2016

As reference... YOUR sample page shows same issue...
WHY?  when will code be corrected.

**Comment by jedifan** [comment]
Will any person be looking into correcting this?

**Comment by jedifan** [comment]
Really... I think this particular function would be VERY useful as many sites use calendars....  Wish I could use it, but it's' broke

**Comment by jedifan** [comment]
CAN SOMEONE LOOK INTO THIS?  Your date tool is completely useless until this is fixed!

**Comment by olton** [comment]
to solve this problem I need to reproduce it. But, I have everything up and running correctly.

**Comment by jedifan** [comment]
understood.  this issue already exists on your own site.  Click here to see the issue http://metroui.org.ua/datepicker.html.   Look at the source code, you'll see the dates are as described...

**Comment by jedifan** [comment]
ANY idea when this will get fixed?  I have it integrated into my site that's about to go live!  IF it's not corrected, I'll sadly have to abandon MetroUI!

**Comment by cabel1989** [comment]
I believe this is all that needs to be changed in the metro.calendar widget

![image](https://cloud.githubusercontent.com/assets/25349998/22303020/670229ac-e2ff-11e6-999d-a305fd3b13f2.png)

**Comment by federosario23** [comment]
Same issue here... And fixed with cabel1989 solution...
THANKS!
