### ISSUE TITLE
jquery.dataTables & Metro css

### ISSUE THREAD

**Issue by MyEunomia** [olton/Metro-UI-CSS#831]
Hi, 

I'm beginner ; I'm trying to customize (a little) the style of my dataTable based upon the example given with the jquery plugin. 

I'm using Dreamweaver CC and EasyPhp as testserver.

So, I change the font color parameter in ".dataTable thead" in metro.css file, in red as example.

In dreamweaver, the modification is effective : the font is now in red ; but nothing change when I'm testing. I've of course updated all the files on the testserver but no way.

Am I wrong to update directly in the metro.css  ?

**Comment by christian4423** [comment]
Have you heard of BEM? It means **B**lock **E**lement **M**odifier. You can update the metro.css but is there a pre-compiler such as sass or less? If so, any change you make in metro.css will be overwritten upon build. But once you find that out you will make a new class in metro, and it will be something like .dataTable .dataTable--red thead with ".dataTable--red" being the modifier. At least that is the convention I like to stick to.
