### ISSUE TITLE
AppBar non-functional with jQuery 3.1.0

### ISSUE THREAD

**Issue by taschultz** [olton/Metro-UI-CSS#834]
Resize and pullMenu properties cannot be read when using jQuery 3.1.0; app bar does not resize and "hamburger" menu does not work when using this version of jQuery.

![metro-errors](https://cloud.githubusercontent.com/assets/12669524/17117765/b07dd518-528b-11e6-9868-a523edfc8c90.PNG)

**Comment by olton** [comment]
Thanks. Fixed in develop branch
