### ISSUE TITLE
Min, max validator not working correct

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#835]
Hi Olton, 
on Your website https://metroui.org.ua/validator.html in section Func examples there are two text inputs with "min value 10" and "max value 10".
If You put "3" in "min value 10" validator says it's ok. This is wrong behaviour. 
If You put "5" in "max value 10" validator says it's not ok. This is also wrong behaviour.

**Comment by olton** [comment]
Thsnk, fixed in develop branch.

**Comment by dtq100** [comment]
Great !
