### ISSUE TITLE
Validator javascript error

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#837]
Hi Olton (again), 
On Your website https://metroui.org.ua/validator.html 
when You hit the Submit button on Func examples,  please look at console in browser. There is error 'undefined' in line:
 console.log(input.data('validateArg'));
for every input, that have no validate arguments set. Not every input needs it, but metro.js assumes that it should be in every input. You can bypass this issue by settin data-validate-arg="" for every validated input, but it's only a workaround of this bug,

**Comment by dtq100** [comment]
Sorry, i thought, that this workaround with data-validate-arg=""  is working, but it's not.

**Comment by dtq100** [comment]
Hi Olton, why this isue is closed?

**Comment by olton** [comment]
this log was removed in develop branch
