### ISSUE TITLE
Responsiveness of start screen like in version 0.95

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#838]
Hi Olton, 
In version 0.95 of metro UI start screen was responsive in this kind of way, that all tiles matched to window size (they shuffeled nicely). Since 2.0 version this is not supported. Could it be done as a new/old feature ?

**Comment by olton** [comment]
At the moment tile has not built-in responsive features. May be in the next middle small version.

**Comment by dtq100** [comment]
Thanks for info. This feature was great in 0.95 version, and i can't wait for it.
