### ISSUE TITLE
validator onbeforesubmit

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#841]
Hi Olton, 
can You tell me, what is the purpose, of using data-on-before-submit="return false"? You are doing this on this website https://metroui.org.ua/validator.html but I cant see the difference in validator behaviour whenever i use this or not.

**Comment by olton** [comment]
this for manual sumbit form

**Comment by dtq100** [comment]
Got it, thanks!

**Comment by olton** [comment]
Metro 4, Validator
https://metroui.org.ua/v4/validator.html
