### ISSUE TITLE
validator - multiple buttons inside form

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#842]
Hi Olton, 
Inside validated form i have multiple buttons. They all need to be in one form. But i need to validate only on one of this buttons click. The others need to not respond on validator. How can i achieve this ?

**Comment by olton** [comment]
for second button set attr type to 'button'

**Comment by dtq100** [comment]
Hi, 
this is working, but...
I'm using asp.net button. This button normally is generated as <input type="submit">. When i change asp.net button parameter "UseSubmitBehaviour" to "false" it's genereting <input type="button">. So far so good. But asp.net is adding onclick="javascript:__doPostBack( some long refference to control id)" and unfortunatelly this triggers the validation. 
Is there any other way to prevent validation on clicking button ?
