### ISSUE TITLE
Validator functions are checking empty value

### ISSUE THREAD

**Issue by akotulu** [olton/Metro-UI-CSS#843]
There is a function called **required** which checks for empty value and the ability for multi func, but why are all the other functions checking for it. Currently I can't add optional fields with functions like date and number, cause they are most of the time empty.

**Comment by hebertbanes** [comment]
its been a long time since you asked, but if still works for you. You can replace lines 9699 and 9703 from metro.js file for number and digits functions and similar for other functions:

`number: function(val){
        	/*return (val - 0) == val && (''+val).trim().length > 0;*/
        	return ( (val - 0) == val && (''+val).trim().length > 0 ) || val === ""; /*hebertbanes Update: '|| ('' + val).trim().length == ""' not required */
        },`
`digits: function(val){
        	/*return /^\d+$/.test(val);*/
            return ( /^\d+$/.test(val) ) || val === ""; /*hebertbanes Update:  '|| val === ""' not required */
        },`
