### ISSUE TITLE
datepicker and asp.net scriptmanager

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#849]
Hi Olton, 
I'm using datepicker with asp.net and it works fine. But when i put scriptmanager on page (just scriptmanager, without updatepanel and any partial postbacks), datepicker is not working correctly. The calendar is showing, but when trying to select date, there is js error: "Sys.ParameterCountException: Parameter count mismatch. "  and its related to this line: 
`var d = (new Date(that._paddy(that._year, 4), that._paddy(that._month, 2), that._paddy(parseInt($(this).html()), 2)).format(that.options.format, null));`

I can workaround this by putting metro.js after scriptmanager. 
Is there any normal solution for this issue, not by this inappropriate workaround ?

**Comment by gminaya** [comment]
Hi

I just set ScriptMode="Release" to the ScriptManeger and it's works.
