### ISSUE TITLE
Disable datepicker

### ISSUE THREAD

**Issue by dtq100** [olton/Metro-UI-CSS#850]
Hi, 
how to programatically disable datepicker and then again enable (in jquery / js) ?

**Comment by EastSideAngus** [comment]
Is there a way to do this or not?

**Comment by EastSideAngus** [comment]
I've tried data-disabled, data-readonly, and the tradtionaly disabled and readonly tags in the input element that I am setting to be a datepicker, and I cannot figure out, or find in the documentation how to set it as readonly either on initialization or later through a JS call.

I will make a new ticket for this.

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/issues/1633
