### ISSUE TITLE
radio/checkbox in charm  is not work

### ISSUE THREAD

**Issue by GotohLtd** [olton/Metro-UI-CSS#852]
radio/checkbox не работает в charm
Для чего нужна функция  в коде виджета charm? Она перехватывает событие и элементы не работают.

```
$(document).on("click", ".charm", function(e){
    e.preventDefault();
    e.stopPropagation();
});
```

**Comment by swb0417** [comment]
I have the same issue. If this can't be made to work I will likely have to abandon a lot of my design ideas. Possibly in favor of another CSS framework.
