### ISSUE TITLE
Is metro ui support IE9？

### ISSUE THREAD

**Issue by qifali** [olton/Metro-UI-CSS#853]
I see metro ui is support ie 9+, so I try IE11 use emulation IE9 document mode,
every css works well ,
but the problem is there are an js error show on the console

> 'MutationObserver' is undefined
MutationObserver need IE11 support, so  we cannot used metro.js if we need to support ie9 + 
is there any other solutions?
thx !

**Comment by garfbradaz** [comment]
It seems not:

http://caniuse.com/#feat=mutationobserver

There is a depreciated polyfiller here though:

https://github.com/Polymer/MutationObservers

**Comment by qifali** [comment]
thx, garfbradaz
