### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by Taymoory** [olton/Metro-UI-CSS#858]
hi.
please help me to design layout like 

![image](https://cloud.githubusercontent.com/assets/13133384/17901437/9f7310cc-6978-11e6-974f-3d09062bb611.png)

or
![image](https://cloud.githubusercontent.com/assets/13133384/17901531/113e5676-6979-11e6-97aa-c0d011c7925d.png)

with tile in my start screen.
thank.

**Comment by lcmassena** [comment]
Use Grid and Tiles. The best way...

Best regards,
Lucas Cariello Massena

Enterprise Architect
Brazil

Mobile:  +55 11 950-622-777
              +55 21 998-840-231

lucas@massena.com.br
lcmassena@msn.com
skype: lcmassena <skype:lcmassena>








Confidentiality Notice: The information contained in this email message,
including any attachment, is confidential and is intended only for the
person or entity to which it is addressed. If you are neither the intended
recipient nor the employee or agent responsible for delivering this message
to the intended recipient, you are hereby notified that you may not review,
retransmit, convert to hard copy, copy, use or distribute this email
message or any attachments to it. If you have received this email in error,
please contact the sender immediately and delete this message from any
computer or other data bank. Thank you.

Confidencialidade: A informação contida nesta mensagem de e-mail, incluindo
quaisquer anexos, é confidencial e está reservada apenas à pessoa ou
entidade para a qual foi endereçada. Se você não é o destinatário ou a
pessoa responsável por encaminhar esta mensagem ao destinatário, você está,
por meio desta, notificado que não deverá rever, retransmitir, imprimir,
copiar, usar ou distribuir esta mensagem de e-mail ou quaisquer anexos.
Caso você tenha recebido esta mensagem por engano, por favor, contate o
remetente imediatamente e apague esta mensagem de seu computador ou de
qualquer outro banco de dados. Muito obrigado.

**Comment by Taymoory** [comment]
​Thank you.​
