### ISSUE TITLE
Metro-ui-css not supported jquery 2.2+

### ISSUE THREAD

**Issue by closeyourmind** [olton/Metro-UI-CSS#865]
![image](https://cloud.githubusercontent.com/assets/22093807/18379081/292cc056-76a3-11e6-87d7-03294ed35c82.png)

**Comment by olton** [comment]
download latest version

**Comment by closeyourmind** [comment]
yes its working in jquery 2.1.3 but not working in jquery 2.2+.By the way im currently working a project using mvc6 and bower always getting the latest version of jquery..

using jquery-3.1.0
![image](https://cloud.githubusercontent.com/assets/22093807/18379970/c3e9dc92-76a7-11e6-9222-698b5dedfab0.png)
![image](https://cloud.githubusercontent.com/assets/22093807/18379970/c3e9dc92-76a7-11e6-9222-698b5dedfab0.png)

**Comment by closeyourmind** [comment]
yes its working in jquery 2.1.3 but not working in 2.2+. By the way im working a project using mvc6 and the bower always getting the latest version of jquery..

![image](https://cloud.githubusercontent.com/assets/22093807/18380248/08cdb5b2-76a9-11e6-9f38-31a094cf545d.png)

**Comment by closeyourmind** [comment]
i found out the cause of the problem..
