### ISSUE TITLE
Datatable responsive isn't working

### ISSUE THREAD

**Issue by ArCiGo** [olton/Metro-UI-CSS#866]
I implemented a Datatable in my project, but the responsive isn't working. I used the latest version of jQuery (3.x).

![screenshot_2](https://cloud.githubusercontent.com/assets/2947307/18395708/5560906c-7685-11e6-953d-2346a77cfc09.png)

My table is inside of one auto-size div

![screenshot_3](https://cloud.githubusercontent.com/assets/2947307/18395874/45fd62f2-7686-11e6-8239-9c9ab66f2e68.png)

I'll appreciate any help.

**Comment by olton** [comment]
which version of Metro UI are you using?

**Comment by ArCiGo** [comment]
v. 3.0.8, and I was using jQuery v. 2.1.3

**Comment by olton** [comment]
Download latest version of metro ui

**Comment by ArCiGo** [comment]
I tried with the new version (3.0.15), and it didn't work. What files do I need?

**Comment by olton** [comment]
create pen with problem on codepen.io

**Comment by closeyourmind** [comment]
hello there, ArCiGo are you using asp.net5

**Comment by closeyourmind** [comment]
if you using asp.net5 in visual studio, the bower there has bug. you need to manually get the jquery 2+ or if you want to use jquery version 3+, you need to add the jquery migration (https://jquery.com/upgrade-guide/3.0/)

**Comment by ArCiGo** [comment]
This is the pen: http://codepen.io/ArCiGo/pen/pEjdKX

**Comment by olton** [comment]
1. Metro UI  only added style for DataTable component and not create responsive style for this plugin
2. You have a mix of versions of Metro UI in code. Check and correct your code

**Comment by olton** [comment]
add this to table definition:
$('#uiTableSucursales').DataTable({
...
"autoWidth": false,
...
})

**Comment by ArCiGo** [comment]
It works for some cases

![sitio_1](https://cloud.githubusercontent.com/assets/2947307/18412743/1b4a0c6e-775c-11e6-96ec-20be314447c0.png)
![sitio_3](https://cloud.githubusercontent.com/assets/2947307/18412744/1b4d43d4-775c-11e6-9501-19e37c828880.png)
![sitio_4](https://cloud.githubusercontent.com/assets/2947307/18412835/5868dda8-775e-11e6-98e5-b7ba1ea74eda.png)

**Comment by bleglaiger** [comment]
Change to jquery version 2.1.3!!!

**Comment by ArCiGo** [comment]
It doesn't work, dude. Firstly I tried with jQuery 2.x, but it didn't work. Then I changed the jQuery version, and I got the same problem. 

The component doesn't have a responsive style, as @olton said.

**Comment by bleglaiger** [comment]
![image](https://cloud.githubusercontent.com/assets/6853502/18642399/183119ee-7e66-11e6-8c15-16249280d692.png)
 this image is from my mobile!!

**Comment by ArCiGo** [comment]
How did you do that?

**Comment by bleglaiger** [comment]
My BundleConfig

![image](https://cloud.githubusercontent.com/assets/6853502/18649072/23c8eb66-7e83-11e6-9dfe-3b380a3592f3.png)



My _Layout.chtml

![image](https://cloud.githubusercontent.com/assets/6853502/18649117/638cc362-7e83-11e6-8cad-91b6d6d50bc9.png)

My Index.chtml

![image](https://cloud.githubusercontent.com/assets/6853502/18649152/875fcfd2-7e83-11e6-92c1-8567da562e6f.png)
