### ISSUE TITLE
toolbar-button with a-tag

### ISSUE THREAD

**Issue by mschop** [olton/Metro-UI-CSS#868]
icons in a.toolbar-button are positioned wrong.

```
<div class="toolbar">
  <div class=toolbar-section">
    <a class="toolbar-button">
      <span class="mif-plus"></span>
    </a>
  </div>
</div>
```

**Comment by olton** [comment]
use span or button to create it

**Comment by mschop** [comment]
@olton This would require js or a form where a simple anchor would be just fine. That's a workaround not a solution.

**Comment by olton** [comment]
@mschop thanks. fixed in develop branch
