### ISSUE TITLE
Cannot read property 'resize' of undefined

### ISSUE THREAD

**Issue by laway** [olton/Metro-UI-CSS#871]
Hi,

Have a problem with app-menu, it throws exception "Cannot read property 'resize' of undefined":

metro.js:2115 Uncaught TypeError: Cannot read property 'resize' of undefined
(anonymous function) @ metro.js:2115
each @ jquery-3.1.0.js:368
each @ jquery-3.1.0.js:157
(anonymous function) @ metro.js:2114
dispatch @ jquery-3.1.0.js:5110
elemData.handle @ jquery-3.1.0.js:4918

Layout looks like this: http://joxi.ru/L21z1PkI6PbB3A

Any ideas? Thanks!

**Comment by olton** [comment]
use lib from develop branch
