### ISSUE TITLE
Conflict with three.js v81 (String.prototype.isColor)

### ISSUE THREAD

**Issue by nidu** [olton/Metro-UI-CSS#872]
Hello, i'm using three.js and metro-ui (v 3.0.13) in a single project. After update to new three.js (v81) i've noticed an interesting bug, particularly [here](https://raw.githubusercontent.com/mrdoob/three.js/r81/build/three.js) at line 7300 where a method `isColor` on some object is called. This object can be of different type including string. Metro defines `String.prototype.isColor` so e.g. `'abc'.isColor` would return `true`. This causes method to fail (i guess three.js doesn't expect `isColor` on a string). So i just can't use `WebGLRenderer` with metro-ui.

Is there anything we can do about it? How do you think - should this problem be resolved in metro-ui or three.js  (i personally think that in metro-ui)?

**Comment by olton** [comment]
Fixed in develop brach, Function moved from prototype to metroUtils object
