### ISSUE TITLE
days countdown limited to two digits

### ISSUE THREAD

**Issue by K4M1coder** [olton/Metro-UI-CSS#880]
i've tried to put a countdown for 2 years deadline but have only sixty-one days on the countdown !!

``` html
        <div class="countdown"
             data-role="countdown"
             data-stop="2018-11-15T08:00:00"
             data-divider-color="fg-grayLight"
        </div>
```

display `61:22:06:00` instead of `761:22:06:00`

**Comment by olton** [comment]
I will add this request to the TODO for the next version

**Comment by olton** [comment]
4 digits for days now in develop branch
