### ISSUE TITLE
Cannot submit a form inside a charm

### ISSUE THREAD

**Issue by ericpreisig** [olton/Metro-UI-CSS#884]
Hello,
because of the "e.preventDefault();" (line 3941) in the metro.js, we cannot submit any form inside the charm which is really annoying.  (I was stuck for 2 hours on this bug)

Maybe we can remove this "e.preventDefault();" I didn't found in what it was useful maybe you guys know ?

**Comment by mschop** [comment]
+1

**Comment by olton** [comment]
I did remove close charms on document click and preventDefaul an d StopPropogation linked with this. This fixed in develop branch

**Comment by sutherland007** [comment]
I've found a way you can close charms by clicking outside them using the document click event and submit inside a charm with no problems by adding this:
```
$(document).on('click', function(e){
     $('[data-role=charm]').each(function(i, el){
        if(!$(e.target).closest(el).length){
             if (!$(el).hasClass('keep-open') && $(el).data('displayed')===true) {
                 $(el).data('charm').close();
             }
        }
     });
 });
```
I've tested it with ruby on rails (using firefox and vivaldi) and nw.js, it worked perfectly fine, My purpose is based on [this link](https://stackoverflow.com/a/3028037/561309) consider it for metro ui 4 and the current version.
