### ISSUE TITLE
<script> breaks the Tab Control or Wizard

### ISSUE THREAD

**Issue by stefankaifer** [olton/Metro-UI-CSS#887]
Hi

I've the following with problem metroui v3 (in metro-ui v2 it worked!):

The Wizard (and Tab Control, too) is breaked, if in the "step-div" (and "frame-div" by the tabcontrol) I put some javascript-code, like in the following example:

`<div class="wizard" data-role="wizard">
    <div class="steps">
        <div class="step">Step1 <script>console.log('Step 1');</script></div>
        <div class="step">Page 2</div>
        <div class="step">Page 3</div>
    </div>
</div>`

Without `<script>` it's working. What's changed in v3? How can I put some javascript-code in each step or frame element?

Thanks

Stefan

**Comment by olton** [comment]
create pen on codepen.io with your problem

**Comment by olton** [comment]
do not put script

**Comment by stefankaifer** [comment]
Hi olton

sorry, but by http://codepen.io/stefankaifer/pen/dpEKAp it's working, but in my .net mvc-application it isn't. But I've found a workaround, that means, you can close this issue.
Regards

Stefan
