### ISSUE TITLE
Targetted Grid System like Bootstrap

### ISSUE THREAD

**Issue by anandbohra** [olton/Metro-UI-CSS#890]
Hi
I liked your project very much & looking for shifting into this from Bootstrap.
can you help me in getting below requirement.
in Bootstrap we can set No of Column for each screen size like Large, Mid Small etc etc. do this Metro UI has similar provision or alternate to it??

also in Bootstrap raw if there are more items then it automatically shifts them to second row. e.g. if row contains 8 items & if I mark cells as col-lg-3 so it will automatically show them as 2 row of 4 items each but I failed to replicate in you CSS.

I have created row with 5 cells (your basic grid) give 

```
 <div class="grid">
     <div class="row cells2">
         <div class="cell">
         </div>
         <div class="cell">
         </div>
         <div class="cell">
         </div>
         <div class="cell">
         </div>
         <div class="cell">
         </div>
     </div>
  </div>
```

in above case only first 2 cells appear next to each other then rest 3 comes in individual lines
also can I specify number of cells for each screen size?
pl help me by providing proper guidance or link to clear my doubts.

**Comment by anandbohra** [comment]
there was formatting issue in main CSS
I added to a separate CSS & seems ok but still awaiting for different column count on different resolutions like Bootstrap


```
.grid .row > .cell {
  margin: 5px;
}


```

**Comment by xiecsuk** [comment]
I would also like to see the capability of re-defining the cell layout as the size of the view-port changes. It allows a much more pleasing layout to be defined on the smaller screen sizes. As **anandbohra** points out, it is possible to do this in [Bootstrap](http://getbootstrap.com/css/#grid) and also [W3.CSS](https://www.w3schools.com/w3css/w3css_responsive.asp). two competing systems.

**Comment by dyesseyumba** [comment]
Thank you @anandbohra ! You really help me. This CSS also works better and remove the margin offset 
between the first line and the other line. 

```

.grid .row > .cell {
    margin: 0px;
    padding:10px;
}

```
I hope that with the next updates the grid system will be simplified.
