### ISSUE TITLE
Set Calendars min or max date after initialisation

### ISSUE THREAD

**Issue by padarox85** [olton/Metro-UI-CSS#891]
Hey, first i love this project.

I'm using 2 calenders to define two dates
After the date in the first calendar is clicked - i need to set this date = min-date @ second calendar
After the date in the second calendar is clicked - i need to set this date = max-date @ first calendar

any chances?

**Comment by NItishSh** [comment]
did you get the solution? i am facing similar issue.

**Comment by padarox85** [comment]
No i didn't get it yet...
Another solution for me is to set the mutliple input only recognize 2 dates - one start and one end date. then i can use only one calendar for my input...

but i need help with it - i'm good in html, php and css but js isn't so good :(
