### ISSUE TITLE
Now KeyCDN as cdn sponsor - provider for Metro UI CSS

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#895]
Now you can use Metro UI CSS from CDN **cdn.metroui.org.ua**

**CSS**
 http://cdn.metroui.org.ua/css/metro.min.css
 http://cdn.metroui.org.ua/css/metro-colors.min.css
 http://cdn.metroui.org.ua/css/metro-schemes.min.css
 http://cdn.metroui.org.ua/css/metro-icons.min.css
 http://cdn.metroui.org.ua/css/metro-responsive.min.css
 http://cdn.metroui.org.ua/css/metro-rtl.min.css
 http://cdn.metroui.org.ua/css/metro-font-cdn.css - this required for use icons from cdn

**JS**
 http://cdn.metroui.org.ua/js/metro.min.js

**Comment by sjcarr81** [comment]
HTTPS is broken, certificate expired and file not found. If you're using a CDN you need to support both HTTP and HTTPS.
