### ISSUE TITLE
Button Export Datatables

### ISSUE THREAD

**Issue by muhamadfarkhan** [olton/Metro-UI-CSS#896]
Button Export Datatables is not showing... Please Help

**Comment by yakupdemirci** [comment]
language: {
                processing: "İşleniyor...",
                search: "Arama:",
                info: "_TOTAL_ kayıttan _START_ - _END_  arası görüntüleniyor ",
                infoEmpty: "Kayıt yok",
                infoFiltered: "(_MAX_ Kayıt gösteriliyor)",
                infoPostFix: "",
                loadingRecords: "Yükleniyor...",
                zeroRecords: "Kayıt Bulunamadı",
                emptyTable: "Tablo boş",
                lengthMenu: 'Kayıt göster :<select>' +
                '<option value="10">10</option>' +
                '<option value="25">25</option>' +
                '<option value="50">50</option>' +
                '<option value="100">100</option>' +
                '<option value="250">250</option>' +
                '<option value="-1">Tümü</option>' +
                '</select>',
                paginate: {
                    first: "İlk",
                    previous: "Önceki",
                    next: "Sonraki",
                    last: "Son"

                },
                aria: {
                    sortAscending: ": Artan şekilde sırala",
                    sortDescending: ": Azalan şekilde sırala"
                }

            },
            dom: 'Bfrtip',
            title: 'Data export',
            buttons: [
                {
                    extend: 'copy',
                    text: '<span class="mif-files-empty"></span>Kopyala ',
                    className: 'button info '
                },
                {
                    extend: 'pdf',
                    text: '<span class="mif-file-pdf"></span>PDF ',
                    className: 'button info'
                },
                {
                    extend: 'excel',
                    text: '<span class="mif-file-excel"></span>XLS ',
                    className: 'button primary'
                },
                {
                    extend: 'print',
                    text: '<span class="mif-printer"></span>Yazdır ',
                    className: 'button success'
                }]
        });
