### ISSUE TITLE
Start Screen opens links twice

### ISSUE THREAD

**Issue by finnjet** [olton/Metro-UI-CSS#903]
Hi,
I am having trouble with the start screen template.
For some reasons tiles that have a link (<a_href>) with them will open the linked URL twice.

Example
<a href="devices.php" class="tile bg-darkBlue fg-white" data-role="tile">
				<div class="tile-content iconic">
					<span class="icon mif-mobile"></span>
				</div>
				<span class="tile-label">Devices</span>
</a>

I can observe this behavior both with Firebug: Two entries for the linked php files with the first one in the aborted state. And in the apache logs.

My guess this is both the a_href and some on.click code in action somewhere.

Anybody any idea how I could stop this behavior?

Thanks!

**Comment by phrei** [comment]
@finnjet I noticed the same behaviour and created a pull-request: https://github.com/olton/Metro-UI-CSS/pull/942
