### ISSUE TITLE
What about a docking panel?

### ISSUE THREAD

**Issue by deviloper** [olton/Metro-UI-CSS#908]
Hi, 
is MetroUI compatible with an existing docking panel framework (like golden-layout or dock spawn) with theming? Or there will be a docking component? It would be very useful.

Thank you
Francesco

**Comment by olton** [comment]
why should he not be working?

**Comment by deviloper** [comment]
I think external components may cause some issues with css or different jquery version dependencies. I think a native metroui docking panel would be the best solution. 

Anyway I think I will try dockspawn soon and report here :)
