### ISSUE TITLE
Bad documentation about the event system

### ISSUE THREAD

**Issue by willstdueswissen** [olton/Metro-UI-CSS#914]
Simple look up here:
http://metroui.org.ua/dialog.html

How to make a callback if a dialog closed?

I tried with data-on-close="func_name" like: http://metroui.org.ua/events.html

**Comment by phantomotaku** [comment]
@willstdueswissen  I know it has been 10 months but I figured it out. It took some digging into the metro.js file but it would look like this:

`data-on-dialog-close='func_name' 
 `
I needed the same functionality today. Maybe we can get this added to the dialog page of the metro ui website.
