### ISSUE TITLE
Validator and AJAX JQUERY call

### ISSUE THREAD

**Issue by federosario23** [olton/Metro-UI-CSS#915]
Is there any function to get the result of the validation of the FORM? Because if there is a AJAX call over an On('submit') the form is validated but submitted no matter if there are any error detected on the fields. If there is a function, it can be use to check before the ajax.

Otherwise which is the correct way to make this work? I should call a function because the response of the call must go inside a div, and not on a page.

**Comment by formae98** [comment]
Rosario, hai risolto il problema?
