### ISSUE TITLE
Uncaught ReferenceError: metroDialog is not defined

### ISSUE THREAD

**Issue by vinitdave27** [olton/Metro-UI-CSS#931]
How to get the reference of metroDialog? I have already imported the metro.js file in the html, but when specifying the method metroDialog.toggle("#dailog"), where "#dialog" is the id of the div. I am getting the error.

Also, how do i use Metro UI in angular to gain access to the metroDialog or $.Dialog?

Appreciate any guidance on the same.

**Comment by PJian** [comment]
use metroDialog.open(angular.element("#dialog")[0]).
