### ISSUE TITLE
MetroUI Sidebar + Datatable = brokensidebar

### ISSUE THREAD

**Issue by jeanblu** [olton/Metro-UI-CSS#938]
On pages containing Sidebar and Dataflex table, after the datatable is reloaded with data,  the document height of page is incremented, but  the sidebar keeps using the original height value.

**Comment by oijkn** [comment]
@olton  Hi, i have the same issue, check the screenshot bellow please :

![capture](https://user-images.githubusercontent.com/18188407/28156801-77bb414a-67b4-11e7-969e-04e7f3e031c8.JPG)

How we can fix this CSS issue, please ?

Thx for your help :)

**Comment by olton** [comment]
link to example please

**Comment by jeanblu** [comment]
I solved my problem doing the following code changes:

Original code with problem:
`<div class="page-content">
        <div class="flex-grid no-responsive-future" style="height: 100%;">
            <div class="row" style="height: 100%">
                <div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: 100%">
                    <ul class="sidebar">`

Code working:
`<div class="page-content">
        <div class="flex-grid no-responsive-future" style="height: 100%;">
            <div class="row" style="height: auto; min-height: 100%">
                <div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: auto;">
                    <ul class="sidebar">`

**Comment by oijkn** [comment]
@jeanblu Thx for this code, works great !
