### ISSUE TITLE
Fetch current date from Datepicker?

### ISSUE THREAD

**Issue by kashgurung** [olton/Metro-UI-CSS#940]
Anyone, please help me! how to fetch current date from Datepicker?  I tried doing this but not working...only when I comment the import metro.js script, it works! Any ideas...
`
$(document).ready(function(){
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    var end = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    $('#datepicker').datepicker({
        format: "MM dd, yyyy",
        todayHighlight: true,
        startDate: today,
        endDate: end,
        autoclose: true
    });
    $('#datepicker').datepicker('setDate', today);
});  

`

**Comment by olton** [comment]
In the metro there is a datepicker own element. Or use the subway or the library from which you have a datepicker
