### ISSUE TITLE
Running dialog in IE9 mode causing error: 'MutationObserver' is undefined

### ISSUE THREAD

**Issue by gebezov** [olton/Metro-UI-CSS#945]
First of all, your work is great and it draw my attention.

However, when I tested the Dialog feature in IE9, it returned error: 'MutationObserver' is undefined.

It worked fine in IE11.

Attached is the detail.

Please help.

Thank you.
[test.zip](https://github.com/olton/Metro-UI-CSS/files/1152233/test.zip)

**Comment by olton** [comment]
Use polyfill https://github.com/Polymer/MutationObservers
