### ISSUE TITLE
Metro UI CSS 4.0

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#947]
Way to 4.0 is begun...

**Comment by Ahmad45123** [comment]
Oo whats new ? Or is it still starting ?

**Comment by olton** [comment]
I am making a план now... pum pum purum ;)

**Comment by olton** [comment]
Whats new: 
1) Full Code Revision  
2) Interective builder with custom fonts, border-radious and much much more 
3) new responsive model 
4) new compoents

**Comment by olton** [comment]
You can observe the process of work on the 4th version at https://metroui.org.ua/v4/

**Comment by JohnArcher** [comment]
Looks very nice and promising! Good job!

**Comment by JohnArcher** [comment]
Don't know if I should open a new issue, but there are misleading infos in the documentation for v4. On https://metroui.org.ua/v4/browsers.html you write at the beginning at the page: "On Windows, we support Internet Explorer 10-11 ..." And at the bottom you write: "Internet Explorer 11+ is supported; IE10 and down is not." So it is not clear, whether IE10 is supported or not. :-)

**Comment by olton** [comment]
@JohnArcher thx, fixed - Internet Explorer 11+ is supported, IE10 - partially, IE9 and down is not.

**Comment by JohnArcher** [comment]
@olton Superb, thanks! Maybe you should also alter the first mentioned line, "Internet Explorer 10-11", as it reads that IE 10 and 11 is supported. Maybe something like "On Windows, we fully support Internet Explorer 11+ (Internet Explorer 10 partially) ..."!?

**Comment by JohnArcher** [comment]
BTW: I am amazed and impressed by the speed of the new development, wow!

And fun fact: In my company (Germany) we have a new employee which is also from the Ukraine :-), but lives here since many years. Hope you are ok with all the weird stuff that happens in your country since some years. :-/

**Comment by olton** [comment]
@JohnArcher for ie there is an enumeration, therefore, separated by commas and without parentheses

**Comment by JohnArcher** [comment]
Maybe we talk about different stuff (or I don't understand you correctly). I mean this phrase: 
![image](https://user-images.githubusercontent.com/990724/30325926-f9eab816-97c6-11e7-9361-6d9298d8fa72.png)

**Comment by olton** [comment]
@JohnArcher Thx, fixed: On Windows, we support Internet Explorer 11 and Microsoft Edge, IE10 supports partially.

**Comment by olton** [comment]
Images base css is done. https://metroui.org.ua/v4/images.html

**Comment by olton** [comment]
Icons is done. https://metroui.org.ua/v4/icons.html Now with groups and search

**Comment by olton** [comment]
Validator
https://metroui.org.ua/v4/validator.html

**Comment by olton** [comment]
Tabs was completely rewritten
https://metroui.org.ua/v4/tabs.html

**Comment by ncxn** [comment]
CDN return 404 error ? and source can not download?

**Comment by olton** [comment]
Metro 4 in develp and not available from cdn

10 жовт. 2017 р. 5:40 дп "ncxn" <notifications@github.com> пише:

**Comment by olton** [comment]
@ncxn Now you can use Metro 4 from cdn, but remember Metro 4 in developing!:
CSS
```<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
or
```
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro.min.css">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-colors.min.css">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-rtl.min.css">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-icons.min.css">
```
JS
```<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>

**Comment by ncxn** [comment]
@olton thanks so much.

**Comment by xiecsuk** [comment]
I have just had a look at Metro 4 and it looks stunning. As I am about to start a new website, should I be thinking about using Metro 4 or stick with the current Metro 3 version?

**Comment by olton** [comment]
@xiecsuk In a month I will release version 4. Version 3 and 4 are not compatible. So decide for yourself.

**Comment by xiecsuk** [comment]
I have decided to go with version 4; no point in using an out-of-date version. Looking forward to the official release.

**Comment by olton** [comment]
Metro 4 is done! Now there is a final testing before the release, which is scheduled for March 1, 2018. I invite everyone to join the testing.

You can find the repository by this link https://github.com/Pro-Club/MetroCL.

After release MetroCL repo will be merged to this repo.
