### ISSUE TITLE
I find a hotkey error

### ISSUE THREAD

**Issue by chenkl1995** [olton/Metro-UI-CSS#949]
* `js/utils/hotkeys.js`
```
        8: "backspace",
        9: "tab",
        10: "return", 
        13: "return",  ==> "enter"
        16: "shift",
```
And [the "return" key seems mean nothing?](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

**Comment by olton** [comment]
Ok, Thanks
