### ISSUE TITLE
Metro UI CSS 4.0 - Grid test

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#950]
Metro UI CSS 4.0
Grid test
https://metroui.org.ua/v4/grid.html

**Comment by cizo** [comment]
Hi Olton,
how difficult it will be to migrate existing web application (built on Metro 3.X) to this new one? Do you plan any major changes in source code that will affect difficulty of rewriting to the new version? From this grid preview I noticed missing **_cellsX_** classes in rows, but this is minor change so far...
Thanks, Cizo

**Comment by olton** [comment]
I will try to make the transition not difficult. Grid now build with flex model  same as in bootstrap with gap and media column classes as cell-ms-x

**Comment by olton** [comment]
updated demo. full description created

**Comment by olton** [comment]
After much thought, it was decided to make a grid similar to Twitter Bootstrap

**Comment by JohnArcher** [comment]
Looks promising, good work!

I guess implementing rowspan (placing several items/cells next to one item/cell) is "just" possible with nested rows!?

**Comment by olton** [comment]
@JohnArcher Yes, nested rows supported

**Comment by olton** [comment]
Grid documentation done
