### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by danielreish** [olton/Metro-UI-CSS#955]
Hi! Please help me! I am using metro version 3 in my mvc project. This is my code:

- View:
```
<div class="cell colspan2">
        <div class="input-control text span2" data-role="datepicker" data-locale="pt" data-
        format="dd/mm/yyyy" data-preset="@ViewBag.Date">
                <label>
                         Date
                 </label>
                 @Html.TextBox("Date", null, new { @readonly = "readonly" })
                 <button class="button" type="button"><span class="mif-calendar"></span></button>
         </div>
</div>
```

- Controller:
```
// GET: /Order/Report
public ActionResult Report()
{
       var model = db.Orders;
       //bug: Add 2 days because metro automatically decreases 2 days
       ViewBag.Date = Convert.ToString(string.Format("{0:yyyy-MM-dd}", DateTime.Today.AddDays(2)));
       return View(model);
}
```

The problem is this bug, where it is added 2 days to the date informed. This problem can also be seen in the examples of the site. 

Is there any fix for this error?

**Comment by finoshj** [comment]
Hi There,

You should use the setDate function to set the date. Here is how i use it in my project. I have a Editor Template for dateTime.  My Datetime picker is a editable one where a user can type in the textbox and also they can select a date from the picker

/****Template****/
@using SrpWeb.Helpers;
@model DateTime?

<div class="input-control text datepicker @ViewData["class"]" data-role="datepicker"  data-format="dd/mm/yyyy"
     data-effect="slide" data-week-start="1" >
  @*This adjusts PICKED date format. Both picked and incoming formats must match for edits to work  day=dddd*@
  @Html.TextBox("", (Model == null) ? String.Empty : ((DateTime)Model).Date.ToString("dd'/'MM'/'yyyy"), new  { @placeholder = "dd/mm/yyyy" })  @*This adjusts INCOMING date format.  Both picked and incoming formats must match for edits to work   day=ddd*@
  <button type="button" class="button"><span class="mif-calendar"></span></button>
</div>

@using (Html.BeginScripts())
{
  <script type="text/javascript">
    $(document).ready(function () {
      $("#@Html.IdForModel()").removeAttr("readonly");
      $('#@Html.IdForModel()').datepicker({ dateFormat: 'dd/mm/yyyy' }).val(); jQuery.validator.methods['date'] = function (value, element) { return true; };

      $("#@Html.IdForModel()").on("blur", function () {
        var d = this.value;
        if (d.length > 0)
        {
          if (ValidateDate(this)) {
          $("#dateformaterror").remove();
          var from = d.split("/");
          var f = new Date(from[2], from[1] - 1, from[0]);
          var dp = $('#@Html.IdForModel()').datepicker();
          dp.datepicker('setDate', f);
        }
        else {
          $("#dateformaterror").remove();
          $("#@Html.IdForModel()").val('');
         $("#@Html.IdForModel()").parent().parent().append("<span id=\"dateformaterror\" class=\"field-validation-error float-left\"><span id=\"dateformaterror-error\">Invalid date</span></span>");
        }
        }

      });
    });



  </script>

    
}
/**************************End of Templete**************/


/************** HTML *************/
 <div>
        @Html.EditorFor(model => model.StartDate, new { @class = "editor-field info float-left" })
        @Html.ValidationMessageFor(model => model.StartDate)
      </div>
/**********************/

/***********Modal***************/
[UIHint("_DateTimeDateOnlyShort")]
    [DisplayName("Start Date")]
    public DateTime? StartDate { get; set; }
/*************************/

Cheers

**Comment by danielreish** [comment]
Solved my problem. Thank you.
