### ISSUE TITLE
Metro 4, form element definition

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#957]
In Metro 4 checnged method for element definition
https://metroui.org.ua/v4/forms.html

Forms in develop...

**Comment by olton** [comment]
Important! No more difficult structures. Metro 4 automatically convert standard elements to if need. You can add data-role attribute to element to conver it. See details on https://metroui.org.ua/v4/forms.html

Forms in develop...

**Comment by olton** [comment]
Forms done

**Comment by JohnArcher** [comment]
Is it possible to add custom icons (e.g. one of the metro ui icons) to input fields? Like, if you add data-role="input" the clear ad/or reveal buttons can be activated. So, can I add another icon _and_ additional functionality (through callback?) when clicking the icon besides reveal and clear?

**Comment by olton** [comment]
To define custom icons:

data-clear-button-icon
data-reveal-button-icon

**Comment by JohnArcher** [comment]
Sorry if I wasn't clear enough. I don't want to have a custom icon for reveal or clear functionality, but I want _new_ functionality. For example I want a custom icon on the left of the input and if I click on this icon a dialog opens (the dialog opening code would be in a callback which I would like to define for that button click). I hope it is more clear now what I mean?

**Comment by olton** [comment]
I'll add it later.

19 вер. 2017 р. 5:19 пп "Micha J." <notifications@github.com> пише:

**Comment by olton** [comment]
@JohnArcher https://github.com/olton/Metro-UI-CSS-4/invitations
