### ISSUE TITLE
Problems with IE11 and MetroUI v3?

### ISSUE THREAD

**Issue by khaeroup** [olton/Metro-UI-CSS#963]
Hello everyone,
I created a small HTML page using MetroUI, everything works fine with Chrome, but when it comes to IE11..it's the worst. Tried to open the example pages on IE11 from MetroUI website and they load correctly...what could it be that i'm missing?

This is the code from the index, looks cool on Chrome, horrific on IE11. 

```
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="./css/metro.css"  />
        <link rel="stylesheet" type="text/css" href="./css/metro-schemes.css"  />
    </head>
    <body>
        <div class="app-bar fixed-top green" data-role="appbar">
            <a class="app-bar-element-static">Name Me!</a>
            <span class="app-bar-divider"></span>
            <a class="app-bar-element place-right" href="./docs.html">Docs</a>
        </div>
    </body>
</html>

```
Thanks :)

**Comment by olton** [comment]
please create pen on Codepen.io

**Comment by khaeroup** [comment]
https://codepen.io/anon/pen/OxqQem There you go ^^" Had to manually copy-paste your CSS..never used codepen :)

**Comment by khaeroup** [comment]
Found the problem. I still had a CSS file i created lying around that was making everything horrific. My fault, topic closed x)
