### ISSUE TITLE
[Metro v3] How to remove leaf from treeview

### ISSUE THREAD

**Issue by oijkn** [olton/Metro-UI-CSS#964]
Hi,

In my project i use your great code to show an treeview where i can add a new element using the function `addLeaf`. The problem is if I want to remove an active item i can't find any function that do the job...

Can you tell me who i can remove an leaf item from the treeview please ? Thx you in advance for you support.

**Comment by olton** [comment]
$(leaf).remove() ?

**Comment by olton** [comment]
there is no direct method, it will be in version 4, but if you can get a leaf in some way: by id or by class, then you can delete it like this: $(leaf).remove()

**Comment by oijkn** [comment]
Well done that make the job :)

```
function tree_remove_leaf_runtime_click(){
    var tree = $("#tree_add_leaf_runtime").data("treeview");
    var node = tree.element.find('li.active');

    node.remove();
}
```

Thx for the help !
