### ISSUE TITLE
Helper Button (clear) in Chrome not rendering properly

### ISSUE THREAD

**Issue by ydalley** [olton/Metro-UI-CSS#966]
The helper-button clear not rendering properly in chrome. The close icon appears in the middle of the text box. The button appears to span the entire textbox (and cover it)

![issue](https://user-images.githubusercontent.com/26444020/32216132-743813f6-be24-11e7-86a1-0888326cdc27.png)

**Comment by olton** [comment]
link to page or example on codepen.io
