### ISSUE TITLE
Suggestion for charms.

### ISSUE THREAD

**Issue by sutherland007** [olton/Metro-UI-CSS#968]
I've found a way you can close charms by clicking outside them using the document click event and submit inside a charm with no problems by adding this:
```
$(document).on('click', function(e){
     $('[data-role=charm]').each(function(i, el){
        if(!$(e.target).closest(el).length){
             if (!$(el).hasClass('keep-open') && $(el).data('displayed')===true) {
                 $(el).data('charm').close();
             }
        }
     });
 });
```
I've tested it with ruby on rails using firefox, vivaldi, chrome, opera and nw.js, it worked perfectly fine, My solution is based on [this link](https://stackoverflow.com/a/3028037/561309) consider it for metro ui 4 and the current version. I left a comment before on #884 but nobody noticed it, so that's why I'm opening a new issue.

**Comment by olton** [comment]
Thanks
