### ISSUE TITLE
Checkbox not working inside Charm

### ISSUE THREAD

**Issue by swb0417** [olton/Metro-UI-CSS#969]
I can't get the checkbox to work when placed in a charm.  I can programmatically change the state of the chekbox, but I don't feel like having to write my own onclick handlers for such a simple task... There is already another issue open identifying the same problem but I have responded to that one on January 20th (almost a year ago now) and so far it has not been looked at.

**Comment by olton** [comment]
please, create pen on codepen.io with your problem

**Comment by swb0417** [comment]
Hi! I don't have a codepen account, but I am attaching a zip file that illustrates the problem. All you will have to do to recreate the problem is set the css and js references to point to files on your system.


 
[CHECKBOX-TEST.zip](https://github.com/olton/Metro-UI-CSS/files/1511810/CHECKBOX-TEST.zip)

**Comment by olton** [comment]
@swb0417 you can create an account on codepen.io absolutely free. I do not have the opportunity to deploy all the archives of anyone who uses Metro and has some problems with it. Sorry.

**Comment by swb0417** [comment]
@olton I tried but I can't seem to properly link to metro that is hosted on my own site from within the code on codepen... Meanwhile I am pretty certain the problem has something to do with the fact that you are setting the "checked" property of one control (input type="checkbox") while responding to an event handler of another (span) control.

When I do this:

```
<label class="switch">
<input type="checkbox" checked="" id="switch1" onclick="tickThis(this)">
<span class="check" id="clickme"onclick="tickThis(this)"></span>
<span class="caption" onclick="tickThis(this)">CHECKBOX</span>
</label>
```

When I inspect the element in my tickThis function, like so:

```
function tickThis(ctrl) {
alert(ctrl.id);
};
```

the alert shows "clickme" even though to switch the state of the checkbox I will have to do this:

`$('#switch1').prop("checked", false)`

**Comment by swb0417** [comment]
Do you have this problem against the latest version?

**Comment by olton** [comment]
@swb0417 why do you have these two helper elements include the onclick handler?
``
<span class="check" id="clickme"onclick="tickThis(this)"></span>
<span class="caption" onclick="tickThis(this)">CHECKBOX</span>

Then the event pops up on a label that changes the state of the checkbox. Place onclick on the label

**Comment by olton** [comment]
@swb0417 I do not understand the goal that you want to achieve :( Why set onclick on additional elements? Set onclick to label.

**Comment by swb0417** [comment]
The onclick on the additional elements was to figure out/test which of the elements was actually firing the onclick event. 

In the example above, the UI shows all 4 elements (label with 3 nested elements) as one switch/checkbox. To programatically check/uncheck the element you will have to set the property of the INPUT element, yet the onclick event fires from the SPAN element with class of "check".

The "goal" I am trying to achive is to get Metro checkboxes/switches working in charms. my question is, have you confirmed that checkboxes are fully functional in charms in the latest version of Metro.

**Comment by olton** [comment]
To programmatically change the status of the checkbox, you need to change the attribute of the input, the onclick event is not generated. The state of the checkbox also changes when the user clicks on the label.
