### ISSUE TITLE
Can't overlapping Panel heading

### ISSUE THREAD

**Issue by thundervoice** [olton/Metro-UI-CSS#970]
Why no each other Element can overlapping the Panel heading? Z-Index lower or higher doesn't works in this Case.
![overlapping](https://user-images.githubusercontent.com/22094049/33441082-15dc8ba8-d5f2-11e7-90a6-e04becb94ae4.png)

**Comment by olton** [comment]
link to page or example on codepen.io

**Comment by thundervoice** [comment]
See the example below:
https://plnkr.co/edit/fehEy7YoAmni9Gql7SV0?p=preview

**Comment by olton** [comment]
add this
``.panel > .content {
        z-index: auto;
      }
``
