### ISSUE TITLE
Tile Slide-up keyline

### ISSUE THREAD

**Issue by jedifan** [olton/Metro-UI-CSS#971]
This issue ALSO EXISTS ON DEMO SITE.  How do I get rid to the 1px white keyline on the slide object?
See https://metroui.org.ua/tiles.html and choose ANY sliding effect, you'll see it.

I've tried adding class to various divs (my body color is grayDarker) 
1. bd-grayDarker
2. ol-grayDarker
3. bg-grayDarker
4. before-bd-grayDarker
5. before-ol-grayDarker
6. before-bg-grayDarker
7. after-bd-grayDarker
8. after-ol-grayDarker
9. after-bg-grayDarker

on
<div class="tile">
<div class="tile tile-content">
<div class="slide">
<div class="slide-over">

Nothing seems to get rid of this line... HELP!

**Comment by olton** [comment]
add style:
`.slide-over {
    box-shadow: none!important;
}`
