### ISSUE TITLE
How to run Notify system without even?

### ISSUE THREAD

**Issue by ncxn** [olton/Metro-UI-CSS#975]
In Metro 3,
Can run Notify by 
```
<script>
    $.Notify({...options...});
</script>
```

Then Can I run this in Metro 4 ?
```
<script>
   $.Metro.notify.create("This is a notify", "Title", {});
</script>
```

**Comment by olton** [comment]
Everything is written in the documentation
https://metroui.org.ua/v4/notify.html

**Comment by rcheung9** [comment]
An extra option for the direction of the Notification sliding out would be nice.

Right now it seems to slide bottom up.  Would be nice to have an option to slide top down.

Alternatively options for left side and right side.

I think if you can set the position of the notification (top left, top right, bottom left, bottom right) independently from the direction of the sliding animation (slide from top, slide from bottom, slide from left, slide from right) that would be awesome.

**Comment by ncxn** [comment]
Hello all,
@rcheung9 , perfect! additional effects, ex: fadeIn, fadeOut, zoom...
@olton , I can not use direct as version 3. So I switched to using the dialog.

Thanks,

**Comment by olton** [comment]
@rcheung9 please create an issue for additional options for Notify after Metro 4 release.
