### ISSUE TITLE
Metro 4 and Select2 / DataTables

### ISSUE THREAD

**Issue by rcheung9** [olton/Metro-UI-CSS#979]
Is Metro 4 going to support Select2 and DataTables?

With Metro 3, I had to modify some CSS to make Select2 look consistent with Metro 3 styling of text boxes.

And Metro 3 had some CSS to override the default DataTables styling of buttons, borders, etc.

**Comment by olton** [comment]
At the moment I do not plan to include support for third-party widgets in Metro 4.

**Comment by Cadorin** [comment]
Why do not only keep the old things from version 3 in order to have support for datatables? Who was using version 3, like me, will have many problems to convert everything to the new version ...

**Comment by olton** [comment]
@Cadorin 
The author of DataTables has never responded to my letters on the integration of its component in Metro3, so I decided not to include support for third-party components in Metro 4. You can write DataTables author to add Metro support 4 if you want

**Comment by phelan1109** [comment]
This issue started as select2 and datatables - I am curious about the select2 functionality as I currently use it in metro V3. V4 is awesome but I cannot move to it unless something like select2 is included.  I currently cannot spend the time to migrate to V4 and figure out a custom solution for large searchable dropdown lists.

Is there a plan for this type of support?

**Comment by olton** [comment]
I don't have any plans to support  third party components. You can write to select2 authors to include support Metro 4

**Comment by phelan1109** [comment]
Perhaps my question was not clear... I understand that you do not wish to include support for third party components.  Is metro4 going to provide similar functionality to select2 that will allow for the searching of large lists?  I also would prefer not to have to deal with select2 but a native solution would be nice...

**Comment by olton** [comment]
I have plans to extend functionality Metro 4 select component. I think in 4.1.0 I add many features to own select component.

**Comment by phelan1109** [comment]
Thanks for the update! It is great to hear that is something you have planned for.  Do you have any projection on when 4.1.0 might be available? I am really excited to begin my migration...

**Comment by olton** [comment]
at the moment there is no release date

**Comment by phelan1109** [comment]
Well I really appreciate all the work you do and have done!  Ill keep an eye peeled in anticipation of this crucial feature.
Thanks!

**Comment by rcheung9** [comment]
Select2 works with Metro4.  Just don't use data-role=select and it's fine.  You might want to override the border-radius.
