### ISSUE TITLE
Popover - Methods bug

### ISSUE THREAD

**Issue by Expertik99** [olton/Metro-UI-CSS#983]
When you click in methods in popovers on button "Show popover" and then you click again, it create another popover with fixed position and "Hide popover" won't help... So i think, it is bug.

![image](https://user-images.githubusercontent.com/1688285/34640034-a8c82790-f2eb-11e7-9dbf-99cd80d3cb10.png)

**Comment by olton** [comment]
Thanks, fixed

**Comment by olton** [comment]
In  next time, please use Metro 4 for prefix issue name
