### ISSUE TITLE
Metro 4 is done!

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#992]
Metro 4 is done! 

Dev repo https://github.com/Pro-Club/MetroCL merged with this.

**Comment by msouzarunner** [comment]
Good job !!!

**Comment by arjarn** [comment]
Great !
I Specially like helper classes : nice to avoid CSS hack to rendering page ;)

**Comment by chongzia** [comment]
Congratulations to you
Thank you for bringing us a very good UI framework.
Thank you for sharing. Thank you for your efforts.
