### ISSUE TITLE
Chevrons don't show up

### ISSUE THREAD

**Issue by rcheung9** [olton/Metro-UI-CSS#993]
https://getmetroui.com/panels.html

I'm using the CDN but the chevrons don't show up.

It just shows up as a little black triangle on the bottom right corner.

**Comment by olton** [comment]
https://codepen.io/olton/pen/JpLROZ/

This example use CDN and all work fine

**Comment by rcheung9** [comment]
Well I figured it out.  It seems if you have it in a <div data-role"navview" class="navview"> it shows up as a triangle.  I removed those two attributes and it started to work again.  But of course the navigation view breaks.

https://getmetroui.com/navview.html

I'm not sure if this is intended behavior since that's what the nav bar looks like (small black triangle at bottom right corner).  It should not affect the contents div though.

**Comment by olton** [comment]
@rcheung9 Thanks, fixed

**Comment by rcheung9** [comment]
Thanks it works.  How do you change color of chevron? When I change the panel title to darker color (like brandColor2), the dark chevron is hard to see.  Tried changing the dropdown-toggle class to color: white but it doesn't work.

**Comment by olton** [comment]
@rcheung9  use classes: `.drop-marker-light` or `.marker-light`

**Comment by JohnArcher** [comment]
Maybe this could also added to the doc (https://metroui.org.ua/dropdown.html)? I tried a lot to get it white.

In general, there are **so many** css classes that can be used, I think it would be helpful to have a comprehensive list of all available classes and maybe a short reference to specific doc (like link to appbar) where this class is relevant and a short description.
I know this is a huge task. :-(
