### ISSUE TITLE
Little things

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#994]
Hi,

Thanks for the hard work done on this Metro 4 framework.

- The appbar : Hamburger Menu don't close when an item is clicked, can you handle it or give us a javascript method to handle that ?
- forms -> textarea : text can be under the cross.
- since I'm using the last metro4 css my dropdown in a vertical menu (class v-menu) stops working
- Can you add an option to disable animation on a tile click ? I'm using an input in a tile and Firefox can't focus the cursor because of the animation.
- On Internet Explorer there is no spaces between tiles (look this in IE : https://metroui.org.ua/v4/tiles.html)
- CalendarPicker : please add an option to choose display order of the date (the top one). For example if I display the calendar I'v got "Sunday, Feb 26" but in french we need to change this order to "Dimanche, 26 Fev" ("Sunday, 26 Feb").

I hope you will understand everything.

**Comment by olton** [comment]
@Falconpage Thanks. Metro 4 Build 4.0.0 - 583 beta
1) use methods: `open()`, `close()` 
2) fixed
3) please create pen on codepen.io with your problem
4) -
5) I created fallback for ie11 to floated blocks
6) I added option header format. Use `data-header-format="%A, %e %b"`

**Comment by Falconpage** [comment]
Thanks for your quick reply.
My codepen : https://codepen.io/Falconpage/pen/zRmpJO

**Comment by olton** [comment]
@Falconpage v-menu and d-menu fixed, thanks. Wait for cdn upd to v4.0.0-584-beta

**Comment by Falconpage** [comment]
Thanks, great job !

1. It works, perfect
2. Tested, nice.
3. Tested, thanks
5. It works on IE11
6. Great, nice to be able to modify this.

4. For the tiles, can you add an option to disable th animation when tile clicked -> need an option to disable this : tile.addClass("transform-" + side);


Thanks again for the great work you have done with Metro4

**Comment by olton** [comment]
@Falconpage I added option canTransform to tile. Set to false to disable tile.addClass("transform-" + side);

`&lt;div data-role="tile" data-can-transform="false"&gt;`

**Comment by Falconpage** [comment]
Perfect ! Thanks.
