### ISSUE TITLE
Notify Issue

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#995]
Hi again,

I'm trying "notify" feature, it works well on codepen : https://codepen.io/Falconpage/pen/bLmXeR
The same code on my server doesn't work.
Any idea ?

**Comment by olton** [comment]
Browser conole log?

**Comment by Falconpage** [comment]
Nothing, strange.
If I try the notify with a callback, nothing on the screen but I'v got the callback alert.

**Comment by olton** [comment]
Investigate where your notify in DOM

**Comment by Falconpage** [comment]
You are right having a look to the code inspector on you documentation website when I notify show me that something missing in my case : `<div class="notify-container"></div>`
I solve the issue understanding that the issue is myself ! I placed jquery and metro js at the end of the head not in the footer of the html code. Everything is ok know, the special div is created well know

**Comment by olton** [comment]
If you placed js in the head, you must add special meta tag and init metro manualy. More in configuring article.

**Comment by Falconpage** [comment]
Thanks and sorry using of your time to this.

**Comment by Falconpage** [comment]
Another question or issue to solve : notify appear under app bar.
A workaround is to add a mt-xx to the notify container but I think it can be handle by your code ?

Can you explain syntax of the notify setup option "container" (container - where notifies showing (default: null)), It can be another workaround of the app bar issue.

**Comment by olton** [comment]
@Falconpage With this option `container`, you can define container where notifies will be showing

**Comment by Falconpage** [comment]
For exemple if I a have this container : `<div class="MyNotify"></div>` I will have to set container = "MyNotify" ?

My workaround (this code after metro.js loading) : 

`if (window.matchMedia("(max-width: 1699px)").matches) {
  $( ".notify-container" ).addClass( "mt-16" );	
}`

**Comment by olton** [comment]
Yes

**Comment by olton** [comment]
@Falconpage Also you can use `Metro.utils.media()` function

```
if (Metro.utils.media("(max-width: 1699px)")) { 
    $( ".notify-container" ).addClass( "mt-16" ); 
}

```

**Comment by olton** [comment]
@Falconpage If you want to change the notify style, you must add options to notify

```
.my-notify {
   ...
}
```

```
var notify = Metro.notify;
notify.create("This is a notify with additional class.", null, {
    cls: "my-notify"
});
```

**Comment by Falconpage** [comment]
Great, thanks for these informations.
