### ISSUE TITLE
Form validation error

### ISSUE THREAD

**Issue by chongzia** [olton/Metro-UI-CSS#996]
https://codepen.io/dreamcc/pen/BYxKrp

**Comment by olton** [comment]
Where detailed description for this?

**Comment by chongzia** [comment]
This means that regular validation is not correct.

**Comment by olton** [comment]
Thanks. Use:
`<input type="text" data-validate="pattern=(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)">`

In the next version, I add modifiers parsing

**Comment by chongzia** [comment]
pattern 
In the fourth generation version of the
It's really super hard to use.
Compared to the third generation.
Instead, the third generation is more friendly.

You can try this code.
'
<input type="text"  placeholder="test"  data-validate="required, pattern=([\w]{6,36})">
<span class="invalid_feedback">error</span>

<input type="text"  placeholder="test"  data-validate="required, pattern=^[\w]{6,36}$">
<span class="invalid_feedback">error</span>

<input type="text"  placeholder="test"  data-validate="required, pattern=[\w]{6,36}">
<span class="invalid_feedback">error</span>‘


Only when it in this way when used is the normal  
But a lot of times I can't just use it that way.
Should be It's too complicated
I have to control the number of characters.
This is not what anyone expected.
’
 <input type="text"  placeholder="test"  data-validate="required, pattern=[\w][\w][\w]">
<span class="invalid_feedback">error</span>'

**Comment by chongzia** [comment]
hope to fix it, use it to be super painful.

**Comment by olton** [comment]
pattern function in Metro 4 has same code as in Metro 3

**Comment by olton** [comment]
```
pattern: function(val, pat){
        if (pat === undefined) {
            return false;
        }
        var reg = new RegExp(pat);
        return reg.test(val);
}
```

**Comment by chongzia** [comment]
You can calm down first.
Take a look at about Number of characters The question of control.

Should be
I have done a lot of attempts at the regular here, and finally I have to submit this problem to you.

pattern=[\w]# {6,36}

**Comment by olton** [comment]
Check your regular expression on this https://regex101.com/ (for javascript)

**Comment by chongzia** [comment]
```
<input type="text" placeholder="test" data-validate="required, pattern=^[\w]{7}$">
<input type="text" placeholder="test" data-validate="required, pattern=^[\w]{7,15}$">
```


Regular without error

https://codepen.io/dreamcc/pen/BYxKrp
Please see how to report the error.

**Comment by olton** [comment]
@chongzia  Metro 4 use `comma` to divide rules. Therefore, the rule does not work. I will think about how to solve this problem.

**Comment by chongzia** [comment]
I find that I have a problem with my description.
So communication often takes a long time,to find the root of the problem.

Why didn't I think of that
Use the word comma to describe it.

**Comment by chongzia** [comment]
Dead tired people

**Comment by olton** [comment]
@chongzia in the dialogue the truth is born :)

**Comment by chongzia** [comment]
I hope I can handle it soon.
Because the input tag for each interaction, 
May all have to use it.

**Comment by olton** [comment]
@chongzia  I change rules divider to `space`. Now works with:

`<input type="text" placeholder="test" data-validate="required pattern=^[\w]{7,15}$">`

**Comment by chongzia** [comment]
I'm trying to

**Comment by chongzia** [comment]
Your code
I copied it to the pen and tested it.
The js section is now reporting the error.


Below is the error log.

metro.js:14572 Uncaught TypeError: Ye[e] is not a function
    at String.<anonymous> (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:226131)
    at Function.each (https://code.jquery.com/jquery-3.2.1.min.js:2:2715)
    at Object.validate (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:225991)
    at HTMLInputElement.<anonymous> (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:227683)
    at Function.each (https://code.jquery.com/jquery-3.2.1.min.js:2:2715)
    at Object._submit (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:227662)
    at HTMLFormElement.t.(anonymous function).onsubmit (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:227420)
(anonymous) @ metro.js:14572
each @ jquery-3.2.1.min.js:2
validate @ metro.js:14557
(anonymous) @ metro.js:14688
each @ jquery-3.2.1.min.js:2
_submit @ metro.js:14686
t.(anonymous function).onsubmit @ metro.js:14672

**Comment by chongzia** [comment]
The address of pen has not changed.

**Comment by olton** [comment]
@chongzia  Wait until the CDN updates

**Comment by chongzia** [comment]
Refresh waiting

At the same time, I want to ask,
How do I get radio of the status ？

Do not use js to selector the Looking for.
Directly to the user.

**Comment by olton** [comment]
I did not quite understand the point, but in Metro 4 You must work with `<input type='radio' data-role='radio'>` as with a standard html element.

**Comment by chongzia** [comment]
等会我创建代码笔记

**Comment by chongzia** [comment]
pen instructions update
The url  there is no change
You can view the comments.

CDN has not been updated？

**Comment by olton** [comment]
CDN updated, clear your browser cache

**Comment by olton** [comment]
to get checkbox value before submitting form, you can use `onsubmit` event for the form

**Comment by olton** [comment]
I will think that I would add a checkbox and radio check to the validator.

**Comment by chongzia** [comment]
I think it's a good idea.

This way, if the user does not choose, the submission is not allowed.
So i don't have to write your own js.
To determine user behavior.

**Comment by olton** [comment]
@chongzia try the following:
1) add attribute `id` to your checkbox
2) add to form attribute `data-on-before-submit="return $('your_checkbox').is(':checked')"`

**Comment by chongzia** [comment]
:ok

**Comment by olton** [comment]
@chongzia MEtro 4 updated to 4.0.3
### 4.0.3
- [x] Validator: rename event onValid to onValidate
- [x] Validator: add events onErrorForm, onValidateForm
- [x] Validator: added checkbox validation (required function)

Read docs (also updated) for more information
