### ISSUE TITLE
Metro 4 - Tiles

### ISSUE THREAD

**Issue by douglasdtc** [olton/Metro-UI-CSS#999]
Hello,
I can't get Tiles to work from v3 to v4.
We have a main page, similar to the Start Screen example from v3, but, when trying to upgrade to v3, nothing works. The tiles documentation are still in v3.
What's different?
Thank you.

**Comment by olton** [comment]
Hi.
In Metro 4, the basis for tiles is a grid based on css grid layouts.
Metro 4 not contain containers for tiles. You must create these manually.

**Comment by hxffelixho** [comment]
@olton

**Comment by hxffelixho** [comment]
do you remove tile-group in metro 4?

**Comment by olton** [comment]
Tile-group in Metro 3 is just a block element. Use class `.tiles-grid` for tiles group container and add style with required `width`.

```
<div class="tiles-grid" style="width: ...">
...
</div>
```

**Comment by olton** [comment]
https://metroui.org.ua/examples/tiles/start.html

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/tiles

**Comment by olton** [comment]
@hxffelixho tiles-group added in 4.0.5

**Comment by olton** [comment]
@douglasdtc 

https://metroui.org.ua/examples/tiles/start.html
https://github.com/olton/Metro-UI-CSS/tree/master/docs/examples/tiles

**Comment by douglasdtc** [comment]
Thank you @olton , I'll try to upgrade and I'll let you know.
